### PR TITLE
sinkv2(cdc): fix sink worker for splitTxn is false

### LINKED ISSUE #7990: TiCDC is stuck when replicating data without split big txn
### What did you do?

TiCDC is stuck when replicating data without split big txn.

1. create tidb and ticdc cluster
2. create a changefeed without split big txn: `tiup cdc:nightly cli changefeed create --sink-uri="mysql://root@xxx:4000/?transaction-atomicity=table" -c "test" --config=changefeed.toml --server xxxx:8300`
3. pause the changefeed: `tiup cdc:nightly cli changefeed pause -c test --server xxxx:8300`
4. add workload: `../tools/workload -database-host xxxxx -database-db-name test -row-count 10000000 -table-count 3 -tps 50000 -workload-type bank`
5. resume the changefeed: `tiup cdc:nightly cli changefeed resume -c test --server xxxxxx:8300`

### What did you expect to see?

Changefeed replicates normally.

### What did you see instead?

Changefeed was stuck.
image

### Versions of the cluster

master

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

Issue Number: close #7990 .

### What is changed and how it works?

Suppose there are 2 transactions with CommitTs `3` and `4`.
Without the PR, sink worker can only advance to `3` even if it can know `4` is finished. And then it will call `tryAcquire`, and it may fail.
With the PR sink worker can advance to `4` with a batch ID.

#### Tests 

 - Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

File: cdc/processor/sinkmanager/table_sink_worker.go [hunk 1]
```diff
@@ -329,11 +324,7 @@ func (w *sinkWorker) handleTask(ctx context.Context, task *sinkTask) (finalErr e
 			events = append(events, x...)
 			allEventSize += size
 			usedMem += size
-			if pos.IsCommitFence() {
-				committedTxnSize += size
-			} else {
-				pendingTxnSize += size
-			}
+			pendingTxnSize += size
```
Comment (hi-rustin) [inline cdc/processor/sinkmanager/table_sink_worker.go:327]: Why do we need to change it?

File: cdc/processor/sinkmanager/table_sink_worker.go [hunk 2]
```diff
@@ -312,11 +312,6 @@ func (w *sinkWorker) handleTask(ctx context.Context, task *sinkTask) (finalErr e
 			pendingTxnSize = 0
 			batchID = 1
 		}
-		if pos.IsCommitFence() {
```
Comment (hi-rustin) [inline cdc/processor/sinkmanager/table_sink_worker.go:315]: Why do we remove it?

File: cdc/processor/sinkmanager/table_sink_worker.go [hunk 3]
```diff
@@ -142,31 +142,33 @@ func (w *sinkWorker) handleTask(ctx context.Context, task *sinkTask) (finalErr e
...
+		if currTxnCommitTs == lastPos.CommitTs {
+			if lastPos.IsCommitFence() {
 				// All transactions before currTxnCommitTs are resolved.
 				err = w.advanceTableSink(task, currTxnCommitTs, committedTxnSize+pendingTxnSize)
 			} else {
-				// This will advance some complete transactions before currTxnCommitTs,
-				// and one partail transaction with `batchID`.
+				// This means all events of the currenet transaction have been fetched, but we can't
+				// ensure whether there are more transaction with the same CommitTs or not.
 				err = w.advanceTableSinkWithBatchID(task, currTxnCommitTs, committedTxnSize+pendingTxnSize, batchID)
```
Comment (hi-rustin) [inline cdc/processor/sinkmanager/table_sink_worker.go:152]: Does this mean whether splitting txn we all use the batch ID as a marker? Could you please add some comments to batch ID to explain what is going on? How do we use the batch ID for different goals?
Because in the past, batch ID was only for the split txn.

File: cdc/processor/sinkmanager/table_sink_worker.go (hunk 1 above)
Comment (hicqu) [reply cdc/processor/sinkmanager/table_sink_worker.go:327]: In `doEmit` the condition about `CommitFence` is handled correctly. So here it's unnecessary to check `CommitFence` again.

File: cdc/processor/sinkmanager/table_sink_worker.go (hunk 2 above)
Comment (hicqu) [reply cdc/processor/sinkmanager/table_sink_worker.go:315]: In `doEmit` the condition about `CommitFence` is handled correctly. So here it's unnecessary to check `CommitFence` again.

File: cdc/processor/sinkmanager/table_sink_worker.go (hunk 3 above)
Comment (hicqu) [reply cdc/processor/sinkmanager/table_sink_worker.go:157]: Done.

**Review by hi-rustin — APPROVED** [review]

**Review by nongfushanquan — APPROVED** [review]
