### PR TITLE
reset internal state of feedStateManager when shouldBeRunning is false

### LINKED ISSUE #9892: changefeed fails directly when a warning is encountered after resume
### What did you do?

resume a failed changefeed

### What did you expect to see?

_No response_

### What did you see instead?

changefeed failed again within 2 minutes

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: close #9892

### What is changed and how it works?
[reset internal state of feedStateManager when shouldBeRunning is false](https://github.com/pingcap/tiflow/pull/9893/files#diff-501a5d79c9eb6daaefb02f468e671628f80f282aa90e34b913cacf17c0a242ddR439-R441)

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`Fix a bug that changefeed fails directly when a warning is encountered after resume`.
```

### CODE REVIEW

**Comment by asddongmen** [comment]
Could you please add a unit test case to cover it?

File: cdc/owner/feed_state_manager.go [hunk 1]
```diff
@@ -416,12 +428,14 @@ func (m *feedStateManager) patchState(feedState model.FeedState) {
 	})
 }
 
-func (m *feedStateManager) cleanUpTaskPositions() {
```
Comment (asddongmen) [inline cdc/owner/feed_state_manager.go:419]: how it works?

Comment (CharlesCheung96) [reply cdc/owner/feed_state_manager.go:419]: Cleanup checkpointTs and resolvedTs before stopping, and it will be initialized when changefeed resumes.

**Review by asddongmen — APPROVED** [review]
