### PR TITLE
test(engine): fix unstable TestNewLogger ut

### LINKED ISSUE #5843: engine UT TestNewLogger timeout
### Which jobs are flaking?

engine-UT

### Which test(s) are flaking?

TestNewLogger 

### Jenkins logs or GitHub Actions link

https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/16864/pipeline/

```
=== FAIL: engine/pkg/logutil TestNewLogger (unknown)

[2022-06-13T04:54:33.497Z] coverage: 50.0% of statements

[2022-06-13T04:54:33.497Z] panic: test timed out after 5m0s

[2022-06-13T04:54:33.497Z] 

[2022-06-13T04:54:33.497Z] goroutine 43 [running]:

[2022-06-13T04:54:33.497Z] testing.(*M).startAlarm.func1()

[2022-06-13T04:54:33.497Z] 	/usr/local/go/src/testing/testing.go:2029 +0xbb

[2022-06-13T04:54:33.497Z] created by time.goFunc

[2022-06-13T04:54:33.497Z] 	/usr/local/go/src/time/sleep.go:176 +0x48

[2022-06-13T04:54:33.497Z] 

[2022-06-13T04:54:33.497Z] goroutine 1 [chan receive, 5 minutes]:

[2022-06-13T04:54:33.497Z] testing.(*T).Run(0xc000602b60, {0x14b54c6, 0xd}, 0x151e488)

[2022-06-13T04:54:33.497Z] 	/usr/local/go/src/testing/testing.go:1487 +0x750

[2022-06-13T04:54:33.497Z] testing.runTests.func1(0x0?)

[2022-06-13T04:54:33.497Z] 	/usr/local/go/src/testing/testing.go:1839 +0x9a

[2022-06-13T04:54:33.497Z] testing.tRunner(0xc000602b60, 0xc00046bb68)

[2022-06-13T04:54:33.497Z] 	/usr/local/go/src/testing/testing.go:1439 +0x214

[2022-06-13T04:54:33.497Z] testing.runTests(0xc000244b40?, {0x1f78f30, 0x1, 0x1}, {0x40?, 0x7f34da81dd40?, 0x1f96d20?})

[2022-06-13T04:54:33.497Z] 	/usr/local/go/src/testing/testing.go:1837 +0x7e5

[2022-06-13T04:54:33.497Z] testing.(*M).Run(0xc000244b40)

[2022-06-13T04:54:33.497Z] 	/usr/local/go/src/testing/testing.go:1719 +0xa72

[2022-06-13T04:54:33.497Z] main.main()

[2022-06-13T04:54:33.497Z] 	_testmain.go:95 +0x3aa

[2022-06-13T04:54:33.497Z] 

[2022-06-13T04:54:33.497Z] goroutine 65 [chan receive, 5 minutes]:

[2022-06-13T04:54:33.497Z] github.com/pingcap/tiflow/engine/pkg/logutil.TestNewLogger(0x0?)

[2022-06-13T04:54:33.497Z] 	/home/jenkins/agent/workspace/ut-check/tiflow/engine/pkg/logutil/log_test.go:58 +0x545

[2022-06-13T04:54:33.497Z] testing.tRunner(0xc000602d00, 0x151e488)

[2022-06-13T04:54:33.497Z] 	/usr/local/go/src/testing/testing.go:1439 +0x214

[2022-06-13T04:54:33.497Z] created by testing.(*T).Run

[2022-06-13T04:54:33.497Z] 	/usr/local/go/src/testing/testing.go:1486 +0x725

[2022-06-13T04:54:33.497Z] 

[2022-06-13T04:54:33.497Z] goroutine 82 [select, 5 minutes]:

[2022-06-13T04:54:33.497Z] github.com/hpcloud/tail.(*Tail).waitForChanges(0xc0005246e0)

[2022-06-13T04:54:33.497Z] 	/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/tail.go:350 +0x2e9

[2022-06-13T04:54:33.497Z] github.com/hpcloud/tail.(*Tail).tailFileSync(0xc0005246e0)

[2022-06-13T04:54:33.497Z] 	/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/tail.go:311 +0x8f6

[2022-06-13T04:54:33.497Z] created by github.com/hpcloud/tail.TailFile

[2022-06-13T04:54:33.497Z] 	/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/tail.go:133 +0x645

[2022-06-13T04:54:33.497Z] 

[2022-06-13T04:54:33.497Z] goroutine 83 [chan receive, 5 minutes]:

[2022-06-13T04:54:33.497Z] gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc0001a6d80)

[2022-06-13T04:54:33.497Z] 	/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:379 +0x65

[2022-06-13T04:54:33.497Z] created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1

[2022-06-13T04:54:33.497Z] 	/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:390 +0xef

[2022-06-13T04:54:33.497Z] 

[2022-06-13T04:54:33.497Z] goroutine 84 [select, 5 minutes]:

[2022-06-13T04:54:33.498Z] github.com/hpcloud/tail/watch.(*InotifyTracker).run(0xc0001fb280)

[2022-06-13T04:54:33.498Z] 	/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/watch/inotify_tracker.go:236 +0x2b6

[2022-06-13T04:54:33.498Z] created by github.com/hpcloud/tail/watch.glob..func1

[2022-06-13T04:54:33.498Z] 	/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/watch/inotify_tracker.go:54 +0x317

[2022-06-13T04:54:33.498Z] 

[2022-06-13T04:54:33.498Z] goroutine 13 [syscall, 5 minutes]:

[2022-06-13T04:54:33.498Z] syscall.Syscall6(0xe8, 0x9, 0xc000427b34, 0x7, 0xffffffffffffffff, 0x0, 0x0)

[2022-06-13T04:54:33.498Z] 	/usr/local/go/src/syscall/asm_linux_amd64.s:43 +0x5

[2022-06-13T04:54:33.498Z] golang.org/x/sys/unix.EpollWait(0x100000000000000?, {0xc000427b34, 0x7, 0xc00059c000?}, 0xc000427b90?)

[2022-06-13T04:54:33.498Z] 	/go/pkg/mod/golang.org/x/sys@v0.0.0-20220520151302-bc2c85ada10a/unix/zsyscall_linux_amd64.go:56 +0xa5

[2022-06-13T04:54:33.498Z] gopkg.in/fsnotify%2ev1.(*fdPoller).wait(0xc00010f040)

[2022-06-13T04:54:33.498Z] 	/go/pkg/mod/gopkg.in/fsnotify.v1@v1.4.7/inotify_poller.go:86 +0x95

[2022-06-13T04:54:33.498Z] gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc0002c90e0)

[2022-06-13T04:54:33.498Z] 	/go/pkg/mod/gopkg.in/fsnotify.v1@v1.4.7/inotify.go:192 +0x345

[2022-06-13T04:54:33.498Z] created by gopkg.in/fsnotify%2ev1.NewWatcher

[2022-06-13T04:54:33.498Z] 	/go/pkg/mod/gopkg.in/fsnotify.v1@v1.4.7/inotify.go:59 +0x36f

[2022-06-13T04:54:33.498Z] 

[2022-06-13T04:54:33.498Z] goroutine 14 [select, 5 minutes]:

[2022-06-13T04:54:33.498Z] github.com/hpcloud/tail/watch.(*InotifyFileWatcher).ChangeEvents.func1()

[2022-06-13T04:54:33.498Z] 	/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/watch/inotify.go:88 +0x1fb

[2022-06-13T04:54:33.498Z] created by github.com/hpcloud/tail/watch.(*InotifyFileWatcher).ChangeEvents

[2022-06-13T04:54:33.498Z] 	/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/watch/inotify.go:77 +0x31b

[2022-06-13T04:54:33.498Z] 
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve?

Issue Number: close #5843 

### What is changed and how it works?
Using zaptest.Buffer to test the log format.

#### Tests 

 - Unit test

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

File: engine/pkg/logutil/log_test.go [hunk 1]
```diff
@@ -42,25 +47,51 @@ func init() {
...
+			select {
+			case line, ok := <-tailHandler.Lines:
+				if !ok {
+					return
+				}
+				fmt.Printf("tail line:%s\n", line)
+				require.NoError(t, line.Err)
+				lineCh <- line.Text
+			case <-ctx.Done():
+				return
```
Comment (amyangfei) [inline engine/pkg/logutil/log_test.go:75]: Close `lineCh` here, otherwise reading from `lineCh` may block the test.

File: engine/pkg/logutil/log_test.go [hunk 2]
```diff
@@ -25,9 +29,10 @@ import (
 	"go.uber.org/zap"
 )
 
-var testFile = "test.log"
+var testFile = "./test.log"
 
 func init() {
+	os.Remove(testFile)
 	logger, prop, err := log.InitLogger(&log.Config{
```
[the remark this answers is not in the document]
Comment (maxshuang) [reply engine/pkg/logutil/log_test.go]: Fix in latest commit.

File: engine/pkg/logutil/log_test.go [hunk 3]
```diff
@@ -25,42 +28,63 @@ import (
 	"go.uber.org/zap"
 )
 
-var testFile = "test.log"
-
-func init() {
-	logger, prop, err := log.InitLogger(&log.Config{
+func TestNewLogger(t *testing.T) {
+	testFile := t.TempDir() + "/test.log"
```
Comment (amyangfei) [inline engine/pkg/logutil/log_test.go:32]: Use `filepath.Join` for better OS compatibility

**Review by amyangfei — COMMENTED** [review]
rest lgtm

File: engine/pkg/logutil/log_test.go [hunk 4]
```diff
@@ -25,42 +29,63 @@ import (
 	"go.uber.org/zap"
 )
 
-var testFile = "test.log"
-
-func init() {
-	logger, prop, err := log.InitLogger(&log.Config{
+func TestNewLogger(t *testing.T) {
+	testFile := filepath.Join(t.TempDir(), "test.log")
+	os.Remove(testFile)
```
Comment (amyangfei) [inline engine/pkg/logutil/log_test.go:34]:
```suggestion
```

File: engine/pkg/logutil/log_test.go [hunk 5]
```diff
@@ -25,42 +29,63 @@ import (
...
-	if err != nil {
-		panic(err)
-	}
-	log.ReplaceGlobals(logger, prop)
-}
+	require.NoError(t, err)
+	log.ReplaceGlobals(lg, prop)
 
-func TestNewLogger(t *testing.T) {
 	defer os.Remove(testFile)
```
Comment (amyangfei) [inline engine/pkg/logutil/log_test.go:44]:
```suggestion
```

**Review by amyangfei — APPROVED** [review]

**Comment by gozssky** [comment]
What's the root cause for the unstable test? It seems this PR can only avoid the test running too long.

File: engine/pkg/logutil/log_test.go [hunk 6]
```diff
@@ -25,42 +29,61 @@ import (
...
-	tail, err := tail.TailFile(testFile, tail.Config{Follow: true})
+	var wg sync.WaitGroup
+	defer wg.Wait()
+
+	tailHandler, err := tail.TailFile(testFile, tail.Config{Follow: true, Poll: true})
 	require.NoError(t, err)
-	defer tail.Stop()
+	defer tailHandler.Stop()
+
+	ctx, cancel := context.WithTimeout(context.Background(), time.Second*3)
```
Comment (gozssky) [inline engine/pkg/logutil/log_test.go:50]: Too short a timeout may also lead to unstable tests, especially in a slow CI environment. If we can ensure test logic is correct and can pass fast, I think it's ci's responsibility to avoid the test running so long.

**Comment by maxshuang** [comment]
> What's the root cause for the unstable test? It seems this PR can only avoid the test running too long.

It seems that In CI, some lines will lost and thus cause long time channel stuck.  But the detail root cause is unknown.
So in this pr, I make following two modification:
1. Use a goroutine to avoid the blocking channel(tail.Lines) stuck (It may cause data loss, not 100% sure).
2. Use a timeout to fast fail.

File: engine/pkg/logutil/log_test.go (hunk 6 above)
Comment (maxshuang) [reply engine/pkg/logutil/log_test.go:50]: Make it fast fail.

**Comment by gozssky** [comment]
Can we use `zaptest.Buffer` instead? It seems this PR doesn't really fix the unstable test.

**Comment by maxshuang** [comment]
> Can we use `zaptest.Buffer` instead? It seems this PR doesn't really fix the unstable test.

This is what I need.

**Review by gozssky — APPROVED** [review]
