### PR TITLE
Fix integration test(syncpoint/bank) fail

### LINKED ISSUE #4655: integration test syncpoint fail
### What did you do?

sudo CASE="syncpoint" docker-compose -f ./deployments/ticdc/docker-compose/docker-compose-mysql-integration.yml up --build

### What did you expect to see?

syncpoint integration test run good

### What did you see instead?

[FATAL] [main.go:95] ["failed to initialize diff process"] [error="no table need to be compared"]
["Welcome to sync_diff_inspector"] ["Release Version"=v5.2.2-115-g6bd23df] 

This error is raised by: https://github.com/pingcap/tidb/pull/32435

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
master
```

Upstream TiKV version (execute `tikv-server --version`):

```console
master
```

TiCDC version (execute `cdc version`):

```console
master
```

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve?

Issue Number: close #4655 

### What is changed and how it works?
For syncpoint:
1. fix get start_ts logic
2. check valid syncpoint before check data

For bank:
Add new added column `CreateTime` for `admin show ddl history`
### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]

File: tests/integration_tests/bank/case.go [hunk 1]
```diff
@@ -624,7 +625,7 @@ func tryGetEndTs(db *sql.DB, tableName string) (result string, ok bool) {
 	var line dataRow
 	row := db.QueryRow(query, tableName)
 	if err := row.Scan(&line.JobID, &line.DBName, &line.TblName, &line.JobType, &line.SchemaState, &line.SchemeID,
-		&line.TblID, &line.RowCount, &line.StartTime, &line.EndTime, &line.State); err != nil {
+		&line.TblID, &line.RowCount, &line.CreateTime, &line.StartTime, &line.EndTime, &line.State); err != nil {
```
Comment (lonng) [inline tests/integration_tests/bank/case.go:628]: Prefer using the query  `select a,b,c from ddl_jobs` to retrieve the DDL jobs to avoid compatibility breaks.
