### PR TITLE
owner, redo: make new s3 storage error unretryable

### LINKED ISSUE #7010: redo: when config an invalid minio uri to create changefeed, owner get stuck
### What did you do?

Use the config file below to create a changefeed:
```
[consistent]
level = "eventual"
storage = "s3://logbucket-1/test-changefeed?access-key=xxx&secret-access-key=xxx&endpoint=http://10.x.x.25:24x27/"
```

### What did you expect to see?

1. changefeed create failed, owner does not stuck.

### What did you see instead?
image

Owner got stuck, TiCDC API request has no response, can't do anything until the changefeed automatic retry backoff interval grows up to an large enough value. 

```log
[2022/09/08 11:54:51.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m24.999390745s] [role=owner]
[2022/09/08 11:54:52.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m25.999554943s] [role=owner]
[2022/09/08 11:54:53.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m26.999463854s] [role=owner]
[2022/09/08 11:54:54.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m27.999334131s] [role=owner]
[2022/09/08 11:54:55.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m28.999554895s] [role=owner]
[2022/09/08 11:54:56.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m29.999186249s] [role=owner]
[2022/09/08 11:54:57.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m30.999323497s] [role=owner]
[2022/09/08 11:54:58.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m31.999212117s] [role=owner]
[2022/09/08 11:54:59.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m32.999716811s] [role=owner]
[2022/09/08 11:54:59.595 +08:00] [WARN] [s3.go:924] ["failed to request s3, retrying"] [error="RequestError: send request failed\ncaused by: dial tcp 10.2.6.25:24927: connect: connection refused"] [backoff=2m4.623051904s]
[2022/09/08 11:55:00.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m33.999327093s] [role=owner]
[2022/09/08 11:55:01.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m34.999192277s] [role=owner]
[2022/09/08 11:55:02.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m35.99960081s] [role=owner]
[2022/09/08 11:55:03.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m36.998865776s] [role=owner]
[2022/09/08 11:55:04.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m37.998911667s] [role=owner]
[2022/09/08 11:55:05.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m38.999373782s] [role=owner]
[2022/09/08 11:55:06.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m39.998752203s] [role=owner]
[2022/09/08 11:55:07.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m40.999355261s] [role=owner]
[2022/09/08 11:55:08.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m41.999363167s] [role=owner]
[2022/09/08 11:55:09.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m42.999541778s] [role=owner]
[2022/09/08 11:55:10.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m43.999177591s] [role=owner]
[2022/09/08 11:55:11.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m44.999066363s] [role=owner]
[2022/09/08 11:55:12.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m45.999091443s] [role=owner]
[2022/09/08 11:55:13.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m46.999563292s] [role=owner]
[2022/09/08 11:55:14.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m47.999325716s] [role=owner]
[2022/09/08 11:55:15.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m48.999504233s] [role=owner]
[2022/09/08 11:55:16.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m49.999053622s] [role=owner]
[2022/09/08 11:55:17.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m50.999032226s] [role=owner]
[2022/09/08 11:55:18.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m51.998994967s] [role=owner]
[2022/09/08 11:55:19.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m52.999290982s] [role=owner]
[2022/09/08 11:55:20.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m53.999705661s] [role=owner]
[2022/09/08 11:55:21.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m54.999295154s] [role=owner]
[2022/09/08 11:55:22.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m55.999036496s] [role=owner]
[2022/09/08 11:55:23.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m56.999496415s] [role=owner]
[2022/09/08 11:55:24.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m57.998983494s] [role=owner]
[2022/09/08 11:55:25.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m58.999207819s] [role=owner]
[2022/09/08 11:55:26.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m59.999547856s] [role=owner]
[2022/09/08 11:55:27.307 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m0.998656485s] [role=owner]
[2022/09/08 11:55:28.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m1.999417125s] [role=owner]
[2022/09/08 11:55:29.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m2.999589473s] [role=owner]
[2022/09/08 11:55:30.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m3.999524987s] [role=owner]
[2022/09/08 11:55:31.307 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m4.998658399s] [role=owner]
[2022/09/08 11:55:32.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m5.999272259s] [role=owner]
[2022/09/08 11:55:33.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m6.999188971s] [role=owner]
[2022/09/08 11:55:34.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m7.999206747s] [role=owner]
[2022/09/08 11:55:35.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m8.999401474s] [role=owner]
[2022/09/08 11:55:36.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m9.999450343s] [role=owner]
[2022/09/08 11:55:37.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m10.999289716s] [role=owner]
[2022/09/08 11:55:38.307 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m11.998621473s] [role=owner]
[2022/09/08 11:55:39.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m12.998922961s] [role=owner]
[2022/09/08 11:55:40.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m13.999374474s] [role=owner]
[2022/09/08 11:55:41.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m14.99951615s] [role=owner]
[2022/09/08 11:55:42.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m15.99935901s] [role=owner]
[2022/09/08 11:55:43.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m16.999128123s] [role=owner]
[2022/09/08 11:55:44.309 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m17.999755097s] [role=owner]
[2022/09/08 11:55:45.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m18.999418879s] [role=owner]
[2022/09/08 11:55:46.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m19.999118645s] [role=owner]
[2022/09/08 11:55:47.307 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m20.998659848s] [role=owner]
[2022/09/08 11:55:48.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m21.998882668s] [role=owner]
[2022/09/08 11:55:49.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m22.999117957s] [role=owner]
[2022/09/08 11:55:50.307 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m23.998702094s] [role=owner]
[2022/09/08 11:55:51.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m24.999170476s] [role=owner]
[2022/09/08 11:55:52.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m25.999454261s] [role=owner]
[2022/09/08 11:55:53.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m26.999329544s] [role=owner]
[2022/09/08 11:55:54.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m27.999591827s] [role=owner]
[2022/09/08 11:55:55.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m28.999655828s] [role=owner]
[2022/09/08 11:55:56.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m29.999470593s] [role=owner]
[2022/09/08 11:55:57.309 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m30.999745127s] [role=owner]
[2022/09/08 11:55:58.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m31.998912616s] [role=owner]
[2022/09/08 11:55:59.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m32.998978947s] [role=owner]
[2022/09/08 11:56:00.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m33.998986717s] [role=owner]
[2022/09/08 11:56:01.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m34.998891866s] [role=owner]
[2022/09/08 11:56:02.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m35.998834112s] [role=owner]
[2022/09/08 11:56:03.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m36.999291815s] [role=owner]
[2022/09/08 11:56:04.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m37.999438921s] [role=owner]
[2022/09/08 11:56:05.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m38.999024464s] [role=owner]
[2022/09/08 11:56:06.307 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m39.998578113s] [role=owner]
[2022/09/08 11:56:07.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m40.999559185s] [role=owner]
[2022/09/08 11:56:08.307 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m41.998670539s] [role=owner]
[2022/09/08 11:56:09.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m42.999103165s] [role=owner]
[2022/09/08 11:56:10.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m43.999178086s] [role=owner]
[2022/09/08 11:56:11.307 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m44.998665747s] [role=owner]
[2022/09/08 11:56:12.307 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m45.998635839s] [role=owner]
[2022/09/08 11:56:13.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m46.999211871s] [role=owner]
[2022/09/08 11:56:14.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m47.998832466s] [role=owner]
[2022/09/08 11:56:15.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m48.998816179s] [role=owner]
[2022/09/08 11:56:16.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m49.99914718s] [role=owner]
[2022/09/08 11:56:17.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m50.998983714s] [role=owner]
[2022/09/08 11:56:18.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m51.999088795s] [role=owner]
[2022/09/08 11:56:19.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m52.999038294s] [role=owner]
[2022/09/08 11:56:20.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m53.999341573s] [role=owner]
[2022/09/08 11:56:21.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m54.99921725s] [role=owner]
[2022/09/08 11:56:22.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m55.999315027s] [role=owner]
[2022/09/08 11:56:23.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m56.998854703s] [role=owner]
[2022/09/08 11:56:24.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m57.998958814s] [role=owner]
[2022/09/08 11:56:25.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m58.998960353s] [role=owner]
[2022/09/08 11:56:26.307 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=2m59.99862447s] [role=owner]
[2022/09/08 11:56:27.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m0.999041661s] [role=owner]
[2022/09/08 11:56:28.307 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m1.998696791s] [role=owner]
[2022/09/08 11:56:29.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m2.999239823s] [role=owner]
[2022/09/08 11:56:30.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m3.999143089s] [role=owner]
[2022/09/08 11:56:31.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m4.999413183s] [role=owner]
[2022/09/08 11:56:32.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m5.999343321s] [role=owner]
[2022/09/08 11:56:33.307 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m6.998561024s] [role=owner]
[2022/09/08 11:56:34.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m7.999489149s] [role=owner]
[2022/09/08 11:56:35.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m8.99935915s] [role=owner]
[2022/09/08 11:56:36.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m9.999054644s] [role=owner]
[2022/09/08 11:56:37.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m10.998804808s] [role=owner]
[2022/09/08 11:56:38.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m11.999194842s] [role=owner]
[2022/09/08 11:56:39.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m12.999468894s] [role=owner]
[2022/09/08 11:56:40.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m13.999247886s] [role=owner]
[2022/09/08 11:56:41.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m14.999210907s] [role=owner]
[2022/09/08 11:56:42.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m15.998856083s] [role=owner]
[2022/09/08 11:56:43.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m16.998984525s] [role=owner]
[2022/09/08 11:56:44.307 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m17.998682125s] [role=owner]
[2022/09/08 11:56:45.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m18.999307724s] [role=owner]
[2022/09/08 11:56:46.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m19.999364433s] [role=owner]
[2022/09/08 11:56:47.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m20.999676246s] [role=owner]
[2022/09/08 11:56:48.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m21.99972741s] [role=owner]
[2022/09/08 11:56:49.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m22.999477969s] [role=owner]
[2022/09/08 11:56:50.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m23.999137187s] [role=owner]
[2022/09/08 11:56:51.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m24.998837154s] [role=owner]
[2022/09/08 11:56:52.307 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m25.998654447s] [role=owner]
[2022/09/08 11:56:53.309 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m26.999769353s] [role=owner]
[2022/09/08 11:56:54.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m27.999219032s] [role=owner]
[2022/09/08 11:56:55.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m28.999379346s] [role=owner]
[2022/09/08 11:56:56.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m29.998962744s] [role=owner]
[2022/09/08 11:56:57.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m30.998863887s] [role=owner]
[2022/09/08 11:56:58.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m31.999422167s] [role=owner]
[2022/09/08 11:56:59.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m32.998959296s] [role=owner]
[2022/09/08 11:57:00.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m33.999412841s] [role=owner]
[2022/09/08 11:57:01.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m34.99942385s] [role=owner]
[2022/09/08 11:57:02.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m35.998747182s] [role=owner]
[2022/09/08 11:57:03.308 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m36.999171091s] [role=owner]
[2022/09/08 11:57:04.220 +08:00] [ERROR] [changefeed.go:218] ["an error occurred in Owner"] [namespace=default] [changefeed=test-1] [error="[CDC:ErrS3StorageInitialize]new s3 storage for redo log: failed to get region of bucket logbucket-1: RequestError: send request failed\ncaused by: dial tcp 10.2.6.25:24927: connect: connection refused"] [errorVerbose="[CDC:ErrS3StorageInitialize]new s3 storage for redo log: failed to get region of bucket logbucket-1: RequestError: send request failed\ncaused by: dial tcp 10.2.6.25:24927: connect: connection refused\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/pkg/errors.WrapError\n\tgithub.com/pingcap/tiflow/pkg/errors/helper.go:32\ngithub.com/pingcap/tiflow/cdc/redo/common.glob..func1\n\tgithub.com/pingcap/tiflow/cdc/redo/common/util.go:63\ngithub.com/pingcap/tiflow/cdc/redo/writer.NewWriter\n\tgithub.com/pingcap/tiflow/cdc/redo/writer/file.go:155\ngithub.com/pingcap/tiflow/cdc/redo/writer.NewLogWriter\n\tgithub.com/pingcap/tiflow/cdc/redo/writer/writer.go:140\ngithub.com/pingcap/tiflow/cdc/redo.NewManager\n\tgithub.com/pingcap/tiflow/cdc/redo/manager.go:264\ngithub.com/pingcap/tiflow/cdc/owner.(*changefeed).initialize\n\tgithub.com/pingcap/tiflow/cdc/owner/changefeed.go:503\ngithub.com/pingcap/tiflow/cdc/owner.(*changefeed).tick\n\tgithub.com/pingcap/tiflow/cdc/owner/changefeed.go:270\ngithub.com/pingcap/tiflow/cdc/owner.(*changefeed).Tick\n\tgithub.com/pingcap/tiflow/cdc/owner/changefeed.go:198\ngithub.com/pingcap/tiflow/cdc/owner.(*ownerImpl).Tick\n\tgithub.com/pingcap/tiflow/cdc/owner/owner.go:194\ngithub.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:266\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:510\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).campaignOwner\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:462\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func3\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:334\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/09/08 11:57:04.220 +08:00] [INFO] [ddl_puller.go:667] ["Close the ddl puller"] [namespace=default] [changefeed=test-1_ddl_puller]
[2022/09/08 11:57:04.278 +08:00] [INFO] [region_range_lock.go:389] ["unlocked range"] [changefeed=default-test-1_ddl_puller] [lockID=224] [regionID=20] [checkpointTs=435843087644753921] [startKey=6d44444c4a6f6241ff64ff644964784c69ff7374ff0000000000ff000000f700000000ff0000006c00000000fb] [endKey=6d44444c4a6f6241ff64ff644964784c69ff7374ff0000000000ff000000f700000000ff0000006d00000000fb]
[2022/09/08 11:57:04.278 +08:00] [INFO] [client.go:1122] ["stream to store closed"] [namespace=default] [changefeed=test-1_ddl_puller] [addr=10.2.6.70:20160] [storeID=1]
[2022/09/08 11:57:04.283 +08:00] [INFO] [region_range_lock.go:389] ["unlocked range"] [changefeed=default-test-1_ddl_puller] [lockID=225] [regionID=16] [checkpointTs=435843087644753921] [startKey=748000fffffffffffffe5f720000000000fa] [endKey=748000fffffffffffffe5f730000000000fa]
[2022/09/08 11:57:04.283 +08:00] [INFO] [client.go:1122] ["stream to store closed"] [namespace=default] [changefeed=test-1_ddl_puller] [addr=10.2.6.70:20160] [storeID=1]
[2022/09/08 11:57:04.297 +08:00] [INFO] [region_range_lock.go:389] ["unlocked range"] [changefeed=default-test-1_ddl_puller] [lockID=223] [regionID=20] [checkpointTs=435843087644753921] [startKey=6d44444c4a6f624cff69ff737400000000ff0000f90000000000ff00006c0000000000fa] [endKey=6d44444c4a6f624cff69ff737400000000ff0000f90000000000ff00006d0000000000fa]
[2022/09/08 11:57:04.297 +08:00] [INFO] [client.go:1122] ["stream to store closed"] [namespace=default] [changefeed=test-1_ddl_puller] [addr=10.2.6.70:20160] [storeID=1]
[2022/09/08 11:57:04.297 +08:00] [INFO] [changefeed.go:591] ["changefeed closed"] [namespace=default] [changefeed=test-1] [info="{\"upstream-id\":7140504203510132547,\"namespace\":\"default\",\"changefeed-id\":\"test-1\",\"sink-uri\":\"tidb://root:xxxx@10.2.6.77:4000/?time-zone=\",\"create-time\":\"2022-09-08T11:49:52.909761018+08:00\",\"start-ts\":435842974673797122,\"target-ts\":0,\"admin-job-type\":1,\"sort-engine\":\"unified\",\"sort-dir\":\"\",\"config\":{\"case-sensitive\":true,\"enable-old-value\":true,\"force-replicate\":false,\"check-gc-safe-point\":true,\"enable-sync-point\":true,\"sync-point-interval\":30000000000,\"sync-point-retention\":3600000000000,\"filter\":{\"rules\":[\"test1.*\"],\"ignore-txn-start-ts\":null,\"event-filters\":null},\"mounter\":{\"worker-num\":16},\"sink\":{\"dispatchers\":null,\"protocol\":\"\",\"column-selectors\":null,\"schema-registry\":\"\",\"transaction-atomicity\":\"table\"},\"consistent\":{\"level\":\"eventual\",\"max-log-size\":64,\"flush-interval\":2000,\"storage\":\"s3://logbucket-1/test-changefeed?access-key=cdcs3accesskey\\u0026secret-access-key=cdcs3accesskey\\u0026endpoint=http://10.2.6.25:24927/\"}},\"state\":\"error\",\"error\":{\"addr\":\"10.2.7.49:8300\",\"code\":\"CDC:ErrS3StorageInitialize\",\"message\":\"[CDC:ErrS3StorageInitialize]new s3 storage for redo log: failed to get region of bucket logbucket-1: RequestError: send request failed\\ncaused by: dial tcp 10.2.6.25:24927: connect: connection refused\"},\"creator-version\":\"v6.3.0-master\"}"] [isRemoved=false]
[2022/09/08 11:57:04.298 +08:00] [WARN] [etcd_worker.go:269] ["EtcdWorker reactor tick took too long"] [duration=3m54.639913481s] [role=owner]
[2022/09/08 11:57:04.308 +08:00] [INFO] [gc_manager.go:94] ["update gc safe point success"] [gcSafePointTs=435828101199953920]
[2022/09/08 11:57:24.258 +08:00] [INFO] [feed_state_manager.go:494] ["changefeed restart backoff interval is changed"] [namespace=default] [changefeed=test-1] [oldInterval=19.980836439s] [newInterval=41.472161125s]
[2022/09/08 11:57:24.291 +08:00] [INFO] [ddl_sink.go:119] ["Try to create ddlSink based on sinkV2"]
[2022/09/08 11:57:24.291 +08:00] [INFO] [sink.go:183] ["succeed to parse parameter from sink uri"] [protocol=] [txnAtomicity=table]
[2022/09/08 11:57:24.307 +08:00] [INFO] [db_helper.go:186] ["sink uri is configured"] [dsn="root:******@tcp(10.2.6.77:4000)/?interpolateParams=true&multiStatements=true&allow_auto_random_explicit_insert=1&charset=utf8mb4&readTimeout=2m&sql_mode=%22ALLOW_INVALID_DATES%2CNO_AUTO_VALUE_ON_ZERO%2CIGNORE_SPACE%2CONLY_FULL_GROUP_BY%2CNO_ENGINE_SUBSTITUTION%22&tidb_placement_mode=%22ignore%22&tidb_txn_mode=optimistic&timeout=2m&transaction_isolation=%22READ-COMMITTED%22&writeTimeout=2m"]
[2022/09/08 11:57:24.312 +08:00] [INFO] [ddl_puller.go:634] ["DDL puller started"] [namespace=default] [changefeed=test-1_ddl_puller] [resolvedTS=435842974673797121]
[2022/09/08 11:57:24.312 +08:00] [INFO] [client.go:583] ["event feed started"] [namespace=default] [changefeed=test-1_ddl_puller] [startTs=435842974673797121] [span="[6d44444c4a6f624cff69ff737400000000ff0000f90000000000ff00006c0000000000fa, 6d44444c4a6f624cff69ff737400000000ff0000f90000000000ff00006d0000000000fa)"]
[2022/09/08 11:57:24.312 +08:00] [INFO] [client.go:583] ["event feed started"] [namespace=default] [changefeed=test-1_ddl_puller] [startTs=435842974673797121] [span="[748000fffffffffffffe5f720000000000fa, 748000fffffffffffffe5f730000000000fa)"]
[2022/09/08 11:57:24.312 +08:00] [INFO] [client.go:583] ["event feed started"] [namespace=default] [changefeed=test-1_ddl_puller] [startTs=435842974673797121] [span="[6d44444c4a6f6241ff64ff644964784c69ff7374ff0000000000ff000000f700000000ff0000006c00000000fb, 6d44444c4a6f6241ff64ff644964784c69ff7374ff0000000000ff000000f700000000ff0000006d00000000fb)"]
[2022/09/08 11:57:24.313 +08:00] [WARN] [s3.go:924] ["failed to request s3, retrying"] [error="RequestError: send request failed\ncaused by: dial tcp 10.2.6.25:24927: connect: connection refused"] [backoff=1.947423803s]
[2022/09/08 11:57:24.314 +08:00] [INFO] [region_range_lock.go:224] ["range locked"] [lockID=226] [regionID=20] [version=4] [checkpointTs=435842974673797121] [startKey=6d44444c4a6f624cff69ff737400000000ff0000f90000000000ff00006c0000000000fa] [endKey=6d44444c4a6f624cff69ff737400000000ff0000f90000000000ff00006d0000000000fa]
[2022/09/08 11:57:24.314 +08:00] [INFO] [region_range_lock.go:224] ["range locked"] [lockID=227] [regionID=16] [version=8] [checkpointTs=435842974673797121] [startKey=748000fffffffffffffe5f720000000000fa] [endKey=748000fffffffffffffe5f730000000000fa]
[2022/09/08 11:57:24.314 +08:00] [INFO] [region_range_lock.go:224] ["range locked"] [lockID=228] [regionID=20] [version=4] [checkpointTs=435842974673797121] [startKey=6d44444c4a6f6241ff64ff644964784c69ff7374ff0000000000ff000000f700000000ff0000006c00000000fb] [endKey=6d44444c4a6f6241ff64ff644964784c69ff7374ff0000000000ff000000f700000000ff0000006d00000000fb]
[2022/09/08 11:57:24.314 +08:00] [INFO] [puller.go:216] ["puller is initialized"] [namespace=default] [changefeed=test-1_ddl_puller] [tableID=-1] [resolvedTs=435842974673797121] [duration=1.850044ms] [spans="[\"[6d44444c4a6f624cff69ff737400000000ff0000f90000000000ff00006c0000000000fa, 6d44444c4a6f624cff69ff737400000000ff0000f90000000000ff00006d0000000000fa)\",\"[6d44444c4a6f6241ff64ff644964784c69ff7374ff0000000000ff000000f700000000ff0000006c00000000fb, 6d44444c4a6f6241ff64ff644964784c69ff7374ff0000000000ff000000f700000000ff0000006d00000000fb)\",\"[748000fffffffffffffe5f720000000000fa, 748000fffffffffffffe5f730000000000fa)\"]"]
[2022/09/08 11:57:24.315 +08:00] [INFO] [client.go:773] ["creating new stream to store to send request"] [namespace=default] [changefeed=test-1_ddl_puller] [regionID=20] [requestID=454] [storeID=1] [addr=10.2.6.70:20160]
[2022/09/08 11:57:24.315 +08:00] [INFO] [client.go:794] ["start new request"] [namespace=default] [changefeed=test-1_ddl_puller] [request="header:<cluster_id:7140504203510132547 ticdc_version:\"6.3.0-master\" > region_id:20 region_epoch:<conf_ver:1 version:4 > checkpoint_ts:435842974673797121 start_key:\"mDDLJobL\\377i\\377st\\000\\000\\000\\000\\377\\000\\000\\371\\000\\000\\000\\000\\000\\377\\000\\000l\\000\\000\\000\\000\\000\\372\" end_key:\"mDDLJobL\\377i\\377st\\000\\000\\000\\000\\377\\000\\000\\371\\000\\000\\000\\000\\000\\377\\000\\000m\\000\\000\\000\\000\\000\\372\" request_id:454 extra_op:ReadOldValue "] [addr=10.2.6.70:20160]
[2022/09/08 11:57:24.315 +08:00] [INFO] [client.go:773] ["creating new stream to store to send request"] [namespace=default] [changefeed=test-1_ddl_puller] [regionID=20] [requestID=456] [storeID=1] [addr=10.2.6.70:20160]
[2022/09/08 11:57:24.315 +08:00] [INFO] [mysql_ddl_sink.go:87] ["MySQL DDL sink is created"] [namespace=default] [changefeed=test-1]
[2022/09/08 11:57:24.316 +08:00] [INFO] [client.go:794] ["start new request"] [namespace=default] [changefeed=test-1_ddl_puller] [request="header:<cluster_id:7140504203510132547 ticdc_version:\"6.3.0-master\" > region_id:20 region_epoch:<conf_ver:1 version:4 > checkpoint_ts:435842974673797121 start_key:\"mDDLJobA\\377d\\377dIdxLi\\377st\\377\\000\\000\\000\\000\\000\\377\\000\\000\\000\\367\\000\\000\\000\\000\\377\\000\\000\\000l\\000\\000\\000\\000\\373\" end_key:\"mDDLJobA\\377d\\377dIdxLi\\377st\\377\\000\\000\\000\\000\\000\\377\\000\\000\\000\\367\\000\\000\\000\\000\\377\\000\\000\\000m\\000\\000\\000\\000\\373\" request_id:456 extra_op:ReadOldValue "] [addr=10.2.6.70:20160]
[2022/09/08 11:57:24.316 +08:00] [INFO] [client.go:773] ["creating new stream to store to send request"] [namespace=default] [changefeed=test-1_ddl_puller] [regionID=16] [requestID=455] [storeID=1] [addr=10.2.6.70:20160]
[2022/09/08 11:57:24.316 +08:00] [INFO] [client.go:794] ["start new request"] [namespace=default] [changefeed=test-1_ddl_puller] [request="header:<cluster_id:7140504203510132547 ticdc_version:\"6.3.0-master\" > region_id:16 region_epoch:<conf_ver:1 version:8 > checkpoint_ts:435842974673797121 start_key:\"t\\200\\000\\377\\377\\377\\377\\377\\377\\376_r\\000\\000\\000\\000\\000\\372\" end_key:\"t\\200\\000\\377\\377\\377\\377\\377\\377\\376_s\\000\\000\\000\\000\\000\\372\" request_id:455 extra_op:ReadOldValue "] [addr=10.2.6.70:20160]
[2022/09/08 11:57:24.326 +08:00] [INFO] [mysql_params.go:315] ["sink uri is configured"] [dsn="root:******@tcp(10.2.6.77:4000)/?interpolateParams=true&multiStatements=true&allow_auto_random_explicit_insert=1&charset=utf8mb4&readTimeout=2m&tidb_placement_mode=%22ignore%22&tidb_txn_mode=optimistic&timeout=2m&transaction_isolation=%22READ-COMMITTED%22&writeTimeout=2m"]
[2022/09/08 11:57:24.332 +08:00] [INFO] [mysql_syncpoint_store.go:146] ["Start mysql syncpoint sink"]
[2022/09/08 11:57:24.341 +08:00] [INFO] [ddl_sink.go:163] ["ddl sink initialized, start processing..."] [namespace=default] [changefeed=test-1] [duration=50.499034ms]
[2022/09/08 11:57:26.261 +08:00] [WARN] [s3.go:924] ["failed to request s3, retrying"] [error="RequestError: send request failed\ncaused by: dial tcp 10.2.6.25:24927: connect: connection refused"] [backoff=3.824482612s]
[2022/09/08 11:57:30.088 +08:00] [WARN] [s3.go:924] ["failed to request s3, retrying"] [error="RequestError: send request failed\ncaused by: dial tcp 10.2.6.25:24927: connect: connection refused"] [backoff=6.757070752s]
[2022/09/08 11:57:36.847 +08:00] [WARN] [s3.go:924] ["failed to request s3, retrying"] [error="RequestError: send request failed\ncaused by: dial tcp 10.2.6.25:24927: connect: connection refused"] [backoff=9.982022904s]
[2022/09/08 11:57:43.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=10.998774449s] [role=owner]
[2022/09/08 11:57:44.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=11.99927975s] [role=owner]
[2022/09/08 11:57:45.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=12.998911148s] [role=owner]
[2022/09/08 11:57:46.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=13.998596815s] [role=owner]
[2022/09/08 11:57:46.831 +08:00] [WARN] [s3.go:924] ["failed to request s3, retrying"] [error="RequestError: send request failed\ncaused by: dial tcp 10.2.6.25:24927: connect: connection refused"] [backoff=31.105431024s]
[2022/09/08 11:57:47.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=14.998926278s] [role=owner]
[2022/09/08 11:57:48.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=15.998923439s] [role=owner]
[2022/09/08 11:57:49.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=16.999419027s] [role=owner]
[2022/09/08 11:57:50.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=17.999416154s] [role=owner]
[2022/09/08 11:57:51.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=18.998482251s] [role=owner]
[2022/09/08 11:57:52.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=19.999215433s] [role=owner]
[2022/09/08 11:57:53.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=20.999343267s] [role=owner]
[2022/09/08 11:57:54.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=21.998768585s] [role=owner]
[2022/09/08 11:57:55.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=22.998997359s] [role=owner]
[2022/09/08 11:57:56.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=23.998526447s] [role=owner]
[2022/09/08 11:57:57.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=24.99923983s] [role=owner]
[2022/09/08 11:57:58.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=25.998397001s] [role=owner]
[2022/09/08 11:57:59.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=26.999119582s] [role=owner]
[2022/09/08 11:58:00.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=27.999244155s] [role=owner]
[2022/09/08 11:58:01.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=28.99842139s] [role=owner]
[2022/09/08 11:58:02.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=29.998723128s] [role=owner]
[2022/09/08 11:58:03.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=30.999210866s] [role=owner]
[2022/09/08 11:58:04.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=31.999418033s] [role=owner]
[2022/09/08 11:58:05.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=32.998992934s] [role=owner]
[2022/09/08 11:58:06.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=33.998835706s] [role=owner]
[2022/09/08 11:58:07.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=34.999068106s] [role=owner]
[2022/09/08 11:58:08.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=35.999382584s] [role=owner]
[2022/09/08 11:58:09.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=36.998384005s] [role=owner]
[2022/09/08 11:58:10.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=37.999378573s] [role=owner]
[2022/09/08 11:58:11.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=38.999099936s] [role=owner]
[2022/09/08 11:58:12.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=39.999036536s] [role=owner]
[2022/09/08 11:58:13.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=40.998995354s] [role=owner]
[2022/09/08 11:58:14.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=41.999156473s] [role=owner]
[2022/09/08 11:58:15.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=42.998613022s] [role=owner]
[2022/09/08 11:58:16.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=43.999136452s] [role=owner]
[2022/09/08 11:58:17.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=44.998971132s] [role=owner]
[2022/09/08 11:58:17.938 +08:00] [WARN] [s3.go:924] ["failed to request s3, retrying"] [error="RequestError: send request failed\ncaused by: dial tcp 10.2.6.25:24927: connect: connection refused"] [backoff=33.64112576s]
[2022/09/08 11:58:18.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=45.998953422s] [role=owner]
[2022/09/08 11:58:19.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=46.99900822s] [role=owner]
[2022/09/08 11:58:20.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=47.99861958s] [role=owner]
[2022/09/08 11:58:21.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=48.999159219s] [role=owner]
[2022/09/08 11:58:22.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=49.998995839s] [role=owner]
[2022/09/08 11:58:23.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=50.998660863s] [role=owner]
[2022/09/08 11:58:24.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=51.999351188s] [role=owner]
[2022/09/08 11:58:25.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=52.998399951s] [role=owner]
[2022/09/08 11:58:26.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=53.999041545s] [role=owner]
[2022/09/08 11:58:27.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=54.998888233s] [role=owner]
[2022/09/08 11:58:28.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=55.998811503s] [role=owner]
[2022/09/08 11:58:29.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=56.999092202s] [role=owner]
[2022/09/08 11:58:30.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=57.999270891s] [role=owner]
[2022/09/08 11:58:31.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=58.999182418s] [role=owner]
[2022/09/08 11:58:32.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=59.998841129s] [role=owner]
[2022/09/08 11:58:33.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m0.998989739s] [role=owner]
[2022/09/08 11:58:34.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m1.999271784s] [role=owner]
[2022/09/08 11:58:35.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m2.99922207s] [role=owner]
[2022/09/08 11:58:36.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m3.998393795s] [role=owner]
[2022/09/08 11:58:37.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m4.99920289s] [role=owner]
[2022/09/08 11:58:38.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m5.998759297s] [role=owner]
[2022/09/08 11:58:39.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m6.998701471s] [role=owner]
[2022/09/08 11:58:40.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m7.999300118s] [role=owner]
[2022/09/08 11:58:41.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m8.999216741s] [role=owner]
[2022/09/08 11:58:42.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m9.999151723s] [role=owner]
[2022/09/08 11:58:43.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m10.999171494s] [role=owner]
[2022/09/08 11:58:44.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m11.998720365s] [role=owner]
[2022/09/08 11:58:45.348 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m12.998688873s] [role=owner]
[2022/09/08 11:58:46.349 +08:00] [WARN] [client.go:259] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=1m13.998908016s] [role=owner]

```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
v6.3.0-master
```

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve?

Issue Number: close #7010 

### What is changed and how it works?
1. Make new s3 storage errors become an unretryable error, so owner would not retry it automatically, which can prevent owner got stuck in the initializing of s3 storage again and again.
2. Make the backend s3 storage retry policy configuable and set the maximum retry time to 3, which would cost about 10s.

So, after this PR, s3 storage connection error would only stuck owner about 10s.

#### Tests 

 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

File: cdc/redo/common/util.go [hunk 1]
```diff
@@ -120,3 +126,37 @@ func ParseLogFileName(name string) (uint64, string, error) {
 	}
 	return commitTs, fileType, nil
 }
+
+// retryerWithLog wrappes the client.DefaultRetryer, and logging when retry triggered.
```
Comment (zhaoxinyu) [inline cdc/redo/common/util.go:130]:
```suggestion
// retryerWithLog wraps the client.DefaultRetryer, and logs when retrying is triggered.
```

**Review by zhaoxinyu — APPROVED** [review]

File: dm/pkg/conn/basedb.go [hunk 2]
```diff
@@ -69,8 +69,8 @@ func (d *DefaultDBProviderImpl) Apply(config *config.DBConfig) (*BaseDB, error)
 		if loadErr := config.Security.LoadTLSContent(); loadErr != nil {
 			return nil, terror.ErrCtlLoadTLSCfg.Delegate(loadErr)
 		}
-		tlsConfig, err := util.ToTLSConfigWithVerifyByRawbytes(config.Security.SSLCABytes,
-			config.Security.SSLCertBytes, config.Security.SSLKEYBytes, config.Security.CertAllowedCN)
+		tlsConfig, err := util.ToTLSConfigWithVerify(config.Security.SSLCA,
```
Comment (D3Hunter) [inline dm/pkg/conn/basedb.go:72]: if we create task from dm api, there's no ca file, only ca bytes

/cc @lance6716

Comment (asddongmen) [reply dm/pkg/conn/basedb.go:72]: Can we just convert these bytes to string key?

Comment (lance6716) [reply dm/pkg/conn/basedb.go:72]: https://github.com/pingcap/tiflow/pull/6913

this is the new API
