### PR TITLE
mounter(ticdc): enum type default value set explicitly to avoid wrong enum value fetched by the encoder

### LINKED ISSUE #9259: type enum default value is ignored when mount the event
### What did you do?

```
create table t(a int primary key, state enum ("created", "working", "finished", "error") collate utf8mb4_general_ci not null default "created");
insert into t values (1, "working");
```

### What did you expect to see?

_No response_

### What did you see instead?

when drop the column `state` and insert new data at the delete-only phase, use old schema to parse the raw value, "created" should be used as the default value to fill the column.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #9259 

### What is changed and how it works?

* mounter set the default value for the enum type explicitly, to make `enum.Value` set correctly.

#### Tests 

 - Unit test

### Release note 

```release-note
`None`
```

### CODE REVIEW

File: cdc/entry/mounter_test.go [hunk 1]
```diff
@@ -957,7 +957,7 @@ func TestGetDefaultZeroValue(t *testing.T) {
 			ColInfo: timodel.ColumnInfo{FieldType: *ftTypeEnumNotNull},
 			// TypeEnum value will be a string and then translate to []byte
 			// NotNull && no default will choose first element
-			Res:     uint64(0),
+			Res:     uint64(1),
```
Comment (CharlesCheung96) [inline cdc/entry/mounter_test.go:960]: please add more tests and comments

**Review by charleszheng44 — APPROVED** [review]
LGTM

**Review by CharlesCheung96 — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]
