### PR TITLE
consumer(ticdc): do not panic the consumer if read previous offset message

### LINKED ISSUE #11386: kafka consumer may read previous message if commit message offset failed
```
[2024/07/03 23:24:56.556 +08:00] [ERROR] [consumer.go:136] ["commit message failed, just continue"] [error="Broker: Unknown member"]
[2024/07/03 23:24:56.587 +08:00] [ERROR] [consumer.go:126] ["read message failed, just continue to retry"] [error="Application maximum poll interval (300000ms) exceeded by 221ms"]
[2024/07/03 23:24:56.748 +08:00] [PANIC] [writer.go:388] ["RowChangedEvent fallback row, ignore it"] [commitTs=450892761914671327] [offset=55842905] [watermark=450892849772232846] [watermarkOffset=55934110] [partition=2] [tableID=339] [schema=sysbench_64_7000w] [table=sbtest57] [stack="main.(*writer).WriteMessage\n\[tgithub.com/pingcap/tiflow/cmd/kafka-consumer/writer.go:388\nmain.(*consumer).Consume\n\tgithub.com/pingcap/tiflow/cmd/kafka-consumer/consumer.go:129\nmain.main.func2\n\tgithub.com/pingcap/tiflow/cmd/kafka-consumer/main.go:101](http://tgithub.com/pingcap/tiflow/cmd/kafka-consumer/writer.go:388/nmain.(*consumer).Consume/n/tgithub.com/pingcap/tiflow/cmd/kafka-consumer/consumer.go:129/nmain.main.func2/n/tgithub.com/pingcap/tiflow/cmd/kafka-consumer/main.go:101)"]
```

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #11386 

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
`None`
```

### CODE REVIEW

File: cmd/kafka-consumer/writer.go [hunk 1]
```diff
@@ -384,13 +384,22 @@ func (w *writer) WriteMessage(ctx context.Context, message *kafka.Message) bool
 			watermark := atomic.LoadUint64(&progress.watermark)
 			// if the kafka cluster is normal, this should not hit.
 			// else if the cluster is abnormal, the consumer may consume old message, then cause the watermark fallback.
-			if row.CommitTs < watermark {
-				log.Panic("RowChangedEvent fallback row, ignore it",
+			if row.CommitTs < watermark && message.TopicPartition.Offset > progress.watermarkOffset {
+				if message.TopicPartition.Offset > progress.watermarkOffset {
+					log.Panic("RowChangedEvent fallback row, ignore it",
```
Comment (CharlesCheung96) [inline cmd/kafka-consumer/writer.go:389]: IMO, we panic here since the offset of single partition should never fall back?  If so, please correct the log message.

**Review by sdojjy — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]
