### PR TITLE
tools: bump golang.org/x/tools to v0.22.0 to fix panic on the mac os sonoma

### LINKED ISSUE #11329: go-generate panic on the mac os sonoma
golang.org/x/tools v7.0.0 cannot be compiled on the corresponding OS, bump it to `v0.22.0`

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #11329

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by lidezhu — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

File: dm/master/openapi_controller.go [hunk 1]
```diff
@@ -511,7 +511,8 @@ func (s *Server) getTask(ctx context.Context, taskName string, req openapi.DMAPI
 	return task, nil
 }
 
-func (s *Server) getTaskStatus(ctx context.Context, taskName string, req openapi.DMAPIGetTaskStatusParams) ([]openapi.SubTaskStatus, error) {
+func (s *Server) getTaskStatus(ctx context.Context, taskName string) ([]openapi.SubTaskStatus, error) {
+	req := openapi.DMAPIGetTaskStatusParams{}
 	if req.SourceNameList == nil || len(*req.SourceNameList) == 0 {
```
Comment (kennytm) [inline dm/master/openapi_controller.go:516]: doesn't this `if` condition becomes unconditionally `true` then?

Comment (lance6716) [reply dm/master/openapi_controller.go:516]: in all cases `req` is `openapi.DMAPIGetTaskStatusParams{}`, so the PR author just push down to here. I guess it's because OpenAPI is not finished developement but we don't have it in plan 😂

Comment (3AceShowHand) [reply dm/master/openapi_controller.go:516]: yes, it's always true i think.
