### PR TITLE
etcd (ticdc): fix etcd transaction operation out of limit. 

### LINKED ISSUE #7131: a large number of task/position found in the etcd cause the cdc cannot work.
### What did you do?

the capture panic and crashed frequently for a long period.

### What did you expect to see?

after the panic was fixed, the cdc server should works normally.

### What did you see instead?

```
[2022/09/20 16:23:35.659 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/3941cc8d-0f46-4a75-941f-a817d68a7bad/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.659 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/0597d9b4-65c9-4815-8c59-98a539ca35f5/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.659 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/c14fad0a-bf8e-4091-b94c-fd9e1db194fd/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.659 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/451e03cc-bb61-4c48-9bbc-9e35c197d2c8/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.659 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/5c78d40b-1217-4e6d-b96b-8a776011d5e1/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.659 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/b6fd703d-edbb-4315-90a6-3eb26d7fa4b3/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.659 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/a824103d-e271-40d1-81ef-5c8902eca794/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.659 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/d0d1b5af-1463-4eb5-8203-27d38c3a2c4e/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.659 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/28a168c2-6ad8-47fd-918f-224616c31a06/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.659 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/b0e2c01f-e52b-42de-9836-6599e085f45a/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.659 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/31cddbd1-a460-4409-b9d1-da5a1afc3989/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.659 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/bff36fdc-2caf-47eb-909b-e170e3c71fd5/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.659 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/5b54df1d-2c7b-4d41-a995-1e934009d3a6/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.659 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/b4511af6-f2a7-4cea-aeb2-80f8bec01940/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.659 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/72e49c50-cf9e-407d-8659-b782bfbb404a/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.659 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/07ca0e7d-0393-446c-8998-08245fabbc70/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.660 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/32130488-3538-4734-9a07-7deb47a4c86e/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.660 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/973c4f90-191d-4522-b8eb-0b3975c505ad/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.660 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/37ab8206-1be9-4090-aef2-dba5d35d3aab/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.660 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/e46f9e36-7f1f-4f84-8394-06edcb2f09e9/canal-json-kafka-test] [value=]
[2022/09/20 16:23:35.660 +08:00] [WARN] [batch.go:57] ["etcd txn ops exceed the limit"] [key=/tidb/cdc/default/default/task/position/65597121-adfb-4b88-8728-60de84e57318/canal-json-kafka-test] [value=]
...
[2022/09/20 16:23:35.723 +08:00] [INFO] [client.go:235] ["WatchWithChan exited"] [role=owner]
[2022/09/20 16:23:35.726 +08:00] [INFO] [capture.go:464] ["owner resigned successfully"] [captureID=97a65870-e9ce-49d1-9306-239eec1bed1a] [ownerRev=5130995]
[2022/09/20 16:23:35.726 +08:00] [WARN] [capture.go:467] ["run owner exited with error"] [captureID=97a65870-e9ce-49d1-9306-239eec1bed1a] [ownerRev=5130995] [error="[CDC:ErrEtcdTxnOpsExceed]patch ops:4002 of a single changefeed exceed etcd txn max ops:128"] [errorVerbose="[CDC:ErrEtcdTxnOpsExceed]patch ops:4002 of a single changefeed exceed etcd txn max ops:128\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/pkg/orchestrator.getBatchChangedState\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/batch.go:60\ngithub.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).applyPatchGroups\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:374\ngithub.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:234\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:491\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).campaignOwner\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:443\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func3\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:313\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/09/20 16:23:35.727 +08:00] [INFO] [capture.go:314] ["owner routine exited"] [captureID=97a65870-e9ce-49d1-9306-239eec1bed1a] [error="[CDC:ErrEtcdTxnOpsExceed]patch ops:4002 of a single changefeed exceed etcd txn max ops:128"] [errorVerbose="[CDC:ErrEtcdTxnOpsExceed]patch ops:4002 of a single changefeed exceed etcd txn max ops:128\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/pkg/orchestrator.getBatchChangedState\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/batch.go:60\ngithub.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).applyPatchGroups\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:374\ngithub.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:234\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:491\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).campaignOwner\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:443\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func3\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:313\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/09/20 16:23:35.727 +08:00] [INFO] [client.go:235] ["WatchWithChan exited"] [role=processor]
[2022/09/20 16:23:35.728 +08:00] [INFO] [processor.go:518] ["processor exited"] [capture=97a65870-e9ce-49d1-9306-239eec1bed1a] [namespace=default] [changefeed=canal-json-kafka-test] [error="[CDC:ErrAdminStopProcessor]stop processor by admin command"] [errorVerbose="[CDC:ErrAdminStopProcessor]stop processor by admin command\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/cdc/processor.(*processor).tick\n\tgithub.com/pingcap/tiflow/cdc/processor/processor.go:555\ngithub.com/pingcap/tiflow/cdc/processor.(*processor).Tick\n\tgithub.com/pingcap/tiflow/cdc/processor/processor.go:497\ngithub.com/pingcap/tiflow/cdc/processor.(*managerImpl).Tick\n\tgithub.com/pingcap/tiflow/cdc/processor/manager.go:128\ngithub.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:266\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:491\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func4\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:334\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/09/20 16:23:35.728 +08:00] [INFO] [processor.go:1050] ["processor closing ..."] [namespace=default] [changefeed=canal-json-kafka-test]
[2022/09/20 16:23:35.728 +08:00] [INFO] [processor.go:1111] ["processor closed"] [namespace=default] [changefeed=canal-json-kafka-test]
[2022/09/20 16:23:35.728 +08:00] [INFO] [capture.go:335] ["processor routine exited"] [captureID=97a65870-e9ce-49d1-9306-239eec1bed1a] [error="[CDC:ErrPDEtcdAPIError]etcd api call error: context canceled"] [errorVerbose="[CDC:ErrPDEtcdAPIError]etcd api call error: context canceled\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/pkg/errors.WrapError\n\tgithub.com/pingcap/tiflow/pkg/errors/helper.go:32\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:505\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func4\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:334\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/09/20 16:23:35.728 +08:00] [INFO] [capture.go:574] ["processor manager closed"] [captureID=97a65870-e9ce-49d1-9306-239eec1bed1a]
[2022/09/20 16:23:35.728 +08:00] [INFO] [capture.go:582] ["message router closed"] [captureID=97a65870-e9ce-49d1-9306-239eec1bed1a]
[2022/09/20 16:23:35.729 +08:00] [INFO] [client.go:771] ["[pd] stop fetching the pending tso requests due to context canceled"] [dc-location=global]
[2022/09/20 16:23:35.729 +08:00] [INFO] [client.go:709] ["[pd] exit tso dispatcher"] [dc-location=global]
[2022/09/20 16:23:35.730 +08:00] [INFO] [capture.go:275] ["the capture routine has exited"]
[2022/09/20 16:23:35.730 +08:00] [INFO] [client.go:771] ["[pd] stop fetching the pending tso requests due to context canceled"] [dc-location=global]
[2022/09/20 16:23:35.730 +08:00] [INFO] [client.go:709] ["[pd] exit tso dispatcher"] [dc-location=global]
[2022/09/20 16:23:35.730 +08:00] [ERROR] [server.go:267] ["http server error"] [error="[CDC:ErrServeHTTP]serve http error: mux: server closed"] [errorVerbose="[CDC:ErrServeHTTP]serve http error: mux: server closed\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/pkg/errors.WrapError\n\tgithub.com/pingcap/tiflow/pkg/errors/helper.go:32\ngithub.com/pingcap/tiflow/cdc/server.(*server).startStatusHTTP.func1\n\tgithub.com/pingcap/tiflow/cdc/server/server.go:267\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/09/20 16:23:35.730 +08:00] [WARN] [server.go:159] ["cdc server exits with error"] [error="[CDC:ErrEtcdTxnOpsExceed]patch ops:4002 of a single changefeed exceed etcd txn max ops:128"] [errorVerbose="[CDC:ErrEtcdTxnOpsExceed]patch ops:4002 of a single changefeed exceed etcd txn max ops:128\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/pkg/orchestrator.getBatchChangedState\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/batch.go:60\ngithub.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).applyPatchGroups\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:374\ngithub.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:234\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:491\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).campaignOwner\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:443\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func3\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:313\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/09/20 16:23:35.731 +08:00] [INFO] [server.go:395] ["table actor system closed"] [duration=278.121µs]
[2022/09/20 16:23:35.731 +08:00] [INFO] [compactor.go:142] ["compactor actor quit"] [ID=6]
[2022/09/20 16:23:35.731 +08:00] [INFO] [compactor.go:142] ["compactor actor quit"] [ID=1]
[2022/09/20 16:23:35.731 +08:00] [INFO] [compactor.go:142] ["compactor actor quit"] [ID=0]
[2022/09/20 16:23:35.731 +08:00] [INFO] [compactor.go:142] ["compactor actor quit"] [ID=7]
[2022/09/20 16:23:35.731 +08:00] [INFO] [compactor.go:142] ["compactor actor quit"] [ID=3]
[2022/09/20 16:23:35.731 +08:00] [INFO] [compactor.go:142] ["compactor actor quit"] [ID=4]
[2022/09/20 16:23:35.731 +08:00] [INFO] [compactor.go:142] ["compactor actor quit"] [ID=5]
[2022/09/20 16:23:35.731 +08:00] [INFO] [compactor.go:142] ["compactor actor quit"] [ID=2]
[2022/09/20 16:23:35.732 +08:00] [INFO] [db.go:265] ["db actor quit"] [ID=0]
[2022/09/20 16:23:35.732 +08:00] [INFO] [db.go:265] ["db actor quit"] [ID=4]
[2022/09/20 16:23:35.732 +08:00] [INFO] [db.go:265] ["db actor quit"] [ID=3]
[2022/09/20 16:23:35.732 +08:00] [INFO] [db.go:265] ["db actor quit"] [ID=7]
[2022/09/20 16:23:35.732 +08:00] [INFO] [db.go:265] ["db actor quit"] [ID=1]
[2022/09/20 16:23:35.732 +08:00] [INFO] [db.go:265] ["db actor quit"] [ID=6]
[2022/09/20 16:23:35.732 +08:00] [INFO] [db.go:265] ["db actor quit"] [ID=2]
[2022/09/20 16:23:35.732 +08:00] [INFO] [db.go:265] ["db actor quit"] [ID=5]
[2022/09/20 16:23:35.735 +08:00] [INFO] [server.go:402] ["sorter actor system closed"] [duration=3.505642ms]
[2022/09/20 16:23:35.735 +08:00] [INFO] [capture.go:574] ["processor manager closed"] [captureID=97a65870-e9ce-49d1-9306-239eec1bed1a]
[2022/09/20 16:23:35.735 +08:00] [INFO] [capture.go:582] ["message router closed"] [captureID=97a65870-e9ce-49d1-9306-239eec1bed1a]

```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve?

Issue Number: close #7131 

### What is changed and how it works?
Add `taskPosition`(s) cleaning logic to `func  DeleteCaptureInfo()` which will be call in a `defer` block when the capture exits, so all `taskPosition`(s) would be cleaned up at the same time. 

If we don't do this, when the `processor` or `owner` panic in the second `tick`, the stale  `taskPosition`(s) would leak since the `etcdWorker` can nerver go up to the stale keys cleaning logic. 

Finally, there will be a huge amount `taskPosition`(s) store in etcd and lead to a `etcd transaction operation out of limit` error.

#### Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)
1. Add a `log.Panic()` below `processor.go` line 559,  make cdc, and start the cdc server again and again.
2. Use `etcdctl` to check is there are leaked `taskPosition`.

### Release note 

```release-note
Fix a bug that may cause cdc unavaliable by commit too many operation in a etcd transaction.
```

### CODE REVIEW

File: cdc/processor/manager.go [hunk 1]
```diff
@@ -127,10 +127,6 @@ func (m *managerImpl) Tick(stdCtx context.Context, state orchestrator.ReactorSta
 		})
 		if err := p.Tick(ctx); err != nil {
 			m.closeProcessor(changefeedID)
-			if cerrors.ErrReactorFinished.Equal(errors.Cause(err)) {
-				continue
-			}
-			return state, errors.Trace(err)
```
Comment (asddongmen) [inline cdc/processor/manager.go:133]: we should return processor error no matter what it is.

Comment (hi-rustin) [reply cdc/processor/manager.go:133]: Can I ask why?

File: cdc/processor/processor.go [hunk 2]
```diff
@@ -507,13 +508,13 @@ func (p *processor) Tick(ctx cdcContext.Context) error {
...
 	p.refreshMetrics()
 
-	if err == nil {
-		return nil
-	}
 	return p.handleErr(err)
 }
 
 func (p *processor) handleErr(err error) error {
+	if err == nil {
```
Comment (hi-rustin) [inline cdc/processor/processor.go:515]: Why do we move this inside?

File: pkg/etcd/etcd.go [hunk 3]
```diff
@@ -547,10 +547,24 @@ func (c *CDCEtcdClientImpl) PutCaptureInfo(
...
+	}
+	// we need to clean all task position related to this capture when the capture is offline
+	// otherwise the task positions may leak
+	// TODO: use changefeed's name space
+	taskKey := TaskPositionKeyPrefix(c.ClusterID, model.DefaultNamespace)
+	// the taskKey format is /tidb/cdc/{clusterID}/{namespace}/task/position/{captureID}
+	taskKey = fmt.Sprintf("%s/%s", taskKey, captureID)
+	_, err = c.Client.Delete(ctx, taskKey, clientv3.WithPrefix())
+	if err != nil {
+		log.Warn("delete task position failed",
```
Comment (hi-rustin) [inline pkg/etcd/etcd.go:565]: Should we print other info? like cluster id and capture id.

**Comment by hi-rustin** [comment]
> What is changed and how it works?

Could you please answer this question and explain what's going on in your PR?

**Comment by hi-rustin** [comment]
> Fix etcd ops out of limit

From the user's perspective, this is difficult to understand.

File: cdc/processor/manager.go (hunk 1 above)
Comment (asddongmen) [reply cdc/processor/manager.go:133]: It is verbose, we don't need this `if` condiction indeed, since we should never return an processor error here.

File: cdc/processor/processor.go (hunk 2 above)
Comment (asddongmen) [reply cdc/processor/processor.go:515]: I just think it is more elegant.

File: pkg/etcd/etcd.go (hunk 3 above)
Comment (asddongmen) [reply pkg/etcd/etcd.go:565]: good idea.

File: cdc/processor/manager.go (hunk 1 above)
Comment (asddongmen) [reply cdc/processor/manager.go:133]: In the original logic, all errors return from `p.tick()` would be wrapped into a `ErrReactorFinished` error, as you can see in line:551, so all error return to here will be catch and the loop should continue. 
In addition, the processor's `handleErr()` has already patch a `taskPosition` to tell the owner it encounters an error,  we can just let go here.

File: cdc/processor/processor.go (hunk 2 above)
Comment (3AceShowHand) [reply cdc/processor/processor.go:515]: it looks that all the unit test in the file `processor_test.go` does not return an error from `p.Tick` method.

If it's possible, a new unit test covering return error logic is expected.

File: cdc/processor/manager.go (hunk 1 above)
Comment (asddongmen) [reply cdc/processor/manager.go:133]: @3AceShowHand  please see: https://github.com/pingcap/tiflow/pull/7216/files#diff-a92d89dfa9f192c1a4325f9600f7df6fb03de4361e37d9107982d585592c632eR550

**Review by 3AceShowHand — APPROVED** [review]

File: cdc/processor/processor_test.go [hunk 4]
```diff
@@ -547,7 +547,7 @@ func TestProcessorError(t *testing.T) {
 	p.sendError(cerror.ErrSinkURIInvalid)
 	err = p.Tick(ctx)
 	tester.MustApplyPatches()
-	require.True(t, cerror.ErrReactorFinished.Equal(errors.Cause(err)))
+	require.Error(t, err)
```
Comment (hi-rustin) [inline cdc/processor/processor_test.go:550]: Do we need to assert the error details?

**Review by hi-rustin — APPROVED** [review]

File: cdc/processor/processor_test.go (hunk 4 above)
Comment (asddongmen) [reply cdc/processor/processor_test.go:550]: no
