### PR TITLE
checker(dm): check the number of connections before starting

### LINKED ISSUE #5005: DM report confusing error message after "too many connection" error
### What did you do?

downstream limit max-server-connections to 50
start a task with two source

### What did you expect to see?

task fail with `downstream too many connection error`

### What did you see instead?

One source succeed, one source failed with error bad connection
```
{
            "result": false,
            "msg": "[code=38032:class=dm-master:scope=internal:level=high], Message: some error occurs in dm-worker: ErrCode:10002 ErrClass:\"database\" ErrScope:\"downstream\" ErrLevel:\"high\" Message:\"fail to initial unit Sync of subtask test : database driver\" RawCause:\"driver: bad connection\" Workaround:\"Please check the database connection, then use `pause-task` to pause the task and then use `resume-task` to resume the task.\" , Workaround: Please execute `query-status` to check status.",
            "source": "source2",
            "worker": "dm-127.0.0.1-8272"
        }
```

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
v5.4.0
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by buchuitoudegou**
### What problem does this PR solve?

Issue Number: close #5005 

### What is changed and how it works?
- add new checker to check the number of connections

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

Side effects

Related changes

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Comment by buchuitoudegou** [comment]
Will add ut later

File: dm/checker/checker.go [hunk 1]
```diff
@@ -250,6 +253,20 @@ func (c *Checker) Init(ctx context.Context) (err error) {
 		}
 	}
 
+	if _, ok := c.checkingItems[config.ConnAmountChecking]; ok {
+		if len(c.stCfgs) > 0 && len(c.instances) > 0 {
+			switch c.stCfgs[0].Mode {
+			case config.ModeAll:
+				c.checkList = append(c.checkList, checker.NewLoaderConnAmountCheker(c.instances[0].targetDB, c.stCfgs))
```
Comment (Ehco1996) [inline dm/checker/checker.go:260]: as this check is somthing about connection count,  do we need to put this item in the head of the check queue?

**Review by Ehco1996 — COMMENTED** [review]
restLGTM

File: dm/checker/checker.go (hunk 1 above)
Comment (buchuitoudegou) [reply dm/checker/checker.go:260]: Will fix it.

Comment (okJiang) [reply dm/checker/checker.go:260]: Checker list is parallel. So it doesn't matter.

https://github.com/pingcap/tiflow/blob/536e18274b90934d7611caca25e40f015e1c163a/dm/pkg/checker/real_checker.go#L131-L139

File: dm/pkg/checker/conn_checker.go [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+		Desc:  "check if user-specified amount of connection exceeds downstream's maximum",
+		State: StateFailure,
+	}
+	baseConn, err := c.targetDB.GetBaseConn(ctx)
+	if err != nil {
+		markCheckError(result, err)
+		return result
+	}
+	var rows *sql.Rows
+	rows, err = baseConn.QuerySQL(tcontext.NewContext(ctx, log.L()), "SHOW VARIABLES LIKE '%max_connections%'")
```
Comment (okJiang) [inline dm/pkg/checker/conn_checker.go:55]: You can reuse func `GetMaxConnections`.

Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go]: Yes. But `GetMaxConnections` has no retry strategy. Users have to retry by themselves if connection errors occur (#5015).

Actually, there are a bunch of different pkgs used for querying SQL, varying from implementation and retry strategy. `BaseConn` is good to have decent retry strategy as well as encapsulation. Should we refactor and integrate them as a whole package?

Comment (okJiang) [reply dm/pkg/checker/conn_checker.go]: lgtm

Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go]: Currently, @lance6716 is planning to refactor the syncer. Idk if this could be part of the plan cuz it seems like a big one to do.

**Review by Ehco1996 — APPROVED** [review]
LGTM

File: dm/pkg/checker/conn_checker.go [hunk 3]
```diff
@@ -0,0 +1,132 @@
...
+}
+
+type LoaderConnAmountChecker struct {
+	connAmountChecker
+}
+
+func NewLoaderConnAmountCheker(targetDB *conn.BaseDB, stCfgs []*config.SubTaskConfig) RealChecker {
+	return &LoaderConnAmountChecker{
+		connAmountChecker: newConnAmountChecker(targetDB, stCfgs, func(stCfgs []*config.SubTaskConfig) int {
+			loaderConn := 0
```
Comment (lichunzhu) [inline dm/pkg/checker/conn_checker.go:117]: loader's checkpoint db will use some connections. Does this part need to be calculated?

File: dm/pkg/checker/conn_checker.go [hunk 4]
```diff
@@ -0,0 +1,132 @@
...
+type SyncerConnAmountChecker struct {
+	connAmountChecker
+}
+
+func NewSyncerConnAmountCheker(targetDB *conn.BaseDB, stCfgs []*config.SubTaskConfig) RealChecker {
+	return &SyncerConnAmountChecker{
+		connAmountChecker: newConnAmountChecker(targetDB, stCfgs, func(stCfgs []*config.SubTaskConfig) int {
+			syncerConn := 0
+			for _, stCfg := range stCfgs {
+				syncerConn += stCfg.SyncerConfig.WorkerCount
```
Comment (lichunzhu) [inline dm/pkg/checker/conn_checker.go:95]: Ditto for syncer

**Review by lichunzhu — COMMENTED** [review]
Do we need a checker for dumpling?

File: dm/pkg/checker/conn_checker.go (hunk 3 above)
Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go:117]: I will have a look at it.

Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go:118]: Every unit maintains 1 db connection for checkpoint. I added it and left a comment. PTAL again😀

File: dm/dm/config/checking_item.go [hunk 5]
```diff
@@ -52,6 +53,7 @@ var AllCheckingItems = map[string]string{
 	ShardAutoIncrementIDChecking: "conflict auto increment ID of shard tables checking item",
 	OnlineDDLChecking:            "online ddl checking item",
 	BinlogDBChecking:             "binlog db checking item",
+	ConnAmountChecking:           "conn amount checking item",
```
Comment (lance6716) [inline dm/dm/config/checking_item.go:56]:
```suggestion
	ConnAmountChecking:           "connection amount checking item",
```

this is the displayed message, should be readable

File: dm/pkg/checker/conn_checker.go [hunk 6]
```diff
@@ -0,0 +1,154 @@
...
+	connAmountChecker
+}
+
+func NewSyncerConnAmountCheker(targetDB *conn.BaseDB, stCfgs []*config.SubTaskConfig) RealChecker {
+	return &SyncerConnAmountChecker{
+		connAmountChecker: newConnAmountChecker(targetDB, stCfgs, func(stCfgs []*config.SubTaskConfig) int {
+			syncerConn := 0
+			for _, stCfg := range stCfgs {
+				// syncer's worker and checkpoint (always keeps one db connection)
+				syncerConn += stCfg.SyncerConfig.WorkerCount + 1
```
Comment (lance6716) [inline dm/pkg/checker/conn_checker.go:96]: maybe syncer has a DDL connection?

File: dm/tests/dmctl_command/run.sh [hunk 7]
```diff
@@ -142,6 +145,39 @@ function run() {
 	fi
 }
 
+function test_full_mode_conn() {
```
Comment (lance6716) [inline dm/tests/dmctl_command/run.sh:148]: please check the actual connection is same as you expected by SHOW PROCESSLIST

**Review by lance6716 — APPROVED** [review]

**Review by lance6716 — CHANGES_REQUESTED** [review]
wrong action

File: dm/pkg/checker/conn_checker.go [hunk 8]
```diff
@@ -0,0 +1,154 @@
...
+}
+
+func (l *LoaderConnAmountChecker) Check(ctx context.Context) *Result {
+	return l.check(ctx, l.Name())
+}
+
+func NewDumperConnAmountChecker(targetDB *conn.BaseDB, dumperThreads int) RealChecker {
+	return &DumperConnAmountChecker{
+		connAmountChecker: newConnAmountChecker(targetDB, nil, func(_ []*config.SubTaskConfig) int {
+			return dumperThreads
```
Comment (lichunzhu) [inline dm/pkg/checker/conn_checker.go:139]: Dumpling needs a connection for generating dumping SQL and a connection for consistency control.
```suggestion
			return dumperThreads+2
```

**Review by lichunzhu — APPROVED** [review]
rest LGTM

File: dm/tests/dmctl_command/run.sh (hunk 7 above)
Comment (buchuitoudegou) [reply dm/tests/dmctl_command/run.sh:148]: Did you mean I should `start-task` and see if they are as expected?

Comment (lance6716) [reply dm/tests/dmctl_command/run.sh:148]: Yes. if you do this check, you can find the forgotten checkpoint/DDL connections on your own.

**Comment by buchuitoudegou** [comment]
The master holds the connection unexpectedly even after stopping the source. 

Will take a look at it and see if we should fix it.

**Comment by buchuitoudegou** [comment]
PTAL @lance6716

File: dm/pkg/checker/conn_checker.go [hunk 9]
```diff
@@ -0,0 +1,160 @@
...
+			return result
+		}
+	}
+	neededConn := c.getConfigConn(c.stCfgs)
+	if neededConn > maxConn {
+		result.Errors = append(
+			result.Errors,
+			NewError("downstream's max_connections: %d is less than the amount %s needs: %d", maxConn, c.workerName, neededConn),
+		)
+		result.Instruction = "set larger max_connections or reduce the pool size of dm"
```
Comment (lance6716) [inline dm/pkg/checker/conn_checker.go:78]:
```suggestion
		result.Instruction = "set larger max_connections or adjust the configuration of dm"
```
I'm not sure if pool size is a common name for loader/syncer that user knows what we are referring :thinking:

File: dm/pkg/checker/conn_checker.go [hunk 10]
```diff
@@ -0,0 +1,160 @@
...
+func NewSyncerConnAmountCheker(targetDB *conn.BaseDB, stCfgs []*config.SubTaskConfig) RealChecker {
+	return &SyncerConnAmountChecker{
+		connAmountChecker: newConnAmountChecker(targetDB, stCfgs, func(stCfgs []*config.SubTaskConfig) int {
+			syncerConn := 0
+			for _, stCfg := range stCfgs {
+				// 1. worker count
+				// 2. checkpoint
+				// 3. ddl connection
+				// 4. downstream tracker
+				// 5. shard group keeper
```
Comment (lance6716) [inline dm/pkg/checker/conn_checker.go:99]: this is pessimistic only?

File: dm/pkg/checker/conn_checker.go [hunk 11]
```diff
@@ -0,0 +1,160 @@
...
+type LoaderConnAmountChecker struct {
+	connAmountChecker
+}
+
+func NewLoaderConnAmountChecker(targetDB *conn.BaseDB, stCfgs []*config.SubTaskConfig) RealChecker {
+	return &LoaderConnAmountChecker{
+		connAmountChecker: newConnAmountChecker(targetDB, stCfgs, func(stCfgs []*config.SubTaskConfig) int {
+			loaderConn := 0
+			for _, stCfg := range stCfgs {
+				// loader's worker and checkpoint (always keeps one db connection)
```
Comment (lance6716) [inline dm/pkg/checker/conn_checker.go:125]: did you check lightning loader?

File: dm/pkg/checker/conn_checker.go (hunk 10 above)
Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go:99]: Actually, I couldn't find any long-living connection in both pessimistic and optimistic shardddl. Would you mind giving some hints?

File: dm/pkg/checker/conn_checker.go (hunk 11 above)
Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go:125]: It seems only one db connection is used for restoring in Lightning (another is for checkpoint). What about skipping this check when using lightning (not really necessary in this case)?

FYI: https://github.com/pingcap/tidb/blob/0e19c1cd647a63fbbabd253fe18a0d54478fee41/br/pkg/lightning/backend/tidb/tidb.go#L94

Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go:125]: It seems loader's config doesn't affect lightning's concurrency, which is related to concurrency of the physical machine.

File: dm/pkg/checker/conn_checker.go (hunk 9 above)
Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go]: address in 0c04e1a

File: dm/pkg/checker/conn_checker.go [hunk 12]
```diff
@@ -0,0 +1,160 @@
...
+	var rows *sql.Rows
+	rows, err = baseConn.QuerySQL(tcontext.NewContext(ctx, log.L()), "SHOW GLOBAL VARIABLES LIKE 'max_connections'")
+	if err != nil {
+		markCheckError(result, err)
+		return result
+	}
+	defer rows.Close()
+	var (
+		maxConn   int
+		_variable string
```
[the remark this answers is not in the document]
Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go]: 0c04e1a

File: dm/pkg/checker/conn_checker.go [hunk 13]
```diff
@@ -0,0 +1,160 @@
...
+	"database/sql"
+
+	"github.com/pingcap/tiflow/dm/dm/config"
+	"github.com/pingcap/tiflow/dm/pkg/conn"
+	tcontext "github.com/pingcap/tiflow/dm/pkg/context"
+	"github.com/pingcap/tiflow/dm/pkg/log"
+)
+
+type connAmountChecker struct {
+	targetDB *conn.BaseDB
```
[the remark this answers is not in the document]
Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go]: 0c04e1a

File: dm/dm/config/checking_item.go [hunk 14]
```diff
@@ -52,6 +53,7 @@ var AllCheckingItems = map[string]string{
 	ShardAutoIncrementIDChecking: "conflict auto increment ID of shard tables checking item",
 	OnlineDDLChecking:            "online ddl checking item",
 	BinlogDBChecking:             "binlog db checking item",
+	ConnAmountChecking:           "connection amount checking item",
```
[the remark this answers is not in the document]
Comment (buchuitoudegou) [reply dm/dm/config/checking_item.go]: 0c04e1a

**Comment by buchuitoudegou** [comment]
ping @lance6716

File: dm/pkg/checker/conn_checker.go (hunk 11 above)
Comment (lance6716) [reply dm/pkg/checker/conn_checker.go:126]: we should be able to change its concurrency, I'll add a working item to https://github.com/pingcap/tiflow/issues/3510 .

And lightning will become the default load unit implementation, so we should not skip checking it. Will think about it later

Comment (lance6716) [reply dm/pkg/checker/conn_checker.go:126]: Now I think we should assign the concurrency of tidb backend (cfg.App.RegionConcurrency ?) to LoaderConfig.PoolSize. We can finish it first before this PR, or you left a TODO in this PR and we merge this PR first.

File: dm/pkg/checker/conn_checker.go (hunk 10 above)
Comment (lance6716) [reply dm/pkg/checker/conn_checker.go:100]: I'm also not familiar with it. If you can give exact explanation in integration test it's OK.

My comment is "5. shard group keeper" is only for pessimistic sharding tasks. So if the task is not the mode we should not count for it.

Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go:100]: I found it's been changed recently (by the optimistic sharddl PR). I'll take a look at it again and see how it works right now😂

File: dm/pkg/checker/conn_checker.go (hunk 11 above)
Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go:126]: Have you filed a PR to resolve it? Perhaps I can leave a TODO here and see if I could work it out (in another PR to solve this).

Comment (lance6716) [reply dm/pkg/checker/conn_checker.go:125]: We can left a TODO here

**Comment by buchuitoudegou** [comment]
In addition to:
1. ddl connection
2. checkpoint connection
3. tracker
4. shard group keeper (pessimistic only)
5. online ddl

Syncer is suspected to have one more db connection, which is unexpected and a probable bug. This PR will be /hold until this is fixed.

**Comment by buchuitoudegou** [comment]
ptal @lance6716

File: dm/checker/checker.go [hunk 15]
```diff
@@ -144,6 +147,23 @@ func (c *Checker) Init(ctx context.Context) (err error) {
 	if egErr := eg.Wait(); egErr != nil {
 		return egErr
 	}
+	// check connections
+	if _, ok := c.checkingItems[config.ConnAmountChecking]; ok {
+		if len(c.stCfgs) > 0 && len(c.instances) > 0 {
```
Comment (lance6716) [inline dm/checker/checker.go:152]: no need to double check `c.instances`?

File: dm/checker/checker.go [hunk 16]
```diff
@@ -144,6 +147,23 @@ func (c *Checker) Init(ctx context.Context) (err error) {
...
+			switch c.stCfgs[0].Mode {
+			case config.ModeAll:
```
Comment (lance6716) [inline dm/checker/checker.go:154]: we can left a TODO for syncer here, otherwise reviewer may get confused why the two cases are same

File: dm/dm/config/checking_item.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (lance6716) [reply dm/dm/config/checking_item.go:56]: your commit is rollbacked

File: dm/dumpling/dumpling.go [hunk 17]
```diff
@@ -164,7 +164,9 @@ func (m *Dumpling) Process(ctx context.Context, pr chan pb.ProcessResult) {
 
 	newCtx, cancel := context.WithCancel(ctx)
 	var dumpling *export.Dumper
-
+	failpoint.Inject("longDumpProcess", func() {
+		m.dumpConfig.Rows = 0
```
Comment (lance6716) [inline dm/dumpling/dumpling.go:168]: why we need to set it?

**Review by lance6716 — COMMENTED** [review]
(reviewing)

File: dm/pkg/checker/conn_checker.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (lance6716) [reply dm/pkg/checker/conn_checker.go:27]: this change is also rollbacked

File: dm/pkg/checker/conn_checker.go [hunk 18]
```diff
@@ -0,0 +1,160 @@
...
+	}
+}
+
+func (c *connAmountChecker) check(ctx context.Context, checkerName string) *Result {
+	result := &Result{
+		Name:  checkerName,
+		Desc:  "check if user-specified amount of connection exceeds downstream's maximum",
+		State: StateFailure,
+	}
+	baseConn, err := c.targetDB.GetBaseConn(ctx)
```
[the remark this answers is not in the document]
Comment (lance6716) [reply dm/pkg/checker/conn_checker.go:50]: this change is also rollbacked

File: dm/pkg/checker/conn_checker.go [hunk 19]
```diff
@@ -0,0 +1,155 @@
...
+	for rows.Next() {
+		err = rows.Scan(&variable, &maxConn)
+		if err != nil {
+			markCheckError(result, err)
+			return result
+		}
+	}
+	neededConn := c.getConfigConn(c.stCfgs)
+	switch {
+	case maxConn != 0 && neededConn > maxConn:
```
Comment (lance6716) [inline dm/pkg/checker/conn_checker.go:75]: we might should also consider currect connections by SHOW PROCESSSLIST.

File: dm/pkg/checker/conn_checker.go [hunk 20]
```diff
@@ -0,0 +1,155 @@
...
+	}
+}
+
+func (l *LoaderConnAmountChecker) Name() string {
+	return "loader_conn_amount_checker"
+}
+
+func (l *LoaderConnAmountChecker) Check(ctx context.Context) *Result {
+	result := l.check(ctx, l.Name())
+	if !l.unlimitedConn && result.State == StateSuccess {
```
Comment (lance6716) [inline dm/pkg/checker/conn_checker.go:121]: maybe we should overwrite the result to warning for fail rather than for StateSuccess. Because lightning will not be blocked when the limit is lower than its need.

File: dm/pkg/checker/conn_checker.go (hunk 19 above)
Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go:75]: currect -> current?

The `maxConn` is returned by `SHOW GLOBAL VARIABLES LIKE 'max_connections'`, will it be affected by the `SHOW PROCESSSLIST `?

File: dm/pkg/checker/conn_checker.go (hunk 20 above)
Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go:121]: Then there is no errors but warning when using Lightning import if the connections is unlimited?

File: dm/pkg/checker/conn_checker.go (hunk 19 above)
Comment (lance6716) [reply dm/pkg/checker/conn_checker.go:75]: Yes current. if there'are already some connections established, we should take them into account

File: dm/pkg/checker/conn_checker.go (hunk 20 above)
Comment (lance6716) [reply dm/pkg/checker/conn_checker.go:121]: I think so. I guess although there's contention on MySQL connections, lightning should be able to finish import. (Please check if lightning will be blocked if some essential connections can't be established)

File: dm/dumpling/dumpling.go (hunk 17 above)
Comment (buchuitoudegou) [reply dm/dumpling/dumpling.go:168]: forbid concurrent dumping. But seems redundant here...it's 0 by default.

**Comment by buchuitoudegou** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/8062/pipeline

/run-dm-integration-test

File: dm/pkg/checker/conn_checker.go (hunk 20 above)
Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go]: 20edb4b

File: dm/pkg/checker/conn_checker.go (hunk 19 above)
Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go]: 20edb4b

File: dm/dumpling/dumpling.go (hunk 17 above)
Comment (buchuitoudegou) [reply dm/dumpling/dumpling.go]: 20edb4b

File: dm/checker/checker.go (hunk 16 above)
Comment (buchuitoudegou) [reply dm/checker/checker.go:154]: 20edb4b

File: dm/checker/checker.go (hunk 15 above)
Comment (buchuitoudegou) [reply dm/checker/checker.go]: 20edb4b

**Comment by buchuitoudegou** [comment]
ptal @lance6716

**Comment by lance6716** [comment]
CI failed 😄

**Comment by buchuitoudegou** [comment]
> CI failed 😄

Fixed

File: dm/checker/checker.go [hunk 21]
```diff
@@ -144,6 +147,25 @@ func (c *Checker) Init(ctx context.Context) (err error) {
 	if egErr := eg.Wait(); egErr != nil {
 		return egErr
 	}
+	// check connections
+	if _, ok := c.checkingItems[config.ConnAmountChecking]; ok {
+		if len(c.stCfgs) > 0 {
+			switch c.stCfgs[0].Mode {
```
Comment (lonng) [inline dm/checker/checker.go:153]: Why do we just check the first item?

Comment (lonng) [inline dm/checker/checker.go:153]: Why do we just check the first item?

Comment (buchuitoudegou) [reply dm/checker/checker.go:153]: `mode` is a global and unique parameter in a task. It's should be the same across all the subtask derived from the same task.

Comment (lonng) [reply dm/checker/checker.go:153]: Is there any code to ensure this behavior? It's better to leave some comments here to make code clear.

Comment (buchuitoudegou) [reply dm/checker/checker.go:153]: yes. will leave a comment here.

FYI: https://github.com/pingcap/tiflow/blob/bd0cc36dd74d12aa7a71a6a6fd7e9d51f14eb242/dm/config/task_converters.go#L49

Comment (buchuitoudegou) [reply dm/checker/checker.go:156]: 5827f28

File: dm/config/checking_item.go [hunk 22]
```diff
@@ -35,6 +35,7 @@ const (
 	ShardAutoIncrementIDChecking = "auto_increment_ID"
 	OnlineDDLChecking            = "online_ddl"
 	BinlogDBChecking             = "binlog_db"
+	ConnAmountChecking           = "conn_amount"
```
Comment (lance6716) [inline dm/config/checking_item.go:38]: should use conn_number. amount is uncountable. Also update other naming.

File: dm/pkg/checker/conn_checker.go [hunk 23]
```diff
@@ -0,0 +1,196 @@
...
+		stCfgs:        stCfgs,
+		getConfigConn: fn,
+		workerName:    workerName,
+	}
+}
+
+func (c *connAmountChecker) check(ctx context.Context, checkerName string) *Result {
+	result := &Result{
+		Name:  checkerName,
+		Desc:  "check if user-specified number of connection exceeds database's maximum",
```
Comment (lance6716) [inline dm/pkg/checker/conn_checker.go:48]:
```suggestion
		Desc:  "check if connetion concurrency exceeds database's maximum connection limit",
```

File: dm/pkg/checker/conn_checker.go [hunk 24]
```diff
@@ -0,0 +1,196 @@
...
+		State: StateFailure,
+	}
+	baseConn, err := c.toCheckDB.GetBaseConn(ctx)
+	//nolint:errcheck
+	defer c.toCheckDB.CloseBaseConn(baseConn)
```
Comment (lance6716) [inline dm/pkg/checker/conn_checker.go:53]: defer should be put after error check.

File: dm/pkg/checker/conn_checker.go [hunk 25]
```diff
@@ -0,0 +1,196 @@
...
+		err = rows.Scan(&variable, &maxConn)
+		if err != nil {
+			markCheckError(result, err)
+			return result
+		}
+	}
+	if maxConn == 0 {
+		c.unlimitedConn = true
+	}
+	processRows, err = baseConn.QuerySQL(tcontext.NewContext(ctx, log.L()), "SHOW PROCESSLIST")
```
Comment (lance6716) [inline dm/pkg/checker/conn_checker.go:79]: I remember we can re-use the connection for query before closing previous rows 🤔

File: dm/pkg/checker/conn_checker.go [hunk 26]
```diff
@@ -0,0 +1,196 @@
...
+		markCheckError(result, err)
+		return result
+	}
+	defer processRows.Close()
+	usedConn := 0
+	for processRows.Next() {
+		usedConn++
+	}
+	usedConn -= 1 // exclude the connection used for show processlist
+	log.L().Debug("connection checker", zap.Int("max_connections", maxConn), zap.Int("used_connections", usedConn))
```
Comment (lance6716) [inline dm/pkg/checker/conn_checker.go:90]:
```suggestion
	log.L().Debug("connection checker", zap.Int("maxConnections", maxConn), zap.Int("usedConnections", usedConn))
```

File: dm/pkg/checker/conn_checker.go [hunk 27]
```diff
@@ -0,0 +1,196 @@
...
+	)
+	for rows.Next() {
+		err = rows.Scan(&variable, &maxConn)
+		if err != nil {
+			markCheckError(result, err)
+			return result
+		}
+	}
+	if maxConn == 0 {
+		c.unlimitedConn = true
```
Comment (lance6716) [inline dm/pkg/checker/conn_checker.go:77]: seems we can return Success here

File: dm/pkg/checker/conn_checker.go (hunk 9 above)
Comment (lance6716) [reply dm/pkg/checker/conn_checker.go:112]: https://github.com/pingcap/tiflow/commit/0c04e1a67e3ffaa25b4618d3d02ffa48267e9d63 is rollbacked

File: dm/pkg/checker/conn_checker.go (hunk 27 above)
Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go:80]: 89e2d9d

File: dm/pkg/checker/conn_checker.go (hunk 25 above)
Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go:84]: 89e2d9d

File: dm/pkg/checker/conn_checker.go (hunk 24 above)
Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go:56]: 89e2d9d

File: dm/config/checking_item.go (hunk 22 above)
Comment (buchuitoudegou) [reply dm/config/checking_item.go]: 89e2d9d

File: dm/pkg/checker/conn_checker.go [hunk 28]
```diff
@@ -0,0 +1,196 @@
...
+	if err != nil {
+		markCheckError(result, err)
+		return result
+	}
+	var rows, processRows *sql.Rows
+	rows, err = baseConn.QuerySQL(tcontext.NewContext(ctx, log.L()), "SHOW GLOBAL VARIABLES LIKE 'max_connections'")
+	if err != nil {
+		markCheckError(result, err)
+		return result
+	}
```
Comment (lance6716) [inline dm/pkg/checker/conn_checker.go:66]: defer rows.Close(). Close() can be called for many times

File: dm/pkg/checker/conn_checker.go [hunk 29]
```diff
@@ -0,0 +1,196 @@
...
+	return "loader_conn_number_checker"
+}
+
+func (l *LoaderConnNumberChecker) Check(ctx context.Context) *Result {
+	result := l.check(ctx, l.Name())
+	if !l.unlimitedConn && result.State == StateFailure {
+		// if the max_connections is set as a specific number
+		// and we failed because of the number connecions needed is smaller than max_connections
+		for _, stCfg := range l.stCfgs {
+			if stCfg.NeedUseLightning() {
```
Comment (lance6716) [inline dm/pkg/checker/conn_checker.go:162]: not-use-lightning should have higher priority than use-lightning

File: dm/tests/dmctl_command/run.sh [hunk 30]
```diff
@@ -665,6 +731,34 @@ function run_validator_cmd {
 		"new\/ignored\/resolved: 0\/4\/0" 1
 }
 
+function run_check_task() {
+	source $cur/../dmctl_basic/check_list/check_task.sh
```
Comment (lance6716) [inline dm/tests/dmctl_command/run.sh:735]: do we need to source it again? line 104

File: dm/tests/dmctl_command/run.sh [hunk 31]
```diff
@@ -154,6 +155,71 @@ function run() {
...
+	run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
+		"check-task $cur/conf/dm-task2.yaml" \
+		"task precheck cannot accurately check the number of connection needed for Lightning, please set a sufficiently large connections for TiDB" 1
+}
+
+function check_full_mode_conn() {
+	# TODO: currently, pool-size are not efficacious for Lightning
+	# which simply determines the concurrency by hardware conditions.
+	# This should be solved in the future.
+	run_sql_tidb "set @@GLOBAL.max_connections=151;"
```
Comment (lance6716) [inline dm/tests/dmctl_command/run.sh:195]: we can limit the connection to 4 and 6 respectively, to test `getConfigConn` is correct

**Review by lance6716 — COMMENTED** [review]
rest lgtm

File: dm/tests/dmctl_command/run.sh (hunk 31 above)
Comment (buchuitoudegou) [reply dm/tests/dmctl_command/run.sh:195]: All these tests are latently checking the correctness of `getConfigConn`. For example, in `checktask_full_mode_conn`, when I set the `max_connections` to 3, the checker can fail, whilst, when I set it to 4, the checker can pass. In this sense, the checker-or more specifically, the `getConfigConn`-is expected to return the value 4 with respect to our config setting, and whether it passes this test or not categorically indicates if it can work accurately.

And in terms of this test, `check_full_mode_conn`, has a disparate intention to evaluate whether the number of connections established between DM and the databases is precisely what we expect beforehand.

File: dm/tests/dmctl_command/run.sh (hunk 30 above)
Comment (buchuitoudegou) [reply dm/tests/dmctl_command/run.sh:735]: will remove one of them

File: dm/pkg/checker/conn_checker.go (hunk 29 above)
Comment (buchuitoudegou) [reply dm/pkg/checker/conn_checker.go:162]: Would you mind suggesting more about this?

File: dm/tests/dmctl_command/run.sh (hunk 31 above)
Comment (lance6716) [reply dm/tests/dmctl_command/run.sh:195]: OK I think SHOW PROCESSLIST and check_rows_equal should be enough

File: dm/pkg/checker/conn_checker.go (hunk 29 above)
Comment (lance6716) [reply dm/pkg/checker/conn_checker.go:162]: sorry I forget all load units are connected to one downstream, so if any one of them is lightning it will become a "soft" limit.

**Review by lance6716 — APPROVED** [review]

**Comment by buchuitoudegou** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/8306/pipeline

/run-dm-integration-test

**Comment by buchuitoudegou** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/8315/pipeline

sequence_sharding_optimistic failed

/run-dm-integration-test

**Comment by lance6716** [comment]
> https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/8315/pipeline
> 
> sequence_sharding_optimistic failed
> 
> /run-dm-integration-test

please open an issue for them. I'm afraid we will forget them.

**Comment by buchuitoudegou** [comment]
> > https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/8315/pipeline
> > sequence_sharding_optimistic failed
> > /run-dm-integration-test
> 
> please open an issue for them. I'm afraid we will forget them.

note in this issue https://github.com/pingcap/tiflow/issues/5731

**Comment by buchuitoudegou** [comment]
> > https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/8315/pipeline
> > sequence_sharding_optimistic failed
> > /run-dm-integration-test
> 
> please open an issue for them. I'm afraid we will forget them.

https://github.com/pingcap/tiflow/issues/6515

**Comment by buchuitoudegou** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/8320/pipeline

shardddl3-1

/run-dm-integration-test

**Comment by buchuitoudegou** [comment]
> https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/8320/pipeline
> 
> shardddl3-1
> 
> /run-dm-integration-test

similar to this: https://github.com/pingcap/tiflow/issues/3461

**Comment by buchuitoudegou** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/8324/pipeline

/run-dm-integration-test

**Comment by buchuitoudegou** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/8326/pipeline

shardddl3-1 again

/run-dm-integration-test

**Comment by buchuitoudegou** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/8329/pipeline

/run-dm-integration-test

**Comment by buchuitoudegou** [comment]
checkpoint_transaction
```
[2022-07-29T07:07:41.645Z] [2022/07/29 15:04:00.319 +08:00] [ERROR] [baseconn.go:184] ["execute statement failed"] [task=sequence_sharding_removemeta] [unit=load] [query="CREATE TABLE `t_target` (`id` bigint NOT NULL AUTO_INCREMENT,`uid` int DEFAULT NULL,`name` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL,`c` int DEFAULT NULL,`d` int DEFAULT NULL,`e` int DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `uid` (`uid`),KEY `c` (`c`),KEY `d` (`d`),KEY `e` (`e`)) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;"] [argument="[]"] [error="Error 1050: Table 't_target' already exists"]
```

**Comment by lance6716** [comment]
> checkpoint_transaction
> 
> ```
> [2022-07-29T07:07:41.645Z] [2022/07/29 15:04:00.319 +08:00] [ERROR] [baseconn.go:184] ["execute statement failed"] [task=sequence_sharding_removemeta] [unit=load] [query="CREATE TABLE `t_target` (`id` bigint NOT NULL AUTO_INCREMENT,`uid` int DEFAULT NULL,`name` varchar(20) COLLATE utf8mb4_bin DEFAULT NULL,`c` int DEFAULT NULL,`d` int DEFAULT NULL,`e` int DEFAULT NULL,PRIMARY KEY (`id`),UNIQUE KEY `uid` (`uid`),KEY `c` (`c`),KEY `d` (`d`),KEY `e` (`e`)) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;"] [argument="[]"] [error="Error 1050: Table 't_target' already exists"]
> ```

this is an acceptable error, not the root cause. please open an issue
