### PR TITLE
sink(ticdc): fix `Unknown system variable 'transaction_isolation'` for some mysql versions

### LINKED ISSUE #4504: sink to mariadb 10.6.5 fails with unknown system variable transaction_isolation
### What did you do?

Create a sink to downstream mariadb 10.6.5.

### What did you expect to see?

The downstream can be created without any errors.

### What did you see instead?

```bash
$ ./cdc cli changefeed list
[
  {
    "id": "test",
    "summary": {
      "state": "error",
      "tso": 431019101257728000,
      "checkpoint": "2022-02-07 12:16:27.000",
      "error": {
        "addr": "192.168.101.2:8300",
        "code": "CDC:ErrOwnerUnknown",
        "message": "[CDC:ErrMySQLConnectionError]fail to open MySQL connection: Error 1193: Unknown system variable 'transaction_isolation'"
      }
    }
  }
]

$ mysql -h 127.0.0.1 -P 3306 -u root -p -e "show variables like '%isolation%'";
Enter password:
+---------------+-----------------+
| Variable_name | Value           |
+---------------+-----------------+
| tx_isolation  | REPEATABLE-READ |
+---------------+-----------------+
```

Seems in mariadb 10.6.5 the variable name has been changed from "transaction_isolation" to "tx_isolation", and it causes the failure.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve?

Issue Number: close #4504

### What is changed and how it works?
Since MySQL 5.7/MySQL 8/Mariadb may use transaction_isolation or tx_isolation, we first select the variable and use the right variable after that. 

### Check List 

Tests 

 - Unit test

### Release note 

```release-note
fix `Unknown system variable 'transaction_isolation'` for some mysql versions
```

### CODE REVIEW

**Comment by zhaoxinyu** [comment]
test case `TestApplyDMLs` failed. PTAL @[maxshuang](https://github.com/maxshuang)

**Comment by maxshuang** [comment]
> test case `TestApplyDMLs` failed. PTAL @[maxshuang](https://github.com/maxshuang)

Thanks for reminding. I have fixed it.

**Review by zhaoxinyu — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

File: cdc/sink/mysql_params.go [hunk 1]
```diff
@@ -287,6 +285,18 @@ func generateDSNByParams(
...
+	// transaction_isolation is mysql newly introduced variable and will vary from MySQL5.7/MySQL8.0/Mariadb
+	isolation, err := checkTiDBVariable(ctx, testDB, "transaction_isolation", defaultTxnIsolationRC)
+	if err != nil {
+		return "", err
+	}
+	if isolation != "" {
+		dsnCfg.Params["transaction_isolation"] = fmt.Sprintf(`"%s"`, defaultTxnIsolationRC)
+	} else {
+		dsnCfg.Params["tx_isolation"] = fmt.Sprintf(`"%s"`, defaultTxnIsolationRC)
+	}
```
Comment (amyangfei) [inline cdc/sink/mysql_params.go:298]: What about checking and setting, in case of both `transaction_isolation` and `tx_isolation` are unknown system variable.

```go

err = checkAndSet("transaction_isolation")
// check error
err = checkAndSet("tx_isolation)
// check error

func checkAndSet(var string) error {
  isolation, err := checkTiDBVariable(ctx, testDB, var, defaultTxnIsolationRC)
  if err != nil {
    return err
  }
  if isolation != "" {
    dsnCfg.Params[var] = fmt.Sprintf(`"%s"`, defaultTxnIsolationRC)
  }
  return nil
}

```

Comment (maxshuang) [reply cdc/sink/mysql_params.go:298]: It may happens for some very old mysql.  
But I think it's ok now.

Comment (amyangfei) [reply cdc/sink/mysql_params.go:298]: well, these two variables co-exist in some MySQL versions.

**Review by amyangfei — APPROVED** [review]
