### PR TITLE
sink(ticdc): add max allowed packet parmameters in sink dsn

### LINKED ISSUE #8622: Compare with v6.6.0, v7.0.0 has 140%-180% performance regression with errors on sysbench oltp_write_only workload
### What did you do?

1. deploy 2 TiDB and cdc
2. run sysbench oltp_write_only

### What did you expect to see?

No performance regression, the cdc_changefeed_checkpoint_lag is similar.

### What did you see instead?

image

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
v7.0.0
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
v7.0.0
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
v7.0.0
```

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve?

Issue Number: close #8622

### What is changed and how it works?

Set `maxAllowedPacket` to zero in sink dsn, in order to fetch `max_allowed_packet` value from downstream server automatically, the default value of go-sql-driver is 4MB, which is too small in some scenarios, especially after we enable multi statements SQL feature.

If data size is larger than `max_allowed_packet` in driver, following error may be raised from sql driver.

```
[2023/03/22 13:48:21.763 +08:00] [ERROR] [packets.go:37] ["read tcp [10.233.80.158:39226](http://10.233.80.158:39226/)->[10.233.80.28:4000](http://10.233.80.28:4000/): i/o timeout"] [component="[mysql]"]
```
#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

File: pkg/sink/mysql/db_helper.go [hunk 1]
```diff
@@ -339,7 +341,7 @@ func QueryMaxPreparedStmtCount(ctx context.Context, db *sql.DB) (int, error) {
 
 // QueryMaxAllowedPacket gets the value of max_allowed_packet
 func QueryMaxAllowedPacket(ctx context.Context, db *sql.DB) (int64, error) {
-	row := db.QueryRowContext(ctx, "select @@global.max_allowed_packet;")
+	row := db.QueryRowContext(ctx, "select @@session.max_allowed_packet;")
```
Comment (amyangfei) [inline pkg/sink/mysql/db_helper.go:344]:
```suggestion
	row := db.QueryRowContext(ctx, "select @@global.max_allowed_packet;")
```

**Review by hicqu — APPROVED** [review]
