### PR TITLE
observer(ticdc): reduce observer logs when error happens

### LINKED ISSUE #8354: When downstream is mysql, there is a lot of ERROR log that will confuse the user.
### What did you do?

create a changefeed sink to mysql.

### What did you expect to see?

no error log

### What did you see instead?

There is a lot of this log:
```
[2023/02/23 12:23:16.525 +08:00] [ERROR] [changefeed.go:939] ["backend observer tick error"] [error="[CDC:ErrMySQLQueryError]MySQL query error: Error 1105 (HY000): query metric error: [domain:9009]Prometheus address is not set in PD and etcd"] [errorVerbose="[CDC:ErrMySQLQueryError]MySQL query error: Error 1105 (HY000): query metric error: [domain:9009]Prometheus address is not set in PD and etcd\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/normalize.go:164\ngithub.com/pingcap/tiflow/pkg/errors.WrapError\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/pkg/errors/helper.go:34\ngithub.com/pingcap/tiflow/pkg/sink/observer.queryMetrics[...]\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/pkg/sink/observer/tidb.go:256\ngithub.com/pingcap/tiflow/pkg/sink/observer.(*TiDBObserver).Tick\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/pkg/sink/observer/tidb.go:126\ngithub.com/pingcap/tiflow/cdc/owner.(*changefeed).tickDownstreamObserver.func1\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cdc/owner/changefeed.go:938\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594"]
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve?

Issue Number: close #8354

### What is changed and how it works?

- Don't log anything if prometheus is not deployed.
- Log observer error every 30s when error happens.

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by nongfushanquan — APPROVED** [review]

File: cdc/owner/changefeed.go [hunk 1]
```diff
@@ -1045,13 +1048,23 @@ func (c *changefeed) checkUpstream() (skip bool, err error) {
...
 			cctx, cancel := context.WithTimeout(ctx, time.Second*5)
 			defer cancel()
 			if err := c.downstreamObserver.Tick(cctx); err != nil {
-				log.Error("backend observer tick error", zap.Error(err))
+				// Prometheus is not deployed, it happens in non production env.
+				if strings.Contains(err.Error(),
+					fmt.Sprintf(":%d", errno.ErrPrometheusAddrIsNotSet)) {
+					return
+				}
+				log.Warn("backend observer tick error", zap.Error(err))
```
Comment (CharlesCheung96) [inline cdc/owner/changefeed.go:1066]: If the downstream is mysql, can the warn logs here be masked?

Comment (amyangfei) [reply cdc/owner/changefeed.go:1066]: If backend is MySQL, `downstreamObserver` is a dummy observer and err is always nil here.

**Review by CharlesCheung96 — APPROVED** [review]
