### PR TITLE
DM: Fix some unstable tests

### LINKED ISSUE #5488: DM optimistic test fail to check conflicting statement
### Which jobs are flaking?

IT shardddl2/DM-040 optimistic

### Which test(s) are flaking?

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/5856/pipeline/

### Jenkins logs or GitHub Actions link

```log
[2022-05-18T09:51:23.369Z] command: query-status test ALTER TABLE `shardddl`.`tb` ADD COLUMN `col1` VARCHAR(10) CHARACTER SET UTF8MB4 count: 0 != expected: 1, failed the 9-th time, will retry again

[2022-05-18T09:51:25.271Z] {

[2022-05-18T09:51:25.271Z]     "result": true,

[2022-05-18T09:51:25.271Z]     "msg": "",

[2022-05-18T09:51:25.271Z]     "sources": [

[2022-05-18T09:51:25.271Z]         {

[2022-05-18T09:51:25.271Z]             "result": true,

[2022-05-18T09:51:25.271Z]             "msg": "",

[2022-05-18T09:51:25.271Z]             "sourceStatus": {

[2022-05-18T09:51:25.271Z]                 "source": "mysql-replica-01",

[2022-05-18T09:51:25.271Z]                 "worker": "worker1",

[2022-05-18T09:51:25.271Z]                 "result": null,

[2022-05-18T09:51:25.271Z]                 "relayStatus": null

[2022-05-18T09:51:25.271Z]             },

[2022-05-18T09:51:25.271Z]             "subTaskStatus": [

[2022-05-18T09:51:25.271Z]                 {

[2022-05-18T09:51:25.271Z]                     "name": "test",

[2022-05-18T09:51:25.271Z]                     "stage": "Running",

[2022-05-18T09:51:25.271Z]                     "unit": "Sync",

[2022-05-18T09:51:25.271Z]                     "result": null,

[2022-05-18T09:51:25.271Z]                     "unresolvedDDLLockID": "",

[2022-05-18T09:51:25.271Z]                     "sync": {

[2022-05-18T09:51:25.271Z]                         "totalEvents": "1",

[2022-05-18T09:51:25.271Z]                         "totalTps": "0",

[2022-05-18T09:51:25.271Z]                         "recentTps": "0",

[2022-05-18T09:51:25.271Z]                         "masterBinlog": "(dm-integration-test-go1180-5856-w0r39-g61g0-bin.000001, 65389)",

[2022-05-18T09:51:25.271Z]                         "masterBinlogGtid": "31020cc0-d68f-11ec-aeb2-0eaa92587239:1-299",

[2022-05-18T09:51:25.271Z]                         "syncerBinlog": "(dm-integration-test-go1180-5856-w0r39-g61g0-bin.000001, 64374)",

[2022-05-18T09:51:25.271Z]                         "syncerBinlogGtid": "31020cc0-d68f-11ec-aeb2-0eaa92587239:1-295",

[2022-05-18T09:51:25.271Z]                         "blockingDDLs": [

[2022-05-18T09:51:25.271Z]                         ],

[2022-05-18T09:51:25.271Z]                         "unresolvedGroups": [

[2022-05-18T09:51:25.272Z]                         ],

[2022-05-18T09:51:25.272Z]                         "synced": false,

[2022-05-18T09:51:25.272Z]                         "binlogType": "remote",

[2022-05-18T09:51:25.272Z]                         "secondsBehindMaster": "0",

[2022-05-18T09:51:25.272Z]                         "blockDDLOwner": "mysql-replica-01-`shardddl1`.`tb1`",

[2022-05-18T09:51:25.272Z]                         "conflictMsg": "[code=11111:class=functional:scope=internal:level=medium], Message: fail to try sync the optimistic shard ddl lock test-`shardddl`.`tb`: there will be conflicts if DDLs ALTER TABLE `shardddl`.`tb` ADD COLUMN `col1` VARCHAR(10) CHARACTER SET UTF8 COLLATE utf8_bin are applied to the downstream. old table info: CREATE TABLE `tbl`(`id` INT(11) NOT NULL, PRIMARY KEY (`id`)) CHARSET UTF8MB4 COLLATE UTF8MB4_BIN, new table info: CREATE TABLE `tbl`(`col1` VARCHAR(10) CHARACTER SET UTF8 COLLATE utf8_bin, `id` INT(11) NOT NULL, PRIMARY KEY (`id`)) CHARSET UTF8MB4 COLLATE UTF8MB4_BIN, Workaround: Please use `show-ddl-locks` command for more details."

[2022-05-18T09:51:25.272Z]                     }

[2022-05-18T09:51:25.272Z]                 }

[2022-05-18T09:51:25.272Z]             ]

[2022-05-18T09:51:25.272Z]         },

[2022-05-18T09:51:25.272Z]         {

[2022-05-18T09:51:25.272Z]             "result": true,

[2022-05-18T09:51:25.272Z]             "msg": "",

[2022-05-18T09:51:25.272Z]             "sourceStatus": {

[2022-05-18T09:51:25.272Z]                 "source": "mysql-replica-02",

[2022-05-18T09:51:25.272Z]                 "worker": "worker2",

[2022-05-18T09:51:25.272Z]                 "result": null,

[2022-05-18T09:51:25.272Z]                 "relayStatus": {

[2022-05-18T09:51:25.272Z]                     "masterBinlog": "(dm-integration-test-go1180-5856-w0r39-g61g0-bin.000001, 73193)",

[2022-05-18T09:51:25.272Z]                     "masterBinlogGtid": "32dfd3b4-d68f-11ec-9725-0eaa92587239:1-307",

[2022-05-18T09:51:25.272Z]                     "relaySubDir": "32dfd3b4-d68f-11ec-9725-0eaa92587239.000001",

[2022-05-18T09:51:25.272Z]                     "relayBinlog": "(dm-integration-test-go1180-5856-w0r39-g61g0-bin.000001, 73193)",

[2022-05-18T09:51:25.272Z]                     "relayBinlogGtid": "32dfd3b4-d68f-11ec-9725-0eaa92587239:1-307",

[2022-05-18T09:51:25.272Z]                     "relayCatchUpMaster": true,

[2022-05-18T09:51:25.272Z]                     "stage": "Running",

[2022-05-18T09:51:25.272Z]                     "result": null

[2022-05-18T09:51:25.272Z]                 }

[2022-05-18T09:51:25.272Z]             },

[2022-05-18T09:51:25.272Z]             "subTaskStatus": [

[2022-05-18T09:51:25.272Z]                 {

[2022-05-18T09:51:25.272Z]                     "name": "test",

[2022-05-18T09:51:25.272Z]                     "stage": "Running",

[2022-05-18T09:51:25.272Z]                     "unit": "Sync",

[2022-05-18T09:51:25.272Z]                     "result": null,

[2022-05-18T09:51:25.272Z]                     "unresolvedDDLLockID": "",

[2022-05-18T09:51:25.272Z]                     "sync": {

[2022-05-18T09:51:25.272Z]                         "totalEvents": "10",

[2022-05-18T09:51:25.272Z]                         "totalTps": "0",

[2022-05-18T09:51:25.272Z]                         "recentTps": "0",

[2022-05-18T09:51:25.272Z]                         "masterBinlog": "(dm-integration-test-go1180-5856-w0r39-g61g0-bin.000001, 73193)",

[2022-05-18T09:51:25.272Z]                         "masterBinlogGtid": "32dfd3b4-d68f-11ec-9725-0eaa92587239:1-307",

[2022-05-18T09:51:25.272Z]                         "syncerBinlog": "(dm-integration-test-go1180-5856-w0r39-g61g0-bin|000001.000001, 72623)",

[2022-05-18T09:51:25.272Z]                         "syncerBinlogGtid": "32dfd3b4-d68f-11ec-9725-0eaa92587239:1-305",

[2022-05-18T09:51:25.272Z]                         "blockingDDLs": [

[2022-05-18T09:51:25.272Z]                         ],

[2022-05-18T09:51:25.272Z]                         "unresolvedGroups": [

[2022-05-18T09:51:25.272Z]                         ],

[2022-05-18T09:51:25.272Z]                         "synced": false,

[2022-05-18T09:51:25.272Z]                         "binlogType": "local",

[2022-05-18T09:51:25.272Z]                         "secondsBehindMaster": "0",

[2022-05-18T09:51:25.272Z]                         "blockDDLOwner": "",

[2022-05-18T09:51:25.272Z]                         "conflictMsg": ""

[2022-05-18T09:51:25.272Z]                     }

[2022-05-18T09:51:25.272Z]                 }

[2022-05-18T09:51:25.272Z]             ]

[2022-05-18T09:51:25.272Z]         }

[2022-05-18T09:51:25.272Z]     ]

[2022-05-18T09:51:25.272Z] }
```

### Anything else we need to know

the conflict is expect, but the conflict statement is not right.
it may be caused by woker1 is slow than worker2, and then the ddl runs in worker1 will be conflict statement. we can change the check statement to be a compatible statement.

### LINKED ISSUE #5489: DM optimistic fail sync data when restart master or worker frequently
### Which jobs are flaking?

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/5855/pipeline/

### Which test(s) are flaking?

IT shardddl4_1/DM-155 optimistic

### Jenkins logs or GitHub Actions link

```log
[2022-05-18T09:28:55.766Z] [2022/05/18 17:28:23.346 +08:00] [DEBUG] [source_worker.go:197] ["runtime status"] [component="worker controller"] [status="{\n    \"status\": [\n        {\n            \"name\": \"test\",\n            \"stage\": \"Paused\",\n            \"unit\": \"Sync\",\n            \"result\": {\n                \"isCanceled\": false,\n                \"errors\": [\n                    {\n                        \"ErrCode\": 36027,\n                        \"ErrClass\": \"sync-unit\",\n                        \"ErrScope\": \"internal\",\n                        \"ErrLevel\": \"high\",\n                        \"Message\": \"startLocation: [position: (dm-integration-test-go1180-5855-lxrlz-pqmwr-bin|000001.000001, 175923), gtid-set: ce5c8dfc-d68b-11ec-b933-d289d6da190a:1-716], endLocation: [position: (dm-integration-test-go1180-5855-lxrlz-pqmwr-bin|000001.000001, 175979), gtid-set: ce5c8dfc-d68b-11ec-b933-d289d6da190a:1-716]: gen insert sqls failed, sourceTable: `shardddl1`.`tb1`, targetTable: `shardddl`.`tb`: Column count doesn't match value count: 4 (columns) vs 5 (values)\",\n                        \"RawCause\": \"\",\n                        \"Workaround\": \"Please check the log files to see if a related DDL has been skipped, and you could use `operate-schema` to get and set the table structure.\"\n                    }\n                ],\n                \"detail\": null\n            },\n            \"unresolvedDDLLockID\": \"\",\n            \"sync\": {\n                \"totalEvents\": \"22\",\n                \"totalTps\": \"0\",\n                \"recentTps\": \"0\",\n                \"masterBinlog\": \"(dm-integration-test-go1180-5855-lxrlz-pqmwr-bin.000001, 186753)\",\n                \"masterBinlogGtid\": \"ce5c8dfc-d68b-11ec-b933-d289d6da190a:1-753\",\n                \"syncerBinlog\": \"(dm-integration-test-go1180-5855-lxrlz-pqmwr-bin|000001.000001, 173995)\",\n                \"syncerBinlogGtid\": \"ce5c8dfc-d68b-11ec-b933-d289d6da190a:1-708\",\n                \"blockingDDLs\": [\n                ],\n                \"unresolvedGroups\": [\n                ],\n                \"synced\": false,\n                \"binlogType\": \"local\",\n                \"secondsBehindMaster\": \"0\",\n                \"blockDDLOwner\": \"\",\n                \"conflictMsg\": \"\"\n            }\n        }\n    ]\n}"]
```

### Anything else we need to know

it need to wait sync ddl finish like https://github.com/pingcap/tiflow/blob/master/dm/tests/shardddl_optimistic/run.sh#L176

### LINKED ISSUE #5490: DM full mode failed to check dump file which should be removed
### Which jobs are flaking?

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/5852/pipeline/

### Which test(s) are flaking?

full_mode/main run

### Jenkins logs or GitHub Actions link

check failed
```log
[2022-05-18T09:08:52.444Z] ls: cannot access /tmp/dm_test/full_mode/worker1/dumped_data.test: No such file or directory

[2022-05-18T09:08:52.444Z] worker1 auto removed dump files

[2022-05-18T09:08:52.444Z] full_mode-schema-create.sql

[2022-05-18T09:08:52.444Z] full_mode.t2-schema.sql

[2022-05-18T09:08:52.444Z] full_mode.t2.0000000000000.sql

[2022-05-18T09:08:52.444Z] metadata

[2022-05-18T09:08:52.444Z] tidb_lightning_checkpoint.pb

[2022-05-18T09:08:52.444Z] ...

[2022-05-18T09:08:52.444Z] make: *** [dm_integration_test] Error 1
```
clean log
```log
[2022-05-18T09:09:05.432Z] [2022/05/18 17:08:52.539 +08:00] [DEBUG] [baseconn.go:164] ["execute statement"] [job=lightning-checkpoint] [query="UPDATE `dm_meta`.`test_lightning_checkpoint_list` set status = ? WHERE `task_name` = ? AND `source_name` = ?"] [argument="[finished test mysql-replica-02]"]

[2022-05-18T09:09:05.432Z] [2022/05/18 17:08:52.545 +08:00] [INFO] [util.go:216] ["delete load worker in etcd for full mode"] [task=test] [source=mysql-replica-02] [worker=worker2]

[2022-05-18T09:09:05.432Z] [2022/05/18 17:08:52.546 +08:00] [INFO] [util.go:158] ["clean dump files"]

[2022-05-18T09:09:05.432Z] [2022/05/18 17:08:52.547 +08:00] [INFO] [lightning.go:330] ["lightning load end"] [task=test] [unit=lightning-load] [IsCanceled=false] [finished_bytes=212] [total_bytes=212] [progress="100.00 %"]
```

### Anything else we need to know

the time of clean data at `[2022-05-18T09:09:05.432Z]`  is after the time of check  at `[2022-05-18T09:08:52.444Z]`.
it may be caused by check-diff before data load finish, and check-diff pass but the data file still was not delete. we can add `query-status` to wait load finish.

### PR DESCRIPTION
**Pull request by WizardXiao**
### What problem does this PR solve?

Issue Number: 
close #5488 
close #5489 
close #5490 

### What is changed and how it works?
1. change the check statement to be a compatible statement for IT shardddl2/DM-040 optimistic.
2. wait sync ddl finish for IT shardddl4_1/DM-155 optimistic.
3. add query-status to wait load finish for IT full_mode/main run.

#### Tests 

 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

File: dm/tests/shardddl4_1/run.sh [hunk 1]
```diff
@@ -975,23 +975,35 @@ function DM_155_CASE {
 	run_sql_source2 "insert into ${shardddl1}.${tb2} values(27,27,27);"
 
 	run_sql_source2 "alter table ${shardddl1}.${tb2} change c b int;"
-	sleep 1
+	sleep 15
```
Comment (lance6716) [inline dm/tests/shardddl4_1/run.sh:978]: does this sleep is needed? check_log_contain_with_retry should contains 30 seconds retry

**Review by lance6716 — APPROVED** [review]

File: dm/tests/shardddl4_1/run.sh (hunk 1 above)
Comment (WizardXiao) [reply dm/tests/shardddl4_1/run.sh:978]: i think we‘d better to sleep 15s. It may exceed 30s( maybe my local computor is slow) , but most of times, it's between 15s and 30s, or less than 15s.

Comment (D3Hunter) [reply dm/tests/shardddl4_1/run.sh:978]: what's this sleep waiting for?

Comment (D3Hunter) [reply dm/tests/shardddl4_1/run.sh:978]: if it's waiting for the handle ddl finished and check using `check_log_contain_with_retry`, maybe increase retry count, such as to 1 minute, in `check_log_contain_with_retry`, not add sleep here, to make it more flexible.

Comment (WizardXiao) [reply dm/tests/shardddl4_1/run.sh:978]: yes, it is waiting for  the handle ddl.  add `check_log_contain_with_retry` to 1 minute will be more statable and it is beneficial for more ITs. i will fix.

File: dm/tests/full_mode/run.sh [hunk 2]
```diff
@@ -202,6 +202,10 @@ function run() {
 	# start DM task only
 	dmctl_start_task "$cur/conf/dm-task.yaml" "--remove-meta"
 
+	run_dm_ctl_with_retry $WORK_DIR "127.0.0.1:$MASTER_PORT" \
+		"query-status test" \
+		"\"stage\": \"Finished\"" 2
```
Comment (GMHDBJD) [inline dm/tests/full_mode/run.sh:207]: run_sql_file is blocking, why would it be in the middle state

Comment (WizardXiao) [reply dm/tests/full_mode/run.sh:207]: i didn't recurrence this [#5490](https://github.com/pingcap/tiflow/issues/5490) when ran locally too, but there was diffrent time between check-diff and clean log in worker2, so i guess it may be in a middle state, maybe the data is coincident. but data files weren't deleted. btw, other case in full_mode has wait `query-status Finished`.

Comment (D3Hunter) [reply dm/tests/full_mode/run.sh:207]: `check_sync_diff` failed in CI job because it task runs slow?

if it's that way, it may not work, since `run_dm_ctl_with_retry` wait for `10*2` seconds, but `check_sync_diff` waits `20*2` seconds

File: dm/tests/shardddl4_1/run.sh [hunk 3]
```diff
@@ -975,23 +975,32 @@ function DM_155_CASE {
 	run_sql_source2 "insert into ${shardddl1}.${tb2} values(27,27,27);"
 
 	run_sql_source2 "alter table ${shardddl1}.${tb2} change c b int;"
-	sleep 1
+	check_log_contain_with_retry "finish to handle ddls in optimistic shard mode.*alter table ${shardddl1}.${tb1} change c b int" \
```
Comment (D3Hunter) [inline dm/tests/shardddl4_1/run.sh:978]: there's a lot of `run-sql & sleep & random-restart` pattern before and after this block, should that need to be changed?

File: dm/tests/full_mode/run.sh (hunk 2 above)
Comment (WizardXiao) [reply dm/tests/full_mode/run.sh:207]: no, `check_sync_diff` pass, but check dump files removed failed.
https://github.com/pingcap/tiflow/pull/5507/files#diff-e1e9a23978ee6357d40677cb4b58be9c20f004503623b09526009f2f7c7e7ae0L210

File: dm/tests/shardddl4_1/run.sh (hunk 3 above)
Comment (WizardXiao) [reply dm/tests/shardddl4_1/run.sh:978]: yes, there is a lot of `random-restart`. but the reason of the failure may be shardding ddls is not completed, update table checkpoint but not global checkpoint, and then restart to sync, it returns `Column count doesn't match value count: 4 (columns) vs 5 (values)`, so it needs to wait sharding group is completed and just this three ddls will finish sharding group and write checkpoint, other ddls will skip or create compatible table structure. so other ddls maybe   still ok without check.

**Review by D3Hunter — APPROVED** [review]
