### PR TITLE
sarama: add keep-alive mechanism for sarama connections

### LINKED ISSUE #12171: cdc changefeed meet error: broken pipe
### What did you do?

The CDC normally runs and synchronizes data to the downstream Kafka. Sometimes, there may be no data to synchronize from the upstream for more than 10 minutes. Then, during the next synchronization, the CDC receives an error from Sarama:

`kafka async send message failed: kafka: Failed to produce message to topic xxx: write tcp IP:PORT->IP:PORT: write: broken pipe.`

Then the changefeed lag will increase.

### What did you expect to see?

The changefeed lag should be normal.

### What did you see instead?

CDC receives broken pipe error, and changefeed lag increases.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v7.5.6
```

Upstream TiKV version (execute `tikv-server --version`):

```console
v7.5.6
```

TiCDC version (execute `cdc version`):

```console
v7.5.6
```

### PR DESCRIPTION
**Pull request by wlwilliamx**
### What problem does this PR solve?

Issue Number: close #12171

This PR addresses the issue of frequent broken pipe errors in CDC when connecting to Kafka. The user reported that multiple clusters frequently triggered CDC alerts (cdc changefeed meet error) with the error message `write tcp ...: write: broken pipe`, occurring on average once every dozens of minutes. Although CDC appeared to function normally — with business operations unaffected and checkpoint lag remaining within acceptable limits — the alerts persisted.

The reason is that CDC had recently removed retries in the Sarama Kafka client (used by CDC) — reducing the retry count from 3 to 0 in #11870. This change was originally made to avoid potential message reordering issues. However, disabling retries caused CDC to surface connection-related errors directly, such as broken pipe, leading to changefeed failures instead of silent retries.

### What is changed and how it works?

This PR improves the reliability of Kafka connections in TiCDC by introducing a **keep-alive mechanism** for sarama that periodically sends heartbeats to all known Kafka brokers. This is a workaround for a known issue where Kafka broker silently closes idle connections, especially when sarama retry is disabled. The keep-alive interval will be a third of(for fault tolerance) `connections.max.idle.ms` in Kafka broker configs. In CDC, three types of Kafka connections are established, which are used for admin requests, DDL and watermark, and DML respectively.

* For the Kafka connection used for admin requests, I added periodic heartbeat sending to all Kafka brokers in the `kafkaTopicManager.backgroundRefreshMeta` goroutine to refresh the connections with all brokers.

* For the Kafka connection used for DDL and watermark, I added the heartbeat sending operation in the `DDLSink.WriteCheckpointTs` function, which will be invoked periodically.

* For the Kafka connection used for DML, I added periodic heartbeat sending to all Kafka brokers in the `saramaAsyncProducer.AsyncRunCallback`.

#### UT
The units tests cover the entire lifecycle of the keep-alive logic. We verify that the keep-alive interval is correctly calculated from the broker's settings by testing the AdjustOptions function. For the DML sink, we ensure the kafkaTopicManager's background routine sends heartbeats periodically. For the DDL sink, we confirm that a call to WriteCheckpointTs reliably triggers a heartbeat.

At the producer level, the tests validate the specific logic within both the synchronous and asynchronous Sarama producers. This includes testing the throttling mechanism in the sync producer to avoid sending heartbeats too frequently, and the background ticker in the async producer that drives the periodic calls.

To achieve this test coverage, a couple of specific strategies were used. To test the DDL sink's heartbeat trigger in isolation, a mock encoder is introduced that returns an error immediately after the heartbeat logic, simplifying the test by avoiding the need to set up a full message production pipeline. Furthermore, to test the producer-level heartbeats, we mock the sarama.Client interface itself. This approach allows us to verify that the heartbeat logic is being invoked, working around a limitation in the Sarama library that prevents direct mocking of the *sarama.Broker struct's methods.

With these tests in place, the keep-alive feature is now well-covered.

#### Tests 

 - Unit test
 - Integration test
 - Manual test
 - Test case PR: https://github.com/PingCAP-QE/test-infra/pull/4094
 - Test plan PR: https://github.com/PingCAP-QE/test-plan/pull/3765, will be run in daily and future patch release.
 - Kafka compatibility test: 0.11.0-0-r0, 0.11.0-1-r0, 1.0.0-r0, 1.0.1-r0, 1.1.0, 1.1.1, 2.0.0, 2.0.1, 2.1.0, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 2.6.0, 2.7.0, 2.8.0, 3.0.0, 3.1.0, 3.2.0. 3.4.0, 3.5.0, 3.6.0, 3.7.0.

A cluster was launched for testing, synchronizing upstream data to the downstream Kafka. The `connections.max.idle.ms` setting on the Kafka broker was configured to 10 seconds. Then, a load was added on the upstream side, randomly writing some data and pausing for a while. This load was run continuously, and it was confirmed that there were no issues.

##### Will it cause performance regression or break compatibility?

No.

##### Do you need to update user documentation, design documentation or monitoring documentation?

No.

### Release note 

```release-note
Improve Kafka connection reliability by introducing a keep-alive mechanism for sarama. This helps prevent unexpected timeouts caused by idle connections being silently closed by Kafka.
```

### CODE REVIEW

File: pkg/sink/kafka/sarama.go [hunk 1]
```diff
@@ -29,8 +29,9 @@ import (
 )
 
 var (
-	defaultKafkaVersion = sarama.V2_0_0_0
-	maxKafkaVersion     = sarama.V2_8_0_0
+	defaultKafkaVersion   = sarama.V2_0_0_0
+	maxKafkaVersion       = sarama.V2_8_0_0
+	keepConnAliveInterval = 5 * time.Minute
```
Comment (wk989898) [inline pkg/sink/kafka/sarama.go]: It is better to use it locally.

Comment (wlwilliamx) [reply pkg/sink/kafka/sarama.go]: Yes, but this is the better way to share a interval to all AdminClient, SyncProducer and AsyncProducer.

Comment (wk989898) [reply pkg/sink/kafka/sarama.go]: There is no need to share the variable, and it should be updated when the user alters `connections.max.idle.ms` in Kafka?

File: pkg/sink/kafka/admin.go [hunk 2]
```diff
@@ -31,6 +31,7 @@ type saramaAdminClient struct {
 
 	client sarama.Client
 	admin  sarama.ClusterAdmin
+	done   chan struct{}
```
Comment (3AceShowHand) [inline pkg/sink/kafka/admin.go]: This looks useless.

File: pkg/sink/kafka/factory.go [hunk 3]
```diff
@@ -212,6 +216,8 @@ func (p *saramaAsyncProducer) AsyncRunCallback(
 					callback()
 				}
 			}
+		case <-ticker.C:
+			hearbeatBroker(p.client)
```
Comment (3AceShowHand) [inline pkg/sink/kafka/factory.go]: typo, heartbeat

File: pkg/sink/kafka/sarama.go [hunk 4]
```diff
@@ -255,3 +256,40 @@ func getKafkaVersionFromBroker(config *sarama.Config, requestVersion int16, addr
 	}
 	return KafkaVersion, nil
 }
+
+// keepConnAlive is used to keep the connection alive.
+func keepConnAlive(client sarama.Client, done chan struct{}) {
```
Comment (3AceShowHand) [inline pkg/sink/kafka/sarama.go]: This method looks good to me, but should be controlled by the context, instead of the done channel.

File: pkg/sink/kafka/sarama_factory.go [hunk 5]
```diff
@@ -75,11 +76,25 @@ func (f *saramaFactory) AdminClient(ctx context.Context) (ClusterAdminClient, er
...
+		return nil, errors.Trace(err)
+	}
+	idleMsInt, err := strconv.Atoi(idleMs)
+	if err != nil || idleMsInt <= 0 {
+		log.Warn("invalid broker config",
+			zap.String("configName", BrokerConnectionsMaxIdleMsConfigName), zap.String("configValue", idleMs))
+		return nil, errors.Trace(err)
+	}
+	keepConnAliveInterval = time.Duration(idleMsInt/2) * time.Millisecond
+	go keepConnAlive(client, a.done)
```
Comment (3AceShowHand) [inline pkg/sink/kafka/sarama_factory.go]: Do not spawn goroutine here.

AdminClient is called by the ddl sink and dml sink.

it's used to initialize the topicManager, this method refresh metadata each 10 minutes, add one branch to the backgroundRefreshMeta method to send heartbeat if necessary.

Comment (3AceShowHand) [reply pkg/sink/kafka/sarama_factory.go]: On the DML sink side, add one branch to the metrics collector is also a choice.

File: pkg/sink/kafka/sarama.go (hunk 1 above)
Comment (3AceShowHand) [reply pkg/sink/kafka/sarama.go]: This should be set to the `option`, and adjust in the AdjustOption method.

File: pkg/sink/kafka/sarama_factory.go [hunk 6]
```diff
@@ -90,14 +105,22 @@ func (f *saramaFactory) SyncProducer(ctx context.Context) (SyncProducer, error)
...
+	if err != nil {
+		return nil, errors.Trace(err)
+	}
+	sp := saramaSyncProducer{
 		id:       f.changefeedID,
 		producer: p,
-	}, nil
+		done:     make(chan struct{}),
+	}
+	go keepConnAlive(client, sp.done)
```
Comment (3AceShowHand) [inline pkg/sink/kafka/sarama_factory.go]: ditto, do not spawn goroutine here.

DDLSink.WriteCheckpointTs method, is called periodically, you can call the heartbeat method here

**Comment by 3AceShowHand** [comment]
If the encoding protocol would send checkpoint to the kafka server, there is no need to send heartbeat.

File: cdc/sink/ddlsink/mq/mq_ddl_sink.go [hunk 7]
```diff
@@ -72,6 +72,8 @@ type DDLSink struct {
 	statistics *metrics.Statistics
 	// admin is used to query kafka cluster information.
 	admin kafka.ClusterAdminClient
+	// connRefresherForDDL is used to refresh the connection for DDL events.
+	connRefresherForDDL kafka.SyncProducer
```
Comment (wk989898) [inline cdc/sink/ddlsink/mq/mq_ddl_sink.go:76]: I think it is a redundant parameter, you can modify the `DDLProducer` interface to add `Heartbeat` method.

File: pkg/sink/kafka/factory.go [hunk 8]
```diff
@@ -115,6 +121,27 @@ func (p *saramaSyncProducer) SendMessages(_ context.Context, topic string, parti
...
+
+	// We don't care about the response and error here, even the connection
+	// is unestablished, we just need to keep the connection alive WHEN it's established.
+	// The connection will be established when a producer send messages.
+	// This is a workaround for the issue that sarama doesn't keep the connection alive
+	// when the connection is idle for a long time and we have disabled the retry in sarama.
+	brokers := p.client.Brokers()
+	for _, b := range brokers {
+		_, _ = b.Heartbeat(&sarama.HeartbeatRequest{})
+	}
```
Comment (wk989898) [inline pkg/sink/kafka/factory.go]: It is better to use a function to replace it.

File: cdc/sink/ddlsink/mq/mq_ddl_sink.go (hunk 7 above)
Comment (3AceShowHand) [reply cdc/sink/ddlsink/mq/mq_ddl_sink.go:76]: k.producer.Heartbeat()

File: cdc/sink/ddlsink/mq/mq_ddl_sink_test.go [hunk 9]
```diff
@@ -292,3 +296,96 @@ func TestGetDLLDispatchRuleByProtocol(t *testing.T) {
...
+func (m *mockEncoder) SetMaxMessageBytes(bytes int) {}
+
+func TestDDLSinkHeartbeat(t *testing.T) {
+	t.Parallel()
+
+	ctx := context.Background()
+	changefeedID := model.DefaultChangeFeedID("test-ddl-sink")
+	// Protocol is needed by newDDLSink but not used in the tested path.
+	proto := config.ProtocolOpen
+	encoder := &mockEncoder{}
```
Comment (3AceShowHand) [inline cdc/sink/ddlsink/mq/mq_ddl_sink_test.go:360]: You set the protocol as the ProtocolOpen but not used, this mockEncoder is redundant, just new a open protocol encoder is much better.

File: cdc/sink/ddlsink/mq/mq_ddl_sink_test.go [hunk 10]
```diff
@@ -292,3 +296,96 @@ func TestGetDLLDispatchRuleByProtocol(t *testing.T) {
...
+
+		require.Equal(t, 0, producer.GetHeartbeatCount())
+
+		// WriteCheckpointTs should first call HeartbeatBrokers, then fail at the encoder.
+		err := ddlSink.WriteCheckpointTs(ctx, 12345, nil)
+
+		// Assert that the heartbeat was called exactly once.
+		require.Equal(t, 1, producer.GetHeartbeatCount())
+		// Assert that the function failed with the mock encoder's specific error.
+		require.ErrorIs(t, err, errMockEncoder)
```
Comment (3AceShowHand) [inline cdc/sink/ddlsink/mq/mq_ddl_sink_test.go:378]: Why test this, just make sure the heartbeat is called should be fine.

File: cdc/sink/ddlsink/mq/mq_ddl_sink_test.go [hunk 11]
```diff
@@ -292,3 +296,96 @@ func TestGetDLLDispatchRuleByProtocol(t *testing.T) {
...
+	})
+
+	// Case 2: DDLSink with a nil connection refresher (e.g., for Pulsar).
+	t.Run("DDLSinkWithNilConnectionRefresher", func(t *testing.T) {
+		t.Parallel()
+		// Create the sink with a nil refresher.
+		ddlSinkNilRefresher := newDDLSink(changefeedID, nil, nil, nil, nil, encoder, proto, nil)
+
+		// The call should not panic and should fail with the mock encoder's error.
```
Comment (3AceShowHand) [inline cdc/sink/ddlsink/mq/mq_ddl_sink_test.go:387]: Just make sure it won't panic should be fine.

File: cdc/sink/dmlsink/mq/manager/kafka_manager.go [hunk 12]
```diff
@@ -61,13 +62,15 @@ func NewKafkaTopicManager(
...
-		changefeedID:      changefeedID,
-		admin:             admin,
-		cfg:               cfg,
-		metaRefreshTicker: time.NewTicker(metaRefreshInterval),
+		defaultTopic:        defaultTopic,
+		changefeedID:        changefeedID,
+		admin:               admin,
+		cfg:                 cfg,
+		metaRefreshTicker:   time.NewTicker(metaRefreshInterval),
+		keepConnAliveTicker: time.NewTicker(keepConnAliveInterval),
```
Comment (3AceShowHand) [inline cdc/sink/dmlsink/mq/manager/kafka_manager.go:73]: close the ticker when when exits the loop.

File: cdc/sink/dmlsink/mq/manager/kafka_manager_test.go [hunk 13]
```diff
@@ -15,13 +15,19 @@ package manager
...
 	"testing"
+	"time"
 
 	"github.com/pingcap/tiflow/cdc/model"
 	"github.com/pingcap/tiflow/pkg/sink/kafka"
 	"github.com/stretchr/testify/require"
 )
 
+// A fake interval to keep the connection alive in kafka topic manager.
+const FOREVER = time.Duration(math.MaxInt64)
```
Comment (3AceShowHand) [inline cdc/sink/dmlsink/mq/manager/kafka_manager_test.go:29]: What is the test purpose here.

File: cdc/sink/util/helper_test.go [hunk 14]
```diff
@@ -15,14 +15,19 @@ package util
...
 	"testing"
+	"time"
 
 	"github.com/pingcap/tiflow/cdc/model"
 	"github.com/pingcap/tiflow/pkg/sink/kafka"
 	"github.com/stretchr/testify/require"
 )
 
+// A fake interval to keep the connection alive in kafka topic manager.
+const FOREVER = time.Duration(math.MaxInt64)
```
Comment (3AceShowHand) [inline cdc/sink/util/helper_test.go:29]: Ditto.

File: pkg/sink/kafka/options.go [hunk 15]
```diff
@@ -588,6 +594,20 @@ func AdjustOptions(
 		}
 	}
 
+	// adjust keepConnAliveInterval by `connections.max.idle.ms` broker config.
+	idleMs, err := admin.GetBrokerConfig(ctx, BrokerConnectionsMaxIdleMsConfigName)
+	if err != nil {
```
Comment (3AceShowHand) [inline pkg/sink/kafka/options.go:599]: If cannot fetch the configuration, simply use the default configuration, print a log to indicate the error.

File: pkg/sink/kafka/sarama_factory.go [hunk 16]
```diff
@@ -90,14 +92,23 @@ func (f *saramaFactory) SyncProducer(ctx context.Context) (SyncProducer, error)
 		return nil, err
 	}
 	config.MetricRegistry = f.registry
-	p, err := sarama.NewSyncProducer(f.option.BrokerEndpoints, config)
+
+	client, err := sarama.NewClient(f.option.BrokerEndpoints, config)
```
Comment (3AceShowHand) [inline pkg/sink/kafka/sarama_factory.go:95]: this client should also be closed.

File: pkg/sink/kafka/sarama_factory.go [hunk 17]
```diff
@@ -90,14 +92,23 @@ func (f *saramaFactory) SyncProducer(ctx context.Context) (SyncProducer, error)
...
+	p, err := sarama.NewSyncProducerFromClient(client)
+	if err != nil {
+		return nil, errors.Trace(err)
+	}
+	sp := saramaSyncProducer{
+		id:                    f.changefeedID,
+		producer:              p,
+		client:                client,
+		keepConnAliveInterval: f.option.KeepConnAliveInterval,
+		lastHeartbeatTime:     time.Now().Add(-f.option.KeepConnAliveInterval),
```
Comment (3AceShowHand) [inline pkg/sink/kafka/sarama_factory.go:109]: simply set this as time.Now() should be fine.

File: pkg/sink/kafka/sarama_factory.go [hunk 18]
```diff
@@ -75,11 +75,13 @@ func (f *saramaFactory) AdminClient(ctx context.Context) (ClusterAdminClient, er
 	if err != nil {
 		return nil, errors.Trace(err)
 	}
-	return &saramaAdminClient{
+	a := saramaAdminClient{
```
Comment (3AceShowHand) [inline pkg/sink/kafka/sarama_factory.go]: unnecessary modification.

File: cdc/sink/ddlsink/mq/mq_ddl_sink.go (hunk 7 above)
Comment (wlwilliamx) [reply cdc/sink/ddlsink/mq/mq_ddl_sink.go:76]: The DDLProducer interface has multiple implementations. Adding a method like Heartbeat solely for this specific case, which is not needed by other implementations, is unnecessary and could cause confusion for users of those other implementations.

File: pkg/sink/kafka/factory.go (hunk 8 above)
Comment (wlwilliamx) [reply pkg/sink/kafka/factory.go]: It's already a function: `func (p *saramaSyncProducer) HeartbeatBrokers()`.

File: cdc/sink/ddlsink/mq/mq_ddl_sink_test.go (hunk 9 above)
Comment (wlwilliamx) [reply cdc/sink/ddlsink/mq/mq_ddl_sink_test.go:360]: Creating a new encoder is quite complex and involves a lot of unnecessary setup. In this case, mocking one is the simplest and most convenient approach, especially since we don’t need any real encoder functionality at all.

File: cdc/sink/ddlsink/mq/mq_ddl_sink_test.go (hunk 10 above)
Comment (wlwilliamx) [reply cdc/sink/ddlsink/mq/mq_ddl_sink_test.go:378]: This is the expected logic coverage — since WriteCheckpointTs is only called once, the heartbeat should also be received only once.

File: cdc/sink/ddlsink/mq/mq_ddl_sink_test.go (hunk 11 above)
Comment (wlwilliamx) [reply cdc/sink/ddlsink/mq/mq_ddl_sink_test.go:387]: This is intentionally designed to return an error. The WriteCheckpointTs function calls EncodeCheckpointEvent, and if EncodeCheckpointEvent does not return an error, WriteCheckpointTs will continue executing. However, the subsequent logic is not relevant to this unit test.

File: cdc/sink/dmlsink/mq/manager/kafka_manager.go (hunk 12 above)
Comment (wlwilliamx) [reply cdc/sink/dmlsink/mq/manager/kafka_manager.go:73]: Good suggestion

File: cdc/sink/util/helper_test.go (hunk 14 above)
Comment (wlwilliamx) [reply cdc/sink/util/helper_test.go:29]: This change is only because an interval parameter was added to the function. Since this unit test doesn’t need it, a fake FOREVER interval is used.

File: cdc/sink/dmlsink/mq/manager/kafka_manager_test.go (hunk 13 above)
Comment (wlwilliamx) [reply cdc/sink/dmlsink/mq/manager/kafka_manager_test.go:29]: Same as below.

File: pkg/sink/kafka/options.go (hunk 15 above)
Comment (wlwilliamx) [reply pkg/sink/kafka/options.go:599]: You want to minimize the impact, right? Good suggestion.

File: pkg/sink/kafka/sarama_factory.go (hunk 17 above)
Comment (wlwilliamx) [reply pkg/sink/kafka/sarama_factory.go:109]: Just make sure the first heartbeat can be sent successfully.

File: pkg/sink/kafka/sarama_factory.go (hunk 18 above)
Comment (wlwilliamx) [reply pkg/sink/kafka/sarama_factory.go]: done

File: cdc/sink/ddlsink/mq/mq_ddl_sink.go (hunk 7 above)
Comment (wk989898) [reply cdc/sink/ddlsink/mq/mq_ddl_sink.go:76]: There are two implementations: Kafka and Pulsar. I think it is more elegant to add a heartbeat method. The user doesn't need to understand the implementations.

File: pkg/sink/kafka/factory.go (hunk 8 above)
Comment (wk989898) [reply pkg/sink/kafka/factory.go]: This code snippet repeats three times in your PR. If the code needs to be modified, we have to update it three times.

File: pkg/sink/kafka/sarama_factory.go (hunk 17 above)
Comment (wk989898) [reply pkg/sink/kafka/sarama_factory.go:109]: It is not necessary to send a heartbeat when the Sarama client is created.

File: cdc/sink/ddlsink/mq/mq_ddl_sink_test.go (hunk 10 above)
Comment (3AceShowHand) [reply cdc/sink/ddlsink/mq/mq_ddl_sink_test.go:378]: but should not report error.

**Review by wk989898 — APPROVED** [review]

File: pkg/sink/kafka/sarama_factory.go (hunk 16 above)
Comment (wlwilliamx) [reply pkg/sink/kafka/sarama_factory.go:95]: It will be closed in sarama producer.
