### PR TITLE
changefeed(ticdc): fix memory quota incompatible from 6.5.0

### LINKED ISSUE #8007: changefeed stuck when enabling pull based sink from v6.5.0
### What did you do?

1. Run a ticdc cluster in v6.5.0, with the `default` server config.
2. Create a changefeed with cdc ctl v6.5.0
3. Upgrade ticdc server config, setting `debug.enable-pull-based-sink` to true 
4. Observe replication status

### What did you expect to see?

Replication is normal

### What did you see instead?

Replication is stuck.

Event count in cdc keeps unchanged.
Screenshot 2023-01-02 at 19 19 35

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

TiCDC version (execute `cdc version`):

V6.5.0 -> master@https://github.com/pingcap/tiflow/commit/73bb333c8b8319ffcb402b676fefaf7bd51e1942

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve?

Issue Number: close #8007 

### What is changed and how it works?

- Auto fix `memory-quota` if it is zero in changefeed info from etcd.
- Auto fix `memory-quota` if it is zero when creating a new changefeed.

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
Fix memory-quota is set to zero unexpectedly which will cause replication stuck.
```

### CODE REVIEW

File: pkg/config/replica_config_test.go [hunk 1]
```diff
@@ -130,6 +130,18 @@ func TestReplicaConfigValidate(t *testing.T) {
 	require.Equal(t, "d1", rules[0].PartitionRule)
 	require.Equal(t, "p1", rules[1].PartitionRule)
 	require.Equal(t, "", rules[2].PartitionRule)
+
+	// Test memory quota can be adjusted
+	conf = GetDefaultReplicaConfig()
+	conf.MemoryQuota = 0
+	err = conf.ValidateAndAdjust(nil)
+	require.Nil(t, err)
```
Comment (3AceShowHand) [inline pkg/config/replica_config_test.go:138]:
```suggestion
	require.NoError(t, err)
```

File: pkg/config/replica_config_test.go [hunk 2]
```diff
@@ -130,6 +130,18 @@ func TestReplicaConfigValidate(t *testing.T) {
...
+	require.Equal(t, uint64(DefaultChangefeedMemoryQuota), conf.MemoryQuota)
+
+	conf.MemoryQuota = uint64(1024)
+	err = conf.ValidateAndAdjust(nil)
+	require.Nil(t, err)
```
Comment (3AceShowHand) [inline pkg/config/replica_config_test.go:143]:
```suggestion
	require.NoError(t, err)
```

**Review by 3AceShowHand — APPROVED** [review]

**Review by nongfushanquan — APPROVED** [review]

**Review by hi-rustin — APPROVED** [review]
