### PR TITLE
processor(ticdc): fix log make cdc instance panic

### LINKED ISSUE #6714: cdc release-6.2 branch panic
### What did you do?

3 cdc instances, perform upgrade pd.

### What did you expect to see?

works normally

### What did you see instead?

cdc instance crashed since panic.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2b6aed3]

goroutine 61 [running]:
github.com/pingcap/tiflow/cdc/processor.(*processor).Close(0xc00035b2c0)
	github.com/pingcap/tiflow/cdc/processor/processor.go:988 +0x93
github.com/pingcap/tiflow/cdc/processor.(*managerImpl).closeProcessor(0xc000b414c0, {{0xc000747dd2?, 0xc000410b40?}, {0xc000747dea?, 0x0?}})
	github.com/pingcap/tiflow/cdc/processor/manager.go:145 +0xe6
github.com/pingcap/tiflow/cdc/processor.(*managerImpl).Tick(0xc000b414c0, {0x7fca640d1150?, 0xc000c9a1e0}, {0x3c3ac08?, 0xc0004761e0})
	github.com/pingcap/tiflow/cdc/processor/manager.go:118 +0x447
github.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run(0xc000b22000, {0x7fca640d1150, 0xc000c9a1e0}, 0xc000d442d0, 0x5f5e100, {0x34cb8fa, 0x9})
	github.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:266 +0xe63
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker(0xc00099c000, {0x3c6c4e0?, 0xc000c9a1e0}, {0x7fca641170d8, 0xc000b414c0}, {0x3c3ac08, 0xc0004761e0}, 0x457925?, {0x34cb8fa, 0x9})
	github.com/pingcap/tiflow/cdc/capture/capture.go:535 +0x185
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func3()
	github.com/pingcap/tiflow/cdc/capture/capture.go:367 +0x30e
created by github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run
	github.com/pingcap/tiflow/cdc/capture/capture.go:350 +0x42a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2b6aed3]
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
release-6.2
```

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #6714 

cdc panic due to visit nil pointer of `*ChangefeedReactorState`

### What is changed and how it works?

* print log by use non-nil `changefeedID`, instead of `*ChangefeedReactorState` to prevent nil pointer, which cause the panic.

Upgrade pd to `v6.3.0`, which is not supported by `v6.2.0`, init upstream failed, `processor.changefeed` is not initialized, so cause the nil.

#### Tests 
 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

File: cdc/processor/processor.go [hunk 1]
```diff
@@ -475,6 +475,7 @@ func isProcessorIgnorableError(err error) bool {
 // the `state` parameter is sent by the etcd worker, the `state` must be a snapshot of KVs in etcd
 // The main logic of processor is in this function, including the calculation of many kinds of ts, maintain table pipeline, error handling, etc.
 func (p *processor) Tick(ctx cdcContext.Context, state *orchestrator.ChangefeedReactorState) (orchestrator.ReactorState, error) {
+	p.changefeed = state
```
Comment (zhaoxinyu) [inline cdc/processor/processor.go:478]: Why moving `p.changefeed = state` from the original place to this line.

Comment (3AceShowHand) [reply cdc/processor/processor.go:478]: initialize the `changefeed` pointer as soon as possible, to prevent call on nil `changefeed`.

Comment (3AceShowHand) [reply cdc/processor/processor.go:478]: Actually, we should refactor the `newProcessor` method to attach the `changefeed` immediately, to prevent the nil pointer, I will do it in the later days.

File: cdc/processor/processor.go [hunk 2]
```diff
@@ -493,7 +494,6 @@ func (p *processor) Tick(ctx cdcContext.Context, state *orchestrator.ChangefeedR
 		return state, nil
 	}
 	startTime := time.Now()
-	p.changefeed = state
```
Comment (nongfushanquan) [inline cdc/processor/processor.go:496]: could you explain why this line here would cause panic?

File: pkg/upstream/upstream.go [hunk 3]
```diff
@@ -158,6 +158,7 @@ func initUpstream(ctx context.Context, up *Upstream, gcServiceID string) error {
 	if err != nil {
 		up.err.Store(err)
 		log.Error("init upstream error", zap.Error(err))
+		return errors.Trace(err)
```
Comment (sdojjy) [inline pkg/upstream/upstream.go:161]: update the above comment

File: cdc/processor/processor.go (hunk 2 above)
Comment (asddongmen) [reply cdc/processor/processor.go:496]: An error may return in line:494, and then the `p.Close()` would be called by `processorManager`, and we use p.changefeed.ID to log the error message, so the panic occurs.
The safe way is use `p.changefeedID` instead of `pd.changefeed.ID`.

**Review by sdojjy — APPROVED** [review]
