### PR TITLE
jobmaster(engine/dm): fix empty worker status for OnWorkerOnline/OnWorkerOffline

### LINKED ISSUE #7691: DM job master meets `unexpected end of JSON input` error can't recover
### What did you do?

- run a DM full mode job on single executor

### What did you expect to see?

_No response_

### What did you see instead?

job master keeps meeting following error

```go
[2022/11/22 11:41:55.873 +00:00] [INFO] [task_runner.go:187] ["Task Closed"] [id=41207] [error="unexpected end of JSON input"] [errorVerbose="unexpected end of JSON input\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20220729040631-518f63d66278/errors.go:174\ngithub.com/pingcap/errors.Trace\n\tgithub.com/pingcap/errors@v0.11.5-0.20220729040631-518f63d66278/juju_adaptor.go:15\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseJobMaster).Poll\n\tgithub.com/pingcap/tiflow/engine/framework/base_jobmaster.go:229\ngithub.com/pingcap/tiflow/engine/framework/internal/eventloop.(*Runner[...]).doRun\n\tgithub.com/pingcap/tiflow/engine/framework/internal/eventloop/runner.go:94\ngithub.com/pingcap/tiflow/engine/framework/internal/eventloop.(*Runner[...]).Run\n\tgithub.com/pingcap/tiflow/engine/framework/internal/eventloop/runner.go:57\ngithub.com/pingcap/tiflow/engine/executor/worker.(*TaskRunner).launchTask.func1\n\tgithub.com/pingcap/tiflow/engine/executor/worker/task_runner.go:203\nruntime.goexit\n\truntime/asm_amd64.s:1594"] [runtime-task-count=2]                                                                                                              [2022/11/22 11:41:55.873 +00:00] [INFO] [task_runner.go:204] ["Task stopped"] [id=41207] [error="unexpected end of JSON input"] [errorVerbose="unexpected end of JSON input\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20220729040631-518f63d66278/errors.go:174\ngithub.com/pingcap/errors.Trace\n\tgithub.com/pingcap/errors@v0.11.5-0.20220729040631-518f63d66278/juju_adaptor.go:15\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseJobMaster).Poll\n\tgithub.com/pingcap/tiflow/engine/framework/base_jobmaster.go:229\ngithub.com/pingcap/tiflow/engine/framework/internal/eventloop.(*Runner[...]).doRun\n\tgithub.com/pingcap/tiflow/engine/framework/internal/eventloop/runner.go:94\ngithub.com/pingcap/tiflow/engine/framework/internal/eventloop.(*Runner[...]).Run\n\tgithub.com/pingcap/tiflow/engine/framework/internal/eventloop/runner.go:57\ngithub.com/pingcap/tiflow/engine/executor/worker.(*TaskRunner).launchTask.func1\n\tgithub.com/pingcap/tiflow/engine/executor/worker/task_runner.go:203\nruntime.goexit\n\truntime/asm_amd64.s:1594"]
```

detail logs:
[unexpected_json.log](https://github.com/pingcap/tiflow/files/10072270/unexpected_json.log)

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

master@https://github.com/pingcap/tiflow/commit/01ac379557eb79501c00e10c582f15410de522b7

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: close #7691

### What is changed and how it works?
- ignore nil extra status bytes for OnWorkerOnline

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

File: engine/jobmaster/dm/dm_jobmaster.go [hunk 1]
```diff
@@ -189,9 +189,14 @@ func (jm *JobMaster) OnWorkerOnline(worker framework.WorkerHandle) error {
 
 // handleOnlineStatus is used by OnWorkerOnline and OnWorkerStatusUpdated.
 func (jm *JobMaster) handleOnlineStatus(worker framework.WorkerHandle) error {
+	extBytes := worker.Status().ExtBytes
+	if len(extBytes) == 0 {
```
Comment (lance6716) [inline engine/jobmaster/dm/dm_jobmaster.go:193]: maybe we can remove the usage of `OnWorkerOnline` callback, only use `OnWorkerStatusUpdated`? That is to say, because DM needs bussiness online message with worker bound information, plain framework online is no use

File: engine/jobmaster/dm/dm_jobmaster.go [hunk 2]
```diff
@@ -201,24 +206,28 @@ func (jm *JobMaster) handleOnlineStatus(worker framework.WorkerHandle) error {
 
 // OnWorkerOffline implements JobMasterImpl.OnWorkerOffline
 func (jm *JobMaster) OnWorkerOffline(worker framework.WorkerHandle, reason error) error {
+	extBytes := worker.Status().ExtBytes
+	if len(extBytes) == 0 {
+		jm.Logger().Warn("worker status extBytes is empty", zap.String(logutil.ConstFieldWorkerKey, worker.ID()))
```
Comment (lance6716) [inline engine/jobmaster/dm/dm_jobmaster.go:211]: it should not happen, otherwise we have no change to UpdateClient. Maybe we can use DPanic level and let the logger turn on `Development` for DPanic

https://github.com/pingcap/tiflow/blob/822a79f6e2e2619d00df4d6b70572cf5064b4ba3/dm/pkg/log/log.go#L118

File: engine/jobmaster/dm/dm_jobmaster.go [hunk 3]
```diff
@@ -344,7 +353,11 @@ func (jm *JobMaster) getInitStatus() ([]runtime.TaskStatus, []runtime.WorkerStat
 			continue
 		}
 		var taskStatus runtime.TaskStatus
-		err := json.Unmarshal(workerHandle.Status().ExtBytes, &taskStatus)
+		extBytes := workerHandle.Status().ExtBytes
+		if len(extBytes) == 0 {
+			return nil, nil, errors.Errorf("extBytes of %d is empty", workerHandle.ID())
```
Comment (lance6716) [inline engine/jobmaster/dm/dm_jobmaster.go:358]: we can `continue` to waiting worker's UpdateStatus?

File: engine/jobmaster/dm/dm_jobmaster.go (hunk 2 above)
Comment (amyangfei) [reply engine/jobmaster/dm/dm_jobmaster.go:211]: Let me check whether `OnWorkerOffline` can happen with receiving `OnWorkerOnline`

File: engine/jobmaster/dm/dm_jobmaster.go (hunk 1 above)
Comment (maxshuang) [reply engine/jobmaster/dm/dm_jobmaster.go:193]: What if `OnWorkerStatusUpdated ` is not called because the message is discarded for some reasons, like `buffer full`?

**Review by lance6716 — APPROVED** [review]

File: engine/jobmaster/dm/dm_jobmaster.go (hunk 1 above)
Comment (GMHDBJD) [reply engine/jobmaster/dm/dm_jobmaster.go:194]: worker will be regard as offline after 2*HeartbeatInterval. https://github.com/pingcap/tiflow/blob/822a79f6e2e2619d00df4d6b70572cf5064b4ba3/engine/jobmaster/dm/worker_manager.go#L159

Comment (GMHDBJD) [reply engine/jobmaster/dm/dm_jobmaster.go:194]: https://github.com/pingcap/tiflow/blob/822a79f6e2e2619d00df4d6b70572cf5064b4ba3/engine/jobmaster/dm/worker_manager.go#L159

**Review by amyangfei — APPROVED** [review]
