### PR TITLE
redo(ticdc): Fix RedoLogWriter unit test

### LINKED ISSUE #11852: Found flaky tests in RedoLogWriter
### What did you do?

Run unit test about `cdc/redo/writer/memory/mem_log_writer_test.go`

### What did you expect to see?

pass all tests

### What did you see instead?

Flaky tests

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
master
```

### PR DESCRIPTION
**Pull request by wk989898**
### What problem does this PR solve?

Issue Number: close #11852 

### What is changed and how it works?
A select blocks until one of its cases can run, then it executes that case. It chooses one at random if multiple are ready.
In these cases, encodingWorkerGroup may run `WriteEvents` or `FlushLog` successfully even if encoding worker is closed. 
```go
select {
case <-ctx.Done():
	return ctx.Err()
case err := <-e.closed:
	return errors.WrapError(errors.ErrRedoWriterStopped, err, "encoding worker is closed")
case e.inputChs[idx] <- event: // executes even if encoding worker is closed
	return nil
}
```

#### Tests 

 - Unit test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by CharlesCheung96 — APPROVED** [review]

File: cdc/redo/writer/memory/mem_log_writer_test.go [hunk 1]
```diff
@@ -106,12 +106,30 @@ func testWriteEvents(t *testing.T, events []writer.RedoEvent) {
 
 	functions := map[string]func(error){
 		"WriteEvents": func(expected error) {
-			err := lw.WriteEvents(ctx, events...)
-			require.ErrorIs(t, errors.Cause(err), expected)
+			if expected == nil {
+				err := lw.WriteEvents(ctx, events...)
+				require.ErrorIs(t, errors.Cause(err), expected)
```
Comment (3AceShowHand) [inline cdc/redo/writer/memory/mem_log_writer_test.go:111]: it looks this should be no error, since expected is nil

File: cdc/redo/writer/memory/mem_log_writer_test.go [hunk 2]
```diff
@@ -106,12 +106,30 @@ func testWriteEvents(t *testing.T, events []writer.RedoEvent) {
...
+					}, time.Second*2, time.Microsecond*10,
+				)
+			}
 		},
 		"FlushLog": func(expected error) {
-			err := lw.FlushLog(ctx)
-			require.ErrorIs(t, errors.Cause(err), expected)
+			if expected == nil {
+				err := lw.FlushLog(ctx)
+				require.ErrorIs(t, errors.Cause(err), expected)
```
Comment (3AceShowHand) [inline cdc/redo/writer/memory/mem_log_writer_test.go:124]: ditto

File: cdc/redo/writer/memory/mem_log_writer_test.go [hunk 3]
```diff
@@ -106,12 +106,30 @@ func testWriteEvents(t *testing.T, events []writer.RedoEvent) {
 
 	functions := map[string]func(error){
 		"WriteEvents": func(expected error) {
-			err := lw.WriteEvents(ctx, events...)
-			require.ErrorIs(t, errors.Cause(err), expected)
+			if expected == nil {
+				err := lw.WriteEvents(ctx, events...)
+				require.Nil(t, err)
```
Comment (3AceShowHand) [inline cdc/redo/writer/memory/mem_log_writer_test.go:111]: require.NoError is prefered.

Also , I am curious, why the expected may be nil and not nil at the same case?

**Review by 3AceShowHand — APPROVED** [review]

File: cdc/redo/writer/memory/mem_log_writer_test.go (hunk 3 above)
Comment (wk989898) [reply cdc/redo/writer/memory/mem_log_writer_test.go:111]: Only the first call raises an error and It is uncertain which function is called

**Comment by wk989898** [comment]
/cherry-pick 8.5, 8.1, 7.5, 7.1, 6.5, 6.1

**Comment by wk989898** [comment]
/cherry-pick 8.5 8.1 7.5 7.1 6.5 6.1

**Comment by wk989898** [comment]
/cherrypick release-8.5, release-8.1, release-7.5, release-7.1, release-6.5, release-6.1,

**Comment by wk989898** [comment]
/cherrypick release-8.5 release-8.1 release-7.5 release-7.1 release-6.5 release-6.1
