### PR TITLE
checker(dm): add onlineddl check

### LINKED ISSUE #4064: Add `OnlineddlChecker`

### LINKED ISSUE #4142: onlineddl(dm): db not closed when init failed
https://github.com/pingcap/tiflow/blob/2bd7c928431a0067273d742b1512738a6cdf78a8/dm/syncer/online-ddl-tools/online_ddl.go#L128-L145

In online_ddl.go, if `s.prepare()` or `s.Load()` failed, we need to close db

### PR DESCRIPTION
**Pull request by okJiang**
### What problem does this PR solve?

Issue Number: close #4064 , close #4142 , close https://github.com/pingcap/tiflow/issues/4243

### What is changed and how it works?

- check ghost table in table structure checker

### Check List 

Tests 

 - Integration test

Related changes

 - Need to update the documentation

### Release note 

```release-note
`None`.
```

### CODE REVIEW

File: dm/checker/checker.go [hunk 1]
```diff
@@ -78,17 +80,21 @@ type Checker struct {
...
 		instances:     make([]*mysqlInstance, 0, len(cfgs)),
 		checkingItems: checkingItems,
-		logger:        log.With(zap.String("unit", "task check")),
-		errCnt:        errCnt,
-		warnCnt:       warnCnt,
+
+		errCnt:  errCnt,
+		warnCnt: warnCnt,
 	}
+	c.tctx = tcontext.Background().WithLogger(logger)
```
Comment (Ehco1996) [inline dm/checker/checker.go:97]: maybe init this ctx when `checker.Init`

File: dm/pkg/checker/table_structure.go [hunk 2]
```diff
@@ -184,6 +191,18 @@ func (c *TablesChecker) checkAST(stmt ast.StmtNode) []*incompatibilityOption {
 	}
 
 	var options []*incompatibilityOption
+	// check table name
+	if c.onlineDDL != nil {
+		log.L().Info("", zap.String("table name", st.Table.Name.O))
```
Comment (Ehco1996) [inline dm/pkg/checker/table_structure.go:196]: maybe add some msg in this log,  empty string is confused

File: dm/tests/new_relay/run.sh [hunk 3]
```diff
@@ -287,6 +287,7 @@ function run() {
 	relay_log_count_2=$(($(ls $WORK_DIR/worker2/relay-dir/$server_uuid_2 | wc -l) - 1))
 	[ "$relay_log_count_1" -ne 1 ]
 	[ "$relay_log_count_2" -ne 1 ]
+	sleep 1
```
Comment (Ehco1996) [inline dm/tests/new_relay/run.sh:290]: why we need sleep here？

File: dm/tests/online_ddl/run.sh [hunk 4]
```diff
@@ -29,6 +20,27 @@ function run() {
 	sed -i "/relay-binlog-name/i\relay-dir: $WORK_DIR/worker2/relay_log" $WORK_DIR/source2.yaml
 	dmctl_operate_source create $WORK_DIR/source1.yaml $SOURCE_ID1
 
+	run_sql_file $cur/data/check.db1.prepare.sql $MYSQL_HOST1 $MYSQL_PORT1 $MYSQL_PASSWORD1
+
+	cp $cur/conf/check-task.yaml $WORK_DIR/check-task.yaml
+
+	run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
+		"check-task $WORK_DIR/check-task.yaml" \
+		"\"result\": true" 1
```
Comment (Ehco1996) [inline dm/tests/online_ddl/run.sh:29]: what does this test check? i think maybe we should check the error from checker  matched with `your ddl is in pt/ghost online-ddl` 🤔

**Comment by okJiang** [comment]
/hold 
Need more modification

File: dm/tests/new_relay/run.sh (hunk 3 above)
Comment (okJiang) [reply dm/tests/new_relay/run.sh:290]: for unstable test, I don't know the reason.

can't purge the worker2's relay log completely without `sleep 1`.

File: dm/checker/checker.go [hunk 5]
```diff
@@ -131,6 +136,14 @@ func (c *Checker) Init(ctx context.Context) (err error) {
 			return terror.ErrTaskCheckGenTableRouter.Delegate(err)
 		}
 
+		if instance.cfg.OnlineDDL && c.onlineDDL == nil {
+			c.onlineDDL, err = onlineddl.NewRealOnlinePlugin(c.tctx, instance.cfg)
```
Comment (D3Hunter) [inline dm/checker/checker.go:140]: c.onlineDDL.storage may be partially inited, db in `c.onlineDDL.storage` should be closed

File: dm/pkg/checker/onlineddl.go [hunk 6]
```diff
@@ -0,0 +1,79 @@
...
+// limitations under the License.
+
+package checker
+
+import (
+	"context"
+	"database/sql"
+
+	"github.com/pingcap/tidb-tools/pkg/filter"
+	"github.com/pingcap/tiflow/dm/pkg/utils"
```
Comment (D3Hunter) [inline dm/pkg/checker/onlineddl.go:21]: format imports

File: dm/tests/online_ddl/run.sh [hunk 7]
```diff
@@ -29,6 +20,27 @@ function run() {
...
+	# prevent start task in process of online-ddl
+	run_sql_file $cur/data/check.gho.db1.sql $MYSQL_HOST1 $MYSQL_PORT1 $MYSQL_PASSWORD1
+	run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
+		"check-task $WORK_DIR/check-task.yaml" \
+		"your ddl is in pt\/ghost online-ddl" 1
+
+	run_sql_file $cur/data/check.pt.db1.sql $MYSQL_HOST1 $MYSQL_PORT1 $MYSQL_PASSWORD1
+	run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
+		"check-task $WORK_DIR/check-task.yaml" \
+		"your ddl is in pt\/ghost online-ddl" 1
```
Comment (D3Hunter) [inline dm/tests/online_ddl/run.sh:33]: maybe add one positive case.

**Review by D3Hunter — COMMENTED** [review]
rest LGTM

**Review by D3Hunter — COMMENTED** [review]
rest LGTM

File: dm/tests/online_ddl/run.sh (hunk 7 above)
Comment (okJiang) [reply dm/tests/online_ddl/run.sh:33]: all `start-task` command will `check-task` first. So that we `start-task` success means `check-task` success.

File: dm/checker/checker.go (hunk 5 above)
Comment (okJiang) [reply dm/checker/checker.go:140]: In fact, we have not used the **db** in `onlineDDL.storage`.

Comment (D3Hunter) [reply dm/checker/checker.go:140]: previous bug, maybe fix it in this pr.

Comment (D3Hunter) [reply dm/checker/checker.go:140]: #4142

Comment (okJiang) [reply dm/checker/checker.go:140]: fixed in https://github.com/pingcap/tiflow/pull/4065/commits/6b6ad535ab1ee2e67d0f6001a452c31d347c05b4

**Review by D3Hunter — APPROVED** [review]
LGTM

File: dm/tests/new_relay/run.sh (hunk 3 above)
Comment (Ehco1996) [reply dm/tests/new_relay/run.sh:290]: maybe use run_dm_ctl_with_retry  to purge relay log, i am afraid of 1s is too short when load is high

**Review by Ehco1996 — COMMENTED** [review]
restLGTM

File: dm/tests/new_relay/run.sh (hunk 3 above)
Comment (okJiang) [reply dm/tests/new_relay/run.sh:290]: The fact is `purge-relay` returns success, but `new_relay_log_count_2>1`. So cannot use run_dm_ctl_with_retry to solve this problem.

I can go further to find the reason for it.

Comment (Ehco1996) [reply dm/tests/new_relay/run.sh:290]: this may caused by source mysql rotate it's binlog file, so maybe this sleep is no help to make test stable
pelase find the reason and fix this if you have time

Comment (okJiang) [reply dm/tests/new_relay/run.sh:290]: It is because `async checkpoint flush` is flushing at `mysql-bin.000003` in this moment. So it can't purge completely.

`master` branch also can triage this unstable test.

So `add sleep 1` is no problem.

Comment (Ehco1996) [reply dm/tests/new_relay/run.sh:290]: please open an issue and leave a comment around this sleep

Comment (okJiang) [reply dm/tests/new_relay/run.sh:290]: left in https://github.com/pingcap/tiflow/issues/4243

**Review by Ehco1996 — APPROVED** [review]
LGTM

**Comment by Ehco1996** [comment]
@okJiang  ut failed

```
FAIL: table_structure_test.go:117: testCheckSuite.TestTablesChecker
table_structure_test.go:181:
    c.Assert(result.State, tc.Equals, StateFailure)
... obtained checker.State = "success"
... expected checker.State = "fail"

```

**Comment by okJiang** [comment]
> @okJiang ut failed
> 
> ```
> FAIL: table_structure_test.go:117: testCheckSuite.TestTablesChecker
> table_structure_test.go:181:
>     c.Assert(result.State, tc.Equals, StateFailure)
> ... obtained checker.State = "success"
> ... expected checker.State = "fail"
> ```

Seems parser support `gbk` character, so that check success.

/run-all-tests
