### PR TITLE
pd(ticdc): enlarge pd grpc client timeout to 10 seconds

### LINKED ISSUE #6689: cdc region cache load store failed
a huge number of logs from the `RegionCache`:

cdc version `v5.3.1`, we shall take investigation into the `RegionCache`

```
[2022/08/06 20:22:25.617 +08:00] [ERROR] [error.go:276] ["encountered error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"] [stack="github.com/tikv/client-go/v2/error.Log\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/error/error.go:276\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:438\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406"]
[2022/08/06 20:22:25.618 +08:00] [ERROR] [error.go:276] ["encountered error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"] [stack="github.com/tikv/client-go/v2/error.Log\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/error/error.go:276\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:438\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406"]
[2022/08/06 20:22:25.630 +08:00] [ERROR] [region_cache.go:1958] ["loadStore from PD failed"] [id=4] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[2022/08/06 20:22:25.631 +08:00] [ERROR] [error.go:276] ["encountered error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"] [stack="github.com/tikv/client-go/v2/error.Log\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/error/error.go:276\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:438\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406"]
[2022/08/06 20:22:25.631 +08:00] [ERROR] [region_cache.go:1958] ["loadStore from PD failed"] [id=1] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[2022/08/06 20:22:25.631 +08:00] [ERROR] [error.go:276] ["encountered error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"] [stack="github.com/tikv/client-go/v2/error.Log\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/error/error.go:276\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:438\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406"]
[2022/08/06 20:22:25.633 +08:00] [ERROR] [region_cache.go:1958] ["loadStore from PD failed"] [id=4] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[2022/08/06 20:22:25.634 +08:00] [ERROR] [error.go:276] ["encountered error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"] [stack="github.com/tikv/client-go/v2/error.Log\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/error/error.go:276\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:438\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406"]
[2022/08/06 20:22:25.639 +08:00] [ERROR] [region_cache.go:1958] ["loadStore from PD failed"] [id=7] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[2022/08/06 20:22:25.639 +08:00] [ERROR] [error.go:276] ["encountered error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"] [stack="github.com/tikv/client-go/v2/error.Log\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/error/error.go:276\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:438\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406"]
[2022/08/06 20:22:25.642 +08:00] [ERROR] [region_cache.go:1958] ["loadStore from PD failed"] [id=7] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[2022/08/06 20:22:25.642 +08:00] [ERROR] [error.go:276] ["encountered error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"] [stack="github.com/tikv/client-go/v2/error.Log\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/error/error.go:276\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:438\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406"]
[2022/08/06 20:22:25.650 +08:00] [ERROR] [region_cache.go:1958] ["loadStore from PD failed"] [id=1] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[2022/08/06 20:22:25.650 +08:00] [ERROR] [error.go:276] ["encountered error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"] [stack="github.com/tikv/client-go/v2/error.Log\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/error/error.go:276\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:438\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406"]
[2022/08/06 20:22:25.651 +08:00] [ERROR] [region_cache.go:1958] ["loadStore from PD failed"] [id=4] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[2022/08/06 20:22:25.651 +08:00] [ERROR] [error.go:276] ["encountered error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"] [stack="github.com/tikv/client-go/v2/error.Log\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/error/error.go:276\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:438\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406"]
[2022/08/06 20:22:25.652 +08:00] [ERROR] [region_cache.go:1958] ["loadStore from PD failed"] [id=4] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[2022/08/06 20:22:25.652 +08:00] [ERROR] [error.go:276] ["encountered error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"] [stack="github.com/tikv/client-go/v2/error.Log\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/error/error.go:276\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:438\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406"]
[2022/08/06 20:22:25.653 +08:00] [ERROR] [region_cache.go:1958] ["loadStore from PD failed"] [id=4] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[2022/08/06 20:22:25.653 +08:00] [ERROR] [error.go:276] ["encountered error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"] [stack="github.com/tikv/client-go/v2/error.Log\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/error/error.go:276\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:438\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406"]
[2022/08/06 20:22:25.664 +08:00] [ERROR] [region_cache.go:1958] ["loadStore from PD failed"] [id=4] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[2022/08/06 20:22:25.664 +08:00] [ERROR] [error.go:276] ["encountered error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"] [stack="github.com/tikv/client-go/v2/error.Log\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/error/error.go:276\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:438\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406"]
[2022/08/06 20:22:25.664 +08:00] [ERROR] [region_cache.go:1958] ["loadStore from PD failed"] [id=4] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[2022/08/06 20:22:25.664 +08:00] [ERROR] [error.go:276] ["encountered error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"] [stack="github.com/tikv/client-go/v2/error.Log\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/error/error.go:276\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:438\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406"]
[2022/08/06 20:22:25.668 +08:00] [ERROR] [region_cache.go:1958] ["loadStore from PD failed"] [id=4] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[2022/08/06 20:22:25.668 +08:00] [ERROR] [error.go:276] ["encountered error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"] [stack="github.com/tikv/client-go/v2/error.Log\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/error/error.go:276\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:438\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406"]
[2022/08/06 20:22:25.673 +08:00] [ERROR] [region_cache.go:1958] ["loadStore from PD failed"] [id=4] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[2022/08/06 20:22:25.673 +08:00] [ERROR] [error.go:276] ["encountered error"] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"] [stack="github.com/tikv/client-go/v2/error.Log\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/error/error.go:276\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:438\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406"]
[2022/08/06 20:22:25.681 +08:00] [ERROR] [region_cache.go:1958] ["loadStore from PD failed"] [id=4] [error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"] [errorVerbose="rpc error: code = DeadlineExceeded desc = context deadline exceeded\ngithub.com/tikv/pd/client.(*client).GetStore\n\tgithub.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:1479\ngithub.com/tikv/client-go/v2/internal/locate.(*Store).reResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:1948\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).checkAndResolve\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:437\ngithub.com/tikv/client-go/v2/internal/locate.(*RegionCache).asyncCheckAndResolveLoop\n\tgithub.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/locate/region_cache.go:406\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
```

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #6689

### What is changed and how it works?

set pd grpc client timeout to 10s, which is default to 3s

#### Tests 

 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

File: pkg/upstream/upstream.go [hunk 1]
```diff
@@ -122,6 +122,7 @@ func initUpstream(ctx context.Context, up *Upstream, gcServiceID string) error {
 
 	up.PDClient, err = pd.NewClientWithContext(
 		ctx, up.PdEndpoints, up.SecurityConfig.PDSecurityOption(),
+		pd.WithCustomTimeoutOption(10*time.Second),
```
Comment (overvenus) [inline pkg/upstream/upstream.go:125]: Please add some comments.

**Review by overvenus — APPROVED** [review]

**Review by sdojjy — APPROVED** [review]
