### PR TITLE
serverutil(engine): fix panic in WatchExecutors

### LINKED ISSUE #6964: master(engine): unexpected core dump for server master
### What did you do?

run a 1 servermaster 1 executor tiflow cluster 

### What did you expect to see?

run normally

### What did you see instead?

server master core dump
```
docker container logs 3c1f3f2a5ab2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c17dfc]

goroutine 13341 [running]:
github.com/pingcap/tiflow/engine/pkg/notifier.(*Receiver[...]).Close(0x400199e090?)
	github.com/pingcap/tiflow/engine/pkg/notifier/notifier.go:65 +0x1c
github.com/pingcap/tiflow/engine/servermaster/serverutil.WatchExecutors({0x37aab80, 0x4001a5dd00}, {0xffff6fe33d78, 0x400032e380}, {0x37a8030, 0x4001a51fb0})
	github.com/pingcap/tiflow/engine/servermaster/serverutil/watch_executors.go:65 +0x3c4
github.com/pingcap/tiflow/engine/servermaster.(*Server).runLeaderService.func13()
	github.com/pingcap/tiflow/engine/servermaster/server.go:940 +0x9c
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75 +0x60
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:72 +0xa8
```

log:
```
[2022/09/04 14:31:43.414 +00:00] [WARN] [discovery_keepalive.go:104] ["metastore session is done"] [executor-id=server-master-990e160a-c73b-4b4e-a0f8-d772d270ed53]
[2022/09/04 14:31:43.414 +00:00] [INFO] [gc_runner.go:67] ["default gc runner exited"]
[2022/09/04 14:31:43.414 +00:00] [WARN] [watch_executors.go:60] ["WatchExecutors took too long"] [duration=1m0.506749028s] [snap=null]
[2022/09/04 14:31:43.414 +00:00] [INFO] [watch_executors.go:52] ["WatchExecutors exited"] [error="watch executors: [DFLOW:ErrMasterSessionDone]master session is done"]
```
[server-master-0.log](https://github.com/pingcap/tiflow/files/9486542/server-master-0.log)

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

```console
master@12ff137
```

### PR DESCRIPTION
**Pull request by liuzix**
### What problem does this PR solve?

Issue Number: close #6964

### What is changed and how it works?
- Fixed a bug in deferred closing of the receiver.

#### Tests 

 - Unit test
 - Integration test

##### Will it cause performance regression or break compatibility?
No.

##### Do you need to update user documentation, design documentation or monitoring documentation?
No.

### Release note 

```release-note
None.
```

### CODE REVIEW

**Review by CharlesCheung96 — APPROVED** [review]

File: engine/servermaster/serverutil/watch_executors.go [hunk 1]
```diff
@@ -64,6 +63,7 @@ func WatchExecutors(ctx context.Context, watcher executorWatcher, user executorI
 	if err != nil {
 		return errors.Annotate(err, "watch executors")
 	}
+	defer updates.Close()
```
Comment (maxshuang) [inline engine/servermaster/serverutil/watch_executors.go:66]: Why we don't trigger this bug before?

Comment (liuzix) [reply engine/servermaster/serverutil/watch_executors.go:66]: If you meant "Why had this bug never been triggered before", then it's probably because the error handling path had never been taken.

**Review by amyangfei — APPROVED** [review]
