### PR TITLE
pdutil (ticdc): refine pd clock interface

### LINKED ISSUE #9294: [dr-autosync] changfeed status change to error during patching pd
### What did you do?

[2023/06/26 13:19:30.273 +08:00] [INFO] [tiup.go:422] ["run cmd"] [cmd="tiup cluster patch tidbcluster /tmp/2023-06-26T13:19:25+08:00.tiup.tar.gz -R pd -y"]

[2023/06/26 13:19:49.682 +08:00] [INFO] [ticdc.go:145] ["will run"] [cmd="tiup cdc:v6.5.3 cli changefeed list  --server=http://ticdc1-peer.e2e-dr-auto-sync-5r-pref-tps-1809605-1-603:8300"]
2023-06-26T13:19:49.685+0800	INFO	k8s/client.go:132	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
[
  {
    "id": "dr-autosyn-changefeed",
    "namespace": "default",
    "summary": {
      "state": "error",
      "tso": 442435313169596438,
      "checkpoint": "2023-06-26 13:19:39.364",
      "error": {
        "time": "2023-06-26T13:19:41.10221041+08:00",
        "addr": "ticdc1-peer:8300",
        "code": "CDC:ErrReachMaxTry",
        "message": "[CDC:ErrReachMaxTry]reach maximum try: 10, error: rpc error: code = Unknown desc = [PD:tso:ErrGenerateTimestamp]generate timestamp failed, requested pd is not leader of cluster: rpc error: code = Unknown desc = [PD:tso:ErrGenerateTimestamp]generate timestamp failed, requested pd is not leader of cluster"
      }
    }
  }
]

### What did you expect to see?

Changefeed should not report this error.

### What did you see instead?

changefeed failed and can't recover automatically.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):
[root@ticdc1-0 bin]# ./cdc version
Release Version: v6.5.3
Git Commit Hash: 1e2f277f2e3d9b57b15db9a2a9b2c62832c071ca
Git Branch: heads/refs/tags/v6.5.3
UTC Build Time: 2023-06-05 10:19:02
Go Version: go version go1.19.9 linux/amd64
Failpoint Build: false

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve?

Issue Number: close #9294 

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with `None`.
```

### CODE REVIEW

**Review by hicqu — APPROVED** [review]

File: pkg/pdutil/clock.go [hunk 1]
```diff
@@ -91,30 +90,26 @@ func (c *clock) Run(ctx context.Context) {
...
 				c.mu.tsProcessingTime = time.Now()
-				c.mu.err = nil
 				c.mu.Unlock()
 				return nil
 			}, retry.WithBackoffBaseDelay(200), retry.WithMaxTries(10))
 			if err != nil {
-				log.Warn("get time from pd failed, will use local time as pd time")
-				c.mu.Lock()
-				now := time.Now()
-				c.mu.tsEventTime = now
```
Comment (CharlesCheung96) [inline pkg/pdutil/clock.go:102]: Why remove this?

Comment (asddongmen) [reply pkg/pdutil/clock.go:102]: It's not necessary now. We can use `tsProcessingTime` to calculate approximate PD time when PD API does not response.

**Review by CharlesCheung96 — APPROVED** [review]
