### PR TITLE
test(dm): fix unsteable test TestRedirectRequestToLeader

### LINKED ISSUE #4554: DM TestRedirectRequestToLeader
### Which jobs are flaking?

verifyCI

### Which test(s) are flaking?

TestRedirectRequestToLeader

https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/ut-check/runs/1090/nodes/45/steps/49/log/?start=0

### Jenkins logs or GitHub Actions link

```log
[2022-02-09T10:01:31.274Z] goroutine 13617 [semacquire, 2 minutes]:
[2022-02-09T10:01:31.274Z] sync.runtime_Semacquire(0xc0032da1f0)
[2022-02-09T10:01:31.274Z] 	/usr/local/go/src/runtime/sema.go:56 +0x45
[2022-02-09T10:01:31.274Z] sync.(*WaitGroup).Wait(0xc0032da1e8)
[2022-02-09T10:01:31.274Z] 	/usr/local/go/src/sync/waitgroup.go:130 +0xe5
[2022-02-09T10:01:31.274Z] github.com/pingcap/tiflow/dm/dm/master.(*Server).Close(0xc0032da160)
[2022-02-09T10:01:31.274Z] 	/home/jenkins/agent/workspace/ut-check/tiflow/dm/dm/master/server.go:271 +0x15d
[2022-02-09T10:01:31.274Z] runtime.Goexit()
[2022-02-09T10:01:31.274Z] 	/usr/local/go/src/runtime/panic.go:632 +0x146
[2022-02-09T10:01:31.274Z] github.com/pingcap/check.(*C).stopNow(...)
[2022-02-09T10:01:31.274Z] 	/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:108
[2022-02-09T10:01:31.274Z] github.com/pingcap/check.(*C).Assert(0xc001906690, 0x5af7800, 0xc001edbd68, 0x7269578, 0x8e1f458, 0xc002d4b908, 0x1, 0x1)
[2022-02-09T10:01:31.274Z] 	/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/helpers.go:179 +0xc5
[2022-02-09T10:01:31.274Z] github.com/pingcap/tiflow/dm/dm/master.(*openAPISuite).TestRedirectRequestToLeader(0xc000b58560, 0xc001906690)
[2022-02-09T10:01:31.274Z] 	/home/jenkins/agent/workspace/ut-check/tiflow/dm/dm/master/openapi_test.go:121 +0xe46
[2022-02-09T10:01:31.274Z] reflect.Value.call(0x5eb1c40, 0xc000b58560, 0x1613, 0x6114672, 0x4, 0xc001cb7ef0, 0x1, 0x1, 0xc001cb7d08, 0x4b46bbe, ...)
[2022-02-09T10:01:31.274Z] 	/usr/local/go/src/reflect/value.go:476 +0x99c
[2022-02-09T10:01:31.274Z] reflect.Value.Call(0x5eb1c40, 0xc000b58560, 0x1613, 0xc001cb7ef0, 0x1, 0x1, 0xc001906780, 0x2, 0x2)
[2022-02-09T10:01:31.274Z] 	/usr/local/go/src/reflect/value.go:337 +0xd9
[2022-02-09T10:01:31.274Z] github.com/pingcap/check.(*suiteRunner).forkTest.func1(0xc001906690)
[2022-02-09T10:01:31.274Z] 	/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0xb3c
[2022-02-09T10:01:31.274Z] github.com/pingcap/check.(*suiteRunner).forkCall.func1(0xc0037983f0, 0xc001906690, 0xc00160c060)
[2022-02-09T10:01:31.274Z] 	/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x11e
[2022-02-09T10:01:31.274Z] created by github.com/pingcap/check.(*suiteRunner).forkCall
[2022-02-09T10:01:31.274Z] 	/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4cd
[2022-02-09T10:01:31.274Z] 
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve?

Issue Number: close #4554 

### What is changed and how it works?

send reuest after master ready 

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by lance6716 — COMMENTED** [review]
please also fix that when test failed `cancel` is not called so it will enter deadlock

File: dm/dm/master/openapi_test.go [hunk 1]
```diff
@@ -151,7 +155,7 @@ func (t *openAPISuite) TestOpenAPIWillNotStartInDefaultConfig(c *check.C) {
 	}), check.IsTrue)
 	c.Assert(s1.openapiHandles, check.IsNil)
 	defer s1.Close()
-	cancel()
+	defer cancel() // this cancel must call before s.Close() to avoid deadlock
```
Comment (D3Hunter) [inline dm/dm/master/openapi_test.go:158]: `cancel()` is the last call, defer or not makes no difference

Comment (Ehco1996) [reply dm/dm/master/openapi_test.go:158]: when some `c.Assert` failed， the last line cancel will not be called 😂  see this [comment](https://github.com/pingcap/tiflow/pull/4556#pullrequestreview-878430557)

Comment (D3Hunter) [reply dm/dm/master/openapi_test.go:158]: then `defer` should be moved before `assert`, else it won't be called either.

Comment (Ehco1996) [reply dm/dm/master/openapi_test.go:158]: sorry I didn't make myself clear

when some `c.Assert` that before `s.Close` and last line's `cancel()` failed, this test will blocked forever in the first `defer s.Close()` because the ctx is not cancelled

so `defer cancel` just needs  to be called before `s.Close`.

Comment (D3Hunter) [reply dm/dm/master/openapi_test.go:158]: > when some c.Assert that before s.Close and last line's cancel() failed, this test will blocked forever in the first defer s.Close()

defer runs when code runs past that point, in this case `defer s.Close()`  which is after the failed `c.Assert` will never run, see:

```go
func Test(t *testing.T) {
	require.True(t, false)
	defer fmt.Println("never run")
}
```

Comment (Ehco1996) [reply dm/dm/master/openapi_test.go:158]: yes, but test failed at L126 `c.Assert(result.Code(), check.Equals, http.StatusOK)`, new added defer is before this line

what i want to change is make sure `defer cancel() ` called before `defer s2.Close()`

**Review by D3Hunter — APPROVED** [review]

**Comment by Ehco1996** [comment]
could you please take another look for this pr ? thanks 🧡🧡🧡

@lance6716

**Review by lance6716 — APPROVED** [review]
