### PR TITLE
owner(ticdc): fix query healthy 500 since changefeed paused.

### LINKED ISSUE #7043: owner is unhealthy when there is any abnormal changefeed
### What did you do?

pause a changefeed

### What did you expect to see?

the owner should be healthy

### What did you see instead?

it's unhealthy

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #7043, ref #4757

### What is changed and how it works?

allow changefeeds abnormal in the cluster when check the healthy

#### Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
`None`.
```

### CODE REVIEW

File: cdc/owner/owner.go [hunk 1]
```diff
@@ -610,33 +610,47 @@ func (o *ownerImpl) handleQueries(query *Query) error {
...
 	}
 	if !o.clusterVersionConsistent(o.captures) {
-		return false, nil
+		return false
 	}
-	for _, cfReactor := range o.changefeeds {
-		provider := cfReactor.GetInfoProvider()
+	for _, changefeed := range o.changefeeds {
+		if changefeed.state == nil {
+			log.Warn("changefeed state is nil",
```
Comment (overvenus) [inline cdc/owner/owner.go:630]:
```suggestion
			log.Warn("isHealthy: changefeed state is nil",
```

File: cdc/owner/owner.go [hunk 2]
```diff
@@ -610,33 +610,47 @@ func (o *ownerImpl) handleQueries(query *Query) error {
...
+				zap.String("namespace", changefeed.id.Namespace),
+				zap.String("changefeed", changefeed.id.ID))
+			continue
+		}
+		if changefeed.state.Info.State != model.StateNormal {
+			log.Warn("changefeed not normal",
```
Comment (overvenus) [inline cdc/owner/owner.go:636]:
```suggestion
			log.Warn("isHealthy: changefeed not normal",
```

File: cdc/owner/owner.go [hunk 3]
```diff
@@ -610,33 +610,47 @@ func (o *ownerImpl) handleQueries(query *Query) error {
...
+				zap.Any("state", changefeed.state.Info.State))
+			continue
+		}
+
+		provider := changefeed.GetInfoProvider()
 		if provider == nil || !provider.IsInitialized() {
 			// The scheduler has not been initialized yet, it is considered
 			// unhealthy, because owner can not schedule tables for now.
-			return false, nil
+			log.Warn("owner is not healthy since changefeed not initialized",
```
Comment (overvenus) [inline cdc/owner/owner.go:647]:
```suggestion
			log.Warn("isHealthy: changefeed is not initialized",
```

**Review by overvenus — APPROVED** [review]
