### PR TITLE
consumer(cdc): fix unstable test move_table

### LINKED ISSUE #2887: CI: kafka integration tests `move_table` meet panic: the commitTs of the emit row is less than the received row.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
CI run integration tests.
2. What did you expect to see?
pass all tests.
3. What did you see instead?
`move_table` fails times and can find an panic in 
[cdc_kafka_consumer.log](https://github.com/pingcap/ticdc/files/7224667/cdc_kafka_consumer.log)

https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/3939/pipeline/

```
[2021/09/24 14:46:49.037 +08:00] [PANIC] [common.go:87] ["the commitTs of the emit row is less than the received row"] [table=move_table.usertable] ["emit row startTs"=427941163863900200] ["emit row commitTs"=427941163863900200] ["last received row commitTs"=427941164073877740] [stack="github.com/pingcap/ticdc/cdc/sink/common.(*UnresolvedTxnCache).Append\n\tgithub.com/pingcap/ticdc/cdc/sink/common/common.go:87\ngithub.com/pingcap/ticdc/cdc/sink.(*mysqlSink).EmitRowChangedEvents\n\tgithub.com/pingcap/ticdc/cdc/sink/mysql.go:115\nmain.(*Consumer).ConsumeClaim\n\tcommand-line-arguments/main.go:442\ngithub.com/Shopify/sarama.(*consumerGroupSession).consume\n\tgithub.com/Shopify/sarama@v1.27.2/consumer_group.go:690\ngithub.com/Shopify/sarama.newConsumerGroupSession.func2\n\tgithub.com/Shopify/sarama@v1.27.2/consumer_group.go:615"]
```
4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - TiCDC version (execute `cdc version`):

        ```
        https://github.com/pingcap/ticdc/pull/2880
        ```

### LINKED ISSUE #5090: kafka sarama client data race
### Which jobs are flaking?

cdc_ghpr_kafka_integration_test

### Which test(s) are flaking?

cli

### Jenkins logs or GitHub Actions link

```log
[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-361)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-362)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-363)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-364)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-365)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-366)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-367)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-368)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-369)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-370)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-371)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-372)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-373)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-374)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-375)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-376)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-377)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-378)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-379)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-380)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-381)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-382)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-383)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-384)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-385)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-386)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-387)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-388)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-389)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-390)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-391)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-392)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-393)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-394)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-395)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-396)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-397)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-398)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-399)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-400)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-401)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-402)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-403)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-404)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-405)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-406)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-407)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-408)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-409)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-410)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-411)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-412)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-413)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-414)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-415)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-416)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-417)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-418)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-419)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-420)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-421)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-422)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-423)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-424)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-425)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-426)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-427)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-428)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-429)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-430)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-431)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-432)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-433)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-434)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-435)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-436)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-437)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-438)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-439)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-440)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-441)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-442)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-443)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-444)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-445)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-446)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-447)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-448)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-449)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-450)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-451)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-452)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-453)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-454)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-455)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-456)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-457)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-458)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-459)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-460)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-461)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-462)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-463)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-464)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-465)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-466)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-467)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-468)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-469)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-470)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-471)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-472)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-473)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-474)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-475)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-476)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-477)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-478)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-479)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-480)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-481)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline#step-997-log-482)[2022-04-01T02:48:48.961Z] + cdc.test -test.coverprofile=/tmp/tidb_cdc_test/cov.cli.cli.9154.out cli changefeed create --start-ts=432218131581632513 --sort-engine=memory '--sink-uri=kafka://127.0.0.1:9092/ticdc-cli-test-16814?protocol=open-protocol&partition-num=4&kafka-version=2.4.1&max-message-bytes=10485760' --tz=Asia/Shanghai -c=custom-changefeed-name

[2022-04-01T02:48:49.891Z] ==================

[2022-04-01T02:48:49.891Z] WARNING: DATA RACE

[2022-04-01T02:48:49.891Z] Read at 0x00000a6908d0 by goroutine 185:

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.version()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/version.go:8 +0x30

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.(*Broker).Open.func1.1()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/broker.go:183 +0x76

[2022-04-01T02:48:49.891Z]   runtime.deferreturn()

[2022-04-01T02:48:49.891Z]       /usr/local/go/src/runtime/panic.go:436 +0x32

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.withRecover()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/utils.go:43 +0x48

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.(*Broker).Open.func2()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/broker.go:172 +0x39

[2022-04-01T02:48:49.891Z] 

[2022-04-01T02:48:49.891Z] Previous write at 0x00000a6908d0 by goroutine 181:

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.version()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/version.go:11 +0x7e

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.(*Broker).Open.func1.1()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/broker.go:183 +0x76

[2022-04-01T02:48:49.891Z]   runtime.deferreturn()

[2022-04-01T02:48:49.891Z]       /usr/local/go/src/runtime/panic.go:436 +0x32

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.withRecover()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/utils.go:43 +0x48

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.(*Broker).Open.func2()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/broker.go:172 +0x39

[2022-04-01T02:48:49.891Z] 

[2022-04-01T02:48:49.891Z] Goroutine 185 (running) created at:

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.(*Broker).Open()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/broker.go:172 +0x3f0

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.(*client).Controller()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/client.go:529 +0x1b0

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.NewClusterAdminFromClient()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/admin.go:159 +0x3b

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.NewClusterAdmin()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/admin.go:152 +0x84

[2022-04-01T02:48:49.891Z]   github.com/pingcap/tiflow/pkg/kafka.NewSaramaAdminClient()

[2022-04-01T02:48:49.891Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/pkg/kafka/cluster_admin_client.go:40 +0x64

[2022-04-01T02:48:49.891Z]   github.com/pingcap/tiflow/cdc/sink.newKafkaSaramaSink()

[2022-04-01T02:48:49.891Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/sink/mq.go:366 +0x21b

[2022-04-01T02:48:49.891Z]   github.com/pingcap/tiflow/cdc/sink.init.2.func3()

[2022-04-01T02:48:49.891Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/sink/sink.go:116 +0x8c

[2022-04-01T02:48:49.891Z]   github.com/pingcap/tiflow/cdc/sink.New()

[2022-04-01T02:48:49.891Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/sink/sink.go:143 +0x2b1

[2022-04-01T02:48:49.891Z]   github.com/pingcap/tiflow/cdc/sink.Validate()

[2022-04-01T02:48:49.891Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/sink/sink.go:157 +0x144

[2022-04-01T02:48:49.891Z]   github.com/pingcap/tiflow/pkg/cmd/cli.(*createChangefeedOptions).validateSink()

[2022-04-01T02:48:49.891Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/pkg/cmd/cli/cli_changefeed_create.go:381 +0x98

[2022-04-01T02:48:49.891Z]   github.com/pingcap/tiflow/pkg/cmd/cli.(*createChangefeedOptions).run()

[2022-04-01T02:48:49.891Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/pkg/cmd/cli/cli_changefeed_create.go:436 +0x6b8

[2022-04-01T02:48:49.891Z]   github.com/pingcap/tiflow/pkg/cmd/cli.newCmdCreateChangefeed.func1()

[2022-04-01T02:48:49.891Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/pkg/cmd/cli/cli_changefeed_create.go:479 +0x151

[2022-04-01T02:48:49.891Z]   github.com/spf13/cobra.(*Command).execute()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0xad7

[2022-04-01T02:48:49.891Z]   github.com/spf13/cobra.(*Command).ExecuteC()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x5c9

[2022-04-01T02:48:49.891Z]   github.com/spf13/cobra.(*Command).Execute()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902 +0x2fd

[2022-04-01T02:48:49.891Z]   github.com/pingcap/tiflow/pkg/cmd.Run()

[2022-04-01T02:48:49.891Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/pkg/cmd/cmd.go:50 +0x300

[2022-04-01T02:48:49.891Z]   github.com/pingcap/tiflow/cmd/cdc.main()

[2022-04-01T02:48:49.891Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cmd/cdc/main.go:27 +0x33

[2022-04-01T02:48:49.891Z]   github.com/pingcap/tiflow/cmd/cdc.TestRunMain()

[2022-04-01T02:48:49.891Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cmd/cdc/main_test.go:35 +0xca

[2022-04-01T02:48:49.891Z]   testing.tRunner()

[2022-04-01T02:48:49.891Z]       /usr/local/go/src/testing/testing.go:1439 +0x213

[2022-04-01T02:48:49.891Z]   testing.(*T).Run.func1()

[2022-04-01T02:48:49.891Z]       /usr/local/go/src/testing/testing.go:1486 +0x47

[2022-04-01T02:48:49.891Z] 

[2022-04-01T02:48:49.891Z] Goroutine 181 (finished) created at:

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.(*Broker).Open()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/broker.go:172 +0x3f0

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.(*client).any()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/client.go:686 +0x144

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.(*client).tryRefreshMetadata()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/client.go:879 +0x17e

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.(*client).RefreshMetadata()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/client.go:489 +0x20f

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.NewClient()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/client.go:170 +0x476

[2022-04-01T02:48:49.891Z]   github.com/Shopify/sarama.NewClusterAdmin()

[2022-04-01T02:48:49.891Z]       /go/pkg/mod/github.com/!shopify/sarama@v1.32.0/admin.go:148 +0x4e

[2022-04-01T02:48:49.891Z]   github.com/pingcap/tiflow/pkg/kafka.NewSaramaAdminClient()

[2022-04-01T02:48:49.891Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/pkg/kafka/cluster_admin_client.go:40 +0x64

[2022-04-01T02:48:49.891Z]   github.com/pingcap/tiflow/cdc/sink.newKafkaSaramaSink()

[2022-04-01T02:48:49.891Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/sink/mq.go:366 +0x21b

[2022-04-01T02:48:49.891Z]   github.com/pingcap/tiflow/cdc/sink.init.2.func3()

[2022-04-01T02:48:49.891Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/sink/sink.go:116 +0x8c

[2022-04-01T02:48:49.891Z]   github.com/pingcap/tiflow/cdc/sink.New()

[2022-04-01T02:48:49.891Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/sink/sink.go:143 +0x2b1

[2022-04-01T02:48:49.891Z]   github.com/pingcap/tiflow/cdc/sink.Validate()

[2022-04-01T02:48:49.891Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/sink/sink.go:157 +0x144

[2022-04-01T02:48:49.892Z]   github.com/pingcap/tiflow/pkg/cmd/cli.(*createChangefeedOptions).validateSink()

[2022-04-01T02:48:49.892Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/pkg/cmd/cli/cli_changefeed_create.go:381 +0x98

[2022-04-01T02:48:49.892Z]   github.com/pingcap/tiflow/pkg/cmd/cli.(*createChangefeedOptions).run()

[2022-04-01T02:48:49.892Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/pkg/cmd/cli/cli_changefeed_create.go:436 +0x6b8

[2022-04-01T02:48:49.892Z]   github.com/pingcap/tiflow/pkg/cmd/cli.newCmdCreateChangefeed.func1()

[2022-04-01T02:48:49.892Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/pkg/cmd/cli/cli_changefeed_create.go:479 +0x151

[2022-04-01T02:48:49.892Z]   github.com/spf13/cobra.(*Command).execute()

[2022-04-01T02:48:49.892Z]       /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0xad7

[2022-04-01T02:48:49.892Z]   github.com/spf13/cobra.(*Command).ExecuteC()

[2022-04-01T02:48:49.892Z]       /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x5c9

[2022-04-01T02:48:49.892Z]   github.com/spf13/cobra.(*Command).Execute()

[2022-04-01T02:48:49.892Z]       /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902 +0x2fd

[2022-04-01T02:48:49.892Z]   github.com/pingcap/tiflow/pkg/cmd.Run()

[2022-04-01T02:48:49.892Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/pkg/cmd/cmd.go:50 +0x300

[2022-04-01T02:48:49.892Z]   github.com/pingcap/tiflow/cmd/cdc.main()

[2022-04-01T02:48:49.892Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cmd/cdc/main.go:27 +0x33

[2022-04-01T02:48:49.892Z]   github.com/pingcap/tiflow/cmd/cdc.TestRunMain()

[2022-04-01T02:48:49.892Z]       /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cmd/cdc/main_test.go:35 +0xca

[2022-04-01T02:48:49.892Z]   testing.tRunner()

[2022-04-01T02:48:49.892Z]       /usr/local/go/src/testing/testing.go:1439 +0x213

[2022-04-01T02:48:49.892Z]   testing.(*T).Run.func1()

[2022-04-01T02:48:49.892Z]       /usr/local/go/src/testing/testing.go:1486 +0x47

[2022-04-01T02:48:49.892Z] ==================

[2022-04-01T02:48:49.892Z] Create changefeed successfully!

[2022-04-01T02:48:49.892Z] ID: custom-changefeed-name

[2022-04-01T02:48:49.892Z] Info: {"sink-uri":"kafka://127.0.0.1:9092/ticdc-cli-test-16814?protocol=open-protocol\u0026partition-num=4\u0026kafka-version=2.4.1\u0026max-message-bytes=10485760","opts":{},"create-time":"2022-04-01T10:48:49.704160167+08:00","start-ts":432218131581632513,"target-ts":0,"admin-job-type":0,"sort-engine":"memory","sort-dir":"","config":{"case-sensitive":true,"enable-old-value":true,"force-replicate":false,"check-gc-safe-point":true,"filter":{"rules":["*.*"],"ignore-txn-start-ts":null},"mounter":{"worker-num":16},"sink":{"dispatchers":null,"protocol":"open-protocol","column-selectors":null},"cyclic-replication":{"enable":false,"replica-id":0,"filter-replica-ids":null,"id-buckets":0,"sync-ddl":false},"scheduler":{"type":"table-number","polling-time":-1},"consistent":{"level":"none","max-log-size":64,"flush-interval":1000,"storage":""}},"state":"normal","error":null,"sync-point-enabled":false,"sync-point-interval":600000000000,"creator-version":"v6.1.0-alpha-51-g448da119"}

[2022-04-01T02:48:49.892Z] --- FAIL: TestRunMain (0.48s)

[2022-04-01T02:48:49.892Z]     testing.go:1312: race detected during execution of test

[2022-04-01T02:48:49.892Z] FAIL

[2022-04-01T02:48:50.454Z] coverage: 3.3% of statements in github.com/pingcap/tiflow/...

[2022-04-01T02:49:12.367Z] make: *** [integration_test_kafka] Error 1
```
https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/10320/pipeline

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### LINKED ISSUE #5101: revert sarama v.1.32.0 to v1.29.0
sarama v1.32.0 has data race bug, which may cause unknown problems to tiflow kafka sink, so we revert it to v1.29.0, which was adopted by cockroach.

https://github.com/pingcap/tiflow/issues/5090
https://github.com/Shopify/sarama/pull/2171

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #2887, close #5101, close #5090

https://github.com/Shopify/sarama/blob/main/config.go#L38-L44
https://github.com/Shopify/sarama/blob/main/config.go#L461

https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html#producerconfigs_max.in.flight.requests.per.connection

### What is changed and how it works?

Consumer may receive `RowChangedEvent` out of order by the commitTs, may caused by the the issues mentioned above.

* Emit row changed event if resolved ts received, just like what cdc do .

revert sarama to 1.29.0, to prevent data race introduced by sarama v1.32.0

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

### Release note 

```release-note
`None`.
```

### CODE REVIEW

File: cdc/owner/changefeed.go [hunk 1]
```diff
@@ -211,7 +211,7 @@ func (c *changefeed) tick(ctx cdcContext.Context, state *orchestrator.Changefeed
 		// This condition implies that the DDL resolved-ts has not yet reached checkpointTs,
 		// which implies that it would be premature to schedule tables or to update status.
 		// So we return here.
-		log.Info("barrierTs < checkpointTs, premature to schedule tables or update status",
+		log.Debug("barrierTs < checkpointTs, premature to schedule tables or update status",
```
Comment (overvenus) [inline cdc/owner/changefeed.go:214]: Why use Debug level? Is it verbose?

File: cdc/sink/common/common.go [hunk 2]
```diff
@@ -83,10 +83,8 @@ func (c *UnresolvedTxnCache) Append(filter *filter.Filter, rows ...*model.RowCha
 			// fail-fast check
 			if len(txns) != 0 && txns[len(txns)-1].commitTs > row.CommitTs {
 				log.Panic("the commitTs of the emit row is less than the received row",
-					zap.Stringer("table", row.Table),
-					zap.Uint64("emit row startTs", row.StartTs),
-					zap.Uint64("emit row commitTs", row.CommitTs),
-					zap.Uint64("last received row commitTs", txns[len(txns)-1].commitTs))
+					zap.Uint64("last received row commitTs", txns[len(txns)-1].commitTs),
```
Comment (overvenus) [inline cdc/sink/common/common.go:86]:
```suggestion
					zap.Uint64("lastReceivedCommitTs", txns[len(txns)-1].commitTs),
```

We prefer camelCase.

**Review by overvenus — COMMENTED** [review]
rest LGTM

File: cdc/owner/changefeed.go (hunk 1 above)
Comment (3AceShowHand) [reply cdc/owner/changefeed.go:214]: yes , it's quite verbose.

Comment (3AceShowHand) [reply cdc/owner/changefeed.go:214]: it would flood logs files, which makes trouble shooting hard.

**Review by overvenus — APPROVED** [review]

**Review by sdojjy — APPROVED** [review]

**Comment by 3AceShowHand** [comment]
integration-test

**Comment by hi-rustin** [comment]
@3AceShowHand The dm test keeps failing, which I feel may be related to the tidb dependency upgrade. Also cdc seems to have been introduced as an unstable test.

/hold
