### PR TITLE
cdc(ddl): ensure strict ordering for multi-table DDLs after split

### LINKED ISSUE #12449: Fix incorrect execution order for multi-table RENAME TABLE DDLs
### What did you do?

1. create a changefeed
2. create table t3 (id int primary key, val int)
3. create table t1 (id int primary key, val int)
4. create table t2 (id int primary key, val int)
5. rename table t1 to t4, t2 to t1, t3 to t2;

### What did you expect to see?

3 rename table DDL was executed in the downstream.

### What did you see instead?

Just rename table t1 to t4 was executed in the downstream.

Currently, when TiCDC encounters a multi-table DDL statement (e.g., RENAME TABLE t1 TO t4, t2 TO t1, t3 TO t2;), it splits this single DDL job into multiple individual DDL events (one for each table rename).

Since these split events originate from the same DDL job, they share the exact same CommitTs. In the current implementation, the ddl_manager sorts DDLs primarily by CommitTs. Because the timestamps are identical, the execution order of these split events becomes non-deterministic or unstable.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v6.5.12
```

Upstream TiKV version (execute `tikv-server --version`):

```console
v6.5.12
```

TiCDC version (execute `cdc version`):

```console
v6.5.12
```

### PR DESCRIPTION
**Pull request by wlwilliamx**
### What problem does this PR solve?

Issue Number: close #12449

### What is changed and how it works?

This PR addresses an issue where split DDLs from a multi-table `RENAME` statement could be executed out of order downstream because they share the same `CommitTs` and the order of ranging map is non-deterministic.

#### Tests 

 - Unit test
 - Integration test
 - Manual test

##### Will it cause performance regression or break compatibility?
None
##### Do you need to update user documentation, design documentation or monitoring documentation?
None
### Release note 

```release-note
Fix the incorrect execution order of split DDLs generated from a multi-table DDL statement (e.g., RENAME TABLE).
```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

File: tests/integration_tests/common_1/data/test.sql [hunk 1]
```diff
@@ -175,3 +175,10 @@ VALUES (1),
 UPDATE `column_is_null`
 SET t = NULL
 WHERE id = 1;
+
+-- rename tables DDL should keep the order of events
+
+create table rename_t3 (id int primary key, val int);
+create table rename_t1 (id int primary key, val int);
+create table rename_t2 (id int primary key, val int);
+rename table rename_t1 to rename_t4, rename_t2 to rename_t1, rename_t3 to rename_t2;
```
Comment (lidezhu) [inline tests/integration_tests/common_1/data/test.sql]: If rename table doesn't behave as expected, it seems this test case still doesn't report any error. May be we need create different table structures and insert some data after the rename?

Comment (wlwilliamx) [reply tests/integration_tests/common_1/data/test.sql]: yes, thanks for reminding

Comment (wlwilliamx) [reply tests/integration_tests/common_1/data/test.sql]: done

**Review by lidezhu — APPROVED** [review]
