### PR TITLE
filter(ticdc): fix incorrect event filter with "rename" DDLs

### LINKED ISSUE #11946: In [[filter.event-filters]], with "rename" DDLs the `matcher` is filtered based on the new name rather than old name
### What did you do?

1. Create 3 tables:

    ```sql
    use test;
    create table a1 (pk int primary key, val int);
    create table a2 like a1;
    create table b3 like a1;
    ```

2. Create a changefeed with configuration:

    ```toml
    [filter]
    rules = ['test.a*', 'test.b*']
    [[filter.event-filters]]
    matcher = ['test.a*']
    ignore-event = ['all ddl']
    ```

    ```sh
    cdc cli changefeed create --sink-uri='file:///tmp/test-cdc-storage?protocol=canal-json' --config=cfg.toml -c xxx
    ```

3. Perform the following renames:

    ```sql
    rename table a1 to b1;
    rename table a2 to c2;
    rename table b3 to a3;
    ```

### What did you expect to see?

As explained in https://docs.pingcap.com/tidb/stable/ticdc-ddl#ddl-replication-considerations-for-renaming-tables, since `filter.rules` is looking at the *old name*, we expect `filter.event-filters[].matcher` is also looking at the *old name* too. That means the downstream should *ignore* the first two renames and only replicate the last.

```sql
-- rename table a1 to b1;  -- ignored
-- rename table a2 to c2;  -- ignored
rename table b3 to a3;  -- replicated
```

### What did you see instead?

The `filter.event-filters[].matcher` rule actually looks at the *new name*, so instead the first two DDLs are replicated while the last one is ignored.

```sql
rename table a1 to b1;  -- incorrectly replicated
rename table a2 to c2;  -- incorrectly replicated
-- rename table b3 to a3;  -- incorrectly ignored
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v8.5.0
```

Upstream TiKV version (execute `tikv-server --version`):

```console
v8.5.0
```

TiCDC version (execute `cdc version`):

```console
v8.5.0
```

### PR DESCRIPTION
**Pull request by wk989898**
### What problem does this PR solve?

Issue Number: close #11946

### What is changed and how it works?
Event Filter wrongly uses the current table info with "rename" DDLs and It should use the previous table info to filter events.

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
Fix incorrect event filter with "rename table" DDLs
```

### CODE REVIEW

**Comment by kennytm** [comment]
does it work if the DDL renamed multiple tables (e.g. `rename a1 to b1, a2 to b2, b3 to a3;`)?

**Comment by wk989898** [comment]
> does it work if the DDL renamed multiple tables (e.g. `rename a1 to b1, a2 to b2, b3 to a3;`)?

Yes, you can check the integration test.

File: pkg/filter/sql_event_filter.go [hunk 1]
```diff
@@ -136,9 +136,21 @@ func (f *sqlEventFilter) shouldSkipDDL(ddl *model.DDLEvent) (skip bool, err erro
...
+	evenType := ddlToEventType(ddl.Type)
 	schema := ddl.TableInfo.TableName.Schema
 	table := ddl.TableInfo.TableName.Table
-	evenType := ddlToEventType(ddl.Type)
+	if evenType == bf.RenameTable {
+		if ddl.PreTableInfo == nil {
+			log.Warn("sql event filter doesn't find old table info when the event type is `rename table`",
+				zap.String("schema", schema),
+				zap.String("table", table),
+				zap.String("type", ddl.Type.String()),
```
Comment (kennytm) [inline pkg/filter/sql_event_filter.go:147]:
```suggestion
				zap.Stringer("type", ddl.Type),
```

**Review by kennytm — APPROVED** [review]
rest lgtm

**Review by asddongmen — APPROVED** [review]

**Comment by kennytm** [comment]
i haven't tested but i think the issue affected 6.5 and 7.1 too
