### PR TITLE
puller(ticdc):  fix stuck detect issue

### LINKED ISSUE #10256: resolved ts stucks when enable-resolved-ts-stuck-detection is on
### What did you do?

1. Deploy TiDB with CDC, with enable-resolved-ts-stuck-detection = true
```
bash-5.1# cat /etc/ticdc/ticdc.toml
log-file = "/var/lib/ticdc/log/ticdc.log"

[debug]
  [debug.puller]
    enable-resolved-ts-stuck-detection = true
    resolved-ts-stuck-interval = "2m"

```
2. Create changefeed and pause it.
3. run workload
```
sysbench --db-driver=mysql --mysql-host=`nslookup upstream-tidb.cdc-testbed-tps-5100017-1-
576 | awk -F: '{print $2}' | awk 'NR==5' | sed s/[[:space:]]//g`  --mysql-port=4000 --mysql-user=root --mysql-db=workload --tables=1 --table-size=500000000 --create_secondary=off --debug=true
 --threads=100 --mysql-ignore-errors=2013,1213,1105,1205,8022,8027,8028,9004,9007,1062 oltp_read_write prepare
```
4. resume changefeed
5. run workload 
```
sysbench --db-driver=mysql --mysql-host=`nslookup upstream-tidb.cdc-testbed-tps-5100017-1-
576 | awk -F: '{print $2}' | awk 'NR==5' | sed s/[[:space:]]//g`  --mysql-port=4000 --mysql-user=root --mysql-db=workload --tables=1 --table-size=500000000 --create_secondary=off --time=18000
 --debug=true --threads=100 --mysql-ignore-errors=2013,1213,1105,1205,8022,8027,8028,9004,9007,1062 oltp_read_write run
```

### What did you expect to see?

CDC Resolved TS should not stuck

### What did you see instead?

img_v3_025s_e7ffd8ea-471e-4e80-9a6d-4b185051e0fg

### Versions of the cluster

bash-5.1# /cdc version
Release Version: v6.5.6
Git Commit Hash: 067bb8031fd2d15763b464052a1e550a81af2196
Git Branch: heads/refs/tags/v6.5.6
UTC Build Time: 2023-12-04 10:28:57
Go Version: go version go1.19.13 linux/amd64
Failpoint Build: false

### PR DESCRIPTION
**Pull request by sdojjy**
### What problem does this PR solve?

Issue Number: close #10256 

### What is changed and how it works?
check if the resolved ts is advanced before

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

File: cdc/puller/puller.go [hunk 1]
```diff
@@ -276,9 +280,13 @@ func (p *pullerImpl) Run(ctx context.Context) error {
 	return g.Wait()
 }
 
-func (p *pullerImpl) detectResolvedTsStuck(initialized bool) error {
-	if p.cfg.Debug.Puller.EnableResolvedTsStuckDetection && initialized {
+func (p *pullerImpl) detectResolvedTsStuck() error {
+	if p.cfg.Debug.Puller.EnableResolvedTsStuckDetection {
 		resolvedTs := p.tsTracker.Frontier()
+		// check if the resolvedTs is advanced before
```
Comment (asddongmen) [inline cdc/puller/puller.go:286]:
```suggestion
		// check if the resolvedTs is advancing,
		// If the resolvedTs in Frontier is less than startResolvedTs, it means that the incremental scan has 
		// not complete yet. We need to make no decision in this scenario. 
```

**Review by asddongmen — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]
