### PR TITLE
sink(ticdc): waiting the asynchronous ddl to synchronize

### LINKED ISSUE #12114: modify column  was retried repeatedly by ticdc and after a time, changefeed status was failed
### What did you do?

1. upstream execute 'alter table xxx modify column value decimal(16,6)'.  The table has 140 million rows.  
2. downstream modify column cost more than 8 hours.

Image

3. TiCDC retried 20 times and failed. after 24 hours, lost data, need rebuild TiCDC task.
It seems like the issue  https://github.com/pingcap/tiflow/issues/10682. The PR just fix add index and drop index. 
Please fix the issue caused by modifying the column

### What did you expect to see?

TiCDC normal

### What did you see instead?

TiCDC failed

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v6.5.3
```

Upstream TiKV version (execute `tikv-server --version`):

```console
v6.5.3
```

TiCDC version (execute `cdc version`):

```console
v6.5.3
```

### LINKED ISSUE #12128: Add unexpected multiple indexes when CDC retries happened
### What did you do?

1. Create a changefeed with sink-uri="mysql://root@127.0.0.1:3306/?read-timeout=10ms"
2. Run add index SQL `alter table xx add index (col);`

### What did you expect to see?

The index should be the same 

### What did you see instead?

The log shows "Execute DDL with error, retry later" and the index are not same.


```sql
# Upstream
show create table t;
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                                          |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `id` int NOT NULL,
  `col` decimal(65,30) DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `col` (`col`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

```sql
#Downstream
show create table t;
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                                                                                                               |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `id` int NOT NULL,
  `col` decimal(65,30) DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `col` (`col`),
  KEY `col_2` (`col`),
  KEY `col_3` (`col`),
  KEY `col_4` (`col`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### Versions of the cluster


TiCDC version (execute `cdc version`):

```console
master
```

### PR DESCRIPTION
**Pull request by wk989898**
### What problem does this PR solve?

Issue Number: close #12114 close #12128

### What is changed and how it works?
When a DDL operation takes a long time, the connection may be lost, even though the DDL is actually executed. Instead of throwing a failure state, we can query the downstream and wait for the DDL to complete.

**Notice**: 
- ~~The add index DDL operates the same as before and does not require waiting.~~ Adding an index DDL requires waiting for a timeout.
- Waiting DDL mechanism only works when downstream is TiDB and the user is at the root.
#### Tests 

 - Unit test
 - Integration test
 - manual test
 ```sql
mysql> select count(*) from information_schema.ddl_jobs where CREATE_TIME >= now() - interval 10 MINUTE;
+----------+
| count(*) |
+----------+
|     9000 |
+----------+
1 row in set (0.90 sec)
mysql> SELECT JOB_ID, JOB_TYPE, SCHEMA_STATE, SCHEMA_ID, TABLE_ID, STATE, QUERY FROM information_schema.ddl_jobs where CREATE_TIME >= now()- interval 10 MINUTE;
...
...
...
9000 rows in set (0.91 sec)
```

### Release note 

```release-note
Wait for the DDL to synchronize when meeting MySQL Invalid connection error
```

### CODE REVIEW

File: cdc/sink/ddlsink/mysql/mysql_ddl_sink.go [hunk 1]
```diff
@@ -306,23 +357,116 @@ func needFormatDDL(db *sql.DB, cfg *pmysql.Config) bool {
...
+// getDDLStatusFromTiDB retrieves the synchronizing status of DDL from TiDB
+func getDDLStatusFromTiDB(ctx context.Context, db *sql.DB, ddl string, createTime int64) (string, error) {
+	linesOfRows := 10
+	rowNum := linesOfRows
+	rowOffset := 0
+	queryMap := make(map[int]string)
+
+	for {
+		// every attempt try 10 history jobs
+		showJobs := fmt.Sprintf("ADMIN SHOW DDL JOBS %d", rowNum)
```
Comment (hongyunyan) [inline cdc/sink/ddlsink/mysql/mysql_ddl_sink.go:388]: please use information_schema.ddl_jobs to get these infos instead of ADMIN SHOW DDL JOBS.
ref // TODO: Use the flollowing SQL to check the ddl job status after tidb optimize
// the information_schema.ddl_jobs table. Ref: https://github.com/pingcap/tidb/issues/55725
//
// SELECT JOB_ID, JOB_TYPE, SCHEMA_STATE, SCHEMA_ID, TABLE_ID, STATE, QUERY
// FROM information_schema.ddl_jobs

File: cdc/sink/ddlsink/mysql/mysql_ddl_sink.go [hunk 2]
```diff
@@ -134,7 +136,35 @@ func (m *DDLSink) WriteDDLEvent(ctx context.Context, ddl *model.DDLEvent) error
 		return m.asyncExecDDL(ctx, ddl)
 	}
 
+	ddlCreateTime := getDDLCreateTime(ctx, m.db)
 	if err := m.execDDLWithMaxRetries(ctx, ddl); err != nil {
+		if m.cfg.IsTiDB && ddlCreateTime != -1 && errors.Cause(err) == mysql.ErrInvalidConn {
```
Comment (hongyunyan) [inline cdc/sink/ddlsink/mysql/mysql_ddl_sink.go:141]: It's better to extract a function for these logic.

File: cdc/sink/ddlsink/mysql/mysql_ddl_sink.go [hunk 3]
```diff
@@ -306,23 +331,123 @@ func needFormatDDL(db *sql.DB, cfg *pmysql.Config) bool {
...
-	if m.statistics != nil {
-		m.statistics.Close()
-	}
-	if m.db != nil {
-		if err := m.db.Close(); err != nil {
-			log.Warn("MySQL ddl sink close db wit error",
-				zap.String("namespace", m.id.Namespace),
-				zap.String("changefeed", m.id.ID),
-				zap.Error(err))
+var checkRunningSQL = `
```
Comment (hongyunyan) [inline cdc/sink/ddlsink/mysql/mysql_ddl_sink.go:353]: we can update the sql to directly selete the jobs whose create_time > ddlCreateTime, instead of loop the rows to check.

Besides, the sql can also add the clause like `AND JOB_TYPE LIKE "add index%%`

File: cdc/sink/ddlsink/mysql/mysql_ddl_sink.go [hunk 4]
```diff
@@ -275,6 +251,54 @@ func (m *DDLSink) execDDL(pctx context.Context, ddl *model.DDLEvent) error {
 	return nil
 }
 
+func (m *DDLSink) waitDDLDone(ctx context.Context, ddl *model.DDLEvent, ddlCreateTime string) error {
+	ticker := time.NewTimer(30 * time.Second)
+	defer ticker.Stop()
+	for {
+		state, err1 := getDDLStateFromTiDB(ctx, m.db, ddl.Query, ddlCreateTime)
```
Comment (hongyunyan) [inline cdc/sink/ddlsink/mysql/mysql_ddl_sink.go:258]:
```suggestion
		state, err := getDDLStateFromTiDB(ctx, m.db, ddl.Query, ddlCreateTime)
```

File: cdc/sink/ddlsink/mysql/mysql_ddl_sink.go [hunk 5]
```diff
@@ -306,23 +330,48 @@ func needFormatDDL(db *sql.DB, cfg *pmysql.Config) bool {
...
-				zap.String("namespace", m.id.Namespace),
-				zap.String("changefeed", m.id.ID),
-				zap.Error(err))
+
+	var jobsResults [][]string
+	jobsResults, err = export.GetSpecifiedColumnValuesAndClose(jobsRows, "QUERY", "STATE")
+	if err != nil {
+		return "", err
+	}
+	for i := 0; i < len(jobsResults); i++ {
```
Comment (hongyunyan) [inline cdc/sink/ddlsink/mysql/mysql_ddl_sink.go:368]: why don't we do that in sql statement like create time?

File: cdc/sink/ddlsink/mysql/mysql_ddl_sink.go [hunk 6]
```diff
@@ -306,23 +330,48 @@ func needFormatDDL(db *sql.DB, cfg *pmysql.Config) bool {
 	return false
 }
 
-// WriteCheckpointTs does nothing.
-func (m *DDLSink) WriteCheckpointTs(_ context.Context, _ uint64, _ []*model.TableInfo) error {
-	// Only for RowSink for now.
-	return nil
+func getDDLCreateTime(ctx context.Context, db *sql.DB) string {
+	ddlCreateTime := "" // default when scan failed
+	row, err := db.QueryContext(ctx, "SELECT UTC_TIMESTAMP()")
```
[the remark this answers is not in the document]
Comment (wk989898) [reply cdc/sink/ddlsink/mysql/mysql_ddl_sink.go]: The `ddlCreateTime` is from downstream.

File: cdc/sink/ddlsink/mysql/mysql_ddl_sink.go [hunk 7]
```diff
@@ -306,23 +327,52 @@ func needFormatDDL(db *sql.DB, cfg *pmysql.Config) bool {
...
 
-// WriteCheckpointTs does nothing.
-func (m *DDLSink) WriteCheckpointTs(_ context.Context, _ uint64, _ []*model.TableInfo) error {
-	// Only for RowSink for now.
-	return nil
+func getDDLCreateTime(ctx context.Context, db *sql.DB) string {
+	ddlCreateTime := "" // default when scan failed
+	row, err := db.QueryContext(ctx, "BEGIN; SET @ticdc_ts := TIDB_PARSE_TSO(@@tidb_current_ts); ROLLBACK; SELECT @ticdc_ts; SET @ticdc_ts=NULL;")
+	if err != nil {
+		log.Warn("selecting utc timestamp failed", zap.Error(err))
```
Comment (hongyunyan) [inline cdc/sink/ddlsink/mysql/mysql_ddl_sink.go:335]:
```suggestion
		log.Warn("selecting tidb current timestamp failed", zap.Error(err))
```

**Review by hongyunyan — APPROVED** [review]
LGTM

**Comment by asddongmen** [comment]
Please complete the "Check List" part of this PR description. Specifically, remove the items that you didn't do and the redundant items (No code).

**Comment by asddongmen** [comment]
Please conduct a manual test to ensure there are no performance issues when there are thousands of tables. I'm concerned about the execution time of the query: `SELECT JOB_ID, JOB_TYPE, SCHEMA_STATE, SCHEMA_ID, TABLE_ID, STATE, QUERY FROM information_schema.ddl_jobs`.

**Comment by wk989898** [comment]
> Please conduct a manual test to ensure there are no performance issues when there are thousands of tables. I'm concerned about the execution time of the query: `SELECT JOB_ID, JOB_TYPE, SCHEMA_STATE, SCHEMA_ID, TABLE_ID, STATE, QUERY FROM information_schema.ddl_jobs`.

I test it with v9.0.0-beta.1.pre-nightly version, and you could find more information in pingcap/tidb#55748

**Review by asddongmen — APPROVED** [review]
