### PR TITLE
ticdc: Fix CPU surge problem in sorter

### LINKED ISSUE #10738: Resolved ts stucks after upgrading to latest CDC build
### What did you do?

1. TIDB cluster (2024-02-23 master) with TiDB Sink and Kafka Changefeed running
2. Upgrade the cluster to 2024-03-05 master

### What did you expect to see?

CDC resolved ts should not stuck

### What did you see instead?

Changefeed stucks:

img_v3_028o_e61e99bf-c6b7-4616-a5ee-0ad0bc1a086g

This issue also seen recently when running changefeed with syncpoint enabled, and run sysbench workload:
image

### Versions of the cluster

```
/cdc version                       
Release Version: v8.0.0-test                                     
Git Commit Hash: d7987a0afd881476c15e7baa6d4fe82a74e44575        
Git Branch: heads/refs/tags/v8.0.0-test                          
UTC Build Time: 2024-03-07 05:00:38                              
Go Version: go version go1.21.6 linux/amd64                      
Failpoint Build: false                                           
```

### PR DESCRIPTION
**Pull request by hongyunyan**
### What problem does this PR solve?

Issue Number: close #10738

### What is changed and how it works?

The problematic code snippet here:https://github.com/pingcap/tiflow/blob/e5edb1906cc6c1c3addf9e82120ebefd96b13e81/cdc/processor/sourcemanager/sorter/pebble/event_sorter.go#L466-L482
is a busy loop that continuously polls an input channel and does some work when an item is available. 
The issue here is with the 'default' clause in the select statement. If there's no item available in the 'inputCh' channel, it will immediately continue to the next iteration instead of blocking until an item is available or the 's.closed' channel is closed. This could lead to high CPU usage as the loop is continuously running.

This PR replace the 'default' clause with a ticker. This will cause the goroutine to block when there's no work to do, reducing CPU usage. 

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by CharlesCheung96** [comment]
Please the backgorung in pr body

File: cdc/processor/sourcemanager/sorter/pebble/event_sorter.go [hunk 1]
```diff
@@ -442,9 +442,8 @@ func (s *EventSorter) handleEvents(
 
 	batch := db.NewBatch()
 	newResolved := spanz.NewHashMap[model.Ts]()
-	startToCollectBatch := time.Now()
 
-	handleItem := func(item eventWithTableID) {
+	encodeItemAndBatch := func(item eventWithTableID) {
```
Comment (CharlesCheung96) [inline cdc/processor/sourcemanager/sorter/pebble/event_sorter.go:446]: please remove newResolved from the closure. Maybe a parameter is good choice.

File: cdc/processor/sourcemanager/sorter/pebble/event_sorter.go [hunk 2]
```diff
@@ -463,21 +462,41 @@ func (s *EventSorter) handleEvents(
...
 
-	for {
-		for len(batch.Repr()) < batchCommitSize && time.Since(startToCollectBatch) < batchCommitInterval {
+	ticker := time.NewTicker(batchCommitInterval / 2)
+	defer ticker.Stop()
+
+	// we batch item and commit until batch size is larger than batchCommitSize,
+	// or the time since the last commit is larger than batchCommitInterval.
+	// we only return false when the sorter is closed.
+	doBatching := func(batch *pebble.Batch) bool {
```
Comment (CharlesCheung96) [inline cdc/processor/sourcemanager/sorter/pebble/event_sorter.go:471]: Maybe we should retuen DBBatchEvent.

File: cdc/processor/sourcemanager/sorter/pebble/event_sorter.go [hunk 3]
```diff
@@ -456,28 +458,44 @@ func (s *EventSorter) handleEvents(
 				zap.String("namespace", s.changefeedID.Namespace),
 				zap.String("changefeed", s.changefeedID.ID))
 		}
+		fmt.Println("set batch here")
```
Comment (asddongmen) [inline cdc/processor/sourcemanager/sorter/pebble/event_sorter.go:461]: Please, remove this line.

File: cdc/processor/sourcemanager/sorter/pebble/event_sorter.go [hunk 4]
```diff
@@ -456,28 +458,44 @@ func (s *EventSorter) handleEvents(
...
 		if err = batch.Set(key, value, &pebbleWriteOptions); err != nil {
 			log.Panic("failed to update pebble batch", zap.Error(err),
 				zap.String("namespace", s.changefeedID.Namespace),
 				zap.String("changefeed", s.changefeedID.ID))
 		}
 	}
 
-	for {
-		for len(batch.Repr()) < batchCommitSize && time.Since(startToCollectBatch) < batchCommitInterval {
+	// we batch item and commit until batch size is larger than batchCommitSize,
```
Comment (asddongmen) [inline cdc/processor/sourcemanager/sorter/pebble/event_sorter.go:469]:
```suggestion
	// Batch item and commit until batch size is larger than batchCommitSize,
```

File: cdc/processor/sourcemanager/sorter/pebble/event_sorter.go [hunk 5]
```diff
@@ -456,28 +458,44 @@ func (s *EventSorter) handleEvents(
...
+	// or the time since the last commit is larger than batchCommitInterval.
+	// we only return false when the sorter is closed.
```
Comment (asddongmen) [inline cdc/processor/sourcemanager/sorter/pebble/event_sorter.go:471]:
```suggestion
	// Only return false when the sorter is closed.
```

**Review by asddongmen — APPROVED** [review]

File: cdc/processor/sourcemanager/sorter/pebble/event_sorter.go [hunk 6]
```diff
@@ -463,21 +464,36 @@ func (s *EventSorter) handleEvents(
...
 
-		batch = db.NewBatch()
-		newResolved = spanz.NewHashMap[model.Ts]()
-		startToCollectBatch = time.Now()
+	for {
+		batchEvent, ok := doBatching()
+		if !ok {
+			return
+		}
+		batchCh <- batchEvent
```
Comment (CharlesCheung96) [inline cdc/processor/sourcemanager/sorter/pebble/event_sorter.go:496]: should an empty batchEvent be ignored?

Comment (hongyunyan) [reply cdc/processor/sourcemanager/sorter/pebble/event_sorter.go:496]: I check whether batchEvent is empty in L395, because whether the batchEvent is empty, we have to  update resolved ts.

**Review by CharlesCheung96 — APPROVED** [review]
