### PR TITLE
chann(ticdc): fix a panic that send on closed channel

### LINKED ISSUE #12244: cdc panic after simulating downstream tidb failure
### What did you do?

1、create BDR cluster
2、run workload
3、simulating downstream(secondary cluster) tidb failure

### What did you expect to see?

no panic

### What did you see instead?

the primary cluster ticdc panic after simulating downstream tidb failure
`2025-07-15 10:53:44.122	
{"namespace":"endless-ha-test-bdr-ddl-tps-7922393-1-59","pod":"tc-ticdc-1","log":"2025-07-15T10:53:44.117515268+08:00 stderr F \tgithub.com/pingcap/tiflow@v0.0.0-20250707050724-ac2fcf466cf3/pkg/orchestrator/etcd_worker.go:290 +0xf09","container":"ticdc"}
2025-07-15 10:53:44.122	
{"namespace":"endless-ha-test-bdr-ddl-tps-7922393-1-59","pod":"tc-ticdc-1","log":"2025-07-15T10:53:44.117518111+08:00 stderr F github.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker(0xc00165fc00, {0x6618fe8, 0xc0040086e0}, {0x7f618920d4c8, 0xc003c9c5a0}, 0xc003678700, 0x2faf080, {0x5a90fd1, 0x5})","container":"ticdc"}
2025-07-15 10:53:44.122	
{"namespace":"endless-ha-test-bdr-ddl-tps-7922393-1-59","pod":"tc-ticdc-1","log":"2025-07-15T10:53:44.117520386+08:00 stderr F \tgithub.com/pingcap/tiflow@v0.0.0-20250707050724-ac2fcf466cf3/cdc/capture/capture.go:589 +0x18b","container":"ticdc"}
2025-07-15 10:53:44.122	
{"namespace":"endless-ha-test-bdr-ddl-tps-7922393-1-59","pod":"tc-ticdc-1","log":"2025-07-15T10:53:44.117529645+08:00 stderr F github.com/pingcap/tiflow/cdc/capture.(*captureImpl).campaignOwner(0xc00165fc00, {0x6618fe8, 0xc0040086e0}, 0xc004008460)","container":"ticdc"}
2025-07-15 10:53:44.122	
{"namespace":"endless-ha-test-bdr-ddl-tps-7922393-1-59","pod":"tc-ticdc-1","log":"2025-07-15T10:53:44.117531816+08:00 stderr F \tgithub.com/pingcap/tiflow@v0.0.0-20250707050724-ac2fcf466cf3/cdc/capture/capture.go:537 +0xf94","container":"ticdc"}
2025-07-15 10:53:44.122	
{"namespace":"endless-ha-test-bdr-ddl-tps-7922393-1-59","pod":"tc-ticdc-1","log":"2025-07-15T10:53:44.117533647+08:00 stderr F github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func3()","container":"ticdc"}
2025-07-15 10:53:44.122	
{"namespace":"endless-ha-test-bdr-ddl-tps-7922393-1-59","pod":"tc-ticdc-1","log":"2025-07-15T10:53:44.117535478+08:00 stderr F \tgithub.com/pingcap/tiflow@v0.0.0-20250707050724-ac2fcf466cf3/cdc/capture/capture.go:375 +0x37","container":"ticdc"}
2025-07-15 10:53:44.122	
{"namespace":"endless-ha-test-bdr-ddl-tps-7922393-1-59","pod":"tc-ticdc-1","log":"2025-07-15T10:53:44.117537749+08:00 stderr F golang.org/x/sync/errgroup.(*Group).Go.func1()","container":"ticdc"}
2025-07-15 10:53:44.122	
{"namespace":"endless-ha-test-bdr-ddl-tps-7922393-1-59","pod":"tc-ticdc-1","log":"2025-07-15T10:53:44.117539699+08:00 stderr F \tgolang.org/x/sync@v0.13.0/errgroup/errgroup.go:79 +0x50","container":"ticdc"}
2025-07-15 10:53:44.122	
{"namespace":"endless-ha-test-bdr-ddl-tps-7922393-1-59","pod":"tc-ticdc-1","log":"2025-07-15T10:53:44.11754151+08:00 stderr F created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 770","container":"ticdc"}
2025-07-15 10:53:44.122	
{"namespace":"endless-ha-test-bdr-ddl-tps-7922393-1-59","pod":"tc-ticdc-1","log":"2025-07-15T10:53:44.117546518+08:00 stderr F \tgolang.org/x/sync@v0.13.0/errgroup/errgroup.go:76 +0x96","container":"ticdc"}
2025-07-15 10:53:44.117	
{"namespace":"endless-ha-test-bdr-ddl-tps-7922393-1-59","pod":"tc-ticdc-1","log":"2025-07-15T10:53:44.117330106+08:00 stderr F panic: send on closed channel","container":"ticdc"}
2025-07-15 10:53:44.117	
{"namespace":"endless-ha-test-bdr-ddl-tps-7922393-1-59","pod":"tc-ticdc-1","log":"2025-07-15T10:53:44.117436314+08:00 stderr F ","container":"ticdc"}
2025-07-15 10:53:44.117	
{"namespace":"endless-ha-test-bdr-ddl-tps-7922393-1-59","pod":"tc-ticdc-1","log":"2025-07-15T10:53:44.117441525+08:00 stderr F goroutine 752 [running]:","container":"ticdc"}
2025-07-15 10:53:44.117	
{"namespace":"endless-ha-test-bdr-ddl-tps-7922393-1-59","pod":"tc-ticdc-1","log":"2025-07-15T10:53:44.11744434+08:00 stderr F github.com/pingcap/tiflow/pkg/chann.(*Chann[...]).Close(...)","container":"ticdc"}`

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
./tidb-server -V
 Release Version: v9.0.0-beta.2.pre-104-gadbdf3f
Edition: Community
Git Commit Hash: adbdf3f0c7daf8345ab29071aa6a098cd9c645a3
Git Branch: HEAD
UTC Build Time: 2025-07-14 13:56:45
GoVersion: go1.23.11
Race Enabled: false
Check Table Before Drop: false
Store: unistore
Kernel Type: Classic

Upstream TiKV version (execute `tikv-server --version`):
./tikv-server -V
 TiKV 
Release Version:   9.0.0-beta.2
Edition:           Community
Git Commit Hash:   4d704035f878f5ac2fe027e383b6d2297e8e6712
Git Commit Branch: HEAD
UTC Build Time:    2025-07-08 18:21:32
Rust Version:      rustc 1.87.0-nightly (96cfc7558 2025-02-27)
Enable Features:   memory-engine pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine trace-async-tasks openssl-vendored
Profile:           dist_release
2025-07-15T06:16:33.930+0800

TiCDC version (execute `cdc version`):
./cdc version
 Release Version: v9.0.0-beta.2.pre-33-gd3067c2
Git Commit Hash: d3067c29d0c414987d166e93c88cc9be05fece7b
Git Branch: HEAD
UTC Build Time: 2025-07-14 06:12:05
Go Version: go version go1.23.10 linux/amd64
Failpoint Build: false
2025-07-15T06:16:34.389+0800

### PR DESCRIPTION
**Pull request by wk989898**
### What problem does this PR solve?

Issue Number: close #12244

### What is changed and how it works?
In some cases, the `Close` of `pkg/chann` may be closed twice, and there is a risk that the signal to a closed channel.

- Resource Nullification: After closing the ddlPuller in cdc/owner/changefeed.go and stopping the ddlHandler in cdc/processor/processor.go, their respective references (c.ddlPuller and p.ddlHandler.r) are explicitly set to nil. This prevents potential double-closing or interaction with stale resource pointers, which could lead to panics.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
   Test passes when simulating downstream TIDB failure

### Release note 

```release-note
Fix a panic when closing ddl puller.
```

### CODE REVIEW

File: cdc/owner/changefeed.go [hunk 1]
```diff
@@ -793,11 +793,12 @@ func (c *changefeed) releaseResources(ctx context.Context) {
 		c.cancel()
 	}
 	c.cancel = func() {}
+	c.wg.Wait()
 
 	if c.ddlPuller != nil {
 		c.ddlPuller.Close()
+		c.ddlPuller = nil
```
Comment (asddongmen) [inline cdc/owner/changefeed.go:802]: Please add an unit test to ensure call `releaseResouces` double time will not panic or error anymore.

File: cdc/processor/manager.go [hunk 2]
```diff
@@ -122,6 +122,10 @@ func (m *managerImpl) Tick(stdCtx context.Context, state orchestrator.ReactorSta
 		currentChangefeedEpoch := changefeedState.Info.Epoch
 		p, exist := m.processors[changefeedID]
 		if !exist {
+			// if the changefeed state is abnormal, it could be skippied
```
Comment (asddongmen) [inline cdc/processor/manager.go]: Please also add a test to ensure it works as expected.

**Review by lidezhu — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]
