### PR TITLE
sinkv2(cdc): fix bugs about enabling redo with pull-based-sink

### LINKED ISSUE #7678: pull-based sink can't work as expected with redo enabled
### What did you do?

Enable redo and pull-based sink.

### What did you expect to see?

_No response_

### What did you see instead?

It doesn't work.

### Versions of the cluster

Ticdc master branch.

### PR DESCRIPTION
**Pull request by hicqu**
### What problem does this PR solve?

Issue Number: close #7678 

### What is changed and how it works?

Fix bugs about enabling redo with pull-based-sink.

#### Tests 

 - Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

File: cdc/processor/sinkmanager/redo_cache.go [hunk 1]
```diff
@@ -81,6 +81,9 @@ func (r *redoEventCache) pop(
 			}
 			return pos.Compare(upperBound[0]) > 0
 		})
+		if fetchCount == 0 {
```
Comment (hi-rustin) [inline cdc/processor/sinkmanager/redo_cache.go:84]: Do we need to add a test for this change?

**Review by hi-rustin — APPROVED** [review]

**Review by nongfushanquan — APPROVED** [review]

File: cdc/processor/sinkmanager/redo_cache.go (hunk 1 above)
Comment (hicqu) [reply cdc/processor/sinkmanager/redo_cache.go:84]: done.
