### PR TITLE
server(cdc): avoid printing help messages when cdc server exits

### LINKED ISSUE #5519: Redundant cdc server usage message in a normal exit
### What did you do?

After using `cdc server` command to add a TiCDC server and creating a changefeed task, I pressed Ctrl+C to normally exit TiCDC. Redundant usage messages was printed.

### What did you expect to see?

No `cdc server` usage message shall be printed

### What did you see instead?
```console
^C[2022/05/23 15:20:28.048 +08:00] [INFO] [helper.go:64] ["got signal to exit"] [signal=interrupt]
Got signal interrupt (Component: cdc ; PID: 430109)
[2022/05/23 15:20:28.049 +08:00] [INFO] [client.go:225] ["WatchWithChan exited"] [role=processor]
[2022/05/23 15:20:28.049 +08:00] [INFO] [client.go:754] ["[pd] stop fetching the pending tso requests due to context canceled"] [dc-location=global]
[2022/05/23 15:20:28.049 +08:00] [INFO] [client.go:692] ["[pd] exit tso dispatcher"] [dc-location=global]
[2022/05/23 15:20:28.049 +08:00] [INFO] [capture.go:323] ["the processor routine has exited"] [error="[CDC:ErrPDEtcdAPIError]etcd api call error: context canceled"] [errorVerbose="[CDC:ErrPDEtcdAPIError]etcd api call error: context canceled\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/pkg/errors.WrapError\n\tgithub.com/pingcap/tiflow/pkg/errors/helper.go:30\ngithub.com/pingcap/tiflow/cdc/capture.(*Capture).runEtcdWorker\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:475\ngithub.com/pingcap/tiflow/cdc/capture.(*Capture).run.func3\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:322\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/05/23 15:20:28.049 +08:00] [INFO] [capture.go:299] ["the owner routine has exited"] []
[2022/05/23 15:20:28.049 +08:00] [ERROR] [server.go:232] ["http server error"] [error="[CDC:ErrServeHTTP]serve http error: mux: server closed"] [errorVerbose="[CDC:ErrServeHTTP]serve http error: mux: server closed\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/pkg/errors.WrapError\n\tgithub.com/pingcap/tiflow/pkg/errors/helper.go:30\ngithub.com/pingcap/tiflow/cdc.(*Server).startStatusHTTP.func1\n\tgithub.com/pingcap/tiflow/cdc/server.go:232\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/05/23 15:20:28.049 +08:00] [INFO] [compactor.go:142] ["compactor actor quit"] [ID=6]
[2022/05/23 15:20:28.049 +08:00] [INFO] [compactor.go:142] ["compactor actor quit"] [ID=0]
[2022/05/23 15:20:28.049 +08:00] [INFO] [compactor.go:142] ["compactor actor quit"] [ID=2]
[2022/05/23 15:20:28.049 +08:00] [INFO] [compactor.go:142] ["compactor actor quit"] [ID=1]
[2022/05/23 15:20:28.049 +08:00] [INFO] [compactor.go:142] ["compactor actor quit"] [ID=3]
[2022/05/23 15:20:28.049 +08:00] [INFO] [compactor.go:142] ["compactor actor quit"] [ID=4]
[2022/05/23 15:20:28.049 +08:00] [INFO] [compactor.go:142] ["compactor actor quit"] [ID=7]
[2022/05/23 15:20:28.049 +08:00] [INFO] [compactor.go:142] ["compactor actor quit"] [ID=5]
[2022/05/23 15:20:28.049 +08:00] [INFO] [leveldb.go:267] ["db actor quit"] [ID=5]
[2022/05/23 15:20:28.049 +08:00] [INFO] [leveldb.go:267] ["db actor quit"] [ID=7]
[2022/05/23 15:20:28.049 +08:00] [INFO] [leveldb.go:267] ["db actor quit"] [ID=0]
[2022/05/23 15:20:28.049 +08:00] [INFO] [leveldb.go:267] ["db actor quit"] [ID=6]
[2022/05/23 15:20:28.049 +08:00] [INFO] [leveldb.go:267] ["db actor quit"] [ID=2]
[2022/05/23 15:20:28.050 +08:00] [INFO] [leveldb.go:267] ["db actor quit"] [ID=3]
[2022/05/23 15:20:28.050 +08:00] [INFO] [leveldb.go:267] ["db actor quit"] [ID=4]
[2022/05/23 15:20:28.049 +08:00] [INFO] [leveldb.go:267] ["db actor quit"] [ID=1]
[2022/05/23 15:20:28.050 +08:00] [WARN] [server.go:630] ["peer-to-peer message handler error"] [error="rpc error: code = Canceled desc = context canceled"] [errorVerbose="rpc error: code = Canceled desc = context canceled\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.Trace\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/juju_adaptor.go:15\ngithub.com/pingcap/tiflow/pkg/p2p.(*MessageServer).receive\n\tgithub.com/pingcap/tiflow/pkg/p2p/server.go:722\ngithub.com/pingcap/tiflow/pkg/p2p.(*MessageServer).SendMessage.func1\n\tgithub.com/pingcap/tiflow/pkg/p2p/server.go:629\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/05/23 15:20:28.050 +08:00] [WARN] [server.go:633] ["error receiving from peer"] [error="context canceled"]
[2022/05/23 15:20:28.055 +08:00] [WARN] [client.go:167] ["peer message client detected error, restarting"] [error="context canceled"] [errorVerbose="context canceled\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.Trace\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/juju_adaptor.go:15\ngithub.com/pingcap/tiflow/pkg/p2p.(*MessageClient).runTx\n\tgithub.com/pingcap/tiflow/pkg/p2p/client.go:232\ngithub.com/pingcap/tiflow/pkg/p2p.(*MessageClient).run.func1\n\tgithub.com/pingcap/tiflow/pkg/p2p/client.go:199\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/05/23 15:20:28.055 +08:00] [INFO] [client.go:116] ["peer message client exited"] [addr=127.0.0.1:8300] [captureID=1520831f-5c26-4a6e-9634-0c2ebed536ee] [error="context canceled"] [errorVerbose="context canceled\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.Trace\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/juju_adaptor.go:15\ngithub.com/pingcap/tiflow/pkg/p2p.(*MessageClient).Run\n\tgithub.com/pingcap/tiflow/pkg/p2p/client.go:133\ngithub.com/pingcap/tiflow/pkg/p2p.(*messageRouterImpl).GetClient.func1\n\tgithub.com/pingcap/tiflow/pkg/p2p/message_router.go:144\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/05/23 15:20:28.055 +08:00] [WARN] [message_router.go:145] ["p2p client exited with error"] [addr=127.0.0.1:8300] [targetCapture=1520831f-5c26-4a6e-9634-0c2ebed536ee] [error="context canceled"] [errorVerbose="context canceled\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.Trace\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/juju_adaptor.go:15\ngithub.com/pingcap/tiflow/pkg/p2p.(*MessageClient).Run\n\tgithub.com/pingcap/tiflow/pkg/p2p/client.go:133\ngithub.com/pingcap/tiflow/pkg/p2p.(*messageRouterImpl).GetClient.func1\n\tgithub.com/pingcap/tiflow/pkg/p2p/message_router.go:144\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/05/23 15:20:28.056 +08:00] [INFO] [capture.go:257] ["capture recovered"] [captureID=3784fefc-2086-4c8a-bba7-b59b4e66921c]
[2022/05/23 15:20:28.056 +08:00] [INFO] [capture.go:234] ["the capture routine has exited"]
[2022/05/23 15:20:28.056 +08:00] [INFO] [client.go:754] ["[pd] stop fetching the pending tso requests due to context canceled"] [dc-location=global]
[2022/05/23 15:20:28.056 +08:00] [INFO] [client.go:692] ["[pd] exit tso dispatcher"] [dc-location=global]
[2022/05/23 15:20:28.056 +08:00] [ERROR] [server.go:151] ["run server"] [error="[CDC:ErrTCPServerClosed]The TCP server has been closed\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/pkg/tcpserver.(*tcpServerImpl).Run.func2\n\tgithub.com/pingcap/tiflow/pkg/tcpserver/tcp_server.go:125\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
Error: run server: [CDC:ErrTCPServerClosed]The TCP server has been closed
Usage:
  cdc server [flags]

Flags:
      --addr string              Set the listening address (default "127.0.0.1:8300")
      --advertise-addr string    Set the advertise listening address for client communication
      --ca string                CA certificate path for TLS connection
      --cert string              Certificate path for TLS connection
      --cert-allowed-cn string   Verify caller's identity (cert Common Name). Use ',' to separate multiple CN
      --config string            Path of the configuration file
      --data-dir string          the path to the directory used to store TiCDC-generated data
      --gc-ttl int               CDC GC safepoint TTL duration, specified in seconds (default 86400)
  -h, --help                     help for server
      --key string               Private key path for TLS connection
      --log-file string          log file path
      --log-level string         log level (etc: debug|info|warn|error) (default "info")
      --pd string                Set the PD endpoints to use. Use ',' to separate multiple PDs (default "http://127.0.0.1:2379")
      --tz string                Specify time zone of TiCDC cluster (default "System")

run server: [CDC:ErrTCPServerClosed]The TCP server has been closed
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v6.0.0
```

Upstream TiKV version (execute `tikv-server --version`):

```console
v6.0.0
```

TiCDC version (execute `cdc version`):

```console
v6.0.0
```

### PR DESCRIPTION
**Pull request by crelax**
### What problem does this PR solve?

Issue Number: close #5519

### What is changed and how it works?
In `func RunE()` of the `cdc server` command, if no error occurs in the validation, return nil directly in spite of errors thrown by the execution. Handle the execution errors using `cobra.CheckErr()`

#### Tests 

 - Integration test 
   - `tests/integration_tests/cdc_server_tips`: The tests cover two scenarios: one `cdc server` command with invalid arguments should print usage tips, while the other is validated and should not.
 - Manual test
   - Start a tidb cluster and add a cluster using `cdc server`
   - Create a changefeed task using `cli changefeed`
   - Press `Ctrl + C` and in the terminal of `cdc server` and check whether there are prompt messages printed
 
##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
Clear redundant cdc server prompt in a normal exit
```

### CODE REVIEW

File: tests/integration_tests/_utils/check_usage_tips [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+# parameter 1: stdout file
+# parameter 2: cmd_status true: cmd is valid and should not print usage tips, false: otherwise
+stdout_file=$1
+cmd_status=$2
+should_print=
+set +e
+
+## check data race
+if [ ! -f "$stdout_file" ]; then
+	exit 0
```
Comment (liuzix) [inline tests/integration_tests/_utils/check_usage_tips:11]: You can print something like `file does not exist` here.

File: tests/integration_tests/cdc_server_tips/run.sh [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+			exit 1
+		fi
+		sleep 1
+	done
+	echo 'succeed to verify meta placement rules'
+}
+
+stop_cdc_and_do_check() {
+	if [[ "$cdc_launched" == "true" ]]; then
+		region_label_test
```
Comment (liuzix) [inline tests/integration_tests/cdc_server_tips/run.sh:74]: Why is this needed here?

File: tests/integration_tests/cdc_server_tips/run.sh [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+	check_usage_tips $stdout_file $cdc_launched
+}
+
+# invalid command and should print usage tips
+trap stop_tidb_cluster EXIT
+try_to_run_cdc "invalid"
+stop_cdc_and_do_check
+echo " 1st test case $TEST_NAME success! "
+
+# should not print usage tips
```
Comment (liuzix) [inline tests/integration_tests/cdc_server_tips/run.sh:91]: Please add more background information in comments, explaining why this test is needed. You can attach the issue link here.

File: tests/integration_tests/cdc_server_tips/run.sh [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+	case $SINK_TYPE in
+	kafka) SINK_URI="kafka+ssl://127.0.0.1:9092/$TOPIC_NAME?protocol=open-protocol&partition-num=4&kafka-client-id=cdc_server_tips&kafka-version=${KAFKA_VERSION}&max-message-bytes=10485760" ;;
+	*) SINK_URI="mysql+ssl://normal:123456@127.0.0.1:3306/" ;;
+	esac
+	run_cdc_cli changefeed create --start-ts=$start_ts --sink-uri="$SINK_URI"
+	if [ "$SINK_TYPE" == "kafka" ]; then
+		run_kafka_consumer $WORK_DIR "kafka://127.0.0.1:9092/$TOPIC_NAME?protocol=open-protocol&partition-num=4&version=${KAFKA_VERSION}&max-message-bytes=10485760"
+	fi
+
+	echo 'Succeed to create a changefeed, no usage tips should be printed'
```
Comment (amyangfei) [inline tests/integration_tests/cdc_server_tips/run.sh:56]: cdc cli doesn't write stdout to file `stdout_file`. Since this PR focuses the behavior in cdc server command, IMO we don't need to create changefeed.

File: tests/integration_tests/cdc_server_tips/run.sh [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+}
+
+# If cdc got initiated normally, no usage tips should be printed when exit
+trap stop_tidb_cluster EXIT
+try_to_run_cdc "valid"
+stop_cdc_and_do_check
+echo " 1st test case $TEST_NAME success! "
+
+# invalid command and should print usage tips
+trap stop_tidb_cluster EXIT
```
Comment (amyangfei) [inline tests/integration_tests/cdc_server_tips/run.sh:80]: trap once at L74 is enough.

File: tests/integration_tests/cdc_server_tips/run.sh [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+WORK_DIR=$OUT_DIR/$TEST_NAME
+CDC_BINARY=cdc.test
+SINK_TYPE=$1
+stdout_file=$WORK_DIR/stdout.log
+cdc_launched=
+
+function try_to_run_cdc() {
+	# $*: invalid args to avoid lauching cdc server
+	rm -rf $WORK_DIR && mkdir -p $WORK_DIR
+	start_tidb_cluster --workdir $WORK_DIR
```
Comment (amyangfei) [inline tests/integration_tests/cdc_server_tips/run.sh:16]: What about moving `start_tidb_cluster` out of `try_to_run_cdc`, starting tidb cluster once and reusing it.

Comment (crelax) [reply tests/integration_tests/cdc_server_tips/run.sh:16]: Thx!

**Review by liuzix — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]
