### PR TITLE
pipeline(ticdc): fix sorter node memory leak

### LINKED ISSUE #7870: ticdc sortNode memory leak

### PR DESCRIPTION
**Pull request by sdojjy**
### What problem does this PR solve?

Issue Number: close #7870

### What is changed and how it works?
fix the memory leak issue in sortNode introduce by #7458

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

File: cdc/processor/pipeline/sorter.go [hunk 1]
```diff
@@ -421,6 +421,9 @@ func (n *sorterNode) start(
 				lastCRTs = e.CRTs
 				ctx.SendToNextNode(pmessage.PolymorphicEventMessage(e))
 			}
+			for i := 0; i < index; i++ {
```
Comment (asddongmen) [inline cdc/processor/pipeline/sorter.go:424]: Please add a comment about why we need this.

**Review by asddongmen — APPROVED** [review]
