### PR TITLE
worker(dm):fix data race of Start/Close of DM-worker's Server

### LINKED ISSUE #6401: data race of Start/Close of DM-worker's Server
### What did you do?

```

[2022-07-21T02:26:46.380Z] WARNING: DATA RACE

[2022-07-21T02:26:46.380Z] Write at 0x00c000888810 by goroutine 94:

[2022-07-21T02:26:46.380Z]   github.com/pingcap/tiflow/dm/worker.(*Server).Start.func1()

[2022-07-21T02:26:46.380Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/worker/server.go:130 +0x6ee

[2022-07-21T02:26:46.380Z]   github.com/pingcap/tiflow/dm/worker.(*Server).Start()

[2022-07-21T02:26:46.380Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/worker/server.go:241 +0xa4

[2022-07-21T02:26:46.380Z]   github.com/pingcap/tiflow/cmd/dm-worker.main()

[2022-07-21T02:26:46.380Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cmd/dm-worker/main.go:93 +0x944

[2022-07-21T02:26:46.380Z]   github.com/pingcap/tiflow/cmd/dm-worker.TestRunMain.func3()

[2022-07-21T02:26:46.380Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cmd/dm-worker/main_test.go:66 +0x2b

[2022-07-21T02:26:46.380Z] 

[2022-07-21T02:26:46.380Z] Previous read at 0x00c000888810 by goroutine 104:

[2022-07-21T02:26:46.380Z]   github.com/pingcap/tiflow/dm/worker.(*Server).Close()

[2022-07-21T02:26:46.380Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/worker/server.go:496 +0x64

[2022-07-21T02:26:46.380Z]   github.com/pingcap/tiflow/cmd/dm-worker.main.func2()

[2022-07-21T02:26:46.380Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cmd/dm-worker/main.go:91 +0x1b7

[2022-07-21T02:26:46.380Z] 

[2022-07-21T02:26:46.380Z] Goroutine 94 (running) created at:

[2022-07-21T02:26:46.380Z]   github.com/pingcap/tiflow/cmd/dm-worker.TestRunMain()

[2022-07-21T02:26:46.380Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cmd/dm-worker/main_test.go:65 +0x331

[2022-07-21T02:26:46.380Z]   testing.tRunner()

[2022-07-21T02:26:46.380Z]       /usr/local/go/src/testing/testing.go:1439 +0x213

[2022-07-21T02:26:46.380Z]   testing.(*T).Run.func1()

[2022-07-21T02:26:46.380Z]       /usr/local/go/src/testing/testing.go:1486 +0x47

[2022-07-21T02:26:46.380Z] 

[2022-07-21T02:26:46.380Z] Goroutine 104 (finished) created at:

[2022-07-21T02:26:46.380Z]   github.com/pingcap/tiflow/cmd/dm-worker.main()

[2022-07-21T02:26:46.380Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cmd/dm-worker/main.go:88 +0x938

[2022-07-21T02:26:46.380Z]   github.com/pingcap/tiflow/cmd/dm-worker.TestRunMain.func3()

[2022-07-21T02:26:46.380Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cmd/dm-worker/main_test.go:66 +0x2b

[2022-07-21T02:26:46.380Z] ==================
```

### What did you expect to see?

_No response_

### What did you see instead?

_No response_

### Versions of the cluster

master

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by liumengya94**
### What problem does this PR solve?

Issue Number: close #6401 

### What is changed and how it works?
I use mutex to protect critical section and thus prevent race condition.

#### Tests 

 - Unit test

##### Will it cause performance regression or break compatibility?
No

##### Do you need to update user documentation, design documentation or monitoring documentation?
No

### Release note 

```release-note
fix data race of Start/Close of DM-worker's Server
```

### CODE REVIEW

**Comment by lance6716** [comment]
Need to add an unit test: before this fix the test can reveal the problem, and after this fix the test should pass

File: dm/worker/server.go [hunk 1]
```diff
@@ -491,6 +489,8 @@ func (s *Server) doClose() {
 
 // Close closes the RPC server, this function can be called multiple times.
 func (s *Server) Close() {
+	s.closeMu.Lock()
+	defer s.closeMu.Unlock()
```
Comment (D3Hunter) [inline dm/worker/server.go:493]: this may not work for this:
- `Start()` try `closeMu.Lock()`, but hasn't success
- `dm-worker` received signal to close
- `Close()` in signal routine try lock and success, and finish close
- `Start()` continue, and start success
- `dm-worker` keeps running

File: dm/worker/server_test.go [hunk 2]
```diff
@@ -731,3 +732,35 @@ func loadSourceConfigWithoutPassword(c *C) *config.SourceConfig {
...
+	c.Assert(cfg.Parse([]string{"-config=./dm-worker.toml"}), IsNil)
+	cfg.Join = masterAddr
+	cfg.KeepAliveTTL = keepAliveTTL
+	cfg.RelayKeepAliveTTL = keepAliveTTL
+
+	s := NewServer(cfg)
+	defer s.Close()
+	go func() {
+		err1 := s.Start()
+		c.Assert(err1, IsNil)
```
Comment (lance6716) [inline dm/worker/server_test.go:755]: it should return `terror.ErrWorkerServerClosed` as the replacement for data race.

Please write an unit test that can discover data race for old code, and check now data race is fixed

File: dm/worker/server_test.go [hunk 3]
```diff
@@ -731,3 +732,35 @@ func loadSourceConfigWithoutPassword(c *C) *config.SourceConfig {
...
+	}()
+	for i := 0; i < 10; i++ {
+		go func() {
+			fmt.Println("111")
```
Comment (lance6716) [inline dm/worker/server_test.go:759]:
```suggestion
```

File: dm/worker/server_test.go [hunk 4]
```diff
@@ -731,3 +732,35 @@ func loadSourceConfigWithoutPassword(c *C) *config.SourceConfig {
...
+			s.Close()
```
Comment (lance6716) [inline dm/worker/server_test.go:760]: Close for multiple time is meaningless. You can use a loop to

for ... {
  waitGroup.Add(2)
  go func() { s.Start(); waitGroup.Done() }
  go func() { s.Close(); waitGroup.Done() }
  waitGroup.Wait()
}

File: dm/worker/server_test.go [hunk 5]
```diff
@@ -731,3 +732,35 @@ func loadSourceConfigWithoutPassword(c *C) *config.SourceConfig {
...
+		}()
+	}
+	c.Assert(utils.WaitSomething(30, 100*time.Millisecond, func() bool {
+		return !s.closed.Load()
+	}), IsTrue)
```
Comment (lance6716) [inline dm/worker/server_test.go:765]: the test should wait its goroutine finished

File: dm/worker/server.go (hunk 1 above)
Comment (D3Hunter) [reply dm/worker/server.go:491]: seems this case doesn't exist, since `inited` is set to true on `close`

Comment (D3Hunter) [reply dm/worker/server.go:491]: > seems this case doesn't exist, since inited is set to true on close

it do exist, since `s.closed = true`, we didn't set `inited` to true in this case, so worker keeps running

File: dm/worker/server.go [hunk 6]
```diff
@@ -61,7 +61,7 @@ type Server struct {
 	// closeMu is used to sync Start/Close and protect 5 fields below
 	closeMu    sync.Mutex
 	closed     atomic.Bool
-	inited     bool
+	callClosed bool
```
Comment (D3Hunter) [inline dm/worker/server.go:64]:
```suggestion
	calledClose bool
```
plz add some comments to explain the difference between `closed` and `calledClose`

File: cmd/dm-worker/main.go [hunk 7]
```diff
@@ -90,9 +90,14 @@ func main() {
 		s.Close()
 	}()
 	err = s.Start()
-	if err != nil {
+	switch errors.Cause(err) {
+	case nil:
+	case terror.ErrWorkerServerClosed:
+		log.L().Info("not need to start dm-worker")
```
Comment (D3Hunter) [inline cmd/dm-worker/main.go:96]:
```suggestion
		log.L().Info("server closed")
```

File: dm/worker/server.go [hunk 8]
```diff
@@ -59,12 +59,12 @@ var (
...
 	// closeMu is used to sync Start/Close and protect 5 fields below
-	closeMu    sync.Mutex
-	closed     atomic.Bool
-	inited     bool
-	rootLis    net.Listener
-	svr        *grpc.Server
-	etcdClient *clientv3.Client
+	closeMu     sync.Mutex
+	closed      atomic.Bool
+	calledClose bool
```
Comment (D3Hunter) [inline dm/worker/server.go:64]: maybe add some comments about difference between `closed` and `calledClose`

File: dm/worker/server_test.go [hunk 9]
```diff
@@ -731,3 +731,43 @@ func loadSourceConfigWithoutPassword(c *C) *config.SourceConfig {
...
+		go func() {
+			err1 := s.Start()
+			switch errors.Cause(err1) {
+			case nil:
+			case terror.ErrWorkerServerClosed:
+				log.L().Info("server closed")
+			default:
+				c.Assert(err1, IsNil)
+			}
+			wg.Done()
```
Comment (D3Hunter) [inline dm/worker/server_test.go:765]: use `defer wg.Done()` at the beginning of the go routine, below too

File: dm/worker/server_test.go [hunk 10]
```diff
@@ -731,3 +731,43 @@ func loadSourceConfigWithoutPassword(c *C) *config.SourceConfig {
...
+		wg.Add(2)
+		go func() {
+			err1 := s.Start()
+			switch errors.Cause(err1) {
+			case nil:
+			case terror.ErrWorkerServerClosed:
+				log.L().Info("server closed")
+			default:
+				c.Assert(err1, IsNil)
+			}
```
Comment (D3Hunter) [inline dm/worker/server_test.go:764]: can assert that `err1==nil || err1== terror.ErrWorkerServerClosed` is true

File: dm/worker/server.go [hunk 11]
```diff
@@ -59,12 +59,15 @@ var (
...
 type Server struct {
 	// closeMu is used to sync Start/Close and protect 5 fields below
-	closeMu    sync.Mutex
-	closed     atomic.Bool
-	inited     bool
-	rootLis    net.Listener
-	svr        *grpc.Server
-	etcdClient *clientv3.Client
+	closeMu sync.Mutex
+	//closed is used to store the current state of the dm-worker server.
```
Comment (D3Hunter) [inline dm/worker/server.go:63]:
```suggestion
	// closed is used to store the current state of the dm-worker server.
```
below comments too

**Review by D3Hunter — COMMENTED** [review]
rest lgtm

File: dm/worker/server.go [hunk 12]
```diff
@@ -59,12 +59,15 @@ var (
...
+	//if the server starts successfully, s.closed.Store(false)
+	closed atomic.Bool
+	//calledClose is used to indicate that dm-worker has received signal to close and closed successfully.
```
Comment (D3Hunter) [inline dm/worker/server.go:66]:
```suggestion
	// calledClose is used to indicate that dm-worker has received signal to close and closed successfully.
	// we use this variable to avoid Start() after Close()
```

File: dm/worker/server.go [hunk 13]
```diff
@@ -111,9 +114,9 @@ func (s *Server) Start() error {
 	startErr := func() error {
 		s.closeMu.Lock()
 		defer s.closeMu.Unlock()
-
-		if s.inited {
-			return terror.ErrWorkerServerClosed.Generate()
+		//If dm-worker has received signal and finished close, start() should not continue
```
Comment (D3Hunter) [inline dm/worker/server.go:117]:
```suggestion
		// if dm-worker has received signal and finished close, start() should not continue
```

File: dm/worker/server.go (hunk 11 above)
Comment (liumengya94) [reply dm/worker/server.go]: Ok, I got it, thanks！

**Review by D3Hunter — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]
