### PR TITLE
capture(ticdc): fix graceful shutdown in k8s

### LINKED ISSUE #8484: TiCDC can not graceful upgrade in k8s
#7400 breaks graceful shutdown in k8s by deleting `CaptureInfo` immediately after a node is drained.  
And #7519 makes TiCDC always returns 503 for every API call which makes it even worse.

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: close #8484

### What is changed and how it works?

1. Allow access etcd client after a capture has been drained.
2. Do not return error in `campaignOwner` after a capture has been drained.

#### Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)
	Run TiCDC cluster in a k8s cluster and rolling restart all TiCDC nodes.

##### Will it cause performance regression or break compatibility?

No.

##### Do you need to update user documentation, design documentation or monitoring documentation?

No.

### Release note 

```release-note
Fix an issue that TiCDC cluster can not graceful upgrade in k8s
```

### CODE REVIEW

File: cdc/capture/capture.go [hunk 1]
```diff
@@ -181,9 +178,6 @@ func (c *captureImpl) GetUpstreamManager() (*upstream.Manager, error) {
 func (c *captureImpl) GetEtcdClient() (etcd.CDCEtcdClient, error) {
 	c.captureMu.Lock()
 	defer c.captureMu.Unlock()
-	if !c.initialized {
-		return nil, cerror.ErrCaptureNotInitialized.GenWithStackByArgs()
-	}
 	return c.EtcdClient, nil
```
Comment (sdojjy) [inline cdc/capture/capture.go:181]: this func does not return error now , change the func definition

File: cdc/api/owner/owner.go [hunk 2]
```diff
@@ -227,18 +227,13 @@ func (h *ownerAPI) handleChangefeedQuery(w http.ResponseWriter, req *http.Reques
 	}
 	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
 	defer cancel()
-	etcdClient, err := h.capture.GetEtcdClient()
-	if err != nil {
-		api.WriteError(w, http.StatusBadRequest, err)
-		return
-	}
-	cfInfo, err := etcdClient.GetChangeFeedInfo(ctx, changefeedID)
+	cfInfo, err := h.capture.GetEtcdClient().GetChangeFeedInfo(ctx, changefeedID)
```
Comment (nongfushanquan) [inline cdc/api/owner/owner.go:230]: Is it not safe to cache etcdclient ?

Comment (overvenus) [reply cdc/api/owner/owner.go:230]: Yes, etcd client is initialized before creating `Capture`, and will not be closed before exiting.

File: cdc/capture/capture.go [hunk 3]
```diff
@@ -326,15 +315,13 @@ func (c *captureImpl) run(stdCtx context.Context) error {
 		// an unrecoverable serious errors (recoverable errors are intercepted in the owner tick)
 		// so we should restart the capture.
 		err := c.campaignOwner(ctx)
-		if err != nil {
+		if err != nil || c.liveness.Load() != model.LivenessCaptureStopping {
 			log.Error("campaign owner routine exited with error, restart the capture",
```
Comment (sdojjy) [inline cdc/capture/capture.go:319]: the log  is not correct when `c.liveness.Load() != model.LivenessCaptureStopping `

**Review by asddongmen — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]
