### PR TITLE
codec(ticdc): simple protocol fix primary key not found and adjust schema

### LINKED ISSUE #10563: simple protocol fix primary key not found

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #10563

### What is changed and how it works?

* fix the primary key that cannot be found, by sort columns after all indexes were found.
* adjust simple avro schema, remove useless field
* add more unit test to the simple protocol encoding.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`None`
```

### CODE REVIEW

File: pkg/sink/codec/simple/avro.go [hunk 1]
```diff
@@ -30,6 +30,46 @@ import (
...
+			}
+		}
+		index["columns"] = columns
+		if idx.Primary {
+			pkInIndexes = true
+		}
+		indexesSchema = append(indexesSchema, index)
+	}
+
+	// sometimes the primary key is not in the index, we need to find it manually.
```
Comment (CharlesCheung96) [inline pkg/sink/codec/simple/avro.go:58]: Could you please add some comments to explain when this problem occurs?

**Review by CharlesCheung96 — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

File: pkg/sink/codec/simple/avro.go (hunk 1 above)
Comment (3AceShowHand) [reply pkg/sink/codec/simple/avro.go:58]: This almost happens all the time.
