### PR TITLE
syncer: support start from empty gtid config

### LINKED ISSUE #3731: can't start a GTID-based incremental task when upstream GTID is empty
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

upstream gtid is empty, and binlog-gtid in meta field in task file is also empty

2. What did you expect to see?

start successfully

3. What did you see instead?

query-status shows "invalid position (mysql-bin.000001, 4) or GTID not enabled in upstream"

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v2.0.5
        ```

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: close #3731 

### What is changed and how it works?
mariadb could use 0-0-0 as empty gtid config
- support user to use uuid:0 as mysql empty gtid config

### Check List 

Tests 
 - Integration test
 - Manual test (mariadb)

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
Support start an incremental task with nil MySQL GTID set.
```

### CODE REVIEW

File: dm/pkg/gtid/gtid.go [hunk 1]
```diff
@@ -80,14 +84,37 @@ func ParserGTID(flavor, gtidStr string) (Set, error) {
...
 	}
+
 	err = m.Set(gtid)
 	return m, err
 }
 
+// check whether a gtid set is nil(start sync from start)
+// mysql: uuid:0
+// mariadb: x-y-0(no need to handle)
+func IsNilMySQLGTIDSet(gStr string) bool {
```
Comment (buchuitoudegou) [inline dm/pkg/gtid/gtid.go:104]: Should we add a unit test for this function either?

File: dm/relay/local_reader_test.go [hunk 2]
```diff
@@ -613,7 +613,7 @@ func (t *testReaderSuite) TestStartSyncByGTID(c *C) {
 		{
 			"ba8f633f-1f15-11eb-b1c7-0242ac110002",
 			"ba8f633f-1f15-11eb-b1c7-0242ac110002.000001",
-			"ba8f633f-1f15-11eb-b1c7-0242ac110002:0",
+			"ba8f633f-1f15-11eb-b1c7-0242ac110002:1",
```
Comment (buchuitoudegou) [inline dm/relay/local_reader_test.go:616]: Should we just add a test case rather than replace it? Because it seems `IsNilMySQLGTIDSet` is used to handle such cases (i.e. xxx:0).

File: dm/pkg/gtid/gtid.go [hunk 3]
```diff
@@ -80,14 +84,37 @@ func ParserGTID(flavor, gtidStr string) (Set, error) {
...
 		return nil, terror.ErrNotSupportedFlavor.Generate(flavor)
 	}
+
 	err = m.Set(gtid)
 	return m, err
 }
 
+// check whether a gtid set is nil(start sync from start)
+// mysql: uuid:0
+// mariadb: x-y-0(no need to handle)
```
Comment (lance6716) [inline dm/pkg/gtid/gtid.go:103]: did you test that mariaDB supports x-y-0?

File: dm/tests/incremental_mode/run.sh [hunk 4]
```diff
@@ -142,16 +120,12 @@ function run() {
...
-	sed -i "s/task-mode-placeholder/incremental/g" $WORK_DIR/dm-task.yaml
-	sed -i "s/binlog-name-placeholder-1//g" $WORK_DIR/dm-task.yaml
-	sed -i "s/binlog-pos-placeholder-1//g" $WORK_DIR/dm-task.yaml
-	sed -i "s/binlog-gtid-placeholder-1/$gtid1/g" $WORK_DIR/dm-task.yaml
-
-	sed -i "s/binlog-name-placeholder-2/$name2/g" $WORK_DIR/dm-task.yaml
-	sed -i "s/binlog-pos-placeholder-2/$pos2/g" $WORK_DIR/dm-task.yaml
-	sed -i "s/binlog-gtid-placeholder-2/$gtid2/g" $WORK_DIR/dm-task.yaml
+	worker1_run_source_1=$(sed "s/$SOURCE_ID1/$SOURCE_ID1\n/g" $WORK_DIR/worker1/log/dm-worker.log | grep -c "$SOURCE_ID1") || true
+	echo "start task in incremental mode with nil gtid/pos"
```
Comment (lance6716) [inline dm/tests/incremental_mode/run.sh:124]:
```suggestion
	echo "start task in incremental mode with zero gtid/pos"
```

File: dm/tests/incremental_mode/run.sh [hunk 5]
```diff
@@ -142,16 +120,12 @@ function run() {
...
+	binlog_name=($(get_binlog_name $MYSQL_HOST1 $MYSQL_PORT1))
```
Comment (lance6716) [inline dm/tests/incremental_mode/run.sh:125]: this should be source2?

File: dm/relay/local_reader_test.go (hunk 2 above)
Comment (GMHDBJD) [reply dm/relay/local_reader_test.go:616]: This gtid is used to generate binlog event, after this pr, xxx:0 will be transformed to nil, but binlog pkg could not generate event with nil gtid.

File: dm/pkg/gtid/gtid.go (hunk 1 above)
Comment (GMHDBJD) [reply dm/pkg/gtid/gtid.go:104]: add in 044a3e3

File: dm/pkg/gtid/gtid.go (hunk 3 above)
Comment (GMHDBJD) [reply dm/pkg/gtid/gtid.go]: test with 0-0-0, update comment in 044a3e3

**Review by lance6716 — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]
