### PR TITLE
DM(syncer):  fix lost lost dml under special sharding ddls

### LINKED ISSUE #5002: DM(syncer): syncer may lost dml under special sharding ddls
### What did you do?

1. open gtid
2. pessimistic shard mode
3. two sub-table in one source
4. sql like this:
    tb1 --> ddl1
    tb1 --> dml (lost)
    tb1 --> ddl2
    tb2 --> ddl1
    tb2 --> ddl2

### What did you expect to see?

Don't lost tb1's dml.

### What did you see instead?

lost tb1's dml

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
v5.3 --> master
```
Upstream MySQL/MariaDB server version:
```console
5.7.22-log
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
5.7.25-TiDB-v5.3.0
```
How did you deploy DM: tiup or manually?
```console
manually
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by WizardXiao**
### What problem does this PR solve?

Issue Number: close #5002 

### What is changed and how it works?
Change the check method of whether sync dml to be `active ddl >= dml`.

### Check List 

Tests 

 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

File: dm/syncer/sharding_group.go [hunk 1]
```diff
@@ -239,7 +239,8 @@ func (sg *ShardingGroup) CheckSyncing(source string, location binlog.Location) (
 	if activeDDLItem == nil {
 		return true
 	}
-	return binlog.CompareLocation(activeDDLItem.FirstLocation, location, sg.enableGTID) > 0
+	// ddl position caculate use last_position's gtid, when last is a dml, it will be equal, but the dml should be synced.
+	return binlog.CompareLocation(activeDDLItem.FirstLocation, location, sg.enableGTID) >= 0
```
Comment (GMHDBJD) [inline dm/syncer/sharding_group.go:243]: I don't think this is a solution. The issue is because last_position is wrong after https://github.com/pingcap/dm/pull/1926, the correct behavior is 
```
DML 
# activeDDLItem.FirstLocation  <-- (endlocation of DML, start location of DDL, lastLocation)
DDL
```
after https://github.com/pingcap/dm/pull/1926
```
DML
DDL
activeDDLItem.FirstLocation(gtid) <-- (endlocation of DDL, lastLocation)
```
so now binlog.CompareLocation(activeDDLItem.FirstLocation, location, sg.enableGTID) greater than 0

Comment (GMHDBJD) [reply dm/syncer/sharding_group.go:243]: But I forgot why we update last location when receive begin, cc @lance6716

Comment (lance6716) [reply dm/syncer/sharding_group.go:243]: maybe to some problems of exit safe point. I'll take a look later

**Review by lance6716 — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
LGTM
