### PR TITLE
framework(engine): record error message when job master closes

### LINKED ISSUE #7021: error message is not set in master meta when business job master meets error
### What did you do?

Hack a business job master, returns error in `Tick` API

### What did you expect to see?

Business job master fails and records `error_message` in master_meta table in metastore.

### What did you see instead?

Business job master fails but `error_message` is empty.

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

master@https://github.com/pingcap/tiflow/commit/3e43a18b34d8f052c33c83266c9f4a10f5abf666

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve?

Issue Number: close #7021

### What is changed and how it works?

- Update `error_message` field before job master calls `doClose`
- Change the interface signature of `UpdateJob` to explicit way, which means the parameter contains all fields that need to be updated.

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

File: engine/framework/base_jobmaster.go [hunk 1]
```diff
@@ -201,13 +201,15 @@ func (d *DefaultBaseJobMaster) Init(ctx context.Context) error {
...
 		if err := d.impl.InitImpl(ctx); err != nil {
+			d.errCenter.OnError(err)
 			return errors.Trace(err)
 		}
 		if err := d.master.markStateInMetadata(ctx, frameModel.MasterStateInit); err != nil {
 			return errors.Trace(err)
 		}
 	} else {
 		if err := d.impl.OnMasterRecovered(ctx); err != nil {
+			d.errCenter.OnError(err)
```
Comment (maxshuang) [inline engine/framework/base_jobmaster.go:212]: 1. Would it be better to set the `errCenter` in `eventLoop`? Or we may lost some error message if we forget to set the `errCenter`.
2. Please add some comment here if we have specific strategy when record the error message.

**Comment by maxshuang** [comment]
Rest LGTM.

File: engine/framework/base_jobmaster.go (hunk 1 above)
Comment (amyangfei) [reply engine/framework/base_jobmaster.go:214]: 1. ErrCenter is logic oriented, instead of runtime work, it is better to record error in implement code, rather than in runtime layer.
2. Comments added. Only record error message when business API returns error.

Comment (amyangfei) [reply engine/framework/base_jobmaster.go:214]: PTAL @maxshuang

**Review by CharlesCheung96 — APPROVED** [review]

File: engine/framework/master.go [hunk 2]
```diff
@@ -737,9 +747,8 @@ func (m *DefaultBaseMaster) exitWithoutSetErrCenter(ctx context.Context, exitRea
 		m.masterMeta.ErrorMsg = err.Error()
 	}
```
Comment (maxshuang) [inline engine/framework/master.go:748]: Please clear the `ErrorMsg` here if the input `err` is nil, or the old ErrorMsg will remain in the job meta table even the job is finished normally.

File: engine/framework/master.go [hunk 3]
```diff
@@ -592,13 +593,22 @@ func (m *DefaultBaseMaster) markStateInMetadata(
...
+
+func (m *DefaultBaseMaster) persistMetaError() {
+	ctx, cancel := context.WithTimeout(context.Background(), time.Second*3)
+	defer cancel()
 
-	masterMeta.State = code
-	return metaClient.Update(ctx, masterMeta)
+	if err := m.errCenter.CheckError(); err != nil {
+		metaClient := metadata.NewMasterMetadataClient(m.id, m.frameMetaClient)
+		m.masterMeta.ErrorMsg = err.Error()
```
Comment (maxshuang) [inline engine/framework/master.go:606]: Be carefully and clear the `ErrorMsg` in other place to avoid error setting the job meta.

File: engine/framework/master.go (hunk 2 above)
Comment (amyangfei) [reply engine/framework/master.go:750]: PTAL @maxshuang

**Review by maxshuang — APPROVED** [review]
