### PR TITLE
sinkv2: fix a bug about redo log mem quota

### LINKED ISSUE #7836: redo mem quota is not released correctly with pull-based-sink
### What did you do?

Create a changefeed with pull-based-sink enabled and eventual consistent enabled. After run for a while, we can see mem quota is full and the changefeed is blocked forever.

### What did you expect to see?

_No response_

### What did you see instead?

After run for a while, we can see mem quota is full and the changefeed is blocked forever.

### Versions of the cluster

I use cdc master branch.

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

Issue Number: close #7836 .

### What is changed and how it works?

* Release memory quota correctly
* Fix a bug about redo cache full
* More logs about memory quota

#### Tests 

 - Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

File: cdc/processor/sinkmanager/mem_quota.go [hunk 1]
```diff
@@ -197,6 +208,10 @@ func (m *memQuota) clean(tableID model.TableID) uint64 {
 
 // close the mem quota and notify the blocked acquire.
 func (m *memQuota) close() {
+	m.mu.Lock()
+	defer m.mu.Unlock()
+	m.tableMemory = make(map[model.TableID][]*memConsumeRecord)
+	m.usedBytes = 0
```
Comment (amyangfei) [inline cdc/processor/sinkmanager/mem_quota.go:214]: Seems both `memQuota.close()` and `memQuota.clean()` for each table are called in SinkManager.Close(), where `memQuota.clean()` is not necessary.

File: cdc/processor/sinkmanager/mem_quota.go [hunk 2]
```diff
@@ -197,6 +208,10 @@ func (m *memQuota) clean(tableID model.TableID) uint64 {
 
 // close the mem quota and notify the blocked acquire.
 func (m *memQuota) close() {
+	m.mu.Lock()
```
[the remark this answers is not in the document]
Comment (hicqu) [reply cdc/processor/sinkmanager/mem_quota.go:211]: Otherwise `release` will panic.

File: cdc/processor/sinkmanager/redo_cache.go [hunk 3]
```diff
@@ -45,138 +75,151 @@ func newRedoEventCache(changefeedID model.ChangeFeedID, capacity uint64) *redoEv
...
+	e.sizes = e.sizes[endIdx:]
+	e.pushCounts = e.pushCounts[endIdx:]
+	e.readyCount -= endIdx
+	e.lowerBound = res.boundary.Next()
 
-	mu         sync.RWMutex
-	events     []*model.RowChangedEvent
-	sizes      []uint64
-	readyCount int // Count of ready events
+	atomic.AddUint64(&e.cache.allocated, ^(res.releaseSize - 1))
```
[the remark this answers is not in the document]
Comment (hicqu) [reply cdc/processor/sinkmanager/redo_cache.go:181]: Yes I think we can. And from metrics we haven't found unexpected things.

File: cdc/processor/sinkmanager/manager.go [hunk 4]
```diff
@@ -152,7 +152,7 @@ func New(
 		m.redoTaskChan = make(chan *redoTask)
 		m.redoWorkerAvailable = make(chan struct{}, 1)
 		// Use at most 1/3 memory quota for redo event cache.
-		m.eventCache = newRedoEventCache(changefeedID, changefeedInfo.Config.MemoryQuota/3)
+		// m.eventCache = newRedoEventCache(changefeedID, changefeedInfo.Config.MemoryQuota/3)
```
Comment (hi-rustin) [inline cdc/processor/sinkmanager/manager.go:155]: Maybe we can directly delete it.

File: cdc/processor/sinkmanager/table_sink_worker.go [hunk 5]
```diff
@@ -77,77 +79,178 @@ func (w *sinkWorker) handleTasks(ctx context.Context, taskChan <-chan *sinkTask)
...
+			return nil
+		}
 	}
-	advanceTableSinkAndResetCurrentSizeWithBatchID := func(commitTs model.Ts) error {
-		err := w.advanceTableSinkWithBatchID(task, commitTs, currentTotalSize, batchID)
-		if err != nil {
-			return errors.Trace(err)
+
+	needEmitAndAdvance := func() bool {
+		return (w.splitTxn && committedTxnSize+pendingTxnSize >= maxUpdateIntervalSize) ||
```
Comment (hi-rustin) [inline cdc/processor/sinkmanager/table_sink_worker.go:127]: Cloud you please add some comments here?

**Review by hi-rustin — APPROVED** [review]

**Review by nongfushanquan — APPROVED** [review]

**Review by amyangfei — APPROVED** [review]
