### PR TITLE
checker(dm): skip  check for mariadb some version

### LINKED ISSUE #4959: DM can not start task with mariadb 10.1.2
### What did you do?

- prepare dm cluster with version nightly 
- create source for mariadb 10.1.2
- try to start task

### What did you expect to see?

start-task success

### What did you see instead?

Below error output:
"errors": [
                                        {
                                                "severity": "warn",
                                                "short_error": "Migrating from MariaDB is experimentally supported. If you must use DM to migrate data from MariaDB, we suggest make your MariaDB \u003e= 10.1.2"
                                        }
                                ],
                                "extra": "address of db instance - [upstream1.dm](http://upstream1.dm/)-migrate-mariadb-basic-testbed-tps-721316-1-926:3306"
                        }
                ],
                "summary": {
                        "passed": false,
                        "total": 10,
                        "successful": 8,
                        "failed": 1,
                        "warning": 1
                }
        }"

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
nightly
```
Upstream MySQL/MariaDB server version:
```console
10.1.2-MariaDB-1~wheezy-wsrep-log
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve?

Issue Number: close #4959 

### What is changed and how it works?
as title

### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)

start task success with mariadb 10.1.2, there just one warning message

```
dmctl start-task tasks/task-from-mariadb.yaml
{
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": true,
            "msg": "",
            "source": "mariadb",
            "worker": "worker1"
        }
    ],
    "checkResult": "fail to check synchronization configuration with type: no errors but some warnings
    	detail: {
		"results": [
			{
				"id": 0,
				"name": "mysql_version",
				"desc": "check whether mysql version is satisfied",
				"state": "warn",
				"errors": [
					{
						"severity": "warn",
						"short_error": "Migrating from MariaDB is experimentally supported. If you must use DM to migrate data from MariaDB, we suggest make your MariaDB \u003e= 10.1.2"
					}
				],
				"extra": "address of db instance xxxx:3308"
			}
		],
		"summary": {
			"passed": true,
			"total": 10,
			"successful": 9,
			"failed": 0,
			"warning": 1
		}
	}"
}

```

Code changes

 - Has exported function/method change

Side effects

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
`fix a but that can not start task when mariadb version < 10.1.6`.
```

### CODE REVIEW

File: dm/pkg/checker/binlog.go [hunk 1]
```diff
@@ -152,6 +155,12 @@ func (pc *MySQLBinlogRowImageChecker) Check(ctx context.Context) *Result {
 		return result
 	}
 
+	// for mariadb.version < 10.1.6.,  we don't need to check binlog_row_image.
```
Comment (lance6716) [inline dm/pkg/checker/binlog.go:159]: can you give a reference link that on these versions, what's the behaviour of binlog_row_image?

Comment (Ehco1996) [reply dm/pkg/checker/binlog.go:159]:
```
// 'binlog_row_image' is introduced since mysql 5.6.2, and mariadb 10.1.6.
// > In MySQL 5.5 and earlier, full row images are always used for both before images and after images.
// So we need check 'binlog_row_image' after mysql 5.6.2 version and mariadb 10.1.6.
// ref:
// - https://dev.mysql.com/doc/refman/5.6/en/replication-options-binary-log.html#sysvar_binlog_row_image
// - https://mariadb.com/kb/en/library/replication-and-binary-log-server-system-variables/#binlog_row_image
```


some ref links are added in  comment of  func `Check`
https://github.com/Ehco1996/ticdc/blob/b9aaca4d82b2df990afa0f10b376b070a4ba4b5e/dm/pkg/checker/binlog.go#L131

**Review by lance6716 — APPROVED** [review]

File: dm/pkg/checker/binlog_test.go [hunk 2]
```diff
@@ -127,3 +127,75 @@ func TestBinlogDB(t *testing.T) {
...
+		state     State
+		needCheck bool
+		rowImage  string
+	}{
+		// mysql < 5.6.2 don't need check
+		{
+			version:   "5.6.1-log",
+			state:     StateSuccess,
+			needCheck: false,
+			rowImage:  "full",
```
Comment (okJiang) [inline dm/pkg/checker/binlog_test.go:147]: If need not check, we maybe should test `rowImage != "full"`.

File: dm/pkg/checker/binlog_test.go [hunk 3]
```diff
@@ -127,3 +127,75 @@ func TestBinlogDB(t *testing.T) {
...
+			needCheck: true,
+			rowImage:  "NOBLOB",
+		},
+
+		// mariadb < 10.1.6 don't need check
+		{
+			version:   "10.1.5-MariaDB-1~wheezy",
+			state:     StateSuccess,
+			needCheck: false,
+			rowImage:  "full",
```
Comment (okJiang) [inline dm/pkg/checker/binlog_test.go:170]: ditto

**Review by okJiang — COMMENTED** [review]
rest LGTM

File: dm/pkg/checker/binlog_test.go (hunk 2 above)
Comment (Ehco1996) [reply dm/pkg/checker/binlog_test.go:147]: It's been a long time, we'll be waiting for you to come back soon 🤣

Comment (Ehco1996) [reply dm/pkg/checker/binlog_test.go:147]: I thought again, for the no need check scenario there is no `binlog_row_image` variable in the db, so this test scenario is redundant? (It doesn't happen in the real world)

Comment (lance6716) [reply dm/pkg/checker/binlog_test.go:147]: needCheck will make sure these's no mock result for SELECT binlog_row_image. In those cases I think remove `rowImage:  "full",` should also be OK

**Review by okJiang — APPROVED** [review]
