### PR TITLE
cmd (ticdc): a better Kafka consumer 

### LINKED ISSUE #10989: Enhance Kafka consumer performance
The following points need to be considered.
- When the consumer crashes, some messages which haven't write to the downstream may be lost. 
- The code needs to be easy to maintain.
- Reduce memory usage

### PR DESCRIPTION
**Pull request by wk989898**
### What problem does this PR solve?

Issue Number: close #10989

### What is changed and how it works?
Rewrite Kafka consumer

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
none
```

### CODE REVIEW

**Comment by asddongmen** [comment]
Keep this PR in draft state until it is ready for review and merge. In the meantime, you can use `/test cdc-integration-kafka-test` to manually trigger the Kafka integration test.

**Comment by asddongmen** [comment]
It would be extremely helpful if you could provide a design documentation for this new Kafka consumer. The documentation can includes the drawbacks of the current Kafka consumer, suggestions for improvements, how the new design solves these problems, and why it is better than the old one.

File: cmd/kafka-consumer/event_group.go [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+
+// NewEventsGroup will create new event group.
+func NewEventsGroup() *eventsGroup {
+	return &eventsGroup{
+		events: make([]*model.RowChangedEvent, 0),
+	}
+}
+
+// Append will append a event to event groups.
+func (g *eventsGroup) Append(e *model.RowChangedEvent) {
```
Comment (asddongmen) [inline cmd/kafka-consumer/event_group.go:35]: A memory base event cache may lead to OOM issue in some cases.

File: cmd/kafka-consumer/kafkago_consumer.go [hunk 2]
```diff
@@ -0,0 +1,164 @@
...
+	cerror "github.com/pingcap/errors"
+	"github.com/pingcap/log"
+	"github.com/segmentio/kafka-go"
+	"go.uber.org/zap"
+)
+
+func kafkaGoGetPartitionNum(address []string, topic string) (int32, error) {
+	client := &kafka.Client{
+		Addr:    kafka.TCP(address...),
+		Timeout: 10 * time.Second,
```
Comment (asddongmen) [inline cmd/kafka-consumer/kafkago_consumer.go:31]: It is better to use a constant rather than a magic number.

File: cmd/kafka-consumer/kafkago_consumer.go [hunk 3]
```diff
@@ -0,0 +1,164 @@
...
+	}
+	for i := 0; i <= 30; i++ {
```
Comment (asddongmen) [inline cmd/kafka-consumer/kafkago_consumer.go:33]: Ditto

File: cmd/kafka-consumer/kafkago_consumer.go [hunk 4]
```diff
@@ -0,0 +1,164 @@
...
+	"strings"
+	"time"
+
+	cerror "github.com/pingcap/errors"
+	"github.com/pingcap/log"
+	"github.com/segmentio/kafka-go"
+	"go.uber.org/zap"
+)
+
+func kafkaGoGetPartitionNum(address []string, topic string) (int32, error) {
```
Comment (asddongmen) [inline cmd/kafka-consumer/kafkago_consumer.go:28]: IMHO, the prefix `kafkaGo` is verbose.

File: cmd/kafka-consumer/main.go [hunk 5]
```diff
@@ -247,29 +93,17 @@ func main() {
...
-	consumer, err := NewConsumer(ctx, consumerOption)
-	if err != nil {
-		log.Panic("Error creating consumer", zap.Error(err))
-	}
 
-	client, err := sarama.NewConsumerGroup(consumerOption.address, consumerOption.groupID, config)
-	if err != nil {
-		log.Panic("Error creating consumer group client", zap.Error(err))
+	switch consumerClient {
+	case "kafka-go":
```
Comment (CharlesCheung96) [inline cmd/kafka-consumer/main.go:99]:
```suggestion
```
remove the dummy branch.

File: cmd/kafka-consumer/saram_consumer.go [hunk 6]
```diff
@@ -0,0 +1,191 @@
...
+		}
+		log.Info("retry get partition number", zap.String("topic", o.topic))
+		time.Sleep(1 * time.Second)
+	}
+
+	return 0, cerror.Errorf("get partition number(%s) timeout", o.topic)
+}
+
+type saramConsumer struct {
+	ready  chan bool
```
Comment (CharlesCheung96) [inline cmd/kafka-consumer/saram_consumer.go:85]: ready is not used.

File: cmd/kafka-consumer/confluent_consumer.go [hunk 7]
```diff
@@ -0,0 +1,159 @@
+// Copyright 2020 PingCAP, Inc.
```
Comment (CharlesCheung96) [inline cmd/kafka-consumer/confluent_consumer.go:1]:
```suggestion
// Copyright 2024 PingCAP, Inc.
```

File: cmd/kafka-consumer/consumer.go [hunk 8]
```diff
@@ -0,0 +1,24 @@
+// Copyright 2020 PingCAP, Inc.
```
Comment (CharlesCheung96) [inline cmd/kafka-consumer/consumer.go:1]:
```suggestion
// Copyright 2024 PingCAP, Inc.
```
ditto

File: cmd/kafka-consumer/saram_consumer.go (hunk 6 above)
Comment (wk989898) [reply cmd/kafka-consumer/saram_consumer.go]: It is related to sarama implementation.

**Comment by CharlesCheung96** [comment]
Please briefly describe the design and core change in the pr body.

**Review by sdojjy — APPROVED** [review]
