### PR TITLE
mq(ticdc): do not assign nil to interface value to prenvent panic on close sink v1

### LINKED ISSUE #7121: cdc close mq produce panic
### What did you do?

use sink v1, do nothing special

### What did you expect to see?

works normally.

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x29d8cce]

goroutine 1416 [running]:
github.com/pingcap/tiflow/cdc/sink/mq.(*mqSink).Close(0x0, {0x21?, 0xc02484ac80?})
        github.com/pingcap/tiflow/cdc/sink/mq/mq.go:322 +0x2e
github.com/pingcap/tiflow/cdc/processor.(*processor).Close(0xc00753f200)
        github.com/pingcap/tiflow/cdc/processor/processor.go:1065 +0xdf5
github.com/pingcap/tiflow/cdc/processor.(*managerImpl).closeProcessor(0xc0007f58c0, {{0xc000772892?, 0xc00c12f128?}, {0xc0007728aa?, 0x4234dff63?}})
        github.com/pingcap/tiflow/cdc/processor/manager.go:155 +0xcb
github.com/pingcap/tiflow/cdc/processor.(*managerImpl).Tick(0xc0007f58c0, {0x7ff3097890d8?, 0xc0006248a0}, {0x3ba0600?, 0xc002080540})
        github.com/pingcap/tiflow/cdc/processor/manager.go:129 +0x456
github.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run(0xc002d18780, {0x7ff3097890d8, 0xc0006248a0}, 0xc0005b3b30, 0x5f5e100, {0x34341d7, 0x9})
        github.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:266 +0xe63
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker(0xc0008930e0, {0x3bd40a0?, 0xc0006248a0}, {0x7ff309a96460, 0xc0007f58c0}, {0x3ba0600, 0xc002080540}, 0x43b892?, {0x34341d7, 0x9})
        github.com/pingcap/tiflow/cdc/capture/capture.go:490 +0x185
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func4()
        github.com/pingcap/tiflow/cdc/capture/capture.go:333 +0x28f
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:72 +0xa5
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #7121

### What is changed and how it works?

https://stackoverflow.com/questions/13476349/check-for-nil-and-nil-interface-in-go

do not assign nil value to a interface

#### Tests 

- Manual test

### Release note 

```release-note
`None`
```

### CODE REVIEW

File: cdc/sink/mq/mq.go [hunk 1]
```diff
@@ -319,11 +319,13 @@ func (k *mqSink) EmitDDLEvent(ctx context.Context, ddl *model.DDLEvent) error {
 // It is only called in the processor, and the processor destroys the
 // table sinks before closing it. So there is no writing after closing.
 func (k *mqSink) Close(ctx context.Context) error {
-	k.resolvedBuffer.Close()
-	// We must finish consuming the data here,
-	// otherwise it will cause the channel to not close properly.
-	for range k.resolvedBuffer.Out() {
-		// Do nothing. We do not care about the data.
+	if k.resolvedBuffer != nil {
```
Comment (hi-rustin) [inline cdc/sink/mq/mq.go:322]: Why this can be empty?

File: cdc/processor/processor.go [hunk 2]
```diff
@@ -670,27 +671,38 @@ func (p *processor) lazyInitImpl(ctx cdcContext.Context) error {
...
 		)
+		if err != nil {
+			log.Info("processor creates sink failed",
+				zap.String("namespace", p.changefeedID.Namespace),
+				zap.String("changefeed", p.changefeedID.ID),
+				zap.Error(err),
+				zap.Duration("duration", time.Since(start)))
+			return errors.Trace(err)
+		}
+		p.sinkV1 = s
```
Comment (hi-rustin) [inline cdc/processor/processor.go:689]: Please add a comment here. Thanks!

**Comment by hi-rustin** [comment]
> * Manual test

How to reproduce and test it?

**Comment by hi-rustin** [comment]
I'm curious as to why we wouldn't have encountered this problem originally.

**Comment by 3AceShowHand** [comment]
> > * Manual test
> 
> How to reproduce and test it?

Deploy 1 Kafka server, create a changefeed with `replication-factor` as `2`, this failed and cause the server panic.

**Comment by 3AceShowHand** [comment]
> I'm curious as to why we wouldn't have encountered this problem originally.

it looks the problem introduced since v6.0.0. https://github.com/pingcap/tiflow/pull/5302/files#diff-55a9a4424fd834ec23f010504e478b5b98b36ad6c267c3807dbb36bd433fd3a5R496

**Comment by asddongmen** [comment]
> I'm curious as to why we wouldn't have encountered this problem originally.

I guess it is cuz we have never met a new sink error in processor before, since we would check sink config and try to new it at the first place we creat a changefeed.

**Review by sdojjy — APPROVED** [review]

File: cdc/processor/processor.go [hunk 3]
```diff
@@ -670,27 +671,41 @@ func (p *processor) lazyInitImpl(ctx cdcContext.Context) error {
...
 		)
+		if err != nil {
+			log.Info("processor creates sink failed",
+				zap.String("namespace", p.changefeedID.Namespace),
+				zap.String("changefeed", p.changefeedID.ID),
+				zap.Error(err),
+				zap.Duration("duration", time.Since(start)))
+			return errors.Trace(err)
+		}
+		// make sure `s` is not nil before assign it to the `sinkV1`, which is an interface.
```
Comment (hi-rustin) [inline cdc/processor/processor.go:689]:
```suggestion
		// Make sure `s` is not nil before assigning it to the `sinkV1`, which is an interface.
		// See: https://go.dev/doc/faq#nil_error
```

File: cdc/processor/processor.go [hunk 4]
```diff
@@ -670,27 +671,41 @@ func (p *processor) lazyInitImpl(ctx cdcContext.Context) error {
...
 		)
+		if err != nil {
+			log.Info("processor creates sink failed",
+				zap.String("namespace", p.changefeedID.Namespace),
+				zap.String("changefeed", p.changefeedID.ID),
+				zap.Error(err),
+				zap.Duration("duration", time.Since(start)))
+			return errors.Trace(err)
+		}
+		// Make sure `s` is not nil before assigning it to the `sinkV1`, which is an interface.
```
Comment (hi-rustin) [inline cdc/processor/processor.go:689]:
```suggestion
		// Make sure `s` is not nil before assigning it to the `sinkV1`, which is an interface.
		// See: https://go.dev/play/p/sDlHncxO3Nz
```

**Review by hi-rustin — APPROVED** [review]

File: cdc/processor/processor.go [hunk 5]
```diff
@@ -670,27 +671,42 @@ func (p *processor) lazyInitImpl(ctx cdcContext.Context) error {
...
+		// See: https://go.dev/play/p/sDlHncxO3Nz
+		if s != nil {
+			p.sinkV1 = s
+		}
```
Comment (amyangfei) [inline cdc/processor/processor.go:693]: After this PR if code runs to L691 `s` can't be `nil`, since the `err` is not nil, which has been checked in L681.
But it is all right to leave the check in L691.
