### PR TITLE
validator(dm): support start from time & fix & integration test

### LINKED ISSUE #5449: start validation from timestamp

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #5449

### What is changed and how it works?
**this pr is large most due to change to `.proto` and test**

- support `validation start --start-time`
- refactor and add more check to `validation start`, `validation start` can be used in 2 ways:
  - enable validator on the fly(like create+start in task operation), in this case all validator of target subtask should not have been enabled before;
  - start stopped validator, all validator of target subtask should have been enabled, and cannot add explicit mode and start-time flag
- add `mode` to `validation status`
- fix bug that we set an not-completely-initialized subtaskConfig into subtask on validator start. now we only update needed config.
- fix bug that we initialized validator when expect stage is stopped(happens on failover), which may cause resource leak.
- extract real binlog from relay log `binlog pos`
- reset FirstValidateTS when loading pending row changes to avoid failed row changes be marked as error row immediately if validator stopped for a long time.
- add more integration test

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

File: dm/dm/master/scheduler/scheduler.go [hunk 1]
```diff
@@ -2733,44 +2733,32 @@ func (s *Scheduler) handleLoadTask(ctx context.Context, loadTaskCh <-chan ha.Loa
 	}
 }
 
-func (s *Scheduler) OperateValidationTask(expectStage pb.Stage, stCfgs map[string]map[string]config.SubTaskConfig) error {
-	s.mu.RLock()
-	defer s.mu.RUnlock()
+// OperateValidationTask operate validator of subtask.
+// 	tasks: tasks need to operate
+// 	validatorStages: stage info of subtask validators
+// 	changedSubtaskCfgs: length should be 0 or equal to validatorStages
```
Comment (lance6716) [inline dm/dm/master/scheduler/scheduler.go:2739]: seems changedSubtaskCfgs can tolerate not the same length as validatorStages 🤔

File: dm/dm/master/server.go [hunk 2]
```diff
@@ -2641,6 +2641,66 @@ func (s *Server) sharedLogic(ctx context.Context, req interface{}, respPointer i
...
 
+func (s *Server) checkStartValidationParams(req *pb.StartValidationRequest) (
+	map[string]map[string]config.SubTaskConfig, string, bool,
+) {
+	explicitModeOrStartTime := req.Mode != nil || req.StartTime != nil
+	mode := config.ValidationFull
+	if req.Mode != nil {
+		mode = req.GetModeValue()
+	}
+	if mode != config.ValidationFull && mode != config.ValidationFast {
```
Comment (lance6716) [inline dm/dm/master/server.go:2652]: seems only need to check this when `req.Mode != nil`. And also refer ValidationFull in below message rather than hard coded value.

**Review by lance6716 — COMMENTED** [review]
will review later

File: dm/dm/master/scheduler/scheduler.go (hunk 1 above)
Comment (D3Hunter) [reply dm/dm/master/scheduler/scheduler.go:2739]: caller should and has make sure about this

**Review by buchuitoudegou — COMMENTED** [review]
Will take a look at IT later.

File: dm/dm/master/server.go [hunk 3]
```diff
@@ -2641,6 +2641,66 @@ func (s *Server) sharedLogic(ctx context.Context, req interface{}, respPointer i
...
+			} else {
+				allEnabled = false
+			}
+		}
+	}
+
+	// if user set mode or start-time explicitly, then we do start operation.
+	// none of the target validators should have enabled
+	if explicitModeOrStartTime && !noneEnabled {
+		msg := fmt.Sprintf("some of target validator(%s) has already enabled.", enabledValidator)
```
[the remark this answers is not in the document]
Comment (D3Hunter) [reply dm/dm/master/server.go:2688]: > Should we list all the validators that have been enabled

not sure how often user start validator only on some subtask, we can enhance it later.

File: dm/dm/config/task_cli_args.go [hunk 4]
```diff
@@ -51,11 +47,8 @@ func (t *TaskCliArgs) Decode(data []byte) error {
 // Verify checks if all fields are legal.
 func (t *TaskCliArgs) Verify() error {
 	if t.StartTime != "" {
-		if _, err := time.Parse(StartTimeFormat, t.StartTime); err != nil {
-			_, err = time.Parse(StartTimeFormat2, t.StartTime)
-			if err != nil {
-				return terror.Annotate(err, "error while parse start-time, expected in the format like '2006-01-02 15:04:05' or '2006-01-02T15:04:05'")
-			}
+		if _, err := utils.ParseStartTime(t.StartTime); err != nil {
+			return terror.Annotate(err, "error while parse start-time, expected in the format like '2006-01-02 15:04:05' or '2006-01-02T15:04:05'")
```
[the remark this answers is not in the document]
Comment (D3Hunter) [reply dm/dm/config/task_cli_args.go:51]: there are 2 other message using `error while parse` style which doesn't meets english grammar, will not change them in this pr. maybe during refactor.

**Comment by D3Hunter** [comment]
ptal of https://github.com/pingcap/tiflow/pull/5534/commits/fc1f2588a1f360ec629dc16f7b0812f4b9dc3e0c too.

fix bug that we initialized validator when expect stage is stopped(happens on failover), which may cause resource leak.

File: dm/pkg/binlog/filename.go [hunk 5]
```diff
@@ -114,3 +114,16 @@ func SplitFilenameWithUUIDSuffix(filename string) (baseName, uuidSuffix, seq str
...
 	return baseName, uuidSuffix, seq, nil
 }
+
+// ExtractRealName removes uuid suffix if it exists and returns real binlog name.
+func ExtractRealName(name string) string {
+	if !strings.Contains(name, posUUIDSuffixSeparator) {
+		return name
+	}
+	baseName, _, seq, err := SplitFilenameWithUUIDSuffix(name)
+	if err != nil {
```
[the remark this answers is not in the document]
Comment (D3Hunter) [reply dm/pkg/binlog/filename.go:127]: https://github.com/pingcap/tiflow/pull/5534/commits/8cb3416e24e789935d406926987128bf1702d54b

File: dm/dm/master/server.go (hunk 2 above)
Comment (D3Hunter) [reply dm/dm/master/server.go]: https://github.com/pingcap/tiflow/pull/5534/commits/9901a6f85ea1d99b4a5dca180c5811a6e3f9820d

**Comment by D3Hunter** [comment]
ptal

File: dm/dm/ctl/master/start_stop_validation.go [hunk 6]
```diff
@@ -33,105 +34,149 @@ const (
...
-		if op == StartValidationOp {
-			// TODO: get `from-time` flag
-			var mode string
-			mode, err = cmd.Flags().GetString("mode")
+	if args.allTask, err = cmd.Flags().GetBool("all-task"); err != nil {
+		return args, err.Error(), false
+	}
+
+	if op == StartValidationOp {
+		args.explicitMode = cmd.Flags().Changed("mode")
```
Comment (lance6716) [inline dm/dm/ctl/master/start_stop_validation.go:86]: since the default value of `mode` is "", we in fact don't need this check. Also for `start-time`.

I'm both OK with these two styles: if explicitMode {checkMode} or if mode != "" {checkMode}

File: dm/dm/master/server.go [hunk 7]
```diff
@@ -2641,6 +2641,67 @@ func (s *Server) sharedLogic(ctx context.Context, req interface{}, respPointer i
...
+		}
+		return nil, fmt.Sprintf("fail to get subtask config by task name `%s` and sources `%v`",
+			req.TaskName, req.Sources), false
+	}
+
+	var enabledValidator string
+	allEnabled, noneEnabled := true, true
+	for taskName := range subTaskCfgs {
+		for sourceID := range subTaskCfgs[taskName] {
+			if s.scheduler.ValidatorEnabled(taskName, sourceID) {
```
Comment (lance6716) [inline dm/dm/master/server.go:2677]: the check for all subtasks is not atomic, is it safe that other RPC changed the status?

**Review by lance6716 — COMMENTED** [review]
leave for lunch

File: dm/dm/master/server.go [hunk 8]
```diff
@@ -2641,6 +2641,67 @@ func (s *Server) sharedLogic(ctx context.Context, req interface{}, respPointer i
...
+		if allEnabled {
+			msg = "all target validator has enabled, cannot do 'validation start' with explicit mode or start-time"
+		}
+		return nil, msg, false
+	}
+	// no explicit mode or start-time:
+	// - do resume when all have enabled
+	// - do start when none enabled
+	if !explicitModeOrStartTime && !allEnabled && !noneEnabled {
+		return nil, fmt.Sprintf("some of target validator(%s) has already enabled.", enabledValidator), false
```
Comment (lance6716) [inline dm/dm/master/server.go:2699]: the final message which is displayed to user can be more clear, such as "some (%s) but not all validator has already enabled, so we can't start nor resume them in one command" or something

File: dm/dm/master/server.go [hunk 9]
```diff
@@ -2652,44 +2713,49 @@ func (s *Server) StartValidation(ctx context.Context, req *pb.StartValidationReq
...
+	validatorStages := make([]ha.Stage, 0)
 	for taskName := range subTaskCfgs {
 		for sourceID := range subTaskCfgs[taskName] {
 			cfg := subTaskCfgs[taskName][sourceID]
-			cfg.ValidatorCfg.Mode = req.Mode
+			if !s.scheduler.ValidatorEnabled(taskName, sourceID) {
+				cfg.ValidatorCfg.Mode = mode
+				cfg.ValidatorCfg.StartTime = startTime
+				changedSubtaskCfgs = append(changedSubtaskCfgs, cfg)
+				log.L().Info("enable validator",
```
Comment (lance6716) [inline dm/dm/master/server.go:2738]: in above comment we use "resume" and "start", but here the corresponding words become "start" and "enable"? Better to unify them for other developer's reading

Comment (D3Hunter) [reply dm/dm/master/server.go:2738]: unified to `enable`(like create+start in task operation), `start`(like start in task op)

File: dm/dm/master/server.go (hunk 7 above)
Comment (D3Hunter) [reply dm/dm/master/server.go:2669]: changed to [acquire subtask latch before check](https://github.com/pingcap/tiflow/pull/5534/commits/cc708a61c22b198cfdded9843bc32b7f19d9a340)

File: dm/dm/ctl/master/start_stop_validation.go (hunk 6 above)
Comment (D3Hunter) [reply dm/dm/ctl/master/start_stop_validation.go:86]: will leave it.

**Comment by D3Hunter** [comment]
ptal @lance6716 @buchuitoudegou

File: dm/tests/dmctl_command/run.sh [hunk 10]
```diff
@@ -152,6 +152,261 @@ function run() {
...
+		"validation start --start-time" \
+		"Error: flag needs an argument: --start-time" 1
+
+	echo "--> (fail) validation start: invalid start-time"
+	run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
+		"validation start --start-time xx" \
+		"Error: start-time should be in the format like '2006-01-02 15:04:05' or '2006-01-02T15:04:05'" 1
+
+	echo "--> (fail) validation start: without all-task and task-name"
+	run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
```
Comment (buchuitoudegou) [inline dm/tests/dmctl_command/run.sh:199]: What about moving these failed cases to `run_validator_error_cmd`?

File: dm/tests/dmctl_command/run.sh [hunk 11]
```diff
@@ -152,6 +152,261 @@ function run() {
...
+
+	echo "--> (fail) validation stop: stop not-enabled validator"
+	run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
+		"validation stop -s $SOURCE_ID1 test" \
+		"\"result\": false" 1 \
+		"some target validator(test with source $SOURCE_ID1) is not enabled" 1
+
+	echo "--> (success) validation start: start validation without explicit mode for source 1"
+	run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
+		"validation start -s $SOURCE_ID1 test" \
```
Comment (buchuitoudegou) [inline dm/tests/dmctl_command/run.sh:260]: Could you add a test case that specifies multiple sources? More than one source is valid too.

File: dm/dm/config/task_cli_args.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (buchuitoudegou) [reply dm/dm/config/task_cli_args.go:51]: I'll note it in the issue. (this error message will be presented to the users, it would better be grammatical valid and make sense).

**Review by buchuitoudegou — APPROVED** [review]
rest LGTM

File: dm/tests/dmctl_command/run.sh (hunk 10 above)
Comment (D3Hunter) [reply dm/tests/dmctl_command/run.sh:199]: some negative case depends on positive case, so it's mixed together, so it's separate with other commands

File: dm/tests/dmctl_command/run.sh [hunk 12]
```diff
@@ -152,6 +152,261 @@ function run() {
...
+
+	dmctl_operate_source create $cur/conf/source1.yaml $SOURCE_ID1
+	dmctl_operate_source create $cur/conf/source2.yaml $SOURCE_ID2
+	dmctl_start_task $cur/conf/dm-task-no-validator.yaml --remove-meta
+	run_dm_ctl_with_retry $WORK_DIR "127.0.0.1:$MASTER_PORT" \
+		"query-status test" \
+		"\"unit\": \"Sync\"" 2
+
+	echo "--> (fail) validation start: missing mode value"
+	run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
```
Comment (lance6716) [inline dm/tests/dmctl_command/run.sh:179]: maybe also check the help message of validation xxx is readable, like `"pause-task \[-s source ...\] \[task-name | task-file\] \[flags\]"`

**Review by lance6716 — APPROVED** [review]

File: dm/dm/config/task_cli_args.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (D3Hunter) [reply dm/dm/config/task_cli_args.go:51]: those string it not introduced in this pr, will move it into https://github.com/pingcap/tiflow/issues/5143

**Comment by lance6716** [comment]
/hold

please unhold after addresss comments

File: dm/tests/dmctl_command/run.sh (hunk 12 above)
Comment (D3Hunter) [reply dm/tests/dmctl_command/run.sh:179]: no gains, cobra will just print cobra.Command.Use & cobra.Command.Short

File: dm/tests/dmctl_command/run.sh (hunk 11 above)
Comment (D3Hunter) [reply dm/tests/dmctl_command/run.sh:260]: https://github.com/pingcap/tiflow/pull/5534/commits/fed53e214610d2cc6469aa613e4db9e675c9366c
