### PR TITLE
master, config(dm): fix case-sensitive compatibility for dmctl

### LINKED ISSUE #5255: DM can't sync uppercase tables if forget to set `case-sensitive: true` in task config
### What did you do?

task config uses uppercase block-allow-list

```
$ cat bin/task.yaml
name: test             # 任务名称，需要全局唯一
task-mode: all         # 任务模式，可设为 "full"、"incremental"、"all"

target-database:       # 下游数据库实例配置
  host: "127.0.0.1"
  port: 4000
  user: "root"
  password: ""         # 如果密码不为空，则推荐使用经过 dmctl 加密的密文

## ******** 功能配置集 **********
block-allow-list:        # 上游数据库实例匹配的表的 block-allow-list 过滤规则集，如果 DM 版本 <= v2.0.0-beta.2 则使用 black-white-list
  bw-rule-1:             # 黑白名单配置的名称
    do-dbs: ["test"] # 迁移哪些库
    do-tables:
    - db-name: "test"
      tbl-name: "TM_DATA"

# ----------- 实例配置 -----------
mysql-instances:
  - source-id: "mysql-replica-01"  # 上游实例或者复制组 ID，参考  的  配置
    block-allow-list:  "bw-rule-1" # 黑白名单配置名称，如果 DM 版本 <= v2.0.0-beta.2 则使用 black-white-list
    meta:
      binlog-name: 'mysql-bin.000001'
      binlog-pos: 4
```

start-task

### What did you expect to see?

not sure what's the expected behaviour for test.TM_DATA :thinking: 

but v2.0.7 can replicate test.TM_DATA with above config.

### What did you see instead?

test.TM_DATA is not replicated

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
(paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: close #5255

### What is changed and how it works?

OpenAPI needs automatically decides the case-sensitive from MySQL, but dmctl should keep the compatibility. So I split the two functions.

### Check List 

Tests 

 - Integration test

Code changes

Side effects

 - Increased code complexity

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
Fix DM can't replicate uppercase tables when the task has case-sensitive: false
```

### CODE REVIEW

File: dm/dm/master/server.go [hunk 1]
```diff
@@ -86,7 +87,11 @@ var (
 	registerOnce      sync.Once
 	runBackgroundOnce sync.Once
 
-	checkAndAdjustSourceConfigFunc = checkAndAdjustSourceConfig
+	// the difference of below functions is checkAndAdjustSourceConfigForDMCtlFunc will not AdjustCaseSensitive. It's a
+	// compatibility compromise.
+	// When we need to change the implementation of dmctl to OpenAPI, we should notice the user about this change.
```
Comment (Ehco1996) [inline dm/dm/master/server.go:92]: this upgrade case is so complex, we may add breaking change in doc and release note

see [here](https://github.com/pingcap/tiflow/issues/5255#issuecomment-1108148106)

/cc @sunzhaoyang @WizardXiao

File: dm/dm/config/source_config.go [hunk 2]
```diff
@@ -308,7 +308,7 @@ func (c *SourceConfig) Adjust(ctx context.Context, db *sql.DB) (err error) {
 		log.L().Warn("using an absolute relay path, relay log can't work when starting multiple relay worker")
 	}
 
-	return c.AdjustCaseSensitive(ctx2, db)
+	return nil
```
Comment (Ehco1996) [inline dm/dm/config/source_config.go:311]: I remembered why this change was introduced, it's because when implementing openAPI , I was referring to the v2 version of the task config 😵

**Review by Ehco1996 — APPROVED** [review]
LGTM

**Review by D3Hunter — APPROVED** [review]
