### PR TITLE
tracker(dm): fix downstream table structure reports key too long

### LINKED ISSUE #5315: DM task pause with Specified key was too long
### What did you do?

followed the documentation: https://docs.pingcap.com/tidb/stable/migrate-large-mysql-to-tidb
everything went fine until the DM part.
[v540_1.zip](https://github.com/pingcap/tiflow/files/8591698/v540_1.zip)

### What did you expect to see?

the task running and keeping the tidb cluster sync with the maria db

### What did you see instead?

query-status return: "RawCause": "[ddl:1071]Specified key was too long; max key length is 3072 bytes"

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
dm-master -V: Release Version: v5.4.0
dm-worker -V: Release Version: v5.4.0
dmctl : v5.4.0
```
Upstream MySQL/MariaDB server version:
```console
10.4.18-MariaDB
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
5.4.0
```
How did you deploy DM: tiup or manually?
```console
TiUP
```
Other interesting information (system version, hardware config, etc):
```console
- set max-index-lengh to 12288 
- Try to use DM 5.3.1 (as Daniël on asktug on slack did ask)
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
Starting component `dmctl`: /root/.tiup/components/dmctl/v5.3.1/dmctl/dmctl /root/.tiup/components/dmctl/v5.3.1/dmctl/dmctl --master-addr xxx:8261 query-status task-xxx
{
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": true,
            "msg": "",
            "sourceStatus": {
                "source": "mysql-dc3-master",
                "worker": "dm-xxx-8262",
                "result": null,
                "relayStatus": null
            },
            "subTaskStatus": [
                {
                    "name": "task-xxx",
                    "stage": "Paused",
                    "unit": "Sync",
                    "result": {
                        "isCanceled": false,
                        "errors": [
                            {
                                "ErrCode": 44003,
                                "ErrClass": "schema-tracker",
                                "ErrScope": "downstream",
                                "ErrLevel": "high",
                                "Message": "startLocation: [position: (, 0), gtid-set: ], endLocation: [position: (mariadb-bin.048312, 96376516), gtid-set: 0-1856393171-6399440815]: failed to create table for `ringover`.`cdn_storage` in schema tracker",
                                "RawCause": "[ddl:1071]Specified key was too long; max key length is 3072 bytes",
                                "Workaround": ""
                            }
                        ],
                        "detail": null
                    },
                    "unresolvedDDLLockID": "",
                    "sync": {
                        "totalEvents": "52",
                        "totalTps": "0",
                        "recentTps": "0",
                        "masterBinlog": "(mariadb-bin.048944, 34179712)",
                        "masterBinlogGtid": "0-1856393171-6452464976",
                        "syncerBinlog": "(mariadb-bin.048312, 96375851)",
                        "syncerBinlogGtid": "0-1856393171-6399440815",
                        "blockingDDLs": [
                        ],
                        "unresolvedGroups": [
                        ],
                        "synced": false,
                        "binlogType": "remote",
                        "secondsBehindMaster": "0"
                    }
                }
            ]
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: close #5315

### What is changed and how it works?

during the refactor of schema tracker, I found this issue is not hard to fix

#### Tests 

 - Unit test

### Release note 

```release-note
Fix a problem that DM will report `Specified key was too long` error
```

### CODE REVIEW

File: dm/pkg/schema/tracker_test.go [hunk 1]
```diff
@@ -775,7 +775,7 @@ func (s *trackerSuite) TestGetDownStreamIndexInfo(c *C) {
 
 	mock.ExpectQuery("SHOW CREATE TABLE " + tableID).WillReturnRows(
 		sqlmock.NewRows([]string{"Table", "Create Table"}).
-			AddRow("test", "create table t(a int primary key, b int, c varchar(10))"))
+			AddRow("test", "create table t(a int primary key, b int, c varchar(10000), key(c))"))
```
Comment (buchuitoudegou) [inline dm/pkg/schema/tracker_test.go:778]: Should we test the maximum number of the `max-index-length` (i.e. `DefMaxOfMaxIndexLength` in TiDB) so that we can ensure we are compatible with create statements of any key length.

Comment (lance6716) [inline dm/pkg/schema/tracker_test.go:778]:
```suggestion
			AddRow("test", "create table t(a int primary key, b int, c varchar(20000), key(c))"))
```

Comment (lance6716) [reply dm/pkg/schema/tracker_test.go]: now 20000 is larger than DefMaxOfMaxIndexLength 😄

**Review by buchuitoudegou — APPROVED** [review]

**Comment by lance6716** [comment]
ping @GMHDBJD @D3Hunter

**Review by D3Hunter — APPROVED** [review]
