### PR TITLE
cmd(ticdc): print error msg if an invalid input was read

### LINKED ISSUE #7903: TiCDC stuck on check tables if eligible to replicate
### What did you do?

Start TiCDC within container with following command:

XXXX:~$ sudo docker run \
>     ...
>         cdc cli changefeed create  \
>     ...
Error: EOF
[WARN] some tables are not eligible to replicate, []model.TableName{model.TableName{Schema:"merchant_infra", Table:"xxxxxx", TableID:0, IsPartition:false}}
Could you agree to ignore those tables, and continue to replicate [Y/N]
EOF

### What did you expect to see?

can startup cdc successfully or providing useful info to continue

### What did you see instead?

Auto error out without meaningful instructions

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v6.1.0
```

Upstream TiKV version (execute `tikv-server --version`): v6.1.0

```console
v6.1.0
```

TiCDC version (execute `cdc version`): 

```console
v6.1.0
```

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: close #7903

### What is changed and how it works?
print error msg if an invalid input was read

#### Tests 

 Manual test (add detailed scripts or steps below)
1. before
```bash
# docker run cdc:test /cdc cli changefeed create --sink-uri="blackhole://" -c storage-perf --server=10.2.6.163:8300 --start-ts=438045762164359180
Error: EOF
Replicate lag (121h36m31.6s) is larger than 1 days, large data may cause OOM, confirm to continue at your own risk [Y/N]
```
2. after
```bash
# docker run cdc:test /cdc cli changefeed create --sink-uri="blackhole://" -c storage-perf --server=10.2.7.167:8301 --start-ts=438045762164359180

Replicate lag (380h54m19.605s) is larger than 1 days, large data may cause OOM, confirm to continue at your own risk [Y/N]
Received invalid input: EOF, abort the command.
Abort changefeed create.
```

### Release note 

```release-note
`None`.
```

### CODE REVIEW

File: pkg/cmd/cli/cli_changefeed_helper.go [hunk 1]
```diff
@@ -41,6 +41,7 @@ func confirmLargeDataGap(cmd *cobra.Command, currentPhysical int64, startTs uint
 		var yOrN string
 		_, err := fmt.Scan(&yOrN)
 		if err != nil {
+			cmd.Printf("got invalid input: %s, abort changefeed %s\n", err.Error(), command)
```
Comment (db-will) [inline pkg/cmd/cli/cli_changefeed_helper.go:44]: nit: Maybe `Received invalid input: ...`?

**Review by db-will — APPROVED** [review]

File: pkg/cmd/cli/cli_changefeed_helper.go [hunk 2]
```diff
@@ -41,6 +41,7 @@ func confirmLargeDataGap(cmd *cobra.Command, currentPhysical int64, startTs uint
 		var yOrN string
 		_, err := fmt.Scan(&yOrN)
 		if err != nil {
+			cmd.Printf("Received invalid input: %s, abort changefeed %s\n", err.Error(), command)
```
Comment (nongfushanquan) [inline pkg/cmd/cli/cli_changefeed_helper.go:44]: The main problem in the issue is the unreadable error msg , such as the table name?

**Review by asddongmen — APPROVED** [review]

File: pkg/cmd/cli/cli_changefeed_helper.go (hunk 2 above)
Comment (hi-rustin) [inline pkg/cmd/cli/cli_changefeed_helper.go:44]:
```suggestion
			cmd.Printf("Received invalid input: %s, abort changefeed %s.\n", err.Error(), command)
```

File: pkg/cmd/cli/cli_changefeed_helper.go [hunk 3]
```diff
@@ -63,6 +64,7 @@ func confirmOverwriteCheckpointTs(
 	var yOrN string
 	_, err := fmt.Scan(&yOrN)
 	if err != nil {
+		cmd.Printf("Received invalid input: %s, abort changefeed resume\n", err.Error())
```
Comment (hi-rustin) [inline pkg/cmd/cli/cli_changefeed_helper.go:67]:
```suggestion
		cmd.Printf("Received invalid input: %s, abort changefeed resume.\n", err.Error())
```

File: pkg/cmd/cli/cli_unsafe.go [hunk 4]
```diff
@@ -43,6 +43,7 @@ func (o *unsafeCommonOptions) confirmMetaDelete(cmd *cobra.Command) error {
 	var yOrN string
```
Comment (hi-rustin) [inline pkg/cmd/cli/cli_unsafe.go:43]: Can we wrap it? Wrap a confirmation function?

**Review by hi-rustin — COMMENTED** [review]
rest LGTM

**Review by amyangfei — APPROVED** [review]

**Comment by CharlesCheung96** [comment]
/needs-cherry-pick-release-6.1
