### PR TITLE
Optimsitic: refine optimstic create/drop table

### LINKED ISSUE #3823: fatal error: concurrent map read and map write in Optimistic Sharding DDL
### What did you do?
```
fatal error: concurrent map read and map write

goroutine 37885 [running]:
runtime.throw(0x24027ce, 0x21)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc08f804f40 sp=0xc08f804f10 pc=0x438592
runtime.mapaccess2(0x20897e0, 0xc09ce4e2d0, 0xc04d162d40, 0xc04d162d40, 0xc04100c97f)
	/usr/local/go/src/runtime/map.go:469 +0x255 fp=0xc08f804f80 sp=0xc08f804f40 pc=0x40f915
reflect.mapaccess(0x20897e0, 0xc09ce4e2d0, 0xc04d162d40, 0x23e208f)
	/usr/local/go/src/runtime/map.go:1318 +0x3f fp=0xc08f804fb8 sp=0xc08f804f80 pc=0x46bb3f
reflect.Value.MapIndex(0x20897e0, 0xc09ce4e2d0, 0x15, 0x1ffd7a0, 0xc04d162d40, 0x98, 0x20898a0, 0xc09ce4f710, 0x15)
	/usr/local/go/src/reflect/value.go:1189 +0x16e fp=0xc08f805030 sp=0xc08f804fb8 pc=0x4c8d0e
encoding/json.mapEncoder.encode(0xc0722c59c0, 0xc06341c100, 0x20897e0, 0xc09ce4e2d0, 0x15, 0x100)
	/usr/local/go/src/encoding/json/encode.go:813 +0x317 fp=0xc08f8051d8 sp=0xc08f805030 pc=0x52f237
encoding/json.mapEncoder.encode-fm(0xc06341c100, 0x20897e0, 0xc09ce4e2d0, 0x15, 0xc04d160100)
	/usr/local/go/src/encoding/json/encode.go:779 +0x6d fp=0xc08f805218 sp=0xc08f8051d8 pc=0x53b9ed
encoding/json.mapEncoder.encode(0xc0722c59e0, 0xc06341c100, 0x2089780, 0xc09764a560, 0x95, 0x100)
	/usr/local/go/src/encoding/json/encode.go:813 +0x366 fp=0xc08f8053c0 sp=0xc08f805218 pc=0x52f286
encoding/json.mapEncoder.encode-fm(0xc06341c100, 0x2089780, 0xc09764a560, 0x95, 0x100)
	/usr/local/go/src/encoding/json/encode.go:779 +0x6d fp=0xc08f805400 sp=0xc08f8053c0 pc=0x53b9ed
encoding/json.structEncoder.encode(0xc0722e2900, 0x3, 0x4, 0xc0722ff020, 0xc06341c100, 0x221e7c0, 0xc09764a540, 0x99, 0x2210100)
	/usr/local/go/src/encoding/json/encode.go:761 +0x2ab fp=0xc08f805498 sp=0xc08f805400 pc=0x52eccb
encoding/json.structEncoder.encode-fm(0xc06341c100, 0x221e7c0, 0xc09764a540, 0x99, 0x3e10100)
	/usr/local/go/src/encoding/json/encode.go:732 +0x8c fp=0xc08f8054f0 sp=0xc08f805498 pc=0x53b94c
encoding/json.(*encodeState).reflectValue(0xc06341c100, 0x221e7c0, 0xc09764a540, 0x99, 0xc08f800100)
	/usr/local/go/src/encoding/json/encode.go:360 +0x82 fp=0xc08f805528 sp=0xc08f8054f0 pc=0x52c342
encoding/json.(*encodeState).marshal(0xc06341c100, 0x221e7c0, 0xc09764a540, 0x100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:332 +0xf9 fp=0xc08f805588 sp=0xc08f805528 pc=0x52bf39
encoding/json.Marshal(0x221e7c0, 0xc09764a540, 0x221e7c0, 0xc09764a540, 0x2cb93c8, 0x76, 0x2cb93c8)
	/usr/local/go/src/encoding/json/encode.go:161 +0x52 fp=0xc08f805600 sp=0xc08f805588 pc=0x52b3b2
github.com/pingcap/dm/pkg/shardddl/optimism.SourceTables.toJSON(...)
	/home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.7/go/src/github.com/pingcap/dm/pkg/shardddl/optimism/table.go:100
github.com/pingcap/dm/pkg/shardddl/optimism.SourceTables.String(0xc080bdd698, 0x8, 0xc06a95ce20, 0x1a, 0xc09ce4e2a0, 0x0, 0x4565f9, 0x3743fb8)
	/home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.7/go/src/github.com/pingcap/dm/pkg/shardddl/optimism/table.go:94 +0x77 fp=0xc08f805678 sp=0xc08f805600 pc=0x1e8ed97
github.com/pingcap/dm/pkg/shardddl/optimism.(*SourceTables).String(0xc09764a510, 0x221e7c0, 0xc09764a510)
	<autogenerated>:1 +0x77 fp=0xc08f8056f8 sp=0xc08f805678 pc=0x1e929f7
go.uber.org/zap/zapcore.encodeStringer(0x23c9577, 0xd, 0x221e7c0, 0xc09764a510, 0x2799658, 0xc0808d89c0, 0x0, 0x0)
	/nfs/cache/mod/go.uber.org/zap@v1.19.0/zapcore/field.go:231 +0xf0 fp=0xc08f805788 sp=0xc08f8056f8 pc=0x550b30
go.uber.org/zap/zapcore.Field.AddTo(0x23c9577, 0xd, 0x19, 0x0, 0x0, 0x0, 0x221e7c0, 0xc09764a510, 0x2799658, 0xc0808d89c0)
	/nfs/cache/mod/go.uber.org/zap@v1.19.0/zapcore/field.go:174 +0xcab fp=0xc08f805860 sp=0xc08f805788 pc=0x55038b
github.com/pingcap/log.(*textEncoder).addFields(0xc0808d89c0, 0xc03b7eb380, 0x3, 0x3)
	/nfs/cache/mod/github.com/pingcap/log@v0.0.0-20210906054005-afc726e70354/zap_text_encoder.go:640 +0x152 fp=0xc08f805928 sp=0xc08f805860 pc=0x87a052
github.com/pingcap/log.(*textEncoder).EncodeEntry(0xc0003d91c0, 0x0, 0xc0648abc03c0e50c, 0x8e27e925ce854, 0x3e17740, 0x0, 0x0, 0x23df159, 0x15, 0x1, ...)
	/nfs/cache/mod/github.com/pingcap/log@v0.0.0-20210906054005-afc726e70354/zap_text_encoder.go:466 +0x5d6 fp=0xc08f805a88 sp=0xc08f805928 pc=0x877bb6
github.com/pingcap/log.(*textIOCore).Write(0xc0004d27e0, 0x0, 0xc0648abc03c0e50c, 0x8e27e925ce854, 0x3e17740, 0x0, 0x0, 0x23df159, 0x15, 0x1, ...)
	/nfs/cache/mod/github.com/pingcap/log@v0.0.0-20210906054005-afc726e70354/zap_text_core.go:64 +0xa9 fp=0xc08f805b78 sp=0xc08f805a88 pc=0x873a29
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc08945c000, 0xc03b7eb380, 0x3, 0x3)
	/nfs/cache/mod/go.uber.org/zap@v1.19.0/zapcore/entry.go:220 +0x12d fp=0xc08f805d20 sp=0xc08f805b78 pc=0x54e7ed
go.uber.org/zap.(*Logger).Info(0xc00040b740, 0x23df159, 0x15, 0xc03b7eb380, 0x3, 0x3)
	/nfs/cache/mod/go.uber.org/zap@v1.19.0/logger.go:192 +0x85 fp=0xc08f805d58 sp=0xc08f805d20 pc=0x76a185
github.com/pingcap/dm/dm/master/shardddl.(*Optimist).handleSourceTables(0xc00081b090, 0x276a310, 0xc09c12f780, 0xc09c138660)
	/home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.7/go/src/github.com/pingcap/dm/dm/master/shardddl/optimist.go:508 +0x75 fp=0xc08f805f70 sp=0xc08f805d58 pc=0x1e98f75
github.com/pingcap/dm/dm/master/shardddl.(*Optimist).watchSourceInfoOperation.func3(0xc08527c320, 0xc00081b090, 0x276a310, 0xc09c12f780, 0xc09c138660)
	/home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.7/go/src/github.com/pingcap/dm/dm/master/shardddl/optimist.go:456 +0x75 fp=0xc08f805fb8 sp=0xc08f805f70 pc=0x1eaaf15
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc08f805fc0 sp=0xc08f805fb8 pc=0x472301
created by github.com/pingcap/dm/dm/master/shardddl.(*Optimist).watchSourceInfoOperation
	/home/jenkins/agent/workspace/build_dm_multi_branch_v2.0.7/go/src/github.com/pingcap/dm/dm/master/shardddl/optimist.go:454 +0x1fb
```
### What did you expect to see?

no panic

### What did you see instead?

panic

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
v2.0.7
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: close #3823

### What is changed and how it works?
- worker flush table info, put source tables when create/drop table
- master watch source tables and add/remove table for lock

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
`None`.
```

### CODE REVIEW

File: dm/pkg/shardddl/optimism/keeper.go [hunk 1]
```diff
@@ -216,26 +216,39 @@ func (tk *TableKeeper) Init(stm map[string]map[string]SourceTables) {
...
 	}
 
+	// update source tables
+	// this often happen when create/drop table
 	if _, ok := tk.tables[st.Task]; !ok {
 		tk.tables[st.Task] = make(map[string]SourceTables)
 	}
+	if _, ok := tk.tables[st.Task][st.Source]; ok {
+		oldST = tk.tables[st.Task][st.Source]
+	}
```
Comment (lichunzhu) [inline dm/pkg/shardddl/optimism/keeper.go:246]: Nit
```suggestion
	oldST = tk.tables[st.Task][st.Source]
···

File: dm/pkg/shardddl/optimism/table.go [hunk 2]
```diff
@@ -152,6 +152,54 @@ func (st *SourceTables) RemoveTable(upSchema, upTable, downSchema, downTable str
...
+func DiffSourceTables(lhs, rhs SourceTables) (map[RouteTable]struct{}, map[RouteTable]struct{}) {
+	lhsTables := lhs.toRouteTable()
+	rhsTables := rhs.toRouteTable()
+
+	droppedTables := make(map[RouteTable]struct{})
+	addedTables := make(map[RouteTable]struct{})
+	for table := range lhsTables {
+		if _, ok := rhsTables[table]; !ok {
+			droppedTables[table] = struct{}{}
+		}
```
Comment (lichunzhu) [inline dm/pkg/shardddl/optimism/table.go:192]: Nit: Can we `delete(rhsTables,table)` we ok is true to save some time?

File: dm/pkg/shardddl/optimism/lock.go [hunk 3]
```diff
@@ -288,20 +288,33 @@ func (l *Lock) TrySync(info Info, tts []TargetTable) (newDDLs []string, cols []s
...
+	}
+
+	// delete drop columns
+	dropColumns := make([]string, 0)
+	for col, sourceColumns := range l.columns {
+		if schemaColumns, ok := sourceColumns[source]; ok {
+			if tableColumn, ok := schemaColumns[schema]; ok {
+				if _, ok := tableColumn[table]; ok {
+					dropColumns = append(dropColumns, col)
+					delete(tableColumn, table)
```
Comment (lichunzhu) [inline dm/pkg/shardddl/optimism/lock.go:314]: Nit: Do we need to delete upper map when `len(tableColumn) == 0`?

File: dm/pkg/shardddl/optimism/lock.go [hunk 4]
```diff
@@ -520,42 +533,50 @@ func (l *Lock) tryRevertDone(source, schema, table string) {
 	l.done[source][schema][table] = false
 }
 
+func (l *Lock) AddTable(source, schema, table string, needLock bool) {
```
Comment (lichunzhu) [inline dm/pkg/shardddl/optimism/lock.go:536]: need a comment

File: dm/dm/master/shardddl/optimist.go [hunk 5]
```diff
@@ -593,9 +593,30 @@ func (o *Optimist) handleSourceTables(ctx context.Context, sourceCh <-chan optim
...
+			}
+			// handle drop table
+			for routeTable := range droppedTable {
+				lock := o.lk.FindLock(utils.GenDDLLockID(st.Task, routeTable.DownSchema, routeTable.DownTable))
+				if lock != nil {
+					cols := lock.TryRemoveTable(st.Source, routeTable.UpSchema, routeTable.UpTable)
+					if !lock.HasTables() {
+						o.lk.RemoveLock(lock.ID)
+					}
+					_, err := optimism.DeleteInfosOperationsTablesByTable(o.cli, st.Task, st.Source, routeTable.UpSchema, routeTable.UpTable, lock.ID, cols)
```
Comment (lichunzhu) [inline dm/dm/master/shardddl/optimist.go:613]: Not important: do we need to batch these delete operations and run them out of `o.mu.Lock` part? I'm afraid this will cause this lock is held for a long time.

File: dm/syncer/optimist.go [hunk 6]
```diff
@@ -144,18 +144,20 @@ func (s *Syncer) handleQueryEventOptimistic(qec *queryEventContext) error {
 	case *ast.DropDatabaseStmt:
 		skipOp = true
 	case *ast.CreateTableStmt:
-		info.TableInfoBefore = tiAfter // for `CREATE TABLE`, we use tiAfter as tiBefore.
-		rev, err = s.optimist.PutInfoAddTable(info)
-		if err != nil {
+		// need to execute the DDL to the downstream, but do not do the coordination with DM-master.
+		op.DDLs = qec.needHandleDDLs
+		skipOp = true
```
Comment (lichunzhu) [inline dm/syncer/optimist.go:149]: What if this table's table structure is different from other shard tables?

**Review by lichunzhu — COMMENTED** [review]
https://github.com/GMHDBJD/ticdc/blob/refineOptimsticCreateTable/dm/dm/master/shardddl/optimist_test.go#L488
Should we remove this function and use the new method in UTs?
Will review later

File: dm/dm/master/shardddl/optimist.go (hunk 5 above)
Comment (GMHDBJD) [reply dm/dm/master/shardddl/optimist.go:613]: I think it's ok because this line usually run when drop a table. For stop-task, the meta data in etcd already delete at https://github.com/pingcap/tiflow/blob/21dedc45c4022be849b575ef12b4fdcd089963ba/dm/dm/master/server.go#L642, hope it will not cause much time. I will add a todo.

File: dm/syncer/optimist.go (hunk 6 above)
Comment (GMHDBJD) [reply dm/syncer/optimist.go:149]: if the new table is smaller than other shard tables, the task will run well. Here is the case

Comment (lichunzhu) [reply dm/syncer/optimist.go:149]: What if there is a conflict?

Comment (GMHDBJD) [reply dm/syncer/optimist.go:149]: Conflict is not support. Even if we put info for that 'create table statement', the normal table is still a conflict table, just like we create a task with conflict tables.

**Comment by GMHDBJD** [comment]
cc @lichunzhu

**Review by lichunzhu — APPROVED** [review]
LGTM

File: dm/dm/master/shardddl/optimist.go [hunk 7]
```diff
@@ -595,9 +595,30 @@ func (o *Optimist) handleSourceTables(ctx context.Context, sourceCh <-chan optim
...
 				return
 			}
-			updated := o.tk.Update(st)
-			o.logger.Info("receive source tables", zap.Stringer("source tables", st),
-				zap.Bool("is deleted", st.IsDeleted), zap.Bool("updated", updated))
+			o.mu.Lock()
+			addedTable, droppedTable := o.tk.Update(st)
+			// handle create table
+			for routeTable := range addedTable {
+				lock := o.lk.FindLock(utils.GenDDLLockID(st.Task, routeTable.DownSchema, routeTable.DownTable))
```
Comment (lance6716) [inline dm/dm/master/shardddl/optimist.go:602]: do we need to create a lock for it when not found a lock?

File: dm/pkg/shardddl/optimism/keeper.go [hunk 8]
```diff
@@ -216,26 +216,37 @@ func (tk *TableKeeper) Init(stm map[string]map[string]SourceTables) {
 
 // Update adds/updates tables into the keeper or removes tables from the keeper.
 // it returns whether added/updated or removed.
```
Comment (lance6716) [inline dm/pkg/shardddl/optimism/keeper.go:218]: should update function comment

**Review by lance6716 — COMMENTED** [review]
will review later

File: dm/dm/master/shardddl/optimist.go (hunk 7 above)
Comment (GMHDBJD) [reply dm/dm/master/shardddl/optimist.go:602]: no need, we only create a lock when receive ddl which changed table schema.

File: dm/dm/master/shardddl/optimist.go [hunk 9]
```diff
@@ -595,9 +595,30 @@ func (o *Optimist) handleSourceTables(ctx context.Context, sourceCh <-chan optim
...
+				if lock != nil {
+					lock.AddTable(st.Source, routeTable.UpSchema, routeTable.UpTable, true)
+				}
+			}
+			// handle drop table
+			for routeTable := range droppedTable {
+				lock := o.lk.FindLock(utils.GenDDLLockID(st.Task, routeTable.DownSchema, routeTable.DownTable))
+				if lock != nil {
+					cols := lock.TryRemoveTable(st.Source, routeTable.UpSchema, routeTable.UpTable)
```
[the remark this answers is not in the document]
Comment (GMHDBJD) [reply dm/dm/master/shardddl/optimist.go:611]: We cannot handle it. e.g. 2 tables
table1 drop column a
drop table2
Now actually we should drop column a in Downstream, but we can't now.

**Review by lance6716 — APPROVED** [review]
