### PR TITLE
precheck(dm): fix MySQL 8.0 SHOW GRANTS with role

### LINKED ISSUE #6448: mysql 8.0 incompatibility - show grants using
### What did you do?

Sync data from Aurora 8.0.23 to TiDB Cloud using DM. And failed to create the task. 

### What did you expect to see?

Succeed to sync data from Aurora to TiDB Cloud.

### What did you see instead?

    detail: {                                                                                                                                                           [23/4699]
                "results": [                                                                                                                                                         
                        {                                                                                                                                                            
                                "id": 0,                                                                                                                                             
                                "name": "mysql_version",                                                                                                                             
                                "desc": "check whether mysql version is satisfied",                                                                                                  
                                "state": "warn",                                                                                                                                     
                                "errors": [                                                                                                                                          
                                        {                                                                                                                                            
                                                "severity": "warn",                                                                                                                  
                                                "short_error": "version suggested less than 8.0.0 but got 8.0.23"                                                                    
                                        }                                                                                                                                            
                                ],                                                                                                                                                   
                                "extra": "address of db instance - ar3vyl3zlmk15x.cxmxisy1o2a2.us-east-1.rds.amazonaws.com:3306"                                                     
                        },                                                                                                                                                           
                        {                                                                                                                                                            
                                "id": 6,                                                                                                                                             
                                "name": "source db replication privilege checker",                                                                                                   
                                "desc": "check replication privileges of source DB",                                                                                                 
                                "state": "fail",                                                                                                                                     
                                "errors": [                                                                                                                                          
                                        {                                                                                                                                            
                                                "severity": "fail",                                                                                                                  
                                                "short_error": "Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for 
the right syntax to use near 'USING `rds_superuser_role`@`%`' at line 1"                                                                                                             
                                        }                                                 
                                ],                                                        
                                "extra": "address of db instance - ar3vyl3zlmk15x.cxmxisy1o2a2.us-east-1.rds.amazonaws.com:3306"
                        },                                                                                                                                                           
                        {                                                                                                                                                            
                                "id": 1,                                                                                                                                             
                                "name": "source db dump privilege checker",                                                                                                          
                                "desc": "check dump privileges of source DB",
                                "state": "fail",                                          
                                "errors": [                                                                                                                                          
                                        {                                                                                                                                            
                                                "severity": "fail",                                                                                                                  
                                                "short_error": "Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for 
the right syntax to use near 'USING `rds_superuser_role`@`%`' at line 1"                                                                                                             
                                        }                                                 
                                ],                                                        
                                "extra": "address of db instance - ar3vyl3zlmk15x.cxmxisy1o2a2.us-east-1.rds.amazonaws.com:3306"
                        }                                                                 
                ],                                                                        
                "summary": {                                                                                                                                                         
                        "passed": false,                                                  
                        "total": 10,                                                      
                        "successful": 7,                                                  
                        "failed": 2,                                                                                                                                                 
                        "warning": 1
                }
        }"


### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
tiup dmctl -V
tiup is checking updates for component dmctl ...
Starting component `dmctl`: /home/admin/.tiup/components/dmctl/v6.1.0/dmctl/dmctl -V
Release Version: v6.1.0
Git Commit Hash: 9f5e3cea2fae0a3dce6cc5ca79e3bcd654b8aa99
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time: 2022-06-07 11:55:24
Go Version: go version go1.18.2 linux/amd64
```
Upstream MySQL/MariaDB server version:
```console
8.0.23
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
MySQL [test]> SELECT tidb_version();`
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.4.0-20220421
Edition: Enterprise
Git Commit Hash: 5c597dc4f7017eab7935705a347c96c097711ce6
Git Branch: heads/refs/tags/v5.4.0-20220421
UTC Build Time: 2022-04-21 10:42:03
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)

```
How did you deploy DM: tiup or manually?
```console
tiup dm deploy datasync v6.1.0 /opt/tidb/dm-cluster.yml
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### LINKED ISSUE #6506: after TiDB introduce concurrent DDL, creating `mysql` database is not written to history DDL
### What did you do?

```sql
MySQL [(none)]> admin show ddl jobs 1000;
```

### What did you expect to see?

```
MySQL [(none)]> admin show ddl jobs 1000;
+--------+---------+----------------------------------+---------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
| JOB_ID | DB_NAME | TABLE_NAME                       | JOB_TYPE      | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE  |
+--------+---------+----------------------------------+---------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
...
|      6 | mysql   | user                             | create table  | public       |         3 |        5 |         0 | 2022-07-28 15:20:50 | 2022-07-28 15:20:50 | 2022-07-28 15:20:50 | synced |
|      4 | mysql   |                                  | create schema | public       |         3 |        0 |         0 | 2022-07-28 15:20:50 | 2022-07-28 15:20:50 | 2022-07-28 15:20:50 | synced |
|      2 | test    |                                  | create schema | public       |         1 |        0 |         0 | 2022-07-28 15:20:50 | 2022-07-28 15:20:50 | 2022-07-28 15:20:50 | synced |
+--------+---------+----------------------------------+---------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
34 rows in set (0.014 sec)
```

### What did you see instead?

```
MySQL [(none)]> admin show ddl jobs 1000;
+--------+---------+----------------------------------+---------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
| JOB_ID | DB_NAME | TABLE_NAME                       | JOB_TYPE      | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE  |
+--------+---------+----------------------------------+---------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
...
|      5 | mysql   | user                             | create table  | public       |         1 |        4 |         0 | 2022-07-28 15:18:18 | 2022-07-28 15:18:18 | 2022-07-28 15:18:18 | synced |
|      3 | test    |                                  | create schema | public       |         2 |        0 |         0 | 2022-07-28 15:18:18 | 2022-07-28 15:18:18 | 2022-07-28 15:18:18 | synced |
+--------+---------+----------------------------------+---------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
33 rows in set (0.018 sec)
```

So CDC's logic about history DDL is not compatible.

### Versions of the cluster

Release Version: v6.2.0-alpha-453-g2a9350923
Edition: Community
Git Commit Hash: 2a935092309bb631a5453950f4e5a3f5e0d729a1
Git Branch: HEAD
UTC Build Time: 2022-07-21 07:08:35
GoVersion: go1.18.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: close #6448 close #6506

### What is changed and how it works?

introduce https://github.com/pingcap/tidb/pull/36565 to fix the issue , and also https://github.com/pingcap/tidb/pull/36576 by the way

#### Tests 

 - Integration test

### Release note 

```release-note
Improve compatibility for MySQL 8.0 upstream
```

### CODE REVIEW

**Comment by lance6716** [comment]
waiting https://github.com/pingcap/tidb/pull/36604

**Review by lichunzhu — APPROVED** [review]
LGTM

**Review by buchuitoudegou — APPROVED** [review]
lgtm. But I don't really understand the changes under cdc/entry. Do they also relate to the compatibility issue of DM?

**Comment by lance6716** [comment]
/hold

wait CDC review

File: cdc/entry/schema/snapshot.go [hunk 1]
```diff
@@ -194,9 +200,36 @@ func NewEmptySnapshot(forceReplicate bool) *Snapshot {
 		forceReplicate:   forceReplicate,
 		currentTs:        0,
 	}
+
 	return &Snapshot{inner: inner, rwlock: new(sync.RWMutex)}
 }
 
+// InitConcurrentDDLTables imitate the creating table logic for concurrent DDL.
```
Comment (liuzix) [inline cdc/entry/schema/snapshot.go:207]:
```suggestion
// InitConcurrentDDLTables imitates the creating table logic for concurrent DDL.
```

File: cdc/entry/schema/snapshot.go [hunk 2]
```diff
@@ -194,9 +200,36 @@ func NewEmptySnapshot(forceReplicate bool) *Snapshot {
...
+// since v6.2.0, tables of concurrent DDL will be directly written to meta
```
Comment (liuzix) [inline cdc/entry/schema/snapshot.go:208]:
```suggestion
// Since v6.2.0, tables of concurrent DDL will be directly written to meta
```

Could you add more context? For example, where is "meta" located?

File: cdc/entry/schema/snapshot.go [hunk 3]
```diff
@@ -194,9 +200,36 @@ func NewEmptySnapshot(forceReplicate bool) *Snapshot {
...
+// without written to history DDL jobs.
```
Comment (liuzix) [inline cdc/entry/schema/snapshot.go:209]:
```suggestion
// without being written to history DDL jobs.
```

File: cdc/entry/schema/snapshot.go [hunk 4]
```diff
@@ -194,9 +200,36 @@ func NewEmptySnapshot(forceReplicate bool) *Snapshot {
...
+func (s *Snapshot) InitConcurrentDDLTables() {
+	mysqlDBInfo := &timodel.DBInfo{
+		ID:      1,
```
Comment (liuzix) [inline cdc/entry/schema/snapshot.go:212]: Could you add a const for `1`?

File: cdc/entry/schema/snapshot.go [hunk 5]
```diff
@@ -194,9 +200,36 @@ func NewEmptySnapshot(forceReplicate bool) *Snapshot {
...
+		Name:    timodel.NewCIStr(mysql.SystemDB),
+		Charset: mysql.UTF8MB4Charset,
+		Collate: mysql.UTF8MB4DefaultCollation,
+		State:   timodel.StatePublic,
+	}
+	mockTS := uint64(1)
```
Comment (liuzix) [inline cdc/entry/schema/snapshot.go:218]: Please comment on the purpose and the value of `mockTS`. Also, I think `dummyTs` can be a better name? Also, can you make it a const?

Comment (lance6716) [reply cdc/entry/schema/snapshot.go]: https://github.com/pingcap/tiflow/pull/6485/commits/700b3a98505876cc05f56d332277ff011880945a

File: cdc/entry/schema/snapshot.go [hunk 6]
```diff
@@ -194,9 +200,43 @@ func NewEmptySnapshot(forceReplicate bool) *Snapshot {
...
+const (
+	mysqlDBID = int64(1)
+	dummyTS   = uint64(1)
+)
+
+// InitConcurrentDDLTables imitates the creating table logic for concurrent DDL.
+// Since v6.2.0, tables of concurrent DDL will be directly written as meta KV in
+// TiKV, without being written to history DDL jobs. So the Snapshot which is not
+// build from meta needs this method to handle history DDL.
+func (s *Snapshot) InitConcurrentDDLTables() {
```
Comment (hi-rustin) [inline cdc/entry/schema/snapshot.go:217]: Should we add a test for this func? Or any tests can cover this bug?

Comment (lance6716) [reply cdc/entry/schema/snapshot.go:217]: old unit tests will fail

**Review by nongfushanquan — APPROVED** [review]

**Comment by lance6716** [comment]
/hold

seems many_tables case always fail

**Comment by lance6716** [comment]
/unhold

/run-dm-integration-test

CI too slow so creating tables from dump files timeout

**Comment by lance6716** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/8452/pipeline/204/

CI passed

/merge

**Comment by lance6716** [comment]
source bound is not stable，will update it later
