### PR TITLE
codec(ticdc): fix some avro encoding bugs

### LINKED ISSUE #4420: Table column type bigint is converted to AVRO decimal logical type but should be converted to long type
### What did you do?

1. Create a table called `employees`. Its `id` column is `bigint`.
```
CREATE TABLE employees (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  employee_name char(50) NOT NULL,
  PRIMARY KEY (id)
);
```

2. Create TiCDC changefeed.
```
tiup cdc cli changefeed create \
--pd="http://localhost:2379" \
--sink-uri="kafka://localhost:9092/test?protocol=avro&partition-num=1&replication-factor=3" \
--config=./configs/test.toml \
--opts "registry=http://localhost:8081" \
--changefeed-id=test
```

3. Insert a row to the table.
```
INSERT INTO employees values (1, 'test1');
```

4. Check Kafka Schedule Registry's schema.
```
...
{
      "name" : "id",
      "type" : {
        "type" : "bytes",
        "logicalType" : "decimal",
        "precision" : 8,
        "scale" : 0
      }
}
...
```

### What did you expect to see?

The AVRO type in Kafka Schema Registry for the `id` column is `decimal` AVRO logical type.

### What did you see instead?

The AVRO type in Kafka Schema Registry for the `id` column should be `long` AVRO type instead.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
Release Version: v5.3.0
Edition: Community
Git Commit Hash: 4a1b2e9fe5b5afb1068c56de47adb07098d768d6
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-24 13:31:41
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

TiCDC version (execute `cdc version`):

```console
5.3.0
```

### LINKED ISSUE #4453: Table column type enum is converted to AVRO decimal logical type but should be converted to Avro string type
### What did you do?

1. Create a table called `employees`. Its `employee_type` column is `enum`.
```
CREATE TABLE employees (
  id int(20) unsigned NOT NULL AUTO_INCREMENT,
  employee_type enum('a','b','c','d','e') COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (id)
);
```

2. Create TiCDC changefeed
```
tiup cdc cli changefeed create \
--pd="http://localhost:2379" \
--sink-uri="kafka://localhost:9092/test?protocol=avro&partition-num=1&replication-factor=3" \
--config=./configs/test.toml \
--opts "registry=http://localhost:8081" \
--changefeed-id=test
```

3. Insert a row
```
INSERT INTO employees values (1, 'b');
```

4. Check Kafka schema registry's schema.
```
...
{
      "name" : "employee_type",
      "type" : {
        "type" : "bytes",
        "logicalType" : "decimal",
        "precision" : 8,
        "scale" : 0
      }
}
...
```

### What did you expect to see?

The avro type of the `employee` field should be `string`

### What did you see instead?

The avro type of the `employee` field is `decimal` logical type

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
Release Version: v5.3.0
Edition: Community
Git Commit Hash: 4a1b2e9fe5b5afb1068c56de47adb07098d768d6
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-24 13:31:41
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

TiCDC version (execute `cdc version`):

```console
5.3.0
```

### LINKED ISSUE #4454: Table column type longtext is converted to AVRO bytes type but should be converted to bytes string type
### What did you do?

1. Create a table called employees. Its `description` column is enum.
```
CREATE TABLE employees (
  id int(20) unsigned NOT NULL AUTO_INCREMENT,
  description longtext COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (id)
);
```

2. Create TiCDC changefeed
```
tiup cdc cli changefeed create \
--pd="http://localhost:2379" \
--sink-uri="kafka://localhost:9092/test?protocol=avro&partition-num=1&replication-factor=3" \
--config=./configs/test.toml \
--opts "registry=http://localhost:8081" \
--changefeed-id=test
```

3. Insert a row
```
INSERT INTO employees values (1, 'test');
```

4. Check Kafka schema registry's schema.
```
...
{
    "name" : "description",
    "type" : [ "null", "bytes" ],
    "default" : null
  }
...
```

### What did you expect to see?

The avro type of the `description` field should be `string`.

### What did you see instead?

The avro type of the `description` field is `bytes`.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
Release Version: v5.3.0
Edition: Community
Git Commit Hash: 4a1b2e9fe5b5afb1068c56de47adb07098d768d6
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-24 13:31:41
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

TiCDC version (execute `cdc version`):

```console
5.3.0
```

### PR DESCRIPTION
**Pull request by zhangyangyu**
### What problem does this PR solve?

Issue Number: close #4454, close #4453, close #4420 

### What is changed and how it works?

To resolve the issues, we need to change the codec data mapping for enum/set(->string) and string/binary. This requires knowing table definition information when performing codec. So I carry the information in `RowChangedEvent`.

### Release note 

```release-note
Fix the wrong data mapping for avro codec of type Enum/Set and TinyText/MediumText/Text/LongText.
```

### CODE REVIEW

File: cdc/entry/mounter.go [hunk 1]
```diff
@@ -467,11 +467,11 @@ func formatColVal(datum types.Datum, tp byte) (
 		v := d.String()
 		return v, sizeOfString(v), "", nil
 	case mysql.TypeEnum:
-		v := datum.GetMysqlEnum().Value
+		v := datum.GetMysqlEnum()
```
Comment (overvenus) [inline cdc/entry/mounter.go:470]: Could you add some comments and unit tests?

File: cdc/sink/codec/avro.go [hunk 2]
```diff
@@ -300,7 +300,7 @@ func getAvroDataTypeFallback(v interface{}) (string, error) {
 var unsignedLongAvroType = avroLogicalType{
 	Type:        "bytes",
 	LogicalType: decimalType,
-	Precision:   8,
+	Precision:   64,
```
Comment (overvenus) [inline cdc/sink/codec/avro.go:303]: Could you add some reference about this change?

File: cdc/sink/codec/avro.go [hunk 3]
```diff
@@ -312,6 +312,9 @@ func getAvroDataTypeFromColumn(col *model.Column) (interface{}, error) {
 	case mysql.TypeDouble:
 		return "double", nil
 	case mysql.TypeVarchar, mysql.TypeString, mysql.TypeVarString:
+		if col.Flag.IsBinary() {
```
Comment (overvenus) [inline cdc/sink/codec/avro.go:315]: Could you add some unit tests?

Comment (overvenus) [reply cdc/sink/codec/avro.go:315]: In the future, maybe we need a flag to control the behavior? Like https://debezium.io/documentation/reference/connectors/mysql.html#mysql-property-binary-handling-mode

Cc @leoppro

**Review by overvenus — COMMENTED** [review]
Could you add tests to cover changes in avro.go? Thanks!

File: cdc/sink/codec/avro.go (hunk 2 above)
Comment (zhangyangyu) [reply cdc/sink/codec/avro.go:303]: Precision `8` is not enough to hold the whole longlong type, this is discussed in #4420 . Confluent schema registry use `64` as the default precision. https://github.com/confluentinc/schema-registry/blob/ba073ebb2bd655e0c0e316a54d355a65c48246e3/avro-data/src/main/java/io/confluent/connect/avro/AvroData.java#L279

**Comment by zhangyangyu** [comment]
/hold

working on more tests

File: cdc/model/sink.go [hunk 4]
```diff
@@ -253,7 +254,8 @@ type RowChangedEvent struct {
 
 	RowID int64 `json:"row-id" msg:"-"` // Deprecated. It is empty when the RowID comes from clustered index table.
 
-	Table *TableName `json:"table" msg:"table"`
+	Table    *TableName         `json:"table" msg:"table"`
+	ColInfos []rowcodec.ColInfo `json:"column-infos" msg:"-"`
```
Comment (lonng) [inline cdc/model/sink.go:258]: Please use `column_infos`.

Comment (zhangyangyu) [reply cdc/model/sink.go:258]: Sorry I don't really get it. Do you mean change the `json:"column-infos"` to `json:"column_infos"`? But all other fields use hyphens instead of underscores.

File: cdc/sink/codec/avro.go (hunk 2 above)
Comment (overvenus) [reply cdc/sink/codec/avro.go:297]: Got it! Could you add the comments in code?

**Review by overvenus — COMMENTED** [review]
Rest LGTM

File: cdc/model/sink.go (hunk 4 above)
Comment (liuzix) [reply cdc/model/sink.go:258]: `msg:"-"` seems to prevent the information from being persisted for Redo. Could you verify the compatibility of this change with Redo?

**Review by hi-rustin — COMMENTED** [review]
Do we need to cp it to 5.4, it looks like you only marked 5.3?

Please write a more detailed description of your PRs, how they work and why they were changed. Thanks!

Also, please add the release note.

File: cdc/model/sink.go (hunk 4 above)
Comment (zhangyangyu) [reply cdc/model/sink.go:258]: Redo only applies to mysql sink currently so does none of avro business. So prevent `ColInfos` from being persisted for Redo seems right. 

But I think the `ColInfos` is important and maybe in future Redo could support avro? Persist `ColInfos` seems bring no trouble. Upgrade is also safe since a `nil` `ColInfos` field is safe for other codecs. But as @liuzix tells me, it will make the redo log large. So I'd like to leave it unpersist in this pull request. 

Could you take a look @Ben1009 ?

Comment (ben1009) [reply cdc/model/sink.go:258]: lgtm for redo part

**Comment by zhangyangyu** [comment]
[]Do we need to cp it to 5.4, it looks like you only marked 5.3? 
[x]Please write a more detailed description of your PRs, how they work and why they were changed. Thanks! 
[x]Also, please add the release note.

All the three issues are marked `severity/moderate`. Usually we don't cherry-pick such PRs. Actually the behaviour affects all versions from v4.0. I will consult the PM.

File: cdc/sink/codec/canal_test.go [hunk 5]
```diff
@@ -451,12 +451,19 @@ var testColumnsTable = []*testColumnTuple{
...
+	canalEntryBuilder := NewCanalEntryBuilder()
 	for _, item := range testColumnsTable {
 		obtainedMySQLType := getMySQLType(item.column)
 		c.Assert(obtainedMySQLType, check.Equals, item.expectedMySQLType)
 
 		obtainedJavaSQLType, err := getJavaSQLType(item.column, obtainedMySQLType)
 		c.Assert(err, check.IsNil)
 		c.Assert(obtainedJavaSQLType, check.Equals, item.expectedJavaSQLType)
+
+		if !item.column.Flag.IsBinary() {
```
Comment (hi-rustin) [inline cdc/sink/codec/canal_test.go:463]: Why only for binary?

File: cdc/sink/codec/avro_test.go [hunk 6]
```diff
@@ -58,43 +59,98 @@ func (s *avroBatchEncoderSuite) TearDownSuite(c *check.C) {
...
+		{Name: "mystring6", Value: "Hello World", Type: mysql.TypeString},
+		{Name: "mystring7", Value: "Hello World", Type: mysql.TypeVarchar},
+		{Name: "myenum", Value: uint64(1), Type: mysql.TypeEnum},
+		{Name: "myset", Value: uint64(1), Type: mysql.TypeSet},
 		{Name: "ts", Value: time.Now().Format(types.TimeFSPFormat), Type: mysql.TypeTimestamp},
 		{Name: "myjson", Value: "{\"foo\": \"bar\"}", Type: mysql.TypeJSON},
-	}, time.Local)
+	}
+
+	colInfos := []rowcodec.ColInfo{
```
Comment (hi-rustin) [inline cdc/sink/codec/avro_test.go:110]: Maybe we can organize this data by structured arrays? Controlling correspondence by index may be difficult with large test data.

**Review by hi-rustin — COMMENTED** [review]
Thanks!

File: cdc/sink/codec/canal_test.go (hunk 5 above)
Comment (zhangyangyu) [reply cdc/sink/codec/canal_test.go:463]: For non-binary. Because the `expectedValue` is dummy for binary: https://github.com/pingcap/tiflow/blob/master/cdc/sink/codec/canal_test.go#L424.

File: cdc/sink/codec/avro_test.go (hunk 6 above)
Comment (zhangyangyu) [reply cdc/sink/codec/avro_test.go:110]: Yes. Actually using arrays restricts the usage pattern. We have to iterate the array(currently no problem). I tried to use the tp map, but it can't be used since the column `Id` is lost in `Column` struct. Add fields to `Column` will cause much code churn. Any suggestions?

**Comment by zhangyangyu** [comment]
It's confirmed that we could just follow our [conventional workflow](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/cherrypick-a-pr.html) and don't need to cherry-pick.

**Review by liuzix — APPROVED** [review]
