### PR TITLE
codec(ticdc): simple protocol set table id by using the physical table id

### LINKED ISSUE #11846: simple protocol set table id for the partition table is incorrect since does not use the physical table id
### What did you do?

```
create table test.t(a int primary key, b int) partition by range (a) (
		partition p0 values less than (10),
		partition p1 values less than (20),
		partition p2 values less than MAXVALUE);
insert into test.t values (1, 1);
insert into test.t values (11, 11);
insert into test.t values (21, 21);
```

### What did you expect to see?

3 row received, the table id should be set as the physical table id

### What did you see instead?

all events belongs to the different table partition, have the same table id 110, this is misleading, cannot tell which partition the row belongs to.
```
[2024/12/09 16:17:40.205 +08:00] [INFO] [encoder.go:144] ["simple encode ddl event"] [value="{\"version\":1,\"type\":\"CREATE\",\"sql\":\"CREATE TABLE `t` (`a` INT PRIMARY KEY,`b` INT) PARTITION BY RANGE (`a`) (PARTITION `p0` VALUES LESS THAN (10),PARTITION `p1` VALUES LESS THAN (20),PARTITION `p2` VALUES LESS THAN (MAXVALUE))\",\"commitTs\":454487509505933316,\"buildTs\":1733732260205,\"tableSchema\":{\"schema\":\"test\",\"table\":\"t\",\"tableID\":110,\"version\":454487509493088269,\"columns\":[{\"name\":\"a\",\"dataType\":{\"mysqlType\":\"int\",\"charset\":\"binary\",\"collate\":\"binary\",\"length\":11},\"nullable\":false,\"default\":null},{\"name\":\"b\",\"dataType\":{\"mysqlType\":\"int\",\"charset\":\"binary\",\"collate\":\"binary\",\"length\":11},\"nullable\":true,\"default\":null}],\"indexes\":[{\"name\":\"primary\",\"unique\":true,\"primary\":true,\"nullable\":false,\"columns\":[\"a\"]}]}}"]
[2024/12/09 16:17:53.319 +08:00] [INFO] [encoder.go:144] ["simple encode ddl event"] [value="{\"version\":1,\"type\":\"BOOTSTRAP\",\"commitTs\":0,\"buildTs\":1733732273319,\"tableSchema\":{\"schema\":\"test\",\"table\":\"t\",\"tableID\":110,\"version\":454487509493088269,\"columns\":[{\"name\":\"a\",\"dataType\":{\"mysqlType\":\"int\",\"charset\":\"binary\",\"collate\":\"binary\",\"length\":11},\"nullable\":false,\"default\":null},{\"name\":\"b\",\"dataType\":{\"mysqlType\":\"int\",\"charset\":\"binary\",\"collate\":\"binary\",\"length\":11},\"nullable\":true,\"default\":null}],\"indexes\":[{\"name\":\"primary\",\"unique\":true,\"primary\":true,\"nullable\":false,\"columns\":[\"a\"]}]}}"]
[2024/12/09 16:17:53.319 +08:00] [INFO] [encoder.go:46] ["simple encode row event"] [value="{\"version\":1,\"database\":\"test\",\"table\":\"t\",\"tableID\":110,\"type\":\"INSERT\",\"commitTs\":454487512756781060,\"buildTs\":1733732273319,\"schemaVersion\":454487509493088269,\"data\":{\"a\":\"1\",\"b\":\"1\"}}"]
[2024/12/09 16:17:58.317 +08:00] [INFO] [encoder.go:144] ["simple encode ddl event"] [value="{\"version\":1,\"type\":\"BOOTSTRAP\",\"commitTs\":0,\"buildTs\":1733732278317,\"tableSchema\":{\"schema\":\"test\",\"table\":\"t\",\"tableID\":110,\"version\":454487509493088269,\"columns\":[{\"name\":\"a\",\"dataType\":{\"mysqlType\":\"int\",\"charset\":\"binary\",\"collate\":\"binary\",\"length\":11},\"nullable\":false,\"default\":null},{\"name\":\"b\",\"dataType\":{\"mysqlType\":\"int\",\"charset\":\"binary\",\"collate\":\"binary\",\"length\":11},\"nullable\":true,\"default\":null}],\"indexes\":[{\"name\":\"primary\",\"unique\":true,\"primary\":true,\"nullable\":false,\"columns\":[\"a\"]}]}}"]
[2024/12/09 16:17:58.318 +08:00] [INFO] [encoder.go:46] ["simple encode row event"] [value="{\"version\":1,\"database\":\"test\",\"table\":\"t\",\"tableID\":110,\"type\":\"INSERT\",\"commitTs\":454487514225049602,\"buildTs\":1733732278318,\"schemaVersion\":454487509493088269,\"data\":{\"a\":\"11\",\"b\":\"11\"}}"]
[2024/12/09 16:18:03.317 +08:00] [INFO] [encoder.go:144] ["simple encode ddl event"] [value="{\"version\":1,\"type\":\"BOOTSTRAP\",\"commitTs\":0,\"buildTs\":1733732283317,\"tableSchema\":{\"schema\":\"test\",\"table\":\"t\",\"tableID\":110,\"version\":454487509493088269,\"columns\":[{\"name\":\"a\",\"dataType\":{\"mysqlType\":\"int\",\"charset\":\"binary\",\"collate\":\"binary\",\"length\":11},\"nullable\":false,\"default\":null},{\"name\":\"b\",\"dataType\":{\"mysqlType\":\"int\",\"charset\":\"binary\",\"collate\":\"binary\",\"length\":11},\"nullable\":true,\"default\":null}],\"indexes\":[{\"name\":\"primary\",\"unique\":true,\"primary\":true,\"nullable\":false,\"columns\":[\"a\"]}]}}"]
[2024/12/09 16:18:03.317 +08:00] [INFO] [encoder.go:46] ["simple encode row event"] [value="{\"version\":1,\"database\":\"test\",\"table\":\"t\",\"tableID\":110,\"type\":\"INSERT\",\"commitTs\":454487515430649861,\"buildTs\":1733732283317,\"schemaVersion\":454487509493088269,\"data\":{\"a\":\"21\",\"b\":\"21\"}}"]
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #11846 

### What is changed and how it works?

* when the simple protocol encode row events, set the table id by using the physical table id, instead of the logic id.
https://github.com/pingcap/tiflow/pull/11845/files#diff-7503164863112a4d454976ac5347d75a046c600a1ab3d5914a741eec262bba79R255
https://github.com/pingcap/tiflow/pull/11845/files#diff-ab57979355b5c3e268e38318362ab236cb5c8a3a27662d4aa79eeadb865da617R557

* add more unit test to cover that `open-protocol` table id is is set correctly.
* add unit test to cover that `canal-json` does not set the table id.

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
fix the row message table id not set by the physical table id cause the consumer don't known the table partition the row belongs to.
```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

File: cdc/entry/schema_test_helper.go [hunk 1]
```diff
@@ -166,13 +166,19 @@ func (s *SchemaTestHelper) DDL2Jobs(ddl string, jobCnt int) []*timodel.Job {
...
-func (s *SchemaTestHelper) DML2Event(dml string, schema, table string) *model.RowChangedEvent {
+func (s *SchemaTestHelper) DML2Event(dml string, schema, table string, partitionID ...string) *model.RowChangedEvent {
 	s.tk.MustExec(dml)
 
 	tableInfo, ok := s.schemaStorage.GetLastSnapshot().TableByName(schema, table)
 	require.True(s.t, ok)
 
-	key, value := s.getLastKeyValue(tableInfo.ID)
+	tableID := tableInfo.ID
+	partitionTableID := tableInfo.TableInfo.GetPartitionInfo().GetPartitionIDByName(partitionID[0])
```
Comment (wk989898) [inline cdc/entry/schema_test_helper.go]: It seems that only `partitionID[0]` will be used.

**Review by wk989898 — APPROVED** [review]

File: cdc/entry/schema_test_helper.go (hunk 1 above)
Comment (3AceShowHand) [reply cdc/entry/schema_test_helper.go]: yes, the caller pass in the partition.
