### PR TITLE
test(engine): fix integration error when check job status

### LINKED ISSUE #6994: test(engine): some integration tests fail to check job status
### What did you do?

make engine_integration_test

### What did you expect to see?

Run normally

### What did you see instead?

Run fail because original `status` has been changed to `state` for job state.

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

```console
master@4a97c45
```

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve?

Issue Number: close #6994 

### What is changed and how it works?
1. Add `sync_diff_inspector` check for `engine_integration_test`
2. Add `--try-num 100` to all integration tests to avoid easy fail  in local test
3.  Modify `.status` to `.state` when check job state

#### Tests 
 - Manual test (add detailed scripts or steps below)
make engine_integration_test

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

File: engine/test/integration_tests/dm_case_sensitive/run.sh [hunk 1]
```diff
@@ -31,7 +31,7 @@ function run() {
 	echo "job_id: $job_id"
 
 	# wait for job finished
-	exec_with_retry --count 30 "curl \"http://127.0.0.1:10245/api/v1/jobs/$job_id\" | tee /dev/stderr | jq -e '.status == \"Finished\"'"
+	exec_with_retry --count 30 "curl \"http://127.0.0.1:10245/api/v1/jobs/$job_id\" | tee /dev/stderr | jq -e '.state == \"Finished\"'"
```
Comment (lonng) [inline engine/test/integration_tests/dm_case_sensitive/run.sh:34]: Why did this test case pass before? I didn't find any changes related to changing `status` to `state`.

Comment (maxshuang) [reply engine/test/integration_tests/dm_case_sensitive/run.sh:34]: `dm_case_sensitive` and `dm_full_mode` tests is not enabled before because they are waiting for some feature like `job detail`.

Comment (maxshuang) [reply engine/test/integration_tests/dm_case_sensitive/run.sh:34]: They will enable these tests soon.

File: engine/test/integration_tests/dm_case_sensitive/run.sh [hunk 2]
```diff
@@ -12,9 +12,9 @@ TABLE_NUM=500
 
 function run() {
 	start_engine_cluster $CONFIG
-	wait_mysql_online.sh --port 3306
-	wait_mysql_online.sh --port 3307
-	wait_mysql_online.sh --port 4000
+	wait_mysql_online.sh --port 3306 --try-nums 100
```
Comment (amyangfei) [inline engine/test/integration_tests/dm_case_sensitive/run.sh:15]: Can make `100` as the default value of `try-nums` in `wait_mysql_online.sh`.

Comment (maxshuang) [reply engine/test/integration_tests/dm_case_sensitive/run.sh]: Fix it.

**Review by CharlesCheung96 — APPROVED** [review]

**Review by amyangfei — APPROVED** [review]
