### PR TITLE
worker(dm): fix Server Start/Close race

### LINKED ISSUE #5089: DM worker can't exit in CI
### Which jobs are flaking?

IT-ha_cases3_1

### Which test(s) are flaking?

DM IT

### Jenkins logs or GitHub Actions link

```
[2022-03-31T09:47:44.177Z] kill dm-worker2
[2022-03-31T09:47:44.177Z] kill: sending signal to 1344 failed: No such process
[2022-03-31T09:47:44.177Z] [Thu Mar 31 17:47:44 CST 2022] <<<<<< START DM-WORKER on port 8263, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/ha_cases3_1/conf/dm-worker2.toml >>>>>>
[2022-03-31T09:47:44.438Z] dmctl test cmd: "pause-task test"
[2022-03-31T09:47:47.719Z] got=3 expected=3
[2022-03-31T09:47:47.974Z] dmctl test cmd: "resume-task test"
[2022-03-31T09:47:47.974Z] got=3 expected=3
[2022-03-31T09:49:39.369Z] use sync_diff_inspector to check increment data
[2022-03-31T09:49:39.369Z] check diff successfully
[2022-03-31T09:49:39.369Z] [Thu Mar 31 17:49:29 CST 2022] <<<<<< finish test_isolate_master_and_worker >>>>>>
[2022-03-31T09:49:39.369Z] 5 dm-master alive
[2022-03-31T09:49:39.369Z] 6 dm-worker alive
[2022-03-31T09:49:39.369Z] 0 dm-syncer alive
...
[2022-03-31T09:50:11.859Z] wait process dm-worker.test exit...
[2022-03-31T09:50:12.794Z] wait process dm-worker.test exit...
[2022-03-31T09:50:13.728Z] wait process dm-worker.test exit...
[2022-03-31T09:50:14.661Z] wait process dm-worker.test exit...
[2022-03-31T09:50:14.661Z] process dm-worker.test didn't exit after 30 seconds
```

DM worker log : 
[worker.log](https://github.com/pingcap/tiflow/files/8394408/worker.log)

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### LINKED ISSUE #5836: data race and worker can't exit (?)
### Which jobs are flaking?

DM-IT

### Which test(s) are flaking?

ha_cases_1
test_kill_and_isolate_worker 

### Jenkins logs or GitHub Actions link

unstable integration tests

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/6677/pipeline

```
wait for port 18262 offline the 20-th time
```

```
 ==================

[2022-06-13T02:59:31.936Z] WARNING: DATA RACE

[2022-06-13T02:59:31.936Z] Write at 0x00c001429828 by goroutine 114:

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/dm/worker.(*Server).Start()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:109 +0x731

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/cmd/dm-worker.main()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/cmd/dm-worker/main.go:93 +0xa2e

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/cmd/dm-worker.TestRunMain.func3()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/cmd/dm-worker/main_test.go:66 +0x2b

[2022-06-13T02:59:31.936Z] 

[2022-06-13T02:59:31.936Z] Previous read at 0x00c001429828 by goroutine 64:

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/dm/worker.(*Server).Close()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:462 +0x66

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/cmd/dm-worker.main.func2()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/cmd/dm-worker/main.go:91 +0x1c7

[2022-06-13T02:59:31.936Z] 

[2022-06-13T02:59:31.936Z] Goroutine 114 (running) created at:

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/cmd/dm-worker.TestRunMain()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/cmd/dm-worker/main_test.go:65 +0x331

[2022-06-13T02:59:31.936Z]   testing.tRunner()

[2022-06-13T02:59:31.936Z]       /usr/local/go/src/testing/testing.go:1439 +0x213

[2022-06-13T02:59:31.936Z]   testing.(*T).Run.func1()

[2022-06-13T02:59:31.936Z]       /usr/local/go/src/testing/testing.go:1486 +0x47

[2022-06-13T02:59:31.936Z] 

[2022-06-13T02:59:31.936Z] Goroutine 64 (finished) created at:

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/cmd/dm-worker.main()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/cmd/dm-worker/main.go:88 +0xa11

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/cmd/dm-worker.TestRunMain.func3()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/cmd/dm-worker/main_test.go:66 +0x2b

[2022-06-13T02:59:31.936Z] ==================

[2022-06-13T02:59:31.936Z] ==================

[2022-06-13T02:59:31.936Z] WARNING: DATA RACE

[2022-06-13T02:59:31.936Z] Write at 0x00c0014297f8 by goroutine 114:

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/dm/worker.(*Server).startKeepAlive()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:230 +0xca

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/dm/worker.(*Server).Start()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:129 +0x866

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/cmd/dm-worker.main()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/cmd/dm-worker/main.go:93 +0xa2e

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/cmd/dm-worker.TestRunMain.func3()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/cmd/dm-worker/main_test.go:66 +0x2b

[2022-06-13T02:59:31.936Z] 

[2022-06-13T02:59:31.936Z] Previous read at 0x00c0014297f8 by goroutine 64:

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/dm/worker.(*Server).stopKeepAlive()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:240 +0x4c

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/dm/worker.(*Server).Close()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:461 +0x4e

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/cmd/dm-worker.main.func2()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/cmd/dm-worker/main.go:91 +0x1c7

[2022-06-13T02:59:31.936Z] 

[2022-06-13T02:59:31.936Z] Goroutine 114 (running) created at:

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/cmd/dm-worker.TestRunMain()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/cmd/dm-worker/main_test.go:65 +0x331

[2022-06-13T02:59:31.936Z]   testing.tRunner()

[2022-06-13T02:59:31.936Z]       /usr/local/go/src/testing/testing.go:1439 +0x213

[2022-06-13T02:59:31.936Z]   testing.(*T).Run.func1()

[2022-06-13T02:59:31.936Z]       /usr/local/go/src/testing/testing.go:1486 +0x47

[2022-06-13T02:59:31.936Z] 

[2022-06-13T02:59:31.936Z] Goroutine 64 (finished) created at:

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/cmd/dm-worker.main()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/cmd/dm-worker/main.go:88 +0xa11

[2022-06-13T02:59:31.936Z]   github.com/pingcap/tiflow/dm/cmd/dm-worker.TestRunMain.func3()

[2022-06-13T02:59:31.936Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/cmd/dm-worker/main_test.go:66 +0x2b

[2022-06-13T02:59:31.936Z] ==================
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: close #5836 close #5089 

### What is changed and how it works?

for #5836 : Server.Start is blocking, so before it we must spawn a goroutine to watch terminate signal. Original in that goroutine we call Server.Close, but Start/Close is not concurrent-safe. Now we use context to do cancellation.

for #5089 : when worker Server is about to close, it will hold the lock, enter doClose, then blocked on waitgroup https://github.com/pingcap/tiflow/blob/9bce8cc1d6265003a95cd61bbc2b2692cbf52d10/dm/dm/worker/server.go#L438-L439
but other goroutine may in the same time stuck at `s.Lock`.

#### Tests 

 - hard to test these functions :thinking: 

### Release note 

```release-note
Fix a bug that start DM-worker and `kill` it immediately will not let process stop.
```

### CODE REVIEW

**Review by GMHDBJD — APPROVED** [review]
LGTM

File: dm/dm/worker/server.go [hunk 1]
```diff
@@ -89,12 +89,13 @@ func NewServer(cfg *Config) *Server {
 	return &s
 }
 
-// Start starts to serving.
+// Start starts to serving. It will block current goroutine until Server.Close or
+// input context canceled.
 // this function should only exit when can't dail DM-master, for other errors it should not exit.
-func (s *Server) Start() error {
+func (s *Server) Start(ctx context.Context) error {
```
Comment (D3Hunter) [inline dm/dm/worker/server.go:95]: why not make start/close mutual exclusive?

Comment (lance6716) [reply dm/dm/worker/server.go:95]: If so, when Server.Start is stuck, we can't Close it.

Comment (D3Hunter) [reply dm/dm/worker/server.go:95]: if we reached `m.Serve()`, `cancel()` cannot cancel it, we need `close` which close the listener.

we only need to make sure field init part(initializing) mutual exclusive with close

**Comment by lance6716** [comment]
changed implementation, PTAL again @GMHDBJD

**Review by D3Hunter — DISMISSED** [review]

**Comment by lance6716** [comment]
/hold

wait @GMHDBJD

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
/hold

will check CI tomorrow

**Comment by lance6716** [comment]
/lgtm cancel

I also try to fix another issue. Please check the new PR description

File: dm/dm/worker/server.go [hunk 2]
```diff
@@ -94,129 +98,152 @@ func NewServer(cfg *Config) *Server {
...
-		return err
-	}
+	var m cmux.CMux
 
-	s.setWorker(nil, true)
+	// protect member from data race. some functions below like GetRelayConfig,
+	// GetSourceBoundConfig has a built-in timeout so it will not be stuck for a
+	// long time.
+	startErr := func() error {
+		if ok := s.ctxMu.Lock(s.ctx); !ok {
```
Comment (D3Hunter) [inline dm/dm/worker/server.go:108]: it makes code more complex, do we really need this ctxmutex? s.ctx is cancel only on close

Comment (lance6716) [reply dm/dm/worker/server.go:108]: it's about other s.Lock should be aware of s.ctx done. please check PR discription

Comment (lance6716) [reply dm/dm/worker/server.go:108]: I remeber the stack shows 

https://github.com/pingcap/tiflow/blob/a1da9b42ec10284c49d276ae932f6f858a02ad92/dm/dm/worker/server.go#L162-L172

s..observeSourceBound is blocked on s.Lock, so it can't s.wg.Done()

Comment (D3Hunter) [reply dm/dm/worker/server.go:108]: we need 1 mutex to sync between operations and 1(may not need) to sync accessing fields. and another mutex to sync start/close. but now there's only 1 mutex.

still trying to accept the idea of `context mutex`, odd to me.

Comment (lance6716) [reply dm/dm/worker/server.go:108]: Maybe using multiple mutex and a good locking order we also can avoid deadlock as well. Will take a look soon

**Review by hi-rustin — CHANGES_REQUESTED** [review]
@ti-chi-bot Please be nice!

File: dm/dm/worker/server.go (hunk 2 above)
Comment (lance6716) [reply dm/dm/worker/server.go]: https://github.com/pingcap/tiflow/pull/6213/commits/66cc7422e11240a5ba15df5902d9a9c57280f678

**Comment by lance6716** [comment]
/run-dm-integration-test

ptal

File: dm/dm/worker/server.go [hunk 3]
```diff
@@ -58,11 +58,19 @@ var (
 // dispatches requests to worker
 // sends responses to RPC client.
 type Server struct {
-	sync.Mutex
+	// closeMu is used to protect 5 fields below
```
Comment (D3Hunter) [inline dm/dm/worker/server.go:61]:
```suggestion
	// closeMu is used to sync Start/Close and protect 5 fields below
```

File: dm/dm/worker/server.go [hunk 4]
```diff
@@ -58,11 +58,19 @@ var (
...
+	closeMu    sync.Mutex
+	closed     atomic.Bool
+	inited     bool
```
Comment (D3Hunter) [inline dm/dm/worker/server.go:64]: `inited` doesn't reflect its meaning accurately which is whether we have called start/close ever.

if we change  call sequence in main from 
```
go signal-process-routine which calls s.Close
s.Start
s.Close
```
to this, we can avoid the chance of calling Close before Start
```
s.Init
go signal-process-routine which calls s.Close
s.Serve
s.Close
```
or better we can run s.Serve in a separate routine

but it's ok for now.

**Review by D3Hunter — APPROVED** [review]

**Comment by lance6716** [comment]
ping @GMHDBJD @buchuitoudegou

**Review by GMHDBJD — APPROVED** [review]
LGTM
