### PR TITLE
worker[engine]: fix bug that worker impl call 'Exit', but may not return

### LINKED ISSUE #5523: [engine]: BaseWorker Exit() will not make worker exit if user don't return
### What did you do?

Implement WorkerImpl, call Exit() but forget to return  

### What did you expect to see?

worker exit as expected

### What did you see instead?

worker doesn't exit if user don't return

91J9RxCYhq

### Versions of the cluster

engine version:

master

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve?

Issue Number: close #5523 

### What is changed and how it works?
Set the error on errCenter when call 'Exit'

#### Tests 

 - Unit test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

File: engine/lib/worker.go [hunk 1]
```diff
@@ -415,19 +415,25 @@ func (w *DefaultBaseWorker) OpenStorage(ctx context.Context, resourcePath resour
...
 	w.workerStatus.ExtBytes = status.ExtBytes
-	if err1 := w.statusSender.UpdateStatus(ctx, w.workerStatus); err1 != nil {
-		return err1
+	if errRet = w.statusSender.UpdateStatus(ctx, w.workerStatus); errRet != nil {
+		return errRet
 	}
 
-	return derror.ErrWorkerFinish.FastGenByArgs()
+	errRet = derror.ErrWorkerFinish.FastGenByArgs()
+	return errRet
```
Comment (liuzix) [inline engine/lib/worker.go:436]:
```suggestion
	return derror.ErrWorkerFinish.FastGenByArgs()
```

Comment (maxshuang) [reply engine/lib/worker.go]: From `return errRet` to `return` to avoid useless copy

**Review by gozssky — APPROVED** [review]
