### PR TITLE
integration test(ticdc): Reintroduce `--wildcards` Option in tar Command for download-integration-test-binaries.sh

### LINKED ISSUE #11631: ticdc: Recurrence of tar Wildcard Handling Issue in download-integration-test-binaries.sh After Refactor
### What did you do?

The issue previously described in #11512 (where tar wildcard handling caused extraction failures in the scripts/download-integration-test-binaries.sh script) has resurfaced after the script was refactored.

During the refactoring, the --wildcards option was not reintroduced, which is required for tar to correctly handle wildcard patterns in some versions. As a result, the script is once again failing to extract the necessary binaries for PD, particularly on systems where tar does not support wildcard patterns by default.

### What did you expect to see?

I expected the scripts/download-integration-test-binaries.sh script to successfully extract the PD binaries from the pd-server.tar.gz archive. This would allow the integration tests to run without any errors or missing binaries.

The solution is to reintroduce the --wildcards option in the tar command, as was done in #11513. This ensures compatibility across different environments and versions of tar.

### What did you see instead?

The script failed to extract the PD binaries from the pd-server.tar.gz archive due to the missing --wildcards option in the tar command. As a result, the third_bin directory was empty, and the integration tests could not run because the necessary PD executables were missing.
CleanShot 2024-09-26 at 16 13 53@2x

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
No TiDB.
```

Upstream TiKV version (execute `tikv-server --version`):

```console
No TiKV.
```

TiCDC version (execute `cdc version`):

```console
v8.3.0
```

### PR DESCRIPTION
**Pull request by wlwilliamx**
### What problem does this PR solve?

Issue Number: close #11631

### What is changed and how it works?

**Description:**

This PR addresses the reoccurrence of the `tar` extraction issue in `scripts/download-integration-test-binaries.sh` following a refactor, where the `--wildcards` option was omitted. This option is necessary for wildcard pattern matching in certain versions of `tar` to correctly extract the required binaries for PD.

#### **Context:**

In a previous issue:#11512 and pr:#11513, a similar problem was identified and resolved by adding the `--wildcards` option to the `tar` command. However, during the refactoring of the script, this option was unintentionally removed, causing the issue to resurface.

The current command:

https://github.com/pingcap/tiflow/blob/4e177d94ca41d5f49a44c5545adfca1c72820f87/scripts/download-integration-test-binaries.sh#L156

https://github.com/pingcap/tiflow/blob/4e177d94ca41d5f49a44c5545adfca1c72820f87/scripts/download-integration-test-binaries.sh#L176-L180

fails on some systems due to lack of support for wildcard matching by default. Without the `--wildcards` option, the necessary binaries are not extracted, leading to test failures.

#### **Solution:**

To fix this issue, I have reintroduced the `--wildcards` option in the `tar` command, ensuring compatibility across different systems. 

This guarantees that `tar` will correctly interpret wildcard patterns, even in environments where it isn’t enabled by default.

#### **Impact:**

- Ensures consistent extraction of binaries across different environments and `tar` implementations.
- Prevents failures in the integration tests by ensuring the correct binaries are extracted and available.

This PR is related to the previous #11513 that addressed the same issue before the script refactor.

#### Tests 

 - Manual test (add detailed scripts or steps below)
```bash
make prepare_test_binaries
```

##### Will it cause performance regression or break compatibility?

No.

##### Do you need to update user documentation, design documentation or monitoring documentation?

No.

### Release note 

```release-note
None
```

### CODE REVIEW

File: scripts/download-integration-test-binaries.sh [hunk 1]
```diff
@@ -206,6 +206,7 @@ cleanup() {
 
 setup() {
 	cleanup
+	rm -rf ${BIN_DIR}
```
Comment (lance6716) [inline scripts/download-integration-test-binaries.sh:209]: What will it delete?

Comment (wlwilliamx) [reply scripts/download-integration-test-binaries.sh:209]: The `BIN_DIR` is the final location where the binaries are stored. The reason I delete this folder before creating it is that if the folder is not empty, running make prepare_test_binaries will result in some strange tar command errors, as shown in the image below. This causes make prepare_test_binaries to fail unless BIN_DIR is manually deleted beforehand.

CleanShot 2024-09-26 at 17 08 55@2x

Comment (lance6716) [reply scripts/download-integration-test-binaries.sh:209]: I think to avoid repeatly downloading and reduce waiting time, we should not delete the whole folder. It's better to ignore existing files one-by-one, and use `mv` to atomically move the files.

Comment (wlwilliamx) [reply scripts/download-integration-test-binaries.sh:209]: This problem is not caused by the `mv` command but by the `tar` command. The error occurs when extracting `pd-server.tar.gz`. The reason is that the script needs to extract all the binary files under the `bin` directory from `pd-server.tar.gz`, so a wildcard `"bin/*"` is used to extract the contents of the `bin/*` directory. However, if there is already a `bin` folder in the current working directory and it contains files that do not exist in the `bin` directory of `pd-server.tar.gz`, the error will occur. This happens because before `tar` is executed, the wildcard is expanded, so it reads all the contents of the current working directory's `bin` folder and passes them as arguments to `tar`, which then tries to extract these files that are not present in the archive, leading to the error.

Additionally, I have also tried not using the wildcard and directly extracting the `bin` directory from `pd-server.tar.gz`. However, if the `BIN_DIR` already contains a folder with the same name, the `mv` command will fail:
CleanShot 2024-09-29 at 11 57 07@2x

Therefore, the simplest and most effective solution is to directly clean the `BIN_DIR` before proceeding. This way, the script can be executed repeatedly without causing any issues. It will not have any negative impact since `BIN_DIR` does not exist by default and is `gitignored` in the project. It is created specifically by the script for this purpose.

Comment (lance6716) [reply scripts/download-integration-test-binaries.sh:209]: Oh, I see that `prepare_test_binaries` is manually executed. I wrongly think it will be executed automatically in integration test so I don't want the cached binaries to be deleted.

BTW, to achieve "atomic" extracting, we can extract them to a temporary folder in the same file system mounting entry and `mv` the folder.

**Review by lance6716 — APPROVED** [review]

**Review by lidezhu — APPROVED** [review]
