### PR TITLE
kv(ticdc): Remove store connect backoff

### LINKED ISSUE #9741: changefeed LAG increased  when a tikv is killed
Every region belongs to the killed tikv store will try to connect that tikv again,  and the retry backoff time is 100ms
If there are thousands of regions, that will cause big changefeed LAG (100ms * region count)

```
[2023/09/13 17:09:03.713 +08:00] [WARN] [client.go:636] ["get grpc stream client failed"] [namespace=default] [changefeed=test] [regionID=1398592] [requestID=102976] [storeID=6] [error="[CDC:ErrTiKVEventFeed]tikv event feed failed: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.2.6.210:20160: connect: connection refused\""] [errorVerbose="[CDC:ErrTiKVEventFeed]tikv event feed failed: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.2.6.210:20160: connect: connection refused\"\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20220729040631-518f63d66278/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20220729040631-518f63d66278/normalize.go:164\ngithub.com/pingcap/tiflow/pkg/errors.WrapError\n\tgithub.com/pingcap/tiflow/pkg/errors/helper.go:34\ngithub.com/pingcap/tiflow/cdc/kv.(*CDCClient).newStream\n\tgithub.com/pingcap/tiflow/cdc/kv/client.go:239\ngithub.com/pingcap/tiflow/cdc/kv.(*eventFeedSession).requestRegionToStore\n\tgithub.com/pingcap/tiflow/cdc/kv/client.go:632\ngithub.com/pingcap/tiflow/cdc/kv.(*eventFeedSession).eventFeed.func3\n\tgithub.com/pingcap/tiflow/cdc/kv/client.go:425\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.1.0/errgroup/errgroup.go:75\nruntime.goexit\n\truntime/asm_amd64.s:1650"]
```

### PR DESCRIPTION
**Pull request by sdojjy**
### What problem does this PR solve?

Issue Number: close #9741

### What is changed and how it works?
remove the kv connect backoff logic by default.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by nongfushanquan — APPROVED** [review]

**Review by hicqu — APPROVED** [review]

File: cdc/kv/client.go [hunk 1]
```diff
@@ -246,10 +246,15 @@ func (c *CDCClient) newStream(ctx context.Context, addr string, storeID uint64)
 			zap.String("changefeed", c.changefeed.ID),
 			zap.String("addr", addr))
 		return nil
-	}, retry.WithBackoffBaseDelay(500),
-		retry.WithMaxTries(2),
-		retry.WithIsRetryableErr(cerror.IsRetryableError),
-	)
+	}
+	if c.config.Debug.EnableKVConnectBackOff {
+		newStreamErr = retry.Do(ctx, streamFunc, retry.WithBackoffBaseDelay(500),
```
Comment (CharlesCheung96) [inline cdc/kv/client.go:251]:
```suggestion
		newStreamErr = retry.Do(ctx, streamFunc, retry.WithBackoffBaseDelay(100),
```

**Comment by sdojjy** [comment]
6 tikv nodes with about 20k regions,  the LAG before this PR is about 6min

img_v2_4ce5efbf-5a1a-4907-89fb-05b7043b734g

after this PR , the LAG is about 40s
df75fb55-0ae3-4f7d-afca-ecbe98fe782c
