### PR TITLE
tests(ticdc): fix inaccurate DDL finish ts

### LINKED ISSUE #8396: CDC integration test bank failed with panic
### Which jobs are flaking?

cdc_ghpr_integration_test

### Which test(s) are flaking?

bank

### Jenkins logs or GitHub Actions link

```log
[2023-02-28T09:16:06.395Z] [2023/02/28 17:16:06.247 +08:00] [WARN] [case.go:147] ["sequence test verify failed"] [error="missing changes sequence account_seq4, current sequence=65, previous sequence=63"] [errorVerbose="missing changes sequence account_seq4, current sequence=65, previous sequence=63\nmain.(*sequenceTest).verify.func1\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/tests/integration_tests/bank/case.go:178\ngithub.com/pingcap/tiflow/pkg/retry.run\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/pkg/retry/retry_with_opt.go:57\ngithub.com/pingcap/tiflow/pkg/retry.Do\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/pkg/retry/retry_with_opt.go:34\nmain.(*sequenceTest).verify\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/tests/integration_tests/bank/case.go:144\nmain.run.func2\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/tests/integration_tests/bank/case.go:592\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598"]

[2023-02-28T09:16:06.395Z] [2023/02/28 17:16:06.248 +08:00] [PANIC] [case.go:593] ["downstream verify failed"] [error="[CDC:ErrReachMaxTry]reach maximum try: 10, error: missing changes sequence account_seq4, current sequence=65, previous sequence=63: missing changes sequence account_seq4, current sequence=65, previous sequence=63"] [stack="main.run.func2\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/tests/integration_tests/bank/case.go:593\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75"]

[2023-02-28T09:16:06.395Z] panic: downstream verify failed

[2023-02-28T09:16:06.395Z] 

[2023-02-28T09:16:06.395Z] goroutine 152 [running]:

[2023-02-28T09:16:06.395Z] go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc0004c50c0?})

[2023-02-28T09:16:06.395Z] 	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65

[2023-02-28T09:16:06.395Z] go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000722270, {0xc000303380, 0x1, 0x1})

[2023-02-28T09:16:06.395Z] 	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec

[2023-02-28T09:16:06.395Z] go.uber.org/zap.(*Logger).Panic(0xc0005a4000?, {0x9085e0?, 0x0?}, {0xc000303380, 0x1, 0x1})

[2023-02-28T09:16:06.395Z] 	/go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:258 +0x59

[2023-02-28T09:16:06.395Z] github.com/pingcap/log.Panic({0x9085e0?, 0x13?}, {0xc000303380?, 0x9edc70?, 0xc000123fb0?})

[2023-02-28T09:16:06.395Z] 	/go/pkg/mod/github.com/pingcap/log@v1.1.1-0.20221116035753-734d527bc87c/global.go:54 +0x8b

[2023-02-28T09:16:06.395Z] main.run.func2()

[2023-02-28T09:16:06.395Z] 	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/tests/integration_tests/bank/case.go:593 +0xaa5

[2023-02-28T09:16:06.395Z] golang.org/x/sync/errgroup.(*Group).Go.func1()

[2023-02-28T09:16:06.395Z] 	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64

[2023-02-28T09:16:06.395Z] created by golang.org/x/sync/errgroup.(*Group).Go

[2023-02-28T09:16:06.395Z] 	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5

[2023-02-28T09:16:06.395Z] exit status 2

[2023-02-28T09:16:06.395Z] + stop_tidb_cluster

[2023-02-28T09:16:24.465Z] make: *** [integration_test_mysql] Error 1
```

### Anything else we need to know

log
https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/18750/pipeline

version
master@https://github.com/pingcap/tiflow/commit/71e2c4998f36077eaff4434b733790f3168c954d

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: close #8396

### What is changed and how it works?

Stable bank tests by fixing inaccurate DDL finish ts.

#### Tests 

 - Integration test

##### Will it cause performance regression or break compatibility?

No

##### Do you need to update user documentation, design documentation or monitoring documentation?

No

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

**Comment by asddongmen** [comment]
Would you mind adding a brief description about why the origin implementation may be using an incorrect ddlFinishedTs? I appreciate your hard work on this problem. Thank you so much! 
LGTM!

**Review by asddongmen — APPROVED** [review]

File: tests/integration_tests/bank/case.go [hunk 1]
```diff
@@ -611,32 +616,60 @@ func run(
...
 		}
 	}
 }
 
-func tryGetEndTs(db *sql.DB, tableName string) (result string, ok bool) {
-	query := "SELECT END_TIME FROM information_schema.ddl_jobs WHERE table_name = ?"
-	log.Info("try get end ts", zap.String("query", query))
-	var endTime string
+func tryGetEndTs(db *sql.DB, tidbAPIEndpoint, tableName string) (result uint64, ok bool) {
+	query := "SELECT JOB_ID FROM information_schema.ddl_jobs WHERE table_name = ?"
```
Comment (overvenus) [inline tests/integration_tests/bank/case.go:635]:
```suggestion
	// Note: We should not use `END_TS` in the table, because it is encoded in
	// the format `2023-03-16 18:12:51`, it's not precise enough.
	query := "SELECT JOB_ID FROM information_schema.ddl_jobs WHERE table_name = ?"
```
