### PR TITLE
client(cdc): use a small backoff to load regions

### LINKED ISSUE #9841: CDC panic: "panic: runtime error: invalid memory address or nil pointer dereference"
### What did you do?

1. Run kafka changefeed with claim check
2. Run workload 

### What did you expect to see?

CDC should not panic

### What did you see instead?

One of 3 CDC node panic seen. (only see it once during 7+ days of testing)

image

### Versions of the cluster

[release-version=v7.4.0] [git-hash=43848f2fb5646822903baee35b62c580498284e2]

### PR DESCRIPTION
**Pull request by hicqu**
### What problem does this PR solve?

Issue Number: close #9841 

### What is changed and how it works?

* reduce backoff of loading regions from `5s` to `100ms`;
* fix a nil pointer panic;

#### Tests 

 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
None
```

### CODE REVIEW

File: cdc/kv/shared_client.go [hunk 1]
```diff
@@ -444,7 +444,7 @@ func (s *SharedClient) divideAndScheduleRegions(
 	backoffBeforeLoad := false
 	for {
 		if backoffBeforeLoad {
-			if err := util.Hang(ctx, 5*time.Second); err != nil {
+			if err := util.Hang(ctx, loadRegionRetryInterval); err != nil {
```
Comment (nongfushanquan) [inline cdc/kv/shared_client.go:447]: could you add comments about the affection  of this interval?

**Review by nongfushanquan — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]
