### PR TITLE
pkg/notify: close notifier properly

### LINKED ISSUE #7073: signalTickLoop may not exit immediately after notifier is closed
### What did you do?

Add following unit test

```diff
--- a/pkg/notify/notify_test.go
+++ b/pkg/notify/notify_test.go
@@ -15,11 +15,13 @@ package notify

 import (
        "context"
+       "sync"
        "testing"
        "time"

        "github.com/pingcap/tiflow/pkg/errors"
        "github.com/stretchr/testify/require"
+       "github.com/uber-go/atomic"
 )

 func TestNotifyHub(t *testing.T) {
@@ -110,3 +112,35 @@ func TestNewReceiverWithClosedNotifier(t *testing.T) {
        _, err := notifier.NewReceiver(50 * time.Millisecond)
        require.True(t, errors.ErrOperateOnClosedNotifier.Equal(err))
 }
+
+func TestNotifierMultiple(t *testing.T) {
+       t.Parallel()
+       notifier := new(Notifier)
+       receiver, err := notifier.NewReceiver(time.Minute)
+       require.NoError(t, err)
+
+       var wg sync.WaitGroup
+       counter := atomic.NewInt32(0)
+
+       wg.Add(1)
+       go func() {
+               defer wg.Done()
+               for {
+                       _, ok := <-receiver.C
+                       if !ok {
+                               return
+                       }
+                       counter.Add(1)
+               }
+       }()
+
+       N := 5
+       for i := 0; i < N; i++ {
+               notifier.Notify()
+               time.Sleep(time.Millisecond * 100)
+       }
+
+       notifier.Close()
+       wg.Wait()
+       require.LessOrEqual(t, counter.Load(), int32(N))
+}
```

### What did you expect to see?

unit test passed

### What did you see instead?

```bash
go test -v -count=1 -run=TestNotifierMultiple
=== RUN   TestNotifierMultiple
=== PAUSE TestNotifierMultiple
=== CONT  TestNotifierMultiple
    notify_test.go:145:
                Error Trace:    /Users/yangfei/work/code/tiflow/pkg/notify/notify_test.go:145
                Error:          "7" is not less than or equal to "5"
                Test:           TestNotifierMultiple
--- FAIL: TestNotifierMultiple (0.50s)
FAIL
exit status 1
FAIL    github.com/pingcap/tiflow/pkg/notify    0.626s
```

This is caused by the following `break`

https://github.com/pingcap/tiflow/blob/3f10ffac77c4df466d41e3f672b77c1afc894838/pkg/notify/notify.go#L69

Further more, if creating a receiver with no ticker, `receiver, err := notifier.NewNotifier(-1)`, the receiver can't be notified after notifier is closed.

```diff
➜  git diff
diff --git a/pkg/notify/notify_test.go b/pkg/notify/notify_test.go
index 86e502f2b..218aa660f 100644
--- a/pkg/notify/notify_test.go
+++ b/pkg/notify/notify_test.go
@@ -116,7 +116,7 @@ func TestNewReceiverWithClosedNotifier(t *testing.T) {
 func TestNotifierMultiple(t *testing.T) {
        t.Parallel()
        notifier := new(Notifier)
-       receiver, err := notifier.NewReceiver(time.Minute)
+       receiver, err := notifier.NewReceiver(-1)
        require.NoError(t, err)

        var wg sync.WaitGroup
```

### Versions of the cluster

TiCDC version (execute `cdc version`):

master@https://github.com/pingcap/tiflow/commit/3f10ffac77c4df466d41e3f672b77c1afc894838

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: close #7073

### What is changed and how it works?
close notifier properly

#### Tests 

 - Unit test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

File: pkg/notify/notify.go [hunk 1]
```diff
@@ -135,11 +97,55 @@ func (n *Notifier) Close() {
...
-			receiver.rec.ticker.Stop()
-		}
-		close(receiver.rec.closeCh)
+		receiver.rec.close()
 	}
 	n.receivers = nil
 	n.closed = true
 }
+
+// Receiver is a receiver of notifier, including the receiver channel and stop receiver function.
```
Comment (amyangfei) [inline pkg/notify/notify.go:106]: Why changing the location of following code, it will generate too many changes in git diff.

File: pkg/notify/notify.go [hunk 2]
```diff
@@ -135,11 +97,55 @@ func (n *Notifier) Close() {
...
+type Receiver struct {
+	C       <-chan struct{}
```
Comment (lonng) [inline pkg/notify/notify.go:108]: It seems the `C` and `c` are identical, can we eliminate the redundancy one?
Ref: https://github.com/pingcap/tiflow/pull/7077/files#diff-d978136a23c5c118a3dc8719ba1abeeb49bb025f44d4d09555602128ab4f79a9R59-R67

**Review by lonng — APPROVED** [review]
Rest LGTM

File: pkg/notify/notify.go [hunk 3]
```diff
@@ -135,11 +97,55 @@ func (n *Notifier) Close() {
...
+			case <-r.closeCh:
+				break loop
+			case <-r.ticker.C:
+			}
+			exit := r.signalNonBlocking()
+			if exit {
+				break loop
+			}
+		}
+		close(r.c)
```
Comment (amyangfei) [inline pkg/notify/notify.go:140]: Can add some comments here to explain why we `close(r.c)` here instead doing it in `receiver.close()`

Comment (CharlesCheung96) [reply pkg/notify/notify.go:140]: [added, PTAL](https://github.com/pingcap/tiflow/pull/7077/files#diff-d978136a23c5c118a3dc8719ba1abeeb49bb025f44d4d09555602128ab4f79a9R146-R147)

File: pkg/notify/notify.go (hunk 1 above)
Comment (CharlesCheung96) [reply pkg/notify/notify.go:106]: To distinguish `Receiver` from`Notifier` code block.

**Review by amyangfei — APPROVED** [review]
