### PR TITLE
cli(cdc): handle error correctly with wrong pd address but with a grpc service

### LINKED ISSUE #6458: With wrong pd address, error message is helpless
### What did you do?

changefeed list with wrong pd address, error message is weird.

-  tiup cdc cli changefeed list --pd=http://tiup-peer:8300/ 

Error: rpc error: code = Unimplemented desc = unknown service etcdserverpb.Cluster

### What did you expect to see?

Like before.

### What did you see instead?

-  tiup cdc cli changefeed list --pd=http://tiup-peer:8300/

Error: rpc error: code = Unimplemented desc = unknown service etcdserverpb.Cluster

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
v6.2.0
```

### PR DESCRIPTION
**Pull request by crelax**
### What problem does this PR solve?

Issue Number: close #6458 

### What is changed and how it works?
Check the PD address(es) by trying to create a PDClient before creating the EtcdClient. The address is guaranteed to represent a valid PD cluster if the PDClient was created successfully.

Previous checks assume the PD address is correct if the EtcdClient got created successfully. However, the EtcdClient can be created without error as long as there is a gRPC service, and it may not a real PD/Etcd cluster. 

#### Tests 
 - Manual test
   - Start a tidb cluster and a ticdc cluster
   - Operate cdc cli `cdc cli changefeed list --pd=xxx`, but use the cdc server address as the wrong pd address. 
   - Check the error message. It should tell the user to check the pd address 
image

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
`Bug fix: handle error correctly with wrong pd address but with a grpc service`
```

### CODE REVIEW

File: pkg/cmd/factory/factory_impl.go [hunk 1]
```diff
@@ -90,6 +90,12 @@ func (f *factoryImpl) GetCredential() *security.Credential {
 
 // EtcdClient creates new cdc etcd client.
 func (f *factoryImpl) EtcdClient() (*etcd.CDCEtcdClient, error) {
+	// check pd-address is an actual pd cluster
+	_, err := f.PdClient()
+	if err != nil {
+		return nil, errors.Trace(err)
+	}
+
```
Comment (liuzix) [inline pkg/cmd/factory/factory_impl.go:98]: Should the PD client be closed?

File: pkg/cmd/factory/factory_impl.go [hunk 2]
```diff
@@ -90,6 +90,12 @@ func (f *factoryImpl) GetCredential() *security.Credential {
 
 // EtcdClient creates new cdc etcd client.
 func (f *factoryImpl) EtcdClient() (*etcd.CDCEtcdClient, error) {
```
Comment (liuzix) [inline pkg/cmd/factory/factory_impl.go:92]: Why putting this check here? Seems confusing why getting an `etcd.CDCEtcdClient` needs to check for PD address's validity.

File: pkg/cmd/factory/factory_impl.go (hunk 1 above)
Comment (crelax) [reply pkg/cmd/factory/factory_impl.go:98]: yes

File: pkg/cmd/cli/cli_unsafe_reset.go [hunk 3]
```diff
@@ -37,19 +37,18 @@ func newUnsafeResetOptions() *unsafeResetOptions {
...
 		return err
 	}
-	etcdClient.ClusterID = o.clusterID
-	o.etcdClient = etcdClient
+	o.pdClient = pdClient
 
-	pdClient, err := f.PdClient()
+	etcdClient, err := f.EtcdClient()
 	if err != nil {
 		return err
```
Comment (liuzix) [inline pkg/cmd/cli/cli_unsafe_reset.go:48]: Please close `pdClient` here.

File: pkg/cmd/factory/factory_impl.go (hunk 2 above)
Comment (crelax) [reply pkg/cmd/factory/factory_impl.go]: It can moved to other places. The reason I put it here is that, for now, the etcd address(es) should be and could only be the addresses of a pd cluster.

File: pkg/cmd/factory/factory_impl.go [hunk 4]
```diff
@@ -139,6 +139,11 @@ func (f *factoryImpl) EtcdClient() (*etcd.CDCEtcdClient, error) {
 	}
 
 	client, err := etcd.NewCDCEtcdClient(ctx, etcdClient, etcd.DefaultCDCClusterID)
+	if err != nil {
+		return nil, cerror.ErrEtcdAPIError.GenWithStack(
+			"etcd operation error, please the cluster status and the address is correct: \"%s\"")
```
Comment (liuzix) [inline pkg/cmd/factory/factory_impl.go:144]:
```suggestion
			"etcd operation error. Please the cluster's status and the address are correct: \"%s\"")
```

File: pkg/cmd/cli/cli_unsafe_reset.go [hunk 5]
```diff
@@ -37,19 +37,19 @@ func newUnsafeResetOptions() *unsafeResetOptions {
 
 // complete adapts from the command line args to the data and client required.
 func (o *unsafeResetOptions) complete(f factory.Factory) error {
```
Comment (liuzix) [inline pkg/cmd/cli/cli_unsafe_reset.go:39]:
```suggestion
func (o *unsafeResetOptions) complete(f factory.Factory) (retErr error) {
```

File: pkg/cmd/cli/cli_unsafe_reset.go [hunk 6]
```diff
@@ -37,19 +37,19 @@ func newUnsafeResetOptions() *unsafeResetOptions {
...
-	etcdClient, err := f.EtcdClient()
+	pdClient, err := f.PdClient()
 	if err != nil {
 		return err
 	}
-	etcdClient.ClusterID = o.clusterID
-	o.etcdClient = etcdClient
+	o.pdClient = pdClient
```
Comment (liuzix) [inline pkg/cmd/cli/cli_unsafe_reset.go:44]:
```suggestion
	o.pdClient = pdClient
	defer func() {
	    if retErr != nil {
	        pdClient.Close()
	    }
	}
```

File: pkg/cmd/cli/cli_unsafe_reset.go [hunk 7]
```diff
@@ -36,20 +36,25 @@ func newUnsafeResetOptions() *unsafeResetOptions {
...
+		if retErr != nil {
+			pdClient.Close()
+		}
+	}()
 
-	pdClient, err := f.PdClient()
+	o.pdClient = pdClient
+	etcdClient, err := f.EtcdClient()
 	if err != nil {
+		pdClient.Close()
```
Comment (liuzix) [inline pkg/cmd/cli/cli_unsafe_reset.go:53]:
```suggestion
```

**Review by liuzix — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Review by liuzix — APPROVED** [review]
