### PR TITLE
sinkv2(cdc): fix and enable redo cache for pull-based-sink

### LINKED ISSUE #7884: pull-based-sink can't work with redo-log enabled
### What did you do?

Create a changefeed with `pull-based-sink` enabled, and consistent level is eventual.

### What did you expect to see?

It should work fine.

### What did you see instead?

It can't work. We meet some problems:

* data inconsistent
* panics on ts regression
* duplicate entry to downstream

### Versions of the cluster

TiCDC master branch.

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

Issue Number: close #7884 

### What is changed and how it works?

Fix bugs about redo cache. And enable it.

#### Tests 

 - Unit test
 - Manual test
  * https://tcms.pingcap.net/dashboard/executions/plan/1326166
  * https://tcms.pingcap.net/dashboard/executions/plan/1326169

### Release note 

```release-note
None
```

### CODE REVIEW

File: cdc/processor/sinkmanager/manager.go [hunk 1]
```diff
@@ -151,7 +151,8 @@ func New(
 		m.redoWorkers = make([]*redoWorker, 0, redoWorkerNum)
 		m.redoTaskChan = make(chan *redoTask)
 		m.redoWorkerAvailable = make(chan struct{}, 1)
-		// TODO: maybe should use at most 1/3 memory quota for redo event cache.
+		// Use 3/4 memory quota as redo event cache.
+		m.eventCache = newRedoEventCache(changefeedID, changefeedInfo.Config.MemoryQuota/4*3)
```
Comment (nongfushanquan) [inline cdc/processor/sinkmanager/manager.go:155]: Is  3/4 more reasonable than 1/3?

Comment (hicqu) [reply cdc/processor/sinkmanager/manager.go:155]: I found that 1/3 or 1/2 can lead low cache hit ratio (about 15%~20%) on heavy load. I guess 3/4 is helpful. I will examine it when I do performance tests.

File: cdc/processor/sinkmanager/table_sink_wrapper.go [hunk 2]
```diff
@@ -73,8 +74,18 @@ type tableSinkWrapper struct {
 }
 
 type rangeEventCount struct {
-	pos    engine.Position
-	events int
+	// firstPos and lastPos are used to merge many rangeEventCount into one.
+	firstPos engine.Position
+	lastPos  engine.Position
```
Comment (amyangfei) [inline cdc/processor/sinkmanager/table_sink_wrapper.go:79]: Comment in L71 should be updated to `lastPos`

File: cdc/processor/sinkmanager/redo_cache.go [hunk 3]
```diff
@@ -135,10 +136,17 @@ func (e *eventAppender) pop(lowerBound, upperBound engine.Position) (res popResu
 	defer e.mu.Unlock()
 
 	if lowerBound.Compare(e.lowerBound) < 0 {
+		// NOTE: the caller will fetch events [lowerBound, res.boundary) from engine.
 		res.success = false
 		res.boundary = e.lowerBound
 		return
 	}
```
Comment (amyangfei) [inline cdc/processor/sinkmanager/redo_cache.go:143]: Not sure why it can return here, could it happen that 

lowerBound < e.lowerBound < e.upperBound <= upperBound
or 
lowerBound < e.lowerBound < upperBound <= e.upperBound

Comment (hicqu) [reply cdc/processor/sinkmanager/redo_cache.go:143]: If `lowerBound < e.lowerBound` it means the cache doesn't contains all required events.
For example we want to fetch `1,2,3,4,5` but there are only `3,4,5` in cache. So we need to fetch `1,2` from engine.

File: cdc/processor/sinkmanager/manager.go (hunk 1 above)
Comment (hi-rustin) [reply cdc/processor/sinkmanager/manager.go:156]: Could you please add these comments to the code?

File: cdc/processor/sinkmanager/table_sink_worker.go [hunk 4]
```diff
@@ -387,12 +389,12 @@ func (w *sinkWorker) fetchFromCache(
 		zap.String("changefeed", w.changefeedID.ID),
 		zap.Int64("tableID", task.tableID),
 		zap.Bool("success", popRes.success),
+		zap.Int("events", len(popRes.events)),
```
Comment (hi-rustin) [inline cdc/processor/sinkmanager/table_sink_worker.go:392]:
```suggestion
		zap.Int("eventsLen", len(popRes.events)),
```

File: cdc/processor/sinkmanager/table_sink_wrapper.go [hunk 5]
```diff
@@ -186,9 +197,20 @@ func (t *tableSinkWrapper) updateRangeEventCounts(eventCount rangeEventCount) {
...
 	defer t.rangeEventCountsMu.Unlock()
 
-	if len(t.rangeEventCounts) == 0 ||
-		t.rangeEventCounts[len(t.rangeEventCounts)-1].pos.Compare(eventCount.pos) < 0 {
+	countsLen := len(t.rangeEventCounts)
+	if countsLen == 0 {
 		t.rangeEventCounts = append(t.rangeEventCounts, eventCount)
+		return
+	}
+	if t.rangeEventCounts[countsLen-1].lastPos.Compare(eventCount.lastPos) < 0 {
```
Comment (hi-rustin) [inline cdc/processor/sinkmanager/table_sink_wrapper.go:205]: Could you please add some comments to explain what's going on here?

**Review by amyangfei — APPROVED** [review]

**Review by hi-rustin — APPROVED** [review]
