### PR TITLE
*: upgrade tidb to include fix

### LINKED ISSUE #11768: dm: after physical import, the auto id might have a large jump
### What did you do?

refer https://github.com/pingcap/tidb/pull/57398

it should be fixed on lightning side, and DM need upgrade it

### What did you expect to see?

_No response_

### What did you see instead?

_No response_

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
(paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #11768

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - [x] No code

### Release note 

```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with `None`.
```

### CODE REVIEW

File: dm/pkg/parser/common_test.go [hunk 1]
```diff
@@ -278,11 +278,11 @@ var testCases = []testCase{
 		[]string{"ALTER TABLE `xtest`.`xt1` DROP INDEX IF EXISTS `i1`"},
 	},
 	{
-		"alter table `t1` drop foreign key if exists fk_t2_id",
-		[]string{"ALTER TABLE `test`.`t1` DROP FOREIGN KEY IF EXISTS `fk_t2_id`"},
+		"alter table `t1` drop foreign key fk_t2_id",
```
Comment (D3Hunter) [inline dm/pkg/parser/common_test.go:281]: see https://github.com/pingcap/tidb/issues/56701

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by lance6716 — APPROVED** [review]
