### PR TITLE
kv-client(ticdc): fix panic when close receiveFromStream

### LINKED ISSUE #9520: panic occurred while handling region errors in kvclient
```log
panic: unlocking a not locked range

goroutine 740 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x6?, 0x6?, {0x0?, 0x0?, 0xc04f5c0f00?})
	go.uber.org/zap@v1.23.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0782256c0, {0xc842410d80, 0x6, 0x6})
	go.uber.org/zap@v1.23.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc842410d80?, {0x3a07046?, 0x4562c9?}, {0xc842410d80, 0x6, 0x6})
	go.uber.org/zap@v1.23.0/logger.go:251 +0x59
github.com/pingcap/log.Panic({0x3a07046?, 0xcc73cafe40?}, {0xc842410d80?, 0xc03d55ef10?, 0xc44abb6000?})
	github.com/pingcap/log@v1.1.1-0.20221116035753-734d527bc87c/global.go:54 +0x8b
github.com/pingcap/tiflow/pkg/regionspan.(*RegionRangeLock).UnlockRange(0xd546d2e200, {0xd03bdf8a40, 0x1b, 0x20}, {0xd03bdf8a60, 0x1b, 0x20}, 0x7b59972, 0x13b6c, 0x62644946e000061)
	github.com/pingcap/tiflow/pkg/regionspan/region_range_lock.go:344 +0x74b
github.com/pingcap/tiflow/cdc/kv.(*eventFeedSession).onRegionFail(0x11149c63340, {0x42cf3a8, 0xd546d2e240}, {{{0x7b59972, 0xbe7, 0x13b6c}, {{0xd03bdf8a40, 0x1b, 0x20}, {0xd03bdf8a60, ...}}, ...}, ...}, ...)
	github.com/pingcap/tiflow/cdc/kv/client.go:641 +0xc5
github.com/pingcap/tiflow/cdc/kv.(*regionWorker).handleSingleRegionError(0xc862e6bdd0, {0x429f980?, 0xc77ec59740}, 0xc875cb45a0)
	github.com/pingcap/tiflow/cdc/kv/region_worker.go:235 +0x87e
github.com/pingcap/tiflow/cdc/kv.(*regionWorker).processEvent(0xc862e6bdd0, {0x42cf3a8, 0xc50bf4bbc0}, 0xd03b0800c0)
	github.com/pingcap/tiflow/cdc/kv/region_worker.go:369 +0x4fb
github.com/pingcap/tiflow/cdc/kv.(*regionWorker).initPoolHandles.func1({0x42cf3a8?, 0xc50bf4bbc0?}, {0x31ed1e0?, 0xd03b0800c0?})
	github.com/pingcap/tiflow/cdc/kv/region_worker.go:403 +0x46
github.com/pingcap/tiflow/pkg/workerpool.(*defaultEventHandle).AddEvents.func2({0xc03d55fe98?, 0xc03d55fd68?})
	github.com/pingcap/tiflow/pkg/workerpool/pool_impl.go:164 +0x8f
github.com/pingcap/tiflow/pkg/workerpool.(*worker).run(0xc000e37c20, {0x42cf3a8, 0xc000e64080?})
	github.com/pingcap/tiflow/pkg/workerpool/pool_impl.go:377 +0x3e2
github.com/pingcap/tiflow/pkg/workerpool.(*defaultPoolImpl).Run.func1()
	github.com/pingcap/tiflow/pkg/workerpool/pool_impl.go:67 +0x28
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: close #9520

### What is changed and how it works?
1. reafactor some codes
2. wait worker exit before evictAllRegions in `eventFeedSession.receiveFromStream`

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`Fix the issue that caused panic when rebuilding grpc connections to tikv`.
```

### CODE REVIEW

File: cdc/kv/client.go [hunk 1]
```diff
@@ -1002,121 +998,146 @@ func (s *eventFeedSession) receiveFromStream(
...
 	// to call exactly once from outer code logic
-	worker := newRegionWorker(s.changefeed, s, addr)
-
-	defer worker.evictAllRegions()
+	worker := newRegionWorker(parentCtx, s.changefeed, s, addr)
+
+	ctx, cancel := context.WithCancel(parentCtx)
+	var retErr error
+	once := sync.Once{}
+	handleExit := func(err error) error {
```
Comment (hicqu) [inline cdc/kv/client.go:1006]: It seems unnecessary. Why not call `cancel` after `eg.Wait` directly?

Comment (CharlesCheung96) [reply cdc/kv/client.go:1006]: This is to be compatible with the previous error handling logic. Otherwise, many tests might have to be changed.

**Review by hicqu — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]
