### PR TITLE
test(dm): fix etcdutil test failed

### LINKED ISSUE #3777: TestEtcdUtil is unstable
### Which jobs are flaking?

https://github.com/pingcap/ticdc/pull/3746 
dm-unit-test

### Which test(s) are flaking?

testEtcdUtilSuite.TestEtcdUtil

### Jenkins logs or GitHub Actions link

```log
----------------------------------------------------------------------
FAIL: etcdutil_test.go:123: testEtcdUtilSuite.TestEtcdUtil
etcdutil_test.go:128:
    t.testRemoveMember(c)
etcdutil_test.go:200:
    c.Assert(respList.Members, HasLen, 2)
... obtained []*etcdserverpb.Member = []*etcdserverpb.Member{(*etcdserverpb.Member)(0xc00065d7c0), (*etcdserverpb.Member)(0xc00065d810), (*etcdserverpb.Member)(0xc00065d860)}
... n int = 2
OOPS: 1 passed, 1 FAILED
--- FAIL: TestSuite (10.20s)
```

https://ci.pingcap.net/blue/organizations/jenkins/atom-ut/detail/atom-ut/3853/tests/

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve?

Issue Number: close #3777

### What is changed and how it works?

* use free port to make test etcd server not confilct with each other
* incr the start timeout of etcd server
* fix RemoveMember somethimes failed because the remove one member that is the one we connected to

* only assert value and ignore ordering  for this case 
```
FAIL: etcdutil_test.go:127: testEtcdUtilSuite.TestEtcdUtil
etcdutil_test.go:129:
    t.testMemberUtilInternal(c, i)
etcdutil_test.go:124:
    c.Assert(m.PeerURLs, DeepEquals, t.urlsToStrings(cfg.APUrls))
... obtained []string = []string{"http://127.0.0.1:34253", "http://127.0.0.1:39747"}
... expected []string = []string{"http://127.0.0.1:39747", "http://127.0.0.1:34253"}
```

### Check List 

Tests 

 - Unit test

Code changes
- None

Side effects
- None

Related changes
- None

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
what's the reason of #3777 , does its port conflict with which test?

**Comment by Ehco1996** [comment]
/hold

still working on fix datarace

**Comment by Ehco1996** [comment]
> what's the reason of #3777 , does its port conflict with some tests?

updated the root case to PR description, now i thinks this cacs is steable enough because i start a test with `go test  --count=100 --failfast  -v`🤣

but i am sorry that i can't fix the datarace , seems it''s a datarace inner **ETCD**

```
==================
WARNING: DATA RACE
Write at 0x0001064b5d90 by goroutine 23:
  google.golang.org/grpc/grpclog.SetLoggerV2()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/google.golang.org/grpc@v1.29.1/grpclog/loggerv2.go:70 +0xb0
  go.etcd.io/etcd/embed.NewZapCoreLoggerBuilder.func1.1()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20210512015243-d19fbe541bf9/embed/config_logging.go:308 +0x48
  sync.(*Once).doSlow()
      /Users/ehco/.gvm/gos/go1.17.4/src/sync/once.go:68 +0xb8
  sync.(*Once).Do()
      /Users/ehco/.gvm/gos/go1.17.4/src/sync/once.go:59 +0x50
  go.etcd.io/etcd/embed.NewZapCoreLoggerBuilder.func1()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20210512015243-d19fbe541bf9/embed/config_logging.go:307 +0x21c
  go.etcd.io/etcd/embed.(*Config).setupLogging()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20210512015243-d19fbe541bf9/embed/config_logging.go:255 +0x2260
  go.etcd.io/etcd/embed.(*Config).Validate()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20210512015243-d19fbe541bf9/embed/config.go:572 +0x38
  github.com/pingcap/tiflow/dm/pkg/etcdutil.(*testEtcdUtilSuite).newConfig()
      /Users/ehco/Documents/pingcap/tiflow/dm/pkg/etcdutil/etcdutil_test.go:63 +0x258
  github.com/pingcap/tiflow/dm/pkg/etcdutil.(*testEtcdUtilSuite).testMemberUtilInternal()
      /Users/ehco/Documents/pingcap/tiflow/dm/pkg/etcdutil/etcdutil_test.go:135 +0x5c
  github.com/pingcap/tiflow/dm/pkg/etcdutil.(*testEtcdUtilSuite).TestEtcdUtil()
      /Users/ehco/Documents/pingcap/tiflow/dm/pkg/etcdutil/etcdutil_test.go:129 +0x48
  runtime.call16()
      /Users/ehco/.gvm/gos/go1.17.4/src/runtime/asm_arm64.s:414 +0x70
  reflect.Value.Call()
      /Users/ehco/.gvm/gos/go1.17.4/src/reflect/value.go:339 +0x98
  github.com/pingcap/check.(*suiteRunner).forkTest.func1()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850 +0x97c
  github.com/pingcap/check.(*suiteRunner).forkCall.func1()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0xd0

Previous read at 0x0001064b5d90 by goroutine 123:
  google.golang.org/grpc/grpclog.V()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/google.golang.org/grpc@v1.29.1/grpclog/grpclog.go:41 +0x34
  google.golang.org/grpc/internal/transport.infof()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/log.go:29 +0x60
  google.golang.org/grpc/internal/transport.(*loopyWriter).run.func1()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/controlbuf.go:508 +0x258
  google.golang.org/grpc/internal/transport.(*loopyWriter).run()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/controlbuf.go:515 +0x188
  google.golang.org/grpc/internal/transport.newHTTP2Server.func2()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/http2_server.go:291 +0x1b8

Goroutine 23 (running) created at:
  github.com/pingcap/check.(*suiteRunner).forkCall()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4ac
  github.com/pingcap/check.(*suiteRunner).forkTest()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:832 +0x18c
  github.com/pingcap/check.(*suiteRunner).doRun()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:666 +0x1ec
  github.com/pingcap/check.(*suiteRunner).run()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:696 +0x104
  github.com/pingcap/check.Run()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:150 +0x4c
  github.com/pingcap/check.RunAll()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:113 +0x6c8
  github.com/pingcap/check.TestingT()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:99 +0x6f0
  github.com/pingcap/tiflow/dm/pkg/etcdutil.TestSuite()
      /Users/ehco/Documents/pingcap/tiflow/dm/pkg/etcdutil/etcdutil_test.go:52 +0x9c
  testing.tRunner()
      /Users/ehco/.gvm/gos/go1.17.4/src/testing/testing.go:1259 +0x198

Goroutine 123 (finished) created at:
  google.golang.org/grpc/internal/transport.newHTTP2Server()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/http2_server.go:288 +0x1d80
  google.golang.org/grpc/internal/transport.NewServerTransport()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/transport.go:534 +0x1d8
  google.golang.org/grpc.(*Server).newHTTP2Transport()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:726 +0x1bc
  google.golang.org/grpc.(*Server).handleRawConn()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:693 +0x44c
  google.golang.org/grpc.(*Server).Serve.func3()
      /Users/ehco/.gvm/pkgsets/go1.17.4/global/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:663 +0x40
==================
```

File: dm/pkg/etcdutil/etcdutil_test.go [hunk 1]
```diff
@@ -20,8 +20,10 @@ import (
 	"testing"
 	"time"
 
+	"github.com/phayes/freeport"
```
Comment (lance6716) [inline dm/pkg/etcdutil/etcdutil_test.go:23]: we have no evidence that the failed CI is caused by port conflict, and I guess in fact that is not the root cause because port conflict will fail the syscall immediately rather than blocking.
And your PR is not a solution because it can't handle time-of-check to time-of-use

**Review by lance6716 — CHANGES_REQUESTED** [review]

File: dm/pkg/etcdutil/etcdutil_test.go (hunk 1 above)
Comment (Ehco1996) [reply dm/pkg/etcdutil/etcdutil_test.go:23]: yes, port conflicts is not the root cause root cause is updated in PR description

but i think this is no harm and more intuitiveto use free port in test ?

File: dm/pkg/etcdutil/etcdutil_test.go [hunk 2]
```diff
@@ -174,26 +177,28 @@ func (t *testEtcdUtilSuite) testMemberUtilInternal(c *C, portCount int) {
...
-	c.Assert(respRemove.Members, HasLen, 2)
-
-	// get another client
-	cli = cluster.RandClient()
+	if err != nil {
+		// remove the leader will meet this error, and next line will check the member count
+		c.Assert(err, ErrorMatches, ".*etcdserver: server stopped")
+	} else {
+		c.Assert(respRemove.Members, HasLen, 2)
+	}
```
Comment (okJiang) [inline dm/pkg/etcdutil/etcdutil_test.go:198]: can split this to two situation, for leader and non-leader

File: dm/pkg/etcdutil/etcdutil_test.go (hunk 1 above)
Comment (lance6716) [reply dm/pkg/etcdutil/etcdutil_test.go:23]: this is already a free port

File: dm/pkg/etcdutil/etcdutil_test.go [hunk 3]
```diff
@@ -33,54 +35,56 @@ import (
 	"github.com/pingcap/tiflow/dm/pkg/terror"
 )
 
-var _ = Suite(&testEtcdUtilSuite{})
+var etcdTestSuite = SerialSuites(&testEtcdUtilSuite{})
```
Comment (WizardXiao) [inline dm/pkg/etcdutil/etcdutil_test.go:38]: just a question, use `SerialSuites` instead of `ParallelSuites` (default) is for avoid some conflicts? shall we also need define `SetUpTest` or `TearDownTest` function for help?

File: dm/pkg/etcdutil/etcdutil_test.go (hunk 2 above)
Comment (Ehco1996) [reply dm/pkg/etcdutil/etcdutil_test.go]: after split to two test case , i found that it's nothing about leader, it's about if we use a client that connected to the member we want to remove we **may** meet `etcdserver: server stopped` this error. so this is a unsteable feautre in etcd self see more in https://github.com/etcd-io/etcd/pull/7242

fixed in https://github.com/pingcap/tiflow/pull/4175/commits/3a71b1270dfdbba84e35519d70ed8f982fd17906

File: dm/pkg/etcdutil/etcdutil_test.go (hunk 1 above)
Comment (Ehco1996) [reply dm/pkg/etcdutil/etcdutil_test.go:23]: we not have port confilcts problem in current codebase, but it have a chance that if someone start another etcd server with **hardcode** port 8361 in other test case, what's more, some other test with embed etcd also use a free port in config such as https://github.com/pingcap/tiflow/blob/afa9a2bf57e0cbff874af06748a9b71d63eef6ca/dm/dm/worker/server_test.go#L105 and https://github.com/pingcap/tiflow/blob/afa9a2bf57e0cbff874af06748a9b71d63eef6ca/dm/pkg/election/election_test.go#L60

so i think we better not keep this hardcode port ?

Comment (lance6716) [reply dm/pkg/etcdutil/etcdutil_test.go:23]: Yes, we can reduce conflict caused by random port of other tests. I prefer we use `tempurl` rather than import a new library

File: dm/pkg/etcdutil/etcdutil_test.go (hunk 3 above)
Comment (Ehco1996) [reply dm/pkg/etcdutil/etcdutil_test.go]: actully SerialSuites doesn't help to reduce datarace, it's a internal data-race bettew grpc server and etcd server 😂
but this comment help me finding out the workaround to solve this problem, add in  https://github.com/pingcap/tiflow/pull/4175/commits/6ea37fa20e76f2b79018cc4a10b6b067749bc6c9

File: dm/pkg/etcdutil/etcdutil_test.go (hunk 1 above)
Comment (Ehco1996) [reply dm/pkg/etcdutil/etcdutil_test.go]: Sounds reasonable, replace to `tempurl` in https://github.com/pingcap/tiflow/pull/4175/commits/6ea37fa20e76f2b79018cc4a10b6b067749bc6c9

**Review by lance6716 — APPROVED** [review]

**Comment by WizardXiao** [comment]
LGTM

**Review by WizardXiao — APPROVED** [review]

**Review by okJiang — APPROVED** [review]
