### PR TITLE
capture(ticdc): fix the problem that openapi is blocked when pd is abnormal

### LINKED ISSUE #4778: Querying status via openapi may be blocked when pd fails
### What did you do?
When network isolation occurs between pd nodes and cdc nodes, run `curl -X GET http://127.0.0.1:8300/status`, and the terminal is stuck.

### What did you expect to see?

```shell
> curl -X GET http://127.0.0.1:8300/status                                                                          
{
 "version": "v5.4.0",
 "git_hash": "14db59be99371a0ef996708fa2867e73b2d7b8af",
 "id": "12f02f4c-59c2-4e73-8f9c-9db516fad91c",
 "pid": 8156,
 "is_owner": true
}
```

### What did you see instead?

There is no return message from the terminal

### Versions of the cluster

TiCDC version (execute `cdc version`):
```console
v5.4.0
14db59be99371a0ef996708fa2867e73b2d7b8af
```

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: close #4778

### What is changed and how it works?
1. Avoid holding a mutex lock in a blocking operation.
2. Add timeout control for EtcdClient get and put operations to prevent possible goroutine leak in openapi.
rZvF5Nx4BM
3. Remove redundant retry operations in `(*openApi).forwardToOwner`

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
`Fix a bug that openapi may be stuck when pd is abnormal`
```

### CODE REVIEW

File: cdc/capture/capture.go [hunk 1]
```diff
@@ -118,9 +118,17 @@ func NewCapture4Test(o owner.Owner) *Capture {
 }
 
 func (c *Capture) reset(ctx context.Context) error {
+	conf := config.GetGlobalServerConfig()
```
Comment (ben1009) [inline cdc/capture/capture.go:121]: do we need ut cover the change?

Comment (CharlesCheung96) [reply cdc/capture/capture.go:121]: Done, PTAL

File: pkg/etcd/client.go [hunk 2]
```diff
@@ -149,8 +158,10 @@ func (c *Client) Txn(ctx context.Context, cmps []clientv3.Cmp, opsThen, opsElse
 // Grant delegates request to clientv3.Lease.Grant
 func (c *Client) Grant(ctx context.Context, ttl int64) (resp *clientv3.LeaseGrantResponse, err error) {
 	err = retryRPC(EtcdGrant, c.metrics[EtcdGrant], func() error {
+		grantCtx, cancel := context.WithTimeout(ctx, etcdClientTimeoutWithoutRetry)
```
Comment (amyangfei) [inline pkg/etcd/client.go:161]: Should we use `etcdClientTimeoutWithRetry` here?

File: pkg/etcd/client.go [hunk 3]
```diff
@@ -181,8 +192,10 @@ func isRetryableError(rpcName string) retry.IsRetryable {
 // Revoke delegates request to clientv3.Lease.Revoke
 func (c *Client) Revoke(ctx context.Context, id clientv3.LeaseID) (resp *clientv3.LeaseRevokeResponse, err error) {
 	err = retryRPC(EtcdRevoke, c.metrics[EtcdRevoke], func() error {
+		revokeCtx, cancel := context.WithTimeout(ctx, etcdClientTimeoutWithoutRetry)
```
Comment (amyangfei) [inline pkg/etcd/client.go:195]: ditto

File: pkg/etcd/client.go [hunk 4]
```diff
@@ -191,8 +204,10 @@ func (c *Client) Revoke(ctx context.Context, id clientv3.LeaseID) (resp *clientv
 // TimeToLive delegates request to clientv3.Lease.TimeToLive
 func (c *Client) TimeToLive(ctx context.Context, lease clientv3.LeaseID, opts ...clientv3.LeaseOption) (resp *clientv3.LeaseTimeToLiveResponse, err error) {
 	err = retryRPC(EtcdRevoke, c.metrics[EtcdRevoke], func() error {
+		timeToLiveCtx, cancel := context.WithTimeout(ctx, etcdClientTimeoutWithoutRetry)
```
Comment (amyangfei) [inline pkg/etcd/client.go:207]: ditto

File: cdc/capture/main_test.go [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+
+	"github.com/pingcap/tiflow/pkg/leakutil"
+	"go.uber.org/goleak"
+)
+
+func TestMain(m *testing.M) {
+	opts := []goleak.Option{
+		// TODO: temporarily ignore leaking goroutines
+		goleak.IgnoreTopFunction("google.golang.org/grpc.(*ccBalancerWrapper).watcher"),
+		goleak.IgnoreTopFunction("google.golang.org/grpc.(*addrConn).resetTransport"),
```
Comment (amyangfei) [inline cdc/capture/main_test.go:27]: Why didn't the gRPC goroutines exit in test case?

File: cdc/capture/capture_test.go [hunk 6]
```diff
@@ -0,0 +1,79 @@
+// Copyright 2021 PingCAP, Inc.
```
Comment (amyangfei) [inline cdc/capture/capture_test.go:1]:
```suggestion
// Copyright 2022 PingCAP, Inc.
```

File: cdc/capture/capture.go [hunk 7]
```diff
@@ -605,6 +606,8 @@ func (c *Capture) WriteDebugInfo(ctx context.Context, w io.Writer) {
 	if c.processorManager != nil {
 		fmt.Fprintf(w, "\n\n*** processors info ***:\n\n")
 		c.processorManager.WriteDebugInfo(ctx, w, doneM)
+	} else {
+		close(doneM)
```
Comment (amyangfei) [inline cdc/capture/capture.go:610]: Is this an existing bug, how can it be reproduced?

File: pkg/etcd/client.go (hunk 2 above)
Comment (CharlesCheung96) [reply pkg/etcd/client.go:161]: We need to ensure that it returns in a reasonable amount of time, otherwise the operation may never retry due to [blocking](https://github.com/pingcap/tiflow/blob/ce83af5ad9c2ad148aab73ca620367d9cfc6fca0/pkg/etcd/client.go#L96).

File: cdc/api/open.go [hunk 8]
```diff
@@ -795,16 +792,9 @@ func (h *openAPI) forwardToOwner(c *gin.Context) {
...
-	err := retry.Do(ctx, func() error {
-		o, err := h.capture.GetOwnerCaptureInfo(ctx)
-		if err != nil {
-			log.Info("get owner failed, retry later", zap.Error(err))
-			return err
-		}
-		owner = o
-		return nil
-	}, retry.WithBackoffBaseDelay(300), retry.WithMaxTries(getOwnerRetryMaxTime))
+	owner, err := h.capture.GetOwnerCaptureInfo(ctx)
```
Comment (amyangfei) [inline cdc/api/open.go:795]: Why do we remove retry here

Comment (CharlesCheung96) [reply cdc/api/open.go:795]: GetOwnerCaptureInfo already has an internal retry mechanism:
1. https://github.com/pingcap/tiflow/blob/master/cdc/capture/capture.go#L616-L621
2. https://github.com/pingcap/tiflow/blob/master/pkg/etcd/etcd.go#L223
3. https://github.com/pingcap/tiflow/blob/master/pkg/etcd/etcd.go#L559

**Review by amyangfei — APPROVED** [review]

**Review by overvenus — APPROVED** [review]
