### PR TITLE
ci(dm): Fix DM `import_v10x` Test Failure Due to TiDB int Type Display Change

### LINKED ISSUE #11680: dm: import_v10x Test Case Fails in DM CI Due to Recent Changes in TiDB
### What did you do?

I submitted a PR to the TiFlow repository, but one of the DM test cases in the GitHub CI, import_v10x, keeps failing. The failure is caused by recent changes in TiDB, specifically in how the default int type is displayed when executing the SHOW CREATE TABLE statement. ref: https://github.com/pingcap/tidb/pull/56529

### What did you expect to see?

import_v10x test passes.

### What did you see instead?

import_v10x test failed.

CleanShot 2024-10-23 at 12 30 01@2x

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
(paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by wlwilliamx**
### What problem does this PR solve?

Issue Number: close #11680

This PR fixes the import_v10x test case in DM’s CI, which has been failing due to recent changes in TiDB. TiDB modified how the default int type is displayed when using the SHOW CREATE TABLE statement, causing the test to break. ref: https://github.com/pingcap/tidb/pull/56529

### What is changed and how it works?

I have updated the import_v10x test to accommodate the changes made in TiDB’s handling of int types in SHOW CREATE TABLE. This ensures compatibility with the latest version of TiDB and prevents the test from failing in future CI runs.

#### Tests 

 - Unit test
 - Integration test

##### Will it cause performance regression or break compatibility?

No.

##### Do you need to update user documentation, design documentation or monitoring documentation?

No.

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by wlwilliamx** [comment]
cc @lance6716

File: dm/tests/import_v10x/run.sh [hunk 1]
```diff
@@ -88,7 +88,7 @@ function run() {
 	run_sql "show create table \`dm_meta\`.\`test_syncer_checkpoint\`" $TIDB_PORT $TIDB_PASSWORD
 	check_contains "\`exit_safe_binlog_name\` varchar(128) DEFAULT ''"
 	# different TiDB will output DEFAULT 0 or DEFAULT '0'
-	check_contains "\`exit_safe_binlog_pos\` int(10) unsigned DEFAULT "
+	check_contains "\`exit_safe_binlog_pos\` int unsigned DEFAULT "
```
Comment (lance6716) [inline dm/tests/import_v10x/run.sh:91]:
```suggestion
	check_contains "\`exit_safe_binlog_pos\` int"
```

Also handle different versions of downstream TiDB

**Review by lance6716 — APPROVED** [review]
rest lgtm

**Review by asddongmen — APPROVED** [review]
