### PR TITLE
sink(ticdc): adjust sql mode compatibility for mysql sink

### LINKED ISSUE #3810: Session SQL mode causes failures
### What did you do?

# Setup
Setup two TiDB clusters and a MySQL Server.
```
tiup -T src playground --tiflash 0 --without-monitor v5.3.0
tiup -T dst playground --db.port 4001 --tiflash 0 --without-monitor v5.3.0
dbdeployer deploy single 8.0.27
```

Setup changefeeds to replicate data from "src" to "dst" (TiDB-to-TiDB) and "src" to "mysql" (TiDB-to-MySQL):
```
./bin/cdc server --pd=http://127.0.0.1:2379
./bin/cdc cli changefeed create --sink-uri="mysql://root@127.0.0.1:4001/" --changefeed-id="tidb-tidb-1"
./bin/cdc cli changefeed create --sink-uri="mysql://root:msandbox@127.0.0.1:8027/" --changefeed-id="tidb-mysql-1"
```

# Test

On src:
```sql
CREATE SCHEMA cdctest;
USE cdctest;
CREATE TABLE t1(id int primary key);
INSERT INTO t1 VALUES(1);
```
Now check on dst and mysql, this should show the `cdctest.t1` table with one row.

On src again:
```sql
SET sql_mode='';
CREATE TABLE t2 (id int primary key auto_increment, c1 timestamp not null);
INSERT INTO t2(c1) VALUES(CURRENT_TIMESTAMP);
INSERT INTO t2(c1) VALUES('0000-00-00 00:00:00');
TABLE t2;
```

### What did you expect to see?

`cdctest.t2` being replicated to the target databases with 2 rows.

### What did you see instead?

```
[2021/12/09 10:27:51.692 +01:00] [WARN] [mysql.go:935] ["execute DMLs with error, retry later"] [error="[CDC:ErrMySQLTxnError]Error 1292: Incorrect datetime value: '0000-00-00 00:00:00' for column 'c1' at row 1: Error 1292: Incorrect datetime value: '0000-00-00 00:00:00' for column 'c1' at row 1"] [errorVerbose="[CDC:ErrMySQLTxnError]Error 1292: Incorrect datetime value: '0000-00-00 00:00:00' for column 'c1' at row 1: Error 1292: Incorrect datetime value: '0000-00-00 00:00:00' for column 'c1' at row 1\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20210513014640-40f9a1999b3b/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByCause\n\tgithub.com/pingcap/errors@v0.11.5-0.20210513014640-40f9a1999b3b/normalize.go:302\ngithub.com/pingcap/ticdc/pkg/errors.WrapError\n\tgithub.com/pingcap/ticdc/pkg/errors/helper.go:30\ngithub.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDMLWithMaxRetries.func1.3\n\tgithub.com/pingcap/ticdc/cdc/sink/mysql.go:985\ngithub.com/pingcap/ticdc/cdc/sink.(*Statistics).RecordBatchExecution\n\tgithub.com/pingcap/ticdc/cdc/sink/statistics.go:112\ngithub.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDMLWithMaxRetries.func1\n\tgithub.com/pingcap/ticdc/cdc/sink/mysql.go:972\ngithub.com/pingcap/ticdc/pkg/retry.run\n\tgithub.com/pingcap/ticdc/pkg/retry/retry_with_opt.go:54\ngithub.com/pingcap/ticdc/pkg/retry.Do\n\tgithub.com/pingcap/ticdc/pkg/retry/retry_with_opt.go:32\ngithub.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDMLWithMaxRetries\n\tgithub.com/pingcap/ticdc/cdc/sink/mysql.go:964\ngithub.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDMLs\n\tgithub.com/pingcap/ticdc/cdc/sink/mysql.go:1125\ngithub.com/pingcap/ticdc/cdc/sink.(*mysqlSinkWorker).run.func3\n\tgithub.com/pingcap/ticdc/cdc/sink/mysql.go:820\ngithub.com/pingcap/ticdc/cdc/sink.(*mysqlSinkWorker).run\n\tgithub.com/pingcap/ticdc/cdc/sink/mysql.go:858\ngithub.com/pingcap/ticdc/cdc/sink.(*mysqlSink).createSinkWorkers.func1\n\tgithub.com/pingcap/ticdc/cdc/sink/mysql.go:661\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
```

After `SET GLOBAL sql_mode='' on dst and mysql and waiting for retry the data was synced.

### Versions of the cluster

TiDB: v5.3.0
MySQL: 8.0.27
CDC: v5.3.0

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve? 

Close #3810.

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by maxshuang — APPROVED** [review]

**Comment by ben1009** [comment]
test fail

File: cdc/sink/mysql.go [hunk 1]
```diff
@@ -348,8 +353,26 @@ func needSwitchDB(ddl *model.DDLEvent) bool {
 	return true
 }
 
+func (s *mysqlSink) adjustSQLModeCompatible(ctx context.Context) error {
+	var oldMode, newMode string
+	row := s.db.QueryRowContext(ctx, "SELECT @@SESSION.sql_mode;")
```
Comment (lance6716) [inline cdc/sink/mysql.go:358]: `s.db` is a `sql.DB` so some session-level changes may get lost after the inner connection is released to the connection pool of `sql.DB` in my memory

**Comment by maxshuang** [comment]
A little question: 
Do we need a unit test to cover some detail scenes, like "0000-00-00 00:00:00" for timestamp? Or mockDB is sufficient  for this case?

**Comment by hicqu** [comment]
> A little question: Do we need a unit test to cover some detail scenes, like "0000-00-00 00:00:00" for timestamp? Or mockDB is sufficient for this case?

It's relative about how a sql mode handles uncompatible records. I think it's unnecessary because it's already described by MySQL document. So just testing the result of "select sql_mode from downstream" is enough.

File: cdc/sink/mysql.go [hunk 2]
```diff
@@ -130,6 +131,28 @@ func newMySQLSink(
...
+	// Adjust sql_mode for cyclic replication.
+	var sinkCyclic *cyclic.Cyclic = nil
+	if val, ok := opts[mark.OptCyclicConfig]; ok {
+		cfg := new(config.CyclicConfig)
+		err := cfg.Unmarshal([]byte(val))
+		if err != nil {
+			return nil, cerror.WrapError(cerror.ErrMySQLInvalidConfig, err)
+		}
+		sinkCyclic = cyclic.NewCyclic(cfg)
+		dsn.Params["sql_mode"] = cyclic.RelaxSQLMode(dsn.Params["sql_mode"])
```
Comment (lance6716) [inline cdc/sink/mysql.go:153]: seems the effect of `RelaxSQLMode` is to remove `STRICT_TRANS_TABLES`, and `dmutils.AdjustSQLModeCompatible` has already done it.

**Review by lance6716 — COMMENTED** [review]
rest lgtm

File: cdc/sink/mysql.go (hunk 2 above)
Comment (hicqu) [reply cdc/sink/mysql.go:153]: Yes you found it. However I prefer to keep both of them because they have different semantics although they do similar things.

**Review by lance6716 — APPROVED** [review]

**Comment by overvenus** [comment]
/run-/dm-integration-test
