### PR TITLE
api(ticdc): Check min service gc safepoint when resume changefeed

### LINKED ISSUE #10463: cdc gets wrong pd gc safe point and causes changefeed exceeds gc ttl wrongly
### What did you do?

1.  cdc shows gc safe point is 446948031767773184
img_v3_0271_e89e428e-48fb-4144-ba65-48c7ad127e9g
2. but pd-ctl shows service-gc-safepoint is 446932460422299648
img_v3_0271_4d0c46ee-f801-4c44-8c87-acbd7c2c910g
3. and tikv metrics about gc is also same with service-gc-safepoint
img_v3_0271_05ed7c1e-0056-4562-9daa-de46e8301b5g
4. this may cause ticdc exceed gc ttl in error
img_v3_0271_c7de1557-f026-4af7-a487-36449fc19afg

### What did you expect to see?

_No response_

### What did you see instead?

cdc gets wrong pd gc safe point and causes changefeed exceeds gc ttl wrongly

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```

### PR DESCRIPTION
**Pull request by sdojjy**
### What problem does this PR solve?

Issue Number: close #10463

### What is changed and how it works?
currently, when the user resumes a failed changefeed,  CDC does not do any GC safe point checking even if the data is already GCed. After this PR,  when the user resumes a changefeed, CDC checks weather the current checkpoint ts is smaller than the min service gc safepoint or not.  If smaller,  ticdc open API will return an `ErrStartTsBeforeGC` error.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

File: cdc/api/v2/api_helpers.go [hunk 1]
```diff
@@ -400,9 +401,19 @@ func (APIV2HelpersImpl) verifyResumeChangefeedConfig(ctx context.Context,
 	pdClient pd.Client,
 	gcServiceID string,
 	changefeedID model.ChangeFeedID,
-	checkpointTs uint64,
+	currentCheckpointTs uint64,
+	overrideCheckpointTs uint64,
 ) error {
-	if checkpointTs == 0 {
+	// not override checkpoint ts, check if the current checkpoint ts is before gc safepoint
+	if overrideCheckpointTs == 0 {
```
Comment (CharlesCheung96) [inline cdc/api/v2/api_helpers.go:408]: Maybe we can reuse `txutil.EnsureChangefeedStartTsSafety` here?

File: cdc/api/v2/api_helpers.go [hunk 2]
```diff
@@ -92,7 +92,8 @@ type APIV2Helpers interface {
 		pdClient pd.Client,
 		gcServiceID string,
 		changefeedID model.ChangeFeedID,
-		checkpointTs uint64,
+		currentCheckpointTs uint64,
+		overrideCheckpointTs uint64,
```
Comment (flowbehappy) [inline cdc/api/v2/api_helpers.go:96]: Better to add  some comments to explain what is the different between `currentCheckpointTs` and `overrideCheckpointTs`.

File: cdc/api/v2/api_helpers.go [hunk 3]
```diff
@@ -400,9 +401,19 @@ func (APIV2HelpersImpl) verifyResumeChangefeedConfig(ctx context.Context,
 	pdClient pd.Client,
 	gcServiceID string,
 	changefeedID model.ChangeFeedID,
-	checkpointTs uint64,
+	currentCheckpointTs uint64,
+	overrideCheckpointTs uint64,
 ) error {
-	if checkpointTs == 0 {
+	// not override checkpoint ts, check if the current checkpoint ts is before gc safepoint
```
Comment (flowbehappy) [inline cdc/api/v2/api_helpers.go:407]:
```suggestion
	// If there is no overrideCheckpointTs, then check whether the currentCheckpointTs is smaller than gc safepoint or not.
```

File: cdc/api/v2/api_helpers.go [hunk 4]
```diff
@@ -400,9 +401,19 @@ func (APIV2HelpersImpl) verifyResumeChangefeedConfig(ctx context.Context,
...
 	gcServiceID string,
 	changefeedID model.ChangeFeedID,
-	checkpointTs uint64,
+	currentCheckpointTs uint64,
+	overrideCheckpointTs uint64,
 ) error {
-	if checkpointTs == 0 {
+	// If there is no overrideCheckpointTs, then check whether the currentCheckpointTs is smaller than gc safepoint or not.
+	if overrideCheckpointTs == 0 {
+		// use safePoint 0 and ttl 0 to get the minServiceGCSafePoint, this gc service will not be saved to pd
```
Comment (flowbehappy) [inline cdc/api/v2/api_helpers.go:409]:
```suggestion
		// Use safePoint 0 and ttl 0 to get the minServiceGCSafePoint. Note that this gc service safe point will not be saved to pd.
```

File: cdc/api/v2/api_helpers.go (hunk 2 above)
Comment (sdojjy) [reply cdc/api/v2/api_helpers.go:96]: done

File: cdc/api/v2/api_helpers.go [hunk 5]
```diff
@@ -396,14 +397,21 @@ func (APIV2HelpersImpl) verifyUpdateChangefeedConfig(
 	return newInfo, newUpInfo, nil
 }
 
+// verifyResumeChangefeedConfig verifies the changefeed config before resuming a changefeed
+// currentCheckpointTs is the checkpointTs of the changefeed before it is paused.
+// overrideCheckpointTs is the checkpointTs of the changefeed that specified by the user.
+// overrideCheckpointTs is 0 if the user does not specify it. otherwise it can be smaller or greater than currentCheckpointTs.
```
Comment (asddongmen) [inline cdc/api/v2/api_helpers.go:403]:
```suggestion
// overrideCheckpointTs is 0 if the user does not specify it.  It can be smaller or greater than currentCheckpointTs.
```

**Review by asddongmen — APPROVED** [review]

**Review by flowbehappy — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]
