### PR TITLE
kafka(ticdc): ddl sink close the underline sink if send ddl or checkpoint failed and refactor the kafka ddl sink

### LINKED ISSUE #12096: cdc:kafka consumer got partition resolved ts fallback when ticdc and kafka got network partition
### What did you do?

1. open kafka changefeed
2. inject network partition chaos between ticdc and kafka

### What did you expect to see?

no error

### What did you see instead?

[2025/03/13 16:17:35.372 +08:00] [PANIC] [writer.go:103] ["partition resolved ts fallback"] [partition=1] [newWatermark=456615706631340446] [offset=8418122] [watermark=456615720538341892] [watermarkOffset=8416182] [stack="main.(*partitionProgress).updateWatermark\n\tgithub.com/pingcap/tiflow/cmd/kafka-consumer/writer.go:103\nmain.(*writer).WriteMessage\n\tgithub.com/pingcap/tiflow/cmd/kafka-consumer/writer.go:392\nmain.(*consumer).Consume\n\tgithub.com/pingcap/tiflow/cmd/kafka-consumer/consumer.go:139\nmain.main.func2\n\tgithub.com/pingcap/tiflow/cmd/kafka-consumer/main.go:98"]

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
master
```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):
master
```console
(paste TiCDC version here)
```

### LINKED ISSUE #12666: Kafka DDL sink leaks Kafka client instances when retrying
### What did you do?

1. Just keep a Kafka changefeed running for several weeks.
2. Observe the memory usage.

### What did you expect to see?

3. The memory usage should be stable.

### What did you see instead?

4. Instead, the memory usage gradually increases at roughly 4 GiB per day.

### Versions of the cluster

v7.5.6

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number:  close #12666, close #12096

### What is changed and how it works?

* owner/ddl_sink should close if meet any error, and rebuilt by the retry.
* kafka factory implementations should wrap error immediately, and caller should just return error, no need to trace the error.
* kafka ddl sink use encoder directly, instead of encoderBuilder
* syncProducer no need to close in a goroutine, since it only deliver one message at a time, won't be blocked if the downstream kafka cluster unavailable.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by wk989898 — APPROVED** [review]

File: pkg/sink/kafka/factory.go [hunk 1]
```diff
@@ -112,49 +111,25 @@ func (p *saramaSyncProducer) SendMessages(ctx context.Context, topic string, par
...
-		// Factory has a background thread to fetch and update the metadata.
-		// If we close the client synchronously, we might get stuck.
-		// Safety:
-		// * If the kafka cluster is running well, it will be closed as soon as possible.
-		// * If there is a problem with the kafka cluster,
-		//   no data will be lost because this is a synchronous client.
-		// * There is a risk of goroutine leakage, but it is acceptable and our main
-		//   goal is not to get stuck with the owner tick.
-		start := time.Now()
-		if err := p.client.Close(); err != nil {
```
Comment (hicqu) [inline pkg/sink/kafka/factory.go:131]: Why not close the clint any more?

Comment (3AceShowHand) [reply pkg/sink/kafka/factory.go:131]: client is removed, sync producer is initialized directly

**Review by hongyunyan — APPROVED** [review]
