### PR TITLE
owner(ticdc): update changefeed configuration changefeed-error-stuck-duration correctly

### LINKED ISSUE #10998: update of changefeed configiration changefeed-error-stuck-duration not working
### What did you do?

1. creaet an kafka changefeed with default configuration (changefeed-error-stuck-duration default 30m)
2. pause and update changefeed, set changefeed-error-stuck-duration to 90m
3. resume changefed
4. Inject network partition between cdc and kafka for 60m

### What did you expect to see?

CDC should be able to tolerate network partition between cdc and kafka for 90m, before that CDC changefeed should not be in failed state.

### What did you see instead?

CDC changefeed in failed state after 30m.
image
img_v3_02a9_30a1b0ad-2ddb-4312-a945-f6d39177706g

### Versions of the cluster

master

### PR DESCRIPTION
**Pull request by wk989898**
### What problem does this PR solve?

Issue Number: close #10998

### What is changed and how it works?
When changefeed state has changed, reacquiring `changefeed-error-stuck-duration`. `feedStateManager` checks for new value about `changefeedErrorStuckDuration` every `feedStateManager.Tick` call so that it can sense the updated value.

#### Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)
    1. start a CDC server
    2. run script
    ```bash
    bin/cdc cli changefeed create -c test --sink-uri "kafka://127.0.0.1:9092/test?topic=test&protocol=open-protocol&max-message-bytes=41943040&compressionType=ZLIB" --changefeed-id="test"
    bin/cdc cli changefeed pause --changefeed-id="test"
    bin/cdc cli changefeed update --changefeed-id="test" --config=changefeed.toml
    bin/cdc cli changefeed resume --changefeed-id="test"
    ```
    changefeed.toml
    ```toml
     changefeed-error-stuck-duration = "1h30m"
    ```
    3. check CDC log
    Screenshot 2024-05-11 at 17 05 18

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
None
```

### CODE REVIEW

File: cdc/owner/feed_state_manager.go [hunk 1]
```diff
@@ -168,6 +168,15 @@ func (m *feedStateManager) Tick(resolvedTs model.Ts,
 		// `handleAdminJob` returns true means that some admin jobs are pending
 		// skip to the next tick until all the admin jobs is handled
 		adminJobPending = true
+		changefeedErrorStuckDuration := *m.state.GetChangefeedInfo().Config.ChangefeedErrorStuckDuration
```
Comment (CharlesCheung96) [inline cdc/owner/feed_state_manager.go:171]: Use `util.GetOrZero` to avoid possible nil pointer dereference

File: cdc/owner/feed_state_manager.go [hunk 2]
```diff
@@ -168,6 +169,15 @@ func (m *feedStateManager) Tick(resolvedTs model.Ts,
...
 		// skip to the next tick until all the admin jobs is handled
 		adminJobPending = true
+		changefeedErrorStuckDuration := util.GetOrZero(m.state.GetChangefeedInfo().Config.ChangefeedErrorStuckDuration)
+		if m.changefeedErrorStuckDuration != changefeedErrorStuckDuration {
+			log.Info("changefeedErrorStuckDuration update",
+				zap.Duration("oldChangefeedErrorStuckDuration", m.changefeedErrorStuckDuration),
+				zap.Duration("newChangefeedErrorStuckDuration", changefeedErrorStuckDuration),
+			)
+		}
+		m.errBackoff.MaxElapsedTime = changefeedErrorStuckDuration
```
Comment (asddongmen) [inline cdc/owner/feed_state_manager.go:179]: Only rewrite it when it is updated.

**Comment by asddongmen** [comment]
Please also add an unit test case to cover this change.

**Review by asddongmen — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]
