### PR TITLE
sink(cdc): fix the check about resolvedTs and checkpointTs

### LINKED ISSUE #9769: table checkpoint-ts can be larger than redo-resolved-ts
### What did you do?

Here is a piece of TiCDC log:
```
egv-transactions-ch2-ticdc-2 ticdc [2023/09/15 20:04:27.713 +05:30] [INFO] [manager.go:850] ["Start table sink"] [namespace=default] [changefeed=egv-transactions-1-hyd] [tableID=74] [startTs=444278613643624570]
egv-transactions-ch2-ticdc-2 ticdc [2023/09/15 20:04:27.713 +05:30] [INFO] [table_sink_wrapper.go:145] ["Sink is started"] [namespace=default] [changefeed=egv-transactions-1-hyd] [tableID=74] [startTs=444278613643624570] [replicateTs=444278628074651689]
egv-transactions-ch2-ticdc-2 ticdc [2023/09/15 20:04:27.713 +05:30] [INFO] [processor.go:325] ["Add Table finished"] [captureID=18f5d46d-f065-4214-b118-b63dd3dc4fb9] [namespace=default] [changefeed=egv-transactions-1-hyd] [tableID=74] [tableResolvedTs=444278613643624570] [tableCheckpointTs=444278613643624570] [globalCheckpointTs=444278613643624570] [state=Replicating] [isPrepare=false]
egv-transactions-ch2-ticdc-2 ticdc [2023/09/15 20:04:27.813 +05:30] [ERROR] [manager.go:1019] ["sinkManager: resolved ts should not less than checkpoint ts"] [namespace=default] [changefeed=egv-transactions-1-hyd] [tableID=74] [resolvedTs=444278613643624570] [checkpointTs="{\"Mode\":0,\"Ts\":444278627681435676,\"BatchID\":18446744073709551615}"]
```

### What did you expect to see?

_No response_

### What did you see instead?

For a given table, checkpoint-ts is larger than redo-resolved-ts.
This check happens at `cdc/processor/sinkmanager/manager.go:1019`.
TiCDC version is `v6.5.4`.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by hicqu**
### What problem does this PR solve?

Issue Number: close #9769 

### What is changed and how it works?

* make owner scheduler broadcast correct ResolvedTs if redo is enbaled;
* correct the check about comparing resolvedTs and checkpointTs in processor;

#### Tests 

 - Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

File: cdc/scheduler/internal/v3/agent/agent.go [hunk 1]
```diff
@@ -275,25 +275,28 @@ func (a *agent) handleMessage(msg []*schedulepb.Message) (
 func (a *agent) handleMessageHeartbeat(request *schedulepb.Heartbeat) (
 	*schedulepb.Message, *schedulepb.Barrier, error,
 ) {
+	// NOTE: for a given table, we don't check ResolvedTs should never less than CheckpointTs
```
Comment (CharlesCheung96) [inline cdc/scheduler/internal/v3/agent/agent.go:278]: This cannot happen in the current implementation.

File: cdc/scheduler/internal/v3/replication/replication_manager.go [hunk 2]
```diff
@@ -573,6 +573,13 @@ func (r *Manager) AdvanceCheckpoint(
 		return true
 	})
 	if cannotProceed {
+		if redoMetaManager.Enabled() {
```
Comment (CharlesCheung96) [inline cdc/scheduler/internal/v3/replication/replication_manager.go:576]: Is it possible to abstract the redo processing logic (L576 and L634) into a function?

File: cdc/scheduler/internal/v3/replication/replication_manager_test.go [hunk 3]
```diff
@@ -652,11 +652,22 @@ func TestReplicationManagerAdvanceCheckpoint(t *testing.T) {
 	require.Equal(t, model.Ts(10), checkpoint)
 	require.Equal(t, model.Ts(20), resolved)
 
-	// some table not exist yet.
+	// some table not exist yet with redo is enabled.
 	currentTables.UpdateTables([]model.TableID{1, 2, 3})
-	checkpoint, resolved = r.AdvanceCheckpoint(currentTables, time.Now(), schedulepb.NewBarrierWithMinTs(30), redoMetaManager)
+	barrier := schedulepb.NewBarrierWithMinTs(30)
```
Comment (CharlesCheung96) [inline cdc/scheduler/internal/v3/replication/replication_manager_test.go:657]: Does the testing here reproduce the customer's problem? If so, maybe we should test redo scenior in a separate function, such as `TestReplicationManagerAdvanceCheckpointWithRedo`.

File: cdc/processor/sinkmanager/manager.go [hunk 4]
```diff
@@ -1008,14 +991,14 @@ func (m *SinkManager) GetTableStats(span tablepb.Span) TableStats {
...
+	if sinkUpperBound < checkpointTs.ResolvedMark() {
+		log.Panic("sinkManager: sink upperbound should not less than checkpoint ts",
 			zap.String("namespace", m.changefeedID.Namespace),
 			zap.String("changefeed", m.changefeedID.ID),
 			zap.Stringer("span", &span),
-			zap.Uint64("resolvedTs", resolvedTs),
-			zap.Any("checkpointTs", checkpointTs),
-			zap.Uint64("barrierTs", tableSink.barrierTs.Load()))
+			zap.Uint64("upperbound", sinkUpperBound),
+			zap.Any("checkpointTs", checkpointTs))
```
Comment (CharlesCheung96) [inline cdc/processor/sinkmanager/manager.go:1001]: Please print resolvedTs

File: cdc/scheduler/internal/v3/agent/agent.go [hunk 5]
```diff
@@ -272,28 +264,18 @@ func (a *agent) handleMessage(msg []*schedulepb.Message) (
...
 		}
 		result = append(result, status)
-		return isValidCheckpointTs
+		return true
 	})
-	if !isValidCheckpointTs {
-		status := result[len(result)-1]
-		checkpointTs := status.Checkpoint.CheckpointTs
-		resolvedTs := status.Checkpoint.ResolvedTs
-		return nil, nil, errors.ErrInvalidCheckpointTs.GenWithStackByArgs(checkpointTs, resolvedTs)
```
Comment (CharlesCheung96) [inline cdc/scheduler/internal/v3/agent/agent.go:295]: Why remove this check?

File: cdc/scheduler/internal/v3/replication/replication_manager.go [hunk 6]
```diff
@@ -512,6 +512,26 @@ func (r *Manager) AdvanceCheckpoint(
 	barrier *schedulepb.BarrierWithMinTs,
 	redoMetaManager redo.MetaManager,
 ) (newCheckpointTs, newResolvedTs model.Ts) {
+	limitBarrierWithRedo := func(newCheckpointTs, newResolvedTs *uint64) {
```
Comment (CharlesCheung96) [inline cdc/scheduler/internal/v3/replication/replication_manager.go:515]: Better use the return value, since it could be more clear, such as:
```go
limitWithRedo := func(newCheckpointTs, newResolvedTs uint64, needFlushMeta bool) (uint64, uint64) {
...
}

// calc newCheckpointTs and newResolvedTs

if redoMetaManager.Enabled() {
   return limitWithRedo(newCheckpointTs, newResolvedTs, needFlushMeta)
}
return newCheckpointTs, newResolvedTs
```

File: cdc/processor/sinkmanager/manager.go (hunk 4 above)
Comment (hicqu) [reply cdc/processor/sinkmanager/manager.go:1001]: I prefer to print upperbound instead, because we compare upperbound with checkpointTs.

**Review by asddongmen — APPROVED** [review]

File: cdc/scheduler/internal/v3/replication/replication_manager.go [hunk 7]
```diff
@@ -512,6 +512,38 @@ func (r *Manager) AdvanceCheckpoint(
...
+	var redoFlushedResolvedTs model.Ts
+	limitBarrierWithRedo := func(newCheckpointTs, newResolvedTs uint64) (uint64, uint64) {
+		flushedMeta := redoMetaManager.GetFlushedMeta()
+		redoFlushedResolvedTs = flushedMeta.ResolvedTs
+		log.Debug("owner gets flushed redo meta",
+			zap.String("namespace", r.changefeedID.Namespace),
+			zap.String("changefeed", r.changefeedID.ID),
+			zap.Uint64("flushedCheckpointTs", flushedMeta.CheckpointTs),
+			zap.Uint64("flushedResolvedTs", flushedMeta.ResolvedTs))
+		if flushedMeta.ResolvedTs != 0 && flushedMeta.ResolvedTs < newResolvedTs {
```
Comment (CharlesCheung96) [inline cdc/scheduler/internal/v3/replication/replication_manager.go:524]: `flushedMeta.ResolvedTs` should always be non-zero in curretn implementation.

**Review by CharlesCheung96 — APPROVED** [review]
