### PR TITLE
cdc/codec: fix string for unsigned value in canal-json.

### LINKED ISSUE #4635: cdc mounter encode default value for `unsigned` into `string`, cause `canal-json` panic.
### What did you do?

The problem is not reproduced yet.

When encoding `RowChangedEvent` by using the `Canal-JSON` , it make the assumption that `uint64` will be used for all `unsigned` SQL type. But it may meet `string`.

### What did you expect to see?

`Canal-JSON` should handle `string` for `unsigned` corrctly.

### What did you see instead?

CDC server panic.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.4.0
```

Upstream TiKV version (execute `tikv-server --version`):

```console
v5.4.0
```

TiCDC version (execute `cdc version`):

```console
v5.4.0
```

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #4635 

### What is changed and how it works?

handle the case when `unsigned` in `string`

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
fix `Canal-JSON` meet `unsigned` SQL typed in `string`, which cause CDC server panic.
```

### CODE REVIEW

File: cdc/sink/codec/canal.go [hunk 1]
```diff
@@ -133,38 +134,47 @@ func (b *canalEntryBuilder) buildHeader(commitTs uint64, schema string, table st
...
+	var number uint64
+	switch v := c.Value.(type) {
+	case uint64:
+		number = v
+	case string:
+		a, err := strconv.ParseUint(v, 10, 64)
+		if err != nil {
+			return javaType, err
+		}
+		number = a
```
Comment (liuzix) [inline cdc/sink/codec/canal.go:175]: Do we have a unit test case covering this?

File: cdc/sink/codec/canal.go [hunk 2]
```diff
@@ -133,38 +134,47 @@ func (b *canalEntryBuilder) buildHeader(commitTs uint64, schema string, table st
...
+	default:
+		return javaType, errors.Errorf("unexpected type for unsigned value: %+v", reflect.TypeOf(v))
```
Comment (maxshuang) [inline cdc/sink/codec/canal.go:177]: Pls don't remove zap.Any("column", c), it will offer detail infomation.
Others LGTM.

**Review by maxshuang — APPROVED** [review]

**Review by overvenus — APPROVED** [review]
