### PR TITLE
changefeed(ticdc): fix barrier ts set incorrectly cause monitor become year

### LINKED ISSUE #11553: barrierTs metrics is inaccurate
image

As shown in the image above, the `barrierTs` is set to a impossible year.

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #11553 

### What is changed and how it works?

* use `MinTableBarrierTs` as the checkpoint barrier.

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

File: cdc/owner/changefeed.go [hunk 1]
```diff
@@ -970,6 +968,7 @@ func (c *changefeed) handleBarrier(ctx context.Context,
 		barrier.MinTableBarrierTs = barrierTs
 	}
 
+	c.metricsChangefeedBarrierTsGauge.Set(float64(oracle.ExtractPhysical(barrier.MinTableBarrierTs)))
```
Comment (CharlesCheung96) [inline cdc/owner/changefeed.go:971]: Please add some comments to explain that MinTableBarrierTs is always the next barrier that blocking the gloabal resolvedTs.

**Review by CharlesCheung96 — APPROVED** [review]
