### PR TITLE
sink(ticdc): fix incorrect `default` field

### LINKED ISSUE #12037: incorrect default value after altering an ADDed column from NOT NULL to NULL
### What did you do?

run sql
```sql
create table t1(
    id int primary key
);
alter table t1 add column col json not null;
alter table t1 modify column col json default null;
insert into t1(id) values(1);
```

### What did you expect to see?

the default value of `col` should be null

### What did you see instead?

the default value of `col` is string literal "null"

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
master
```

TiCDC version (execute `cdc version`):

```console
master
```

### PR DESCRIPTION
**Pull request by wk989898**
### What problem does this PR solve?

Issue Number: close #12037

### What is changed and how it works?
`OriginDefaultValue` is used as the column value when the default value is invisible. 
It should not be used as the `default` field.

**Affected protocol**
- Cloud Storage
- Simple
- Avro
- Debezium

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
fix incorrect `default` field.
```

### CODE REVIEW

**Review by flowbehappy — APPROVED** [review]

File: cdc/model/schema_storage.go [hunk 1]
```diff
@@ -501,9 +501,6 @@ func (ti *TableInfo) GetPrimaryKeyColumnNames() []string {
 // GetColumnDefaultValue returns the default definition of a column.
 func GetColumnDefaultValue(col *model.ColumnInfo) interface{} {
 	defaultValue := col.GetDefaultValue()
```
Comment (3AceShowHand) [inline cdc/model/schema_storage.go:503]: It looks can return the `col.GetDefaultValue()` directly.

**Comment by 3AceShowHand** [comment]
Is the method `GetColumnDefaultValue` only used by encoding protocols ?

Will this modification also affect other components?

**Comment by wk989898** [comment]
> Is the method `GetColumnDefaultValue` only used by encoding protocols ?
> 
> Will this modification also affect other components?

I tracked this method and found it was only used in the schema encoding.

**Comment by 3AceShowHand** [comment]
`GetColumnDefaultValue` can be removed, just call `col.GetDefaultValue()` should works.

**Review by lidezhu — APPROVED** [review]
LGTM

**Review by asddongmen — APPROVED** [review]
