### PR TITLE
bugfix: fix update statement execute error in safemode cause dm-worker panic

### LINKED ISSUE #4317: panic when executeBatchJobs meet error
### What did you do?

make a slow downstrem and decrease sycner's maxDMLConnectionTimeout
so every execSQL will meet a timeout error

---
```
[2022/01/13 14:33:19.604 +08:00] [ERROR] [db.go:221] ["execute statements failed after retry"] [task=test] [unit="binlog replication"] [queries="[DELETE FROM `sspanel`.`sspanel_user` WHERE `id` = ? LIMIT 1 REPLACE INTO `sspanel`.`sspanel_user` (`id`,`password`,`last_login`,`is_superuser`,`username`,`first_name`,`last_name`,`email`,`is_staff`,`is_active`,`date_joined`,`inviter_id`,`balance`,`invitecode_num`,`level`,`level_expire_time`,`theme`,`vmess_uuid`,`download_traffic`,`last_use_time`,`ss_password`,`ss_port`,`total_traffic`,`upload_traffic`,`uid`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)]"] [arguments="[[7] [7 ehco1 <nil> 1 1 1 1 1 1 1 2022-01-11 09:56:23.000000 1 <nil> 1 1 2022-01-11 09:56:38.000000 d 1 0 <nil> 1 1 1 1 <nil>]]"] [error="[code=10006:class=database:scope=not-set:level=high], Message: execute statement failed: REPLACE INTO `sspanel`.`sspanel_user` (`id`,`password`,`last_login`,`is_superuser`,`username`,`first_name`,`last_name`,`email`,`is_staff`,`is_active`,`date_joined`,`inviter_id`,`balance`,`invitecode_num`,`level`,`level_expire_time`,`theme`,`vmess_uuid`,`download_traffic`,`last_use_time`,`ss_password`,`ss_port`,`total_traffic`,`upload_traffic`,`uid`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?), RawCause: invalid connection"]
panic: runtime error: index out of range [1] with length 1

goroutine 750 [running]:
github.com/pingcap/tiflow/dm/syncer.(*DMLWorker).executeBatchJobs.func1(0x14005947e98, 0x14005dbebb0, 0x0, 0x14005947ea8, {0x14004c79710, 0x1, 0x1}, 0x14005947e40)
	github.com/pingcap/tiflow/dm/syncer/dml_worker.go:209 +0xb4
github.com/pingcap/tiflow/dm/syncer.(*DMLWorker).executeBatchJobs(0x14005dbebb0, 0x0, {0x14004c79710, 0x1, 0x1})
	github.com/pingcap/tiflow/dm/syncer/dml_worker.go:248 +0x3dc
github.com/pingcap/tiflow/dm/syncer.(*DMLWorker).executeJobs(0x14005dbebb0, 0x0, 0x14005e39f80)
	github.com/pingcap/tiflow/dm/syncer/dml_worker.go:180 +0x330
created by github.com/pingcap/tiflow/dm/syncer.(*DMLWorker).run
	github.com/pingcap/tiflow/dm/syncer/dml_worker.go:102 +0xac
```

## RootCause

https://github.com/pingcap/tiflow/blob/0cd880f6887f4626ba1516e8b48b7b72a9c87233/dm/syncer/dml_worker.go#L209

use wrong job index `affect` 
should use `affect-1` and check `jobs` length beacuse `affect` always equal  to job count in one batch
https://github.com/pingcap/tiflow/blob/0cd880f6887f4626ba1516e8b48b7b72a9c87233/dm/pkg/conn/baseconn.go#L154

### What did you expect to see?

task paused but worker still alive

### What did you see instead?

worker panic

### Versions of the cluster

master

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: close #4317

### What is changed and how it works?

- when update job split into multiple dmls(delete + replace), len(dmls)>len(jobs), we should determine the error dml is generated from which job
- - when in multipleRows mode, we combine multiple jobs into one dml, if dml execute failed, we cannot determine which job it is 

so simply use the first job when meet error and `len(jobs)!=len(dmls)`, which not affect other feature.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
Fix the issue that update statement execute error in safemode may cause DM-worker panic.
```

### CODE REVIEW

File: dm/syncer/dml_worker.go [hunk 1]
```diff
@@ -196,17 +196,24 @@ func (w *DMLWorker) executeJobs(queueID int, jobCh chan *job) {
...
 	defer func() {
 		if err == nil {
 			w.successFunc(queueID, len(dmls), jobs)
 		} else {
-			w.fatalFunc(jobs[affect], err)
+			if len(queries) == len(jobs) {
+				w.fatalFunc(jobs[affect], err)
+			} else {
+				w.logger.Warn("length of queries not equals length of jobs, cannot determine which job failed, use first one instead", zap.Int("queries", len(queries)), zap.Int("jobs", len(jobs)))
+				w.fatalFunc(jobs[0], err)
```
Comment (glorv) [inline dm/syncer/dml_worker.go:215]: Since we can determine the exact job that trigger this failure, we should add a log about the first and last job's binlog location. Or maybe we can create a new job with the start location of the first job and end location of the last job.

**Review by glorv — APPROVED** [review]
LGTM

File: dm/syncer/dml_worker.go (hunk 1 above)
Comment (GMHDBJD) [reply dm/syncer/dml_worker.go:215]: May not, if we want to inject DDL before the error DDL, the first job is better then all jobs.

**Review by lichunzhu — APPROVED** [review]
LGTM
