### PR TITLE
validator(dm): fix dmworker panic due to validator

### LINKED ISSUE #5184: starting validator makes dmworker panic
### What did you do?

1. start task with validator on
2. `dmctl query-status`

### What did you expect to see?

print the status of the worker

### What did you see instead?

worker panicked and exited

### Versions of the cluster

commit: bca4b480792536d2548fc3a02c41ebd93f86e25f

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by buchuitoudegou**
### What problem does this PR solve?

Issue Number: close #5184 

### What is changed and how it works?
put off initializing workers until start validator workers.

### Check List 

Tests 

Code changes

Side effects

Related changes

### Release note 

```release-note
`None`
```

### CODE REVIEW

File: dm/syncer/data_validator.go [hunk 1]
```diff
@@ -571,6 +570,7 @@ func (v *DataValidator) Stage() pb.Stage {
 
 func (v *DataValidator) startValidateWorkers() {
 	v.wg.Add(v.workerCnt)
+	v.workers = make([]*validateWorker, v.workerCnt)
```
Comment (Ehco1996) [inline dm/syncer/data_validator.go:573]: which line panic,  can't understand why this fixes the problem, could you please explain more?

Comment (buchuitoudegou) [reply dm/syncer/data_validator.go:573]: ptal https://github.com/pingcap/tiflow/pull/5181#discussion_r852549354

**Comment by lance6716** [comment]
Add a test to avoid regression

File: dm/syncer/data_validator.go (hunk 1 above)
Comment (D3Hunter) [reply dm/syncer/data_validator.go:573]: v.workers has already inited here
https://github.com/pingcap/tiflow/blob/56ccdf2178468331687ae2f07e83e38111811b27/dm/syncer/data_validator.go#L174

it panics here? not checks worker:
https://github.com/pingcap/tiflow/blob/56ccdf2178468331687ae2f07e83e38111811b27/dm/syncer/validator_checkpoint.go#L191

maybe we should init this field when create workers

Comment (buchuitoudegou) [reply dm/syncer/data_validator.go:573]: > v.workers has already inited here
> 
> https://github.com/pingcap/tiflow/blob/56ccdf2178468331687ae2f07e83e38111811b27/dm/syncer/data_validator.go#L174

Yes, and I removed this to put off initializing the workers array till we start validating. 

https://github.com/pingcap/tiflow/blob/56ccdf2178468331687ae2f07e83e38111811b27/dm/syncer/validator_checkpoint.go#L191
> 
> maybe we should init this field when create workers

It's not because we didn't initialize worker's field but merely the worker itself is nil (because we just initialized the workers' array but the workers inside were nil before starting).

**Review by D3Hunter — APPROVED** [review]

**Comment by D3Hunter** [comment]
> Add a test to avoid regression

it's an bug internal to validator, so doesn't affects query-status when validator is off

**Comment by buchuitoudegou** [comment]
I've added a simple ut. PTAL @lance6716

**Review by lance6716 — APPROVED** [review]
Another convention is use make([]type, 0, cap) for slices, so we will not access not initialized values
