### PR TITLE
engine(externalresource): handle cleanBeforeOpen option before getting persisted resource

### LINKED ISSUE #7399: dm chaos test meets ResourceFilesNotFoundError and fails
### What did you do?

Run chaos test, ref: https://github.com/pingcap/tiflow/actions/runs/3276912635/jobs/5393527322

### What did you expect to see?

_No response_

### What did you see instead?

- Test failed

`` Error: 0/18 21:21:03.721 +00:00] [ERROR] [main.go:87] ["run cases failed"] [error="different data for table `dmjob`.`tb0`"] [errorVerbose="different data for table `dmjob`.`tb0` ``

- DM dump and load worker don't finish, dump worker keeps failing

```go
[2022/10/18 21:16:14.538 +00:00] [INFO] [worker.go:280] ["worker finished exiting"] [job_id=8002fd57-a7df-45ce-b0f9-de595b1582df] [worker_id=64097aeb-382d-4649-b559-cce8fe3269bf] [caused="ResourceFilesNotFoundError: {"Ident":{"Executor":"chaos-executor-0-c0efd57c","WorkerID":"4059f82b-d657-4e42-99ad-8ca3f0e6a0ca","Name":"38303032666435372d613764662d343563652d623066392d6465353935623135383264662d7265706c6963612d3033"},"URI":"s3://engine-it/chaos-executor-0-c0efd57c/4059f82b-d657-4e42-99ad-8ca3f0e6a0ca/38303032666435372d613764662d343563652d623066392d6465353935623135383264662d7265706c6963612d3033","Details":""}"] [causedVerbose="ResourceFilesNotFoundError: {"Ident":{"Executor":"chaos-executor-0-c0efd57c","WorkerID":"4059f82b-d657-4e42-99ad-8ca3f0e6a0ca","Name":"38303032666435372d613764662d343563652d623066392d6465353935623135383264662d7265706c6963612d3033"},"URI":"s3://engine-it/chaos-executor-0-c0efd57c/4059f82b-d657-4e42-99ad-8ca3f0e6a0ca/38303032666435372d613764662d343563652d623066392d6465353935623135383264662d7265706c6963612d3033","Details":""}
github.com/pingcap/tiflow/engine/pkg/rpcerror.(*Prototype[...]).GenWithStack
        github.com/pingcap/tiflow/engine/pkg/rpcerror/normalize.go:101
github.com/pingcap/tiflow/engine/pkg/externalresource/internal/s3.(*FileManager).GetPersistedResource
        github.com/pingcap/tiflow/engine/pkg/externalresource/internal/s3/file_manager.go:125
github.com/pingcap/tiflow/engine/pkg/externalresource/broker.(*DefaultBroker).getPersistResource
        github.com/pingcap/tiflow/engine/pkg/externalresource/broker/broker.go:343
github.com/pingcap/tiflow/engine/pkg/externalresource/broker.(*DefaultBroker).OpenStorage
        github.com/pingcap/tiflow/engine/pkg/externalresource/broker/broker.go:174
github.com/pingcap/tiflow/engine/framework.(*DefaultBaseWorker).OpenStorage
        github.com/pingcap/tiflow/engine/framework/worker.go:515
github.com/pingcap/tiflow/engine/executor/dm.(*dmWorker).setupStorage
        github.com/pingcap/tiflow/engine/executor/dm/worker.go:202
github.com/pingcap/tiflow/engine/executor/dm.(*dmWorker).InitImpl
        github.com/pingcap/tiflow/engine/executor/dm/worker.go:140
github.com/pingcap/tiflow/engine/framework.(*DefaultBaseWorker).Init
        github.com/pingcap/tiflow/engine/framework/worker.go:258
github.com/pingcap/tiflow/engine/framework/internal/eventloop.(*Runner[...]).doRun
        github.com/pingcap/tiflow/engine/framework/internal/eventloop/runner.go:84
github.com/pingcap/tiflow/engine/framework/internal/eventloop.(*Runner[...]).Run
        github.com/pingcap/tiflow/engine/framework/internal/eventloop/runner.go:59
github.com/pingcap/tiflow/engine/executor/worker.(*TaskRunner).launchTask.func1
        github.com/pingcap/tiflow/engine/executor/worker/task_runner.go:222
runtime.goexit
        runtime/asm_amd64.s:1594"] [duration=3.06168924s]
```

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

master@https://github.com/pingcap/tiflow/commit/9abde064c9a50aef77ffd3aa8be609d3265e4ed0

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: close #7399

L349 and L353 are non-atomic operations. If a worker successfully executes L349 but fails in L353, there will be an inconsistency between the resource and meta data (In this case, the resource does not exist while meta still exists).
And we can avoid this problem by handling the cleanBeforeOpen option before getting persistent resource

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by amyangfei** [comment]
> L349 and L353 are asynchronous operations.

Does this mean L349 and L353 are non-atomic operations?

**Review by amyangfei — COMMENTED** [review]
Better to add a unit test.

**Comment by CharlesCheung96** [comment]
> 

Added, PTAL.

File: engine/pkg/externalresource/broker/broker.go [hunk 1]
```diff
@@ -340,20 +340,23 @@ func (b *DefaultBroker) getPersistResource(
...
-	desc, err := fm.GetPersistedResource(ctx, ident)
-	if err != nil {
-		return nil, err
-	}
+	var desc internal.ResourceDescriptor
 
 	if options.cleanBeforeOpen {
 		err := fm.RemoveResource(ctx, ident)
-		if err != nil {
+		if err != nil && !derrors.ErrResourceDoesNotExist.Equal(err) {
```
Comment (amyangfei) [inline engine/pkg/externalresource/broker/broker.go:347]: Does `RemoveResource` return `ErrResourceDoesNotExist` if resource does not exist. If so we can add a comment to this function.

**Review by amyangfei — APPROVED** [review]
rest lgtm

**Review by GMHDBJD — APPROVED** [review]
LGTM

File: engine/pkg/externalresource/broker/broker.go (hunk 1 above)
Comment (CharlesCheung96) [inline engine/pkg/externalresource/broker/broker.go:347]:
```suggestion
		// LocalFileManager may return ErrResourceDoesNotExist, which can be 
		// ignored because the resource no longer exists.
		if err != nil && !derrors.ErrResourceDoesNotExist.Equal(err) {
```

**Comment by amyangfei** [comment]
Please fix lint
```go
[2022-10-20T03:03:34.108Z] run gofumports
[2022-10-20T03:03:34.108Z] tools/bin/gofumports -l -w $(find . -name '*.go' -type f | grep -vE 'vendor|kv_gen|proto|pb\.go|pb\.gw\.go') 2>&1 | awk '{ print } END { if (NR > 0) { exit 1  }  }'
[2022-10-20T03:03:34.108Z] ./engine/pkg/externalresource/broker/broker.go
[2022-10-20T03:03:34.108Z] make: *** [fmt] Error 1
```
