### PR TITLE
owner(cdc): drain warnings when closing changefeed

### LINKED ISSUE #11277: Changefeed failed with ddlSink not ready when injecting downstream network latency/partition, CDC scale out/in and capture pod failure
### What did you do?

0. TiDB cluster with 6 cdc nodes
1. Create MySQL sink changefeed 
```
cdc  cli  changefeed  create "--server=127.0.0.1:8301"  "--sink-uri=mysql://root:@downstream-tidb.cdc-testbed-tps-7542625-1-963:4000?worker-count=256
```
2. pause changefeed
3. run sysbench prepare 
```
sysbench --db-driver=mysql --mysql-host=upstream-tidb  --mysql-port=4000 --mysql-user=root --mysql-db=workload --tables=100 --table-size=50000 --create_secondary=off --debug=true --threads=32 --mysql-ignore-errors=2013,1213,1105,1205,8022,8027,8028,9004,9007,1062 oltp_write_only prepare
```
4. resume changefeed
5. run sysbench run
```
sysbench --db-driver=mysql --mysql-host=upstream-tidb  --mysql-port=4000 --mysql-user=root --mysql-db=workload --tables=100 --table-size=50000 --create_secondary=off --time=1800 --debug=true --threads=32 --mysql-ignore-errors=2013,1213,1105,1205,8022,8027,8028,9004,9007,1062 oltp_write_only run
```
6. which sysbench run in progress, do the following steps in parallel:
6.1 inject 200ms Network Latecy between CDC and downstream TiDB
6.2 Run below steps 
6.2.1 Scale in TiCDC from 6 to 2 nodes
6.2.2 Inject CDC owner Pod failure for 20s to swtich CDC owner
6.2.3 Scale out TiCDC from 2 to 6, and at the same time inject CDC to Downsteam network partition 5s.
6.2.4 restart call capture (inject Pod failure for 20s for each CDC node
6.2.5 Scale In TiCDC from 6 to 1, and at the same time inject CDC to Downstream network partition for 5s.

### What did you expect to see?

CDC changefeed should continue replication after all the ops and chaos finished, and data should be consistent

### What did you see instead?
img_v3_02bl_25a59b49-b89c-4abb-9d5e-04877972ad9g

```
[2024/06/08 11:42:40.683 +00:00] [ERROR] [feed_state_manager.go:462] ["processor reports an error"]
[2024/06/08 11:42:40.683 +00:00] [WARN] [feed_state_manager.go:564] ["changefeed meets an error"] , "too many connections"
[2024/06/08 11:42:40.683 +00:00] [WARN] [ddl_sink.go:154] ["ddl sink initialize failed"] context canceled
[2024/06/08 11:42:40.683 +00:00] [INFO] [ddl_sink.go:282] ["owner ddl sink background loop exits"]
[2024/06/08 11:42:40.684 +00:00] [INFO] [changefeed.go:792] ["changefeed closed"]
[2024/06/08 11:42:40.733 +00:00] [WARN] [changefeed.go:294] ["an warning occurred in Owner"]  not ready
```

### Versions of the cluster

Release Version: v7.5.2
Git Commit Hash: 7c968ee228d8b775d8119a19bd42c310a0509571
Git Branch: HEAD
UTC Build Time: 2024-06-07 13:22:07
Go Version: go version go1.21.10 linux/amd64
Failpoint Build: false

### PR DESCRIPTION
**Pull request by sdojjy**
### What problem does this PR solve?

Issue Number: close #11277

### What is changed and how it works?
changefeed will detect when handle warning errors if the checkpoint ts is stuck, if changefeed's checkpoint ts is not forward for 30 minutes, changefeed will be changed to the `fail` state.

when closing a changefeed,  the `checkpointTsAdvanced` time is reset to 0,  but the warning errors in warningCh is not cleaned up,  So when ticdc ticks the closed changefeed again and handle the old warning errors. the following condition is always true,   changefeed will be set to the `fail` state.
```
checkpointTsStuck := time.Since(m.checkpointTsAdvanced) > m.changefeedErrorStuckDuration
```

this PR will drain warningCh when closing changefeed

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

File: cdc/owner/changefeed.go [hunk 1]
```diff
@@ -811,6 +811,18 @@ func (c *changefeed) releaseResources(ctx context.Context) {
 	c.initialized.Store(false)
 	c.isReleased = true
 
+OUT:
```
Comment (flowbehappy) [inline cdc/owner/changefeed.go:814]: Please add comments to explain why we should drain the warnings before releaseResoruces @sdojjy
