### PR TITLE
servermaster(engine): fix leader hangs after etcd leader transfers

### LINKED ISSUE #5874: job manager enters unexpected state
### What did you do?

run chaos test, ref: https://github.com/pingcap/tiflow/runs/6875901896?check_suite_focus=true

### What did you expect to see?

_No response_

### What did you see instead?

Job manager in the server master leader met error, but it didn't exit and recover

first error
```go
[2022/06/14 07:57:41.021 +00:00] [WARN] [center.go:53] ["More than one error is received"] [error="[DFLOW:ErrMasterTooManyPendingEvents]master has too many pending events"] [errorVerbose="[DFLOW:ErrMasterTooManyPendingEvents]master has too many pending events\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/engine/framework/master.(*WorkerManager).enqueueEvent\n\tgithub.com/pingcap/tiflow/engine/framework/master/worker_manager.go:576\ngithub.com/pingcap/tiflow/engine/framework/master.(*WorkerManager).OnWorkerStatusUpdateMessage\n\tgithub.com/pingcap/tiflow/engine/framework/master/worker_manager.go:425\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseMaster).registerMessageHandlers.func2\n\tgithub.com/pingcap/tiflow/engine/framework/master.go:385\ngithub.com/pingcap/tiflow/pkg/p2p.(*MessageServer).AddHandler.func1\n\tgithub.com/pingcap/tiflow/pkg/p2p/server.go:431\ngithub.com/pingcap/tiflow/pkg/workerpool.(*defaultEventHandle).AddEvent.func2\n\tgithub.com/pingcap/tiflow/pkg/workerpool/pool_impl.go:140\ngithub.com/pingcap/tiflow/pkg/workerpool.(*worker).run\n\tgithub.com/pingcap/tiflow/pkg/workerpool/pool_impl.go:377\ngithub.com/pingcap/tiflow/pkg/workerpool.(*defaultPoolImpl).Run.func1\n\tgithub.com/pingcap/tiflow/pkg/workerpool/pool_impl.go:67\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20220513210516-0976fa681c29/errgroup/errgroup.go:74\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/06/14 07:57:41.420 +00:00] [INFO] [master.go:348] ["Heartbeat Ping received"] [msg="{\"send-time\":729816742093,\"from-worker-id\":\"71d976f1-e641-4968-bbb0-3727dff153c5\",\"epoch\":4,\"is-finished\":false}"] [master-id=dataflow-engine-job-manager]
```

detail logs:

[chaos-base-logs.network-emulation-dataflow.zip](https://github.com/pingcap/tiflow/files/8899088/chaos-base-logs.network-emulation-dataflow.zip)

### Versions of the cluster

Dataflow Engine version (run `df-master -V` or `df-executor -V`):

master@https://github.com/pingcap/tiflow/commit/65e67fc4b2155ca41a0e907f586ac370e67cd99c

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve?

Issue Number: close #5874

### What is changed and how it works?

the `runLeaderService` function should be terminated if etcd leader is transferred. Make every independent logic running in a `errorgroup.Go` block.

#### Tests 

 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

File: engine/servermaster/server.go [hunk 1]
```diff
@@ -759,30 +754,45 @@ func (s *Server) runLeaderService(ctx context.Context) (err error) {
...
+		defer metricTicker.Stop()
+		leaderTicker := time.NewTicker(time.Millisecond * 200)
+		defer leaderTicker.Stop()
+		for {
+			select {
+			case <-errgCtx.Done():
+				// errgCtx is a leaderCtx actually
+				return perrors.Trace(errgCtx.Err())
+			case <-leaderTicker.C:
+				if !s.isEtcdLeader() {
```
Comment (liuzix) [inline engine/servermaster/server.go:777]: Would it be better if `runLeaderService` is canceled from outside if the Etcd leadership is lost?

Comment (amyangfei) [reply engine/servermaster/server.go]: Yes, move the cancel logic to `leaderLoop`, it is a logic related to server manager, instead of session or campaign library.
Besides we don't watch the etcd leader change event, so only check it periodically.

**Comment by amyangfei** [comment]
PTAL @liuzix @maxshuang @gozssky

**Review by gozssky — APPROVED** [review]

**Review by maxshuang — APPROVED** [review]
