### PR TITLE
ddlManager (ticdc): Fix a bug that could lead to TiCDC replicating DDL events of ineligible tables.

### LINKED ISSUE #9819: Ineligible create table DDL is sent after it become ligible by next DDL
```
create table t (a int);
insert int t values (1);

alter table t add primary key (a);

insert int t values (2);
insert int t values (3);
```

The first one create table DDL should not be sent to the downstream, but it was observed unexpectedly.

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve?

Issue Number: close #9819 

#### Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
Fix a bug that could lead to TiCDC replicating DDL events of ineligible tables.
```

### CODE REVIEW

**Review by nongfushanquan — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]

File: cdc/owner/ddl_manager.go [hunk 1]
```diff
@@ -232,12 +233,22 @@ func (m *ddlManager) tick(
...
 
-				if event.TableInfo != nil &&
-					m.schema.IsIneligibleTableID(event.TableInfo.TableName.TableID) {
-					log.Warn("ignore the DDL event of ineligible table",
-						zap.String("changefeed", m.changfeedID.ID), zap.Any("ddl", event))
-					continue
+				// TODO: find a better place to do this check
+				// check if the ddl event is belong to an ineligible table.
+				// If so, we should ignore it.
+				if filter.IsSchemaDDL(event.Type) {
```
Comment (CharlesCheung96) [inline cdc/owner/ddl_manager.go:239]:
```suggestion
				if !filter.IsSchemaDDL(event.Type) {
```

Comment (asddongmen) [reply cdc/owner/ddl_manager.go]: thanks !
