### PR TITLE
sink(ticdc): asynchronously close the mq producers

### LINKED ISSUE #4241: mysql changefeed blocked by abnormal kafka changefeed
### What did you do?

- 1 TiCDC, 1 broker, 1 mysql; 3 kafka changefeeds, 1 mysql changefeed
- At first, all changefeeds work normally
- When kafka service stopped, the 3 kafka changefeeds don't sync data as expected, but the checkpoint of  mysql changefeed also will not move on.
- [
  {
    "id": "kafka-task-1",
    "summary": {
      "state": "normal",
      "tso": 430296185518948355,
      "checkpoint": "2022-01-06 14:14:42.308",
      "error": null
    }
  },
  {
    "id": "kafka-task-3",
    "summary": {
      "state": "normal",
      "tso": 430296185518948355,
      "checkpoint": "2022-01-06 14:14:42.308",
      "error": null
    }
  },
  {
    "id": "kafka-task-4",
    "summary": {
      "state": "normal",
      "tso": 430296185518948355,
      "checkpoint": "2022-01-06 14:14:42.308",
      "error": null
    }
  },
  {
    "id": "mysql-task-1",
    "summary": {
      "state": "normal",
      "tso": 430296201260695559,
      "checkpoint": "2022-01-06 14:15:42.358",
      "error": null
    }
  }
]
[root@CentOS76_VM log]# date
Thu Jan  6 14:42:04 CST 2022

### What did you expect to see?

mysql changefeed still can works normally

### What did you see instead?

cdc log has expected ERROR: [ERROR] [changefeed.go:118] ["an error occurred in Owner"] [changefeedID=kafka-task-3] [error="[CDC:ErrKafkaNewSaramaProducer]new sarama producer: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
WARN: [WARN] [client.go:226] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=20m39.000245874s]

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
5.4.0
```

TiCDC version (execute `cdc version`):

```console
5.4.0
```

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #4241 

### What is changed and how it works?

as suggested by https://github.com/pingcap/tiflow/pull/4249#issuecomment-1099812788, close the sink asynchronously.

close the producer (kafka / pulsar) in an asynchronous way.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Master branch, close the sink Manager would block a period of time. 
Screen Shot 2022-04-18 at 1 58 46 PM

This PR, sink Manager closed immediately, does not block the processor's progress.
Screen Shot 2022-04-18 at 2 11 50 PM

Code changes

Side effects

Related changes

### Release note 

```release-note
None
```

### CODE REVIEW

File: cdc/processor/pipeline/table_actor.go [hunk 1]
```diff
@@ -134,12 +134,14 @@ func NewTableActor(cdcCtx cdcContext.Context,
...
 
+		changefeedID: changefeedVars.ID,
+
 		stopCtx: cctx,
 	}
 
 	startTime := time.Now()
 	log.Info("table actor starting",
-		zap.String("changfeed", changefeedVars.ID),
+		zap.String("changefeed", changefeedVars.ID),
```
Comment (hi-rustin) [inline cdc/processor/pipeline/table_actor.go:144]: Why not use changefeedID?

**Review by hi-rustin — COMMENTED** [review]
Can we do some correctness tests? For example, the correctness of shutting down the producer asynchronously after encountering a kafka error and resuming it again?

**Comment by 3AceShowHand** [comment]
> Can we do some correctness tests? For example, the correctness of shutting down the producer asynchronously after encountering a kafka error and resuming it again?

It looks already covered by the integration test `kafka_sink_error_resume` ?

**Comment by hi-rustin** [comment]
> > Can we do some correctness tests? For example, the correctness of shutting down the producer asynchronously after encountering a kafka error and resuming it again?
> 
> It looks already covered by the integration test `kafka_sink_error_resume` ?

I don't think it's the same as the scenario where we actually have a problem? Otherwise this integration test should have caught the problem long ago?

**Comment by 3AceShowHand** [comment]
> > > Can we do some correctness tests? For example, the correctness of shutting down the producer asynchronously after encountering a kafka error and resuming it again?
> > 
> > 
> > It looks already covered by the integration test `kafka_sink_error_resume` ?
> 
> I don't think it's the same as the scenario where we actually have a problem? Otherwise this integration test should have caught the problem long ago?

**Comment by 3AceShowHand** [comment]
> > > Can we do some correctness tests? For example, the correctness of shutting down the producer asynchronously after encountering a kafka error and resuming it again?
> > 
> > 
> > It looks already covered by the integration test `kafka_sink_error_resume` ?
> 
> I don't think it's the same as the scenario where we actually have a problem? Otherwise this integration test should have caught the problem long ago?

I think the test purpose is that `the producer asynchronously closed after encountering a kafka error and resuming it again`, it's should be covered already.

> Otherwise this integration test should have caught the problem long ago?

Do you mean the problem that `blocked a long time`? It's not covered by the case ` kafka_sink_error_resume`, so that does not expose the problem.  Let's have a try to cover it by the integration test.

**Comment by 3AceShowHand** [comment]
> > > Can we do some correctness tests? For example, the correctness of shutting down the producer asynchronously after encountering a kafka error and resuming it again?
> > 
> > 
> > It looks already covered by the integration test `kafka_sink_error_resume` ?
> 
> I don't think it's the same as the scenario where we actually have a problem? Otherwise this integration test should have caught the problem long ago?

I think the test purpose is that `the producer asynchronously closed after encountering a kafka error and resuming it again`, it's should be covered already.

> Otherwise this integration test should have caught the problem long ago?

Do you mean the problem that `blocked a long time`? It's not covered by the case ` kafka_sink_error_resume`, so that does not expose the problem.  We have some test in test-infra to inject chaos to make the problems happens periodically. I will try to cover it in the integration test.

File: cdc/owner/ddl_sink.go [hunk 2]
```diff
@@ -264,5 +264,8 @@ func (s *ddlSinkImpl) close(ctx context.Context) (err error) {
 		err = s.syncPointStore.Close()
 	}
 	s.wg.Wait()
-	return err
+	if err != nil && errors.Cause(err) != context.Canceled {
```
Comment (hi-rustin) [inline cdc/owner/ddl_sink.go:267]: Do we still use close here, instead of asyncclose?

**Review by hi-rustin — COMMENTED** [review]
Can we add asynchronous close only to the close method of mq sink so that we don't need to add a new interface for the producer and write duplicate code. This behavior should really just be a special case of an mq sink close.

**Review by hi-rustin — APPROVED** [review]

**Comment by hi-rustin** [comment]
Do we only need the two versions of cherry-pick?

**Comment by hi-rustin** [comment]
> Can we add asynchronous close only to the close method of mq sink so that we don't need to add a new interface for the producer and write duplicate code. This behavior should really just be a special case of an mq sink close.

Or maybe we can pass ctx directly into close, I don't know how to do that better. cc: @asddongmen @overvenus @3AceShowHand  What do you think?

**Comment by 3AceShowHand** [comment]
> > Can we add asynchronous close only to the close method of mq sink so that we don't need to add a new interface for the producer and write duplicate code. This behavior should really just be a special case of an mq sink close.
> 
> Or maybe we can pass ctx directly into close, I don't know how to do that better. cc: @asddongmen @overvenus @3AceShowHand What do you think?

I would prefer the current implementation, it looks simple enough.

**Comment by 3AceShowHand** [comment]
> > Can we add asynchronous close only to the close method of mq sink so that we don't need to add a new interface for the producer and write duplicate code. This behavior should really just be a special case of an mq sink close.
> 
> Or maybe we can pass ctx directly into close, I don't know how to do that better. cc: @asddongmen @overvenus @3AceShowHand What do you think?

> maybe we can pass ctx directly into close

Do you mean `Producer.Close()`?  It looks like we have to start a goroutine just like now.

The current one is simple enough I think.

File: cdc/sink/mq.go [hunk 3]
```diff
@@ -310,8 +310,13 @@ func (k *mqSink) EmitDDLEvent(ctx context.Context, ddl *model.DDLEvent) error {
 }
 
 func (k *mqSink) Close(ctx context.Context) error {
-	err := k.mqProducer.Close()
-	return errors.Trace(err)
+	closedCh := k.mqProducer.AsyncClose()
+	select {
+	case <-ctx.Done():
```
Comment (asddongmen) [inline cdc/sink/mq.go:315]: Please add a comment here to tell this `ctx` is a `canceled context` so that this select statement will never block.

File: cdc/sink/mq.go [hunk 4]
```diff
@@ -310,8 +310,13 @@ func (k *mqSink) EmitDDLEvent(ctx context.Context, ddl *model.DDLEvent) error {
 }
 
 func (k *mqSink) Close(ctx context.Context) error {
```
Comment (asddongmen) [inline cdc/sink/mq.go:312]: It is better add a comment here to indicate that this func is non-blocking.

**Review by sdojjy — APPROVED** [review]
