### PR TITLE
sink(ticdc): remove force consume when redo is disabled

### LINKED ISSUE #1683: CDC Synchronize big transaction is too slow
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Pause changfeed.
- Start transaction operation  which has 5GB data in TiDB,  this process duration time is about half an hour. 
- Resume changfeed, observe the big transaction sync status.

2. What did you expect to see?

3. What did you see instead?
sync duration time is more than 5 hours， 
image

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        Release Version: v5.0.1
   

>  Edition: Community
> Git Commit Hash: 4141f837ad4655a567119db743b7b752a95f5aa2
> Git Branch: heads/refs/tags/v5.0.1
> UTC Build Time: 2021-04-17 04:28:49

        ```

    - TiCDC version (execute `cdc version`):

        ```
> Release Version: v5.0.0-master
> Git Commit Hash: 6363c4810edf2e25f63df28ace9b6f0a2939c6b9
> Git Branch: heads/refs/tags/v5.0.1
> UTC Build Time: 2021-04-17 04:40:20

        ```

### LINKED ISSUE #5453: Make mysql sink batch flush data to alleviate OOM problems

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: close #5453, close #1683

### What is changed and how it works?
In order to solve the OOM problem of single table, we refactor flowControl and Sink modules on the basis of splitting transaction, so that they can obtain data in batches and send it to the downstream, which reduces the memory consumption of individual table to constant level: 
1. In flowcontrol module, allocate and release based on resolvedTs and batchID.
2. In sink module, replace model.Ts with model.ResolvedTs to support batch-based memory release.
3. In sinkNode, release memory based on checkpointTs and batchID.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 > down stream: TiDB
total row of txn: 30 million
txn size: ~5.4 GB
downstream: tidb cluster
memory of cdc node: 32 GB

The results show that memory consumption of single table is constant. However, a lower quota value may affect throughput, so it is recommended to increase the quota of single tables to 30-40 MB.

image
image
image
image
image
image

> compare with #5454 
quota: 100MB
down stream: TiDB
total row of txn: 30 million
txn size: ~5.4 GB
downstream: tidb cluster
memory of cdc node: 32 GB

[up-TiCDC_2022-06-06T10_33_19.155Z.json.zip](https://github.com/pingcap/tiflow/files/8843760/up-TiCDC_2022-06-06T10_33_19.155Z.json.zip)

[heap_profile.zip](https://github.com/pingcap/tiflow/files/8843828/heap_profile.zip)

##### Will it cause performance regression or break compatibility?
No

##### Do you need to update user documentation, design documentation or monitoring documentation?
No

### Release note 

```release-note
`Optimize the memory consumption required for TiCDC to process large transactions`.
```

### CODE REVIEW

**Review by nongfushanquan — COMMENTED** [review]
could you add some comments to explain the method to solved the problem

**Comment by CharlesCheung96** [comment]
> could you add some comments to explain the method to solve the problem

Done, PTAL.

File: cdc/model/mounter.go [hunk 1]
```diff
@@ -108,16 +103,42 @@ const (
...
+
+// ParseTs parses a timestamp based on the r.mode.
+func (r ResolvedTs) ParseTs() uint64 {
+	switch r.Mode {
+	case NormalResolvedMode:
+		return r.Ts
+	case BatchResolvedMode:
+		return r.Ts - 1
+	default:
+		return 0
```
[the remark this answers is not in the document]
Comment (CharlesCheung96) [reply cdc/model/mounter.go:129]: Not normally. Maybe it's better to throw defensive errors?

File: cdc/sink/flowcontrol/flow_control.go [hunk 2]
```diff
@@ -72,45 +88,53 @@ func NewTableFlowController(quota uint64) *TableFlowController {
...
-	callBack func(batch bool) error,
+	callBack func(batchID uint64) error,
 ) error {
 	commitTs := msg.CRTs
 	lastCommitTs := atomic.LoadUint64(&c.lastCommitTs)
+	blockingCallBack := func() error {
+		err := callBack(c.batchID)
+
+		if commitTs == lastCommitTs {
+			c.batchID++
```
[the remark this answers is not in the document]
Comment (CharlesCheung96) [reply cdc/sink/flowcontrol/flow_control.go:99]: Good idea!

[the remark this answers is not in the document]
Comment (CharlesCheung96) [reply cdc/sink/flowcontrol/flow_control.go:99]: We can't just reset the batchID here, because the batchID of the same txn needs to be increased linearly. 
In addition, resetBatch may be called multiple times for a single row change event, so it needs to be idempotent.

File: cdc/sink/flowcontrol/flow_control.go [hunk 3]
```diff
@@ -134,48 +160,55 @@ func (c *TableFlowController) enqueueSingleMsg(msg *model.PolymorphicEvent, size
...
+	if txnEntry.batchID == c.batchID && txnEntry.startTs == msg.Row.StartTs &&
+		txnEntry.rowCount < c.maxRowsPerTxn && txnEntry.size < c.maxSizePerTxn {
 		txnEntry.size += size
 		txnEntry.rowCount++
 		return
 	}
 
 	// 3. Split the txn or handle a new txn with the same commitTs.
+	if c.batchGroupCount >= c.batchSize {
+		_ = callback()
```
Comment (nongfushanquan) [inline cdc/sink/flowcontrol/flow_control.go:186]: Should reset batch here ?

Comment (CharlesCheung96) [reply cdc/sink/flowcontrol/flow_control.go:186]: Yes, batch is reset inside [callback](https://github.com/pingcap/tiflow/pull/5712/files#diff-cfe8ccb173f8b93acc1b97cc5825fdb565d539634714fadffacdf18ea4bc8b26R100).

File: cdc/model/mounter.go [hunk 4]
```diff
@@ -108,16 +108,48 @@ const (
...
+}
+
+// IsBatchMode returns true if the resolved ts is BatchResolvedMode.
+func (r ResolvedTs) IsBatchMode() bool {
+	return r.Mode == BatchResolvedMode
+}
+
+// ParseTs returns a timestamp `ts` based on the r.mode, which means that all events
+// whose commitTs is less than or equal to `ts` are sent to Sink.
+func (r ResolvedTs) ParseTs() uint64 {
```
Comment (3AceShowHand) [inline cdc/model/mounter.go:128]: How about rename it to `Get()` ?

File: cdc/model/mounter.go [hunk 5]
```diff
@@ -108,16 +108,48 @@ const (
...
+		return 0
+	}
+}
+
+// EqualOrGreater judge whether the resolved ts is equal or greater than the given ts.
+func (r ResolvedTs) EqualOrGreater(r1 ResolvedTs) bool {
+	if r.Ts == r1.Ts {
+		return r.BatchID >= r1.BatchID
+	}
+	return r.Ts > r1.Ts
```
Comment (3AceShowHand) [inline cdc/model/mounter.go:149]: `EqualOrGreater` -> `>=`. 

L149, shall we use `>=` ?

Comment (CharlesCheung96) [reply cdc/model/mounter.go:149]: We have already considered the equal case in line 146, so it is unnecessary to judge again. Besides, does using `>=` make the semantics more explicit?

File: cdc/model/mounter.go (hunk 4 above)
Comment (CharlesCheung96) [reply cdc/model/mounter.go:128]: How about `GetTs()`?

**Review by amyangfei — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]
