### PR TITLE
meta(engine): fix irreentrance problem of creating meta kv table

### LINKED ISSUE #6581: Initialize of sqlKVClientImpl is not thread-safe
### What did you do?

run chaos test, ref: https://github.com/pingcap/tiflow/runs/7641218953?check_suite_focus=true

### What did you expect to see?

_No response_

### What did you see instead?

```go
[2022/08/02 22:12:45.828 +00:00] [INFO] [client.go:104] ["add new server master client"] [addr=server-master:10240]
Error: 8/02 22:[12](https://github.com/pingcap/tiflow/runs/7641218953?check_suite_focus=true#step:20:13):45.875 +00:00] [ERROR] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=9.131208ms] [sql="CREATE TABLE `dfe_proj_default_meta_kvs` (`seq_id` bigint unsigned AUTO_INCREMENT,`created_at` datetime(3) NULL,`updated_at` datetime(3) NULL,`meta_key` varbinary(2048) not null,`meta_value` blob,`job_id` varchar(64) not null,PRIMARY KEY (`seq_id`),UNIQUE INDEX uidx_jk (`job_id`,`meta_key`))"] [affected-rows=0] [error="Error 1050: Table 'dfe_proj_default_meta_kvs' already exists"]
Error: 8/02 22:12:45.875 +00:00] [ERROR] [main.go:87] ["run cases failed"] [error="[DFLOW:ErrMetaOpFail]meta operation fail: Error 1050: Table 'dfe_proj_default_meta_kvs' already exists"] [errorVerbose="[DFLOW:ErrMetaOpFail]meta operation fail: Error 1050: Table 'dfe_proj_default_meta_kvs' already exists\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.Trace\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/juju_adaptor.go:15\ngithub.com/pingcap/tiflow/engine/test/e2e.(*ChaosCli).InitializeMetaClient\n\tgithub.com/pingcap/tiflow/engine/test/e2e/e2e_test_cli.go:288\nmain.runFakeJobCase\n\tgithub.com/pingcap/tiflow/engine/chaos/cases/case_fake_job.go:86\nmain.runCases.func1\n\tgithub.com/pingcap/tiflow/engine/chaos/cases/cases.go:31\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-202205[13](https://github.com/pingcap/tiflow/runs/7641218953?check_suite_focus=true#step:20:14)210516-0976fa681c29/errgroup/errgroup.go:74\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
```

https://github.com/pingcap/tiflow/blob/0ad449d21dc442d546bd89dfff662336f0023ad4/engine/pkg/meta/internal/sqlkv/sql_impl.go#L89-L94

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

master@https://github.com/pingcap/tiflow/commit/e876831e86a9322439e0098589e510a33710ed5c

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve?

Problem:
1. gorm 'AutoMigrate' function (1) first checks if table exists and (2) then creates table, which is not thread-safe.
When two threads call 'AutoMigrate' concurrently,  we will meet 'table already exists' error.
2. meta kv table is project-isolated and needs to be created dynamically, so if multi-jobs with same projectID runs concurrently, they may create meta kv table concurrently.

Issue Number: close #6581 

### What is changed and how it works?
Ignore the 'table exists' error to avoid multi-jobs with the same projectID create the same meta kv table concurrently.

#### Tests 

 - Unit test

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

File: engine/pkg/meta/internal/sqlkv/sql_impl.go [hunk 1]
```diff
@@ -71,25 +75,31 @@ func NewSQLKVClientImpl(sqlDB *sql.DB, table string, jobID metaModel.JobID) (*sq
...
 
 	return impl, nil
 }
 
-// Initialize initializes metakv table
-// NOTE: Make Sure to call InitializeEpochModel before Initialize any KVClient
-func (c *sqlKVClientImpl) Initialize(ctx context.Context) error {
-	if err := c.tableScopeDB.
-		WithContext(ctx).
-		AutoMigrate(&sqlkvModel.MetaKV{}); err != nil {
```
Comment (amyangfei) [inline engine/pkg/meta/internal/sqlkv/sql_impl.go:92]: An alternative way is to keep the `AutoMigrate` and ignore the `table already exists` error, which doesn't need to hard code create table DDL.

Comment (gozssky) [reply engine/pkg/meta/internal/sqlkv/sql_impl.go:92]: It looks weird that `AutoMigrate` doesn't handle `table already exists` internally. 🤔

Comment (maxshuang) [reply engine/pkg/meta/internal/sqlkv/sql_impl.go:92]: > It looks weird that `AutoMigrate` doesn't handle `table already exists` internally. 🤔

It's the problem of implment. It first checks the existence of the table and then create the table. 
So it's designed to be irreentrance. May need some protection.

Comment (maxshuang) [reply engine/pkg/meta/internal/sqlkv/sql_impl.go:92]: I will check if `CREATE TABLE IF NOT EXISTS` is a common SQL.
If so, may be we can make a pr for the gorm.

Comment (gozssky) [reply engine/pkg/meta/internal/sqlkv/sql_impl.go:92]: > 

Can we use a lock to protect the `AutoMigrate` function? It seems it is not thread-safe.

Comment (maxshuang) [reply engine/pkg/meta/internal/sqlkv/sql_impl.go:92]: The competition comes from other jobs, not the single job calls 'initialize' concurrently.

Comment (maxshuang) [reply engine/pkg/meta/internal/sqlkv/sql_impl.go:92]: The competition comes from other jobs, not the single job calls 'initialize' concurrently.

File: engine/pkg/meta/internal/sqlkv/sql_impl.go [hunk 2]
```diff
@@ -15,10 +15,14 @@ package sqlkv
 
 import (
 	"context"
-	"database/sql"
 	"sync"
 	"time"
 
+	"database/sql"
```
Comment (gozssky) [inline engine/pkg/meta/internal/sqlkv/sql_impl.go:21]: Remove the blank line before it.

File: engine/pkg/meta/internal/sqlkv/sql_impl.go (hunk 1 above)
Comment (gozssky) [reply engine/pkg/meta/internal/sqlkv/sql_impl.go]: If multiple jobs need the same table, is it better to create the table before creating `sqlKVClientImpl`? (Just for discussion)

**Comment by maxshuang** [comment]
https://github.com/pingcap/tiflow/pull/6588#discussion_r936499848

@gozssky I can't reply your comment, so I reply here.
It's designed to create the meta kv table inside the 'creating client', because table name is related to 'projectID' and I want to hide this implement internally.

File: engine/pkg/meta/internal/sqlkv/sql_impl.go (hunk 1 above)
Comment (maxshuang) [reply engine/pkg/meta/internal/sqlkv/sql_impl.go]: It's designed to create the meta kv table inside the 'creating client', because the table name is related to 'projectID' and I want to hide this implement internally.

Or just as you said, we can create the meta kv table in `JobMaster`.

**Review by gozssky — APPROVED** [review]

File: engine/pkg/meta/internal/sqlkv/sql_impl.go [hunk 3]
```diff
@@ -71,34 +74,38 @@ func NewSQLKVClientImpl(sqlDB *sql.DB, table string, jobID metaModel.JobID) (*sq
...
 		WithContext(ctx).
 		AutoMigrate(&sqlkvModel.MetaKV{}); err != nil {
-		return cerrors.ErrMetaOpFail.Wrap(err)
+		// since meta kv table is project-isolated and needs to be created dynamically,
+		// 'table exists' error will be raised if multi-jobs create meta kv table concurrently.
+		// Ignore the specific mysql error code: 1050
+		if errMySQL, ok := err.(*mysql.MySQLError); !ok || errMySQL.Number != mysqlerr.ER_TABLE_EXISTS_ERROR {
+			return err
+		}
+		log.Info("meet 'table exists' error when creating meta kv table, but can be ignored")
```
Comment (amyangfei) [inline engine/pkg/meta/internal/sqlkv/sql_impl.go:101]: Can log a short error via `logutil.ShortError(err)`, which contains table name

**Review by amyangfei — COMMENTED** [review]
rest lgtm

**Review by amyangfei — APPROVED** [review]
