### PR TITLE
cdc: fix sourcemanager.Close deadlock

### LINKED ISSUE #8329: `processor.Close` is blocked by `SourceManager.Close`
### What did you do?

Rolling upgrade TiDB and TiCDC cluster.

Changefeed lag is increasing and TiCDC OOM due to `processor.Close` is blocked between

https://github.com/pingcap/tiflow/blob/40ba4175a57a45d5facabe1e8f876368ca3a9b59/cdc/processor/processor.go#L958-L971

Because there is a log "Processor try to close source manager" but no "Processor closed source manager successfully" or "Failed to close source manager".

It also causes OOM on agent receiving message.

### What did you expect to see?

Lag is steady and no OOM.

### What did you see instead?

Changefeed lag is increasing and TiCDC OOM.

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
40ba4175a57a45d5facabe1e8f876368ca3a9b59
```

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: close #8329

### What is changed and how it works?

There is case that might cause sourcemanager.Close deadlock, because it blocking sends error but there no goroutine receive it.

Also, I find it is nearly impossible to test this fix in unit test for now, I might send another PR for adding unit tests later. 

#### Tests 

 - Integration test

##### Will it cause performance regression or break compatibility?

No

##### Do you need to update user documentation, design documentation or monitoring documentation?

No

### Release note 

```release-note
Fix an issue that might cause checkpoint stuck and TiCDC OOM during rolling upgrade 
```

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]

File: cdc/processor/sourcemanager/puller/puller_wrapper.go [hunk 1]
```diff
@@ -99,7 +101,17 @@ func (n *Wrapper) Start(
 		defer n.wg.Done()
 		err := n.p.Run(ctxC)
 		if err != nil && !cerrors.Is(err, context.Canceled) {
-			errChan <- err
+			select {
+			case errChan <- err:
+				// Do not blocking sending error, bcause there the err channal
```
Comment (nongfushanquan) [inline cdc/processor/sourcemanager/puller/puller_wrapper.go:106]: because

Comment (overvenus) [reply cdc/processor/sourcemanager/puller/puller_wrapper.go:106]:
```suggestion
				// Do not block sending error, because there the err channel
```

File: cdc/processor/sourcemanager/puller/puller_wrapper.go [hunk 2]
```diff
@@ -99,7 +101,17 @@ func (n *Wrapper) Start(
 		defer n.wg.Done()
 		err := n.p.Run(ctxC)
 		if err != nil && !cerrors.Is(err, context.Canceled) {
-			errChan <- err
+			select {
+			case errChan <- err:
+				// Do not block sending error, because there the err channel
```
Comment (overvenus) [inline cdc/processor/sourcemanager/puller/puller_wrapper.go:106]:
```suggestion
				// Do not block sending error, because the err channel
```

File: cdc/processor/sourcemanager/puller/puller_wrapper.go [hunk 3]
```diff
@@ -99,7 +101,17 @@ func (n *Wrapper) Start(
 		defer n.wg.Done()
 		err := n.p.Run(ctxC)
 		if err != nil && !cerrors.Is(err, context.Canceled) {
-			errChan <- err
+			select {
+			case errChan <- err:
+				// Do not block sending error, because the err channel
+				// might be full and no goroutine receives.
+			default:
+				log.Warn("puller faill to send error",
```
Comment (overvenus) [inline cdc/processor/sourcemanager/puller/puller_wrapper.go:109]:
```suggestion
				log.Warn("puller fail to send error",
```

**Review by nongfushanquan — APPROVED** [review]
