### PR TITLE
relay/meta(dm): fix potential data races after saving GTID

### LINKED ISSUE #4166: data race of R/W to relay status
### What did you do?

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/2337/pipeline

```
[2021-12-30T09:20:32.109Z] WARNING: DATA RACE

[2021-12-30T09:20:32.109Z] Write at 0x00c006b8b3f8 by goroutine 411:

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/pkg/gtid.(*MySQLGTIDSet).Set()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/pkg/gtid/gtid.go:125 +0xa5

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/relay.(*Relay).handleEvents()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/relay/relay.go:555 +0x12be

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/relay.(*Relay).process()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/relay/relay.go:310 +0xad4

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/relay.(*Relay).Process()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/relay/relay.go:151 +0xde

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/dm/worker.(*realRelayHolder).run()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/relay.go:143 +0x203

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/dm/worker.(*realRelayHolder).Start.func1()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/relay.go:118 +0x8a

[2021-12-30T09:20:32.109Z] 

[2021-12-30T09:20:32.109Z] Previous read at 0x00c006b8b3f8 by goroutine 154:

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/pkg/gtid.(*MySQLGTIDSet).Clone()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/pkg/gtid/gtid.go:179 +0x8b

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/relay.(*LocalMeta).GTID()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/relay/meta.go:353 +0x12c

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/relay.(*Relay).Status()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/relay/relay.go:888 +0x310

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/dm/worker.(*realRelayHolder).Status()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/relay.go:161 +0x1af

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/dm/worker.(*realTaskStatusChecker).checkRelayStatus()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/task_checker.go:302 +0xcd

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/dm/worker.(*realTaskStatusChecker).check()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/task_checker.go:407 +0xd9

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/dm/worker.(*realTaskStatusChecker).run()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/task_checker.go:215 +0x2bb

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/dm/worker.(*realTaskStatusChecker).Start.func1()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/task_checker.go:176 +0x8a

[2021-12-30T09:20:32.109Z] 

[2021-12-30T09:20:32.109Z] Goroutine 411 (running) created at:

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/dm/worker.(*realRelayHolder).Start()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/relay.go:116 +0x86

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/dm/worker.(*SourceWorker).EnableRelay()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/source_worker.go:342 +0x10c4

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/dm/worker.(*Server).enableRelay()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:726 +0x195

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/dm/worker.(*Server).operateRelaySource()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:710 +0x2e8

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/dm/worker.(*Server).handleRelayConfig()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:618 +0x4a4

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/dm/worker.(*Server).observeRelayConfig()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:321 +0xe2b

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/dm/worker.(*Server).Start.func3()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:151 +0xcd

[2021-12-30T09:20:32.109Z] 

[2021-12-30T09:20:32.109Z] Goroutine 154 (running) created at:

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/dm/worker.(*realTaskStatusChecker).Start()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/task_checker.go:174 +0x86

[2021-12-30T09:20:32.109Z]   github.com/pingcap/tiflow/dm/dm/worker.(*SourceWorker).Start()

[2021-12-30T09:20:32.109Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/source_worker.go:133 +0x1454
```

### What did you expect to see?

no race

### What did you see instead?

_No response_

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
(paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by dsdashun**
### What problem does this PR solve?

Issue Number: close #4166 

### What is changed and how it works?
When a GTID set is saved into `LocalMeta`, clone this GTID set first and then do the updating.  
Otherwise, after a GTID set is saved into `LocalMeta`, the input GTID set and the one inside `LocalMeta` are referencing the same object.  It'll cause potential data race when modifying the input GTID set object and reading the GTID set inside `LocalMeta` happen simultaneously.  

### Check List 

Tests 

 - Unit test

Code changes

N/A

Side effects

N/A

Related changes

N/A

### Release note 

```release-note
None
```

### CODE REVIEW

File: dm/relay/meta.go [hunk 1]
```diff
@@ -212,7 +212,7 @@ func (lm *LocalMeta) Save(pos mysql.Position, gset gtid.Set) error {
 		lm.BinlogGTID = ""
 	} else {
 		lm.BinlogGTID = gset.String()
-		lm.gset = gset
+		lm.gset = gset.Clone() // need to clone and set, in order to avoid the local meta's gset and the input gset referencing the same object, causing contentions later
```
Comment (Ehco1996) [inline dm/relay/meta.go:215]: maybe just add a lock in `func (r *Relay) SaveMeta(pos mysql.Position, gset gtid.Set)` is more intuitive 😬

Comment (dsdashun) [reply dm/relay/meta.go:215]: Adding a lock on `(*Relay).SaveMeta()` won't work.  Because the data race happens when the doing the `(gtid.Set).Set()` and `(gtid.Set).Clone()` on the same object.  Even if `(*Relay).SaveMeta()` is executed serially, data race will still happen when the input `gtid.Set` object is also referenced by the `LocalMeta` afterwards.  

Actually, there are two solutions on the problem.  The first one is to add a locking mechanism on corresponding methods in `gtid.Set` implementation.  The second one is to ensure that the `gtid.Set` object inside `LocalMeta` is independent.  

The first method involves many modifications and may have some performance penalty.  What's more, some current mechanism in `LocalMeta` tends to favor the second method.  For example, `(*LocalMeta).GTID()` clones the `gtid.Set` before return, which intends to isolate the returning `gtid.Set` object from the object inside `LocalMeta`. 

So considering only the `gtid.Set` object  inside `LocalMeta` is accessed frequently, and currently there are no places where the `gtid.Set` inside `LocalMeta` is updated directly (which means `(*LocalMeta).gset` is always updated by assigning a new object, rather than calling `(*LocalMeta).gset.Set()` ), I used the second method to fix this problem.

Comment (Ehco1996) [reply dm/relay/meta.go:215]: thanks explain this reason i will read more carefully later

Comment (Ehco1996) [reply dm/relay/meta.go:215]: this commets [help](https://github.com/pingcap/tiflow/issues/4166#issuecomment-1018476045), i got the reason of datarace now ~

File: dm/relay/meta_test.go [hunk 2]
```diff
@@ -234,3 +235,65 @@ func (r *testMetaSuite) TestLocalMeta(c *C) {
 	currentDir := lm.Dir()
 	c.Assert(strings.HasSuffix(currentDir, cs.uuidWithSuffix), IsTrue)
 }
+
+func (r *testMetaSuite) TestLocalMetaPotentialDataRace(c *C) {
```
Comment (Ehco1996) [inline dm/relay/meta_test.go:239]: could please use testify to rewrite this test? see https://github.com/pingcap/tiflow/issues/2164

**Review by Ehco1996 — COMMENTED** [review]
restLGTM

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
don't forget to sign cla https://github.com/pingcap/tiflow/pull/4455#issuecomment-1019792900

File: dm/relay/meta_test.go (hunk 2 above)
Comment (dsdashun) [reply dm/relay/meta_test.go:239]: OK，I'll submit another PR to rewrite the test

**Review by Ehco1996 — APPROVED** [review]
LGTM
