### PR TITLE
kv: workaround the ErrPrewriteNotMatch by reconnection EventFeed RPC

### LINKED ISSUE #2386: Capture restart: tikv reported duplicated request to the same region, which is not expected
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- 2xCDC server, 2x changefeed, 200 tables.
[root@IDC-172-16-xxx~]# tiup cdc:v4.0.14 cli changefeed list --pd=http://172.16.xxx:2379
Starting component `cdc`: /root/.tiup/components/cdc/v4.0.14/cdc cli changefeed list --pd=http://172.16.xxx:2379
[
  {
    "id": "kafka-task-11",
    "summary": {
      "state": "normal",
      "tso": 426606071522525189,
      "checkpoint": "2021-07-27 16:03:34.536",
      "error": null
    }
  },
  {
    "id": "replication-task-11",
    "summary": {
      "state": "normal",
      "tso": 426606071719133316,
      "checkpoint": "2021-07-27 16:03:35.286",
      "error": null
    }
  }
]

#  tiup cdc:v4.0.14 cli capture list --pd=http://172.16.xxx:2379
Starting component `cdc`: /root/.tiup/components/cdc/v4.0.14/cdc cli capture list --pd=http://172.16.xxx:2379
[
  {
    "id": "3378b726-26cb-4963-8280-3ee679024a76",
    "is-owner": false,
    "address": "172.16.xxx2:8300"
  },
  {
    "id": "d2600da4-cdc4-4420-84a4-e57e826ffbc7",
    "is-owner": true,
    "address": "172.16.xxx:8300"
  }
]

- Load data: $ bin/go-ycsb run mysql -P ./workloads/oncall2929 -p mysql.host=172.16.xxx -p mysql.port=4000 -p operationcount=5000000  --threads=10
$ bin/go-ycsb run mysql -P ./workloads/oncall2929 -p mysql.host=172.16.xxx -p mysql.port=4000 -p operationcount=5000000  --threads=200 -p databasename=test123 -p tablename=test222

2. What did you expect to see?
No error
3. What did you see instead?
cdc log has panic:

[2021/07/27 16:04:34.191 +08:00] [INFO] [region_range_lock.go:218] ["range locked"] [lockID=4552] [regionID=1448181] [startKey=748000000000000eff425f698000000000ff0000020400000000ff05f7bc4c07800034ffa8e4eeb8000419a9ff9a00000000000000fd] [endKey=748000000000000eff425f698000000000ff0000020400000000ff05f818db07800034ff8cf46008000419a9ff9a00000000000000fd] [checkpointTs=426606086831734920]
[2021/07/27 16:04:34.191 +08:00] [INFO] [client.go:858] ["start new request"] [request="{\"header\":{\"cluster_id\":6985429421391688222,\"ticdc_version\":\"4.0.14\"},\"region_id\":1448181,\"region_epoch\":{\"conf_ver\":1097,\"version\":5725},\"checkpoint_ts\":426606086831734920,\"start_key\":\"dIAAAAAAAA7/Ql9pgAAAAAD/AAACBAAAAAD/Bfe8TAeAADT/qOTuuAAEGan/mgAAAAAAAAD9\",\"end_key\":\"dIAAAAAAAA7/Ql9pgAAAAAD/AAACBAAAAAD/BfgY2weAADT/jPRgCAAEGan/mgAAAAAAAAD9\",\"request_id\":656854}"] [addr=172.16.6.11:20170]
[2021/07/27 16:04:34.191 +08:00] [INFO] [client.go:1345] ["region state entry will be replaced because received message of newer requestID"] [regionID=1448181] [oldRequestID=656846] [requestID=656854] [addr=172.16.6.11:20170]
[2021/07/27 16:04:34.192 +08:00] [INFO] [client.go:1039] ["EventFeed disconnected"] [regionID=1448181] [requestID=656854] [span="[748000000000000eff425f698000000000ff0000020400000000ff05f7bc4c07800034ffa8e4eeb8000419a9ff9a00000000000000fd, 748000000000000eff425f698000000000ff0000020400000000ff05f818db07800034ff8cf46008000419a9ff9a00000000000000fd)"] [checkpoint=426606086831734920] [error="[CDC:ErrEventFeedEventError]duplicate_request:<region_id:1448181 > "]
[2021/07/27 16:04:34.192 +08:00] [INFO] [region_range_lock.go:370] ["unlocked range"] [lockID=4552] [regionID=1448181] [startKey=748000000000000eff425f698000000000ff0000020400000000ff05f7bc4c07800034ffa8e4eeb8000419a9ff9a00000000000000fd] [endKey=748000000000000eff425f698000000000ff0000020400000000ff05f818db07800034ff8cf46008000419a9ff9a00000000000000fd] [checkpointTs=426606086831734920]
[2021/07/27 16:04:34.192 +08:00] [PANIC] [client.go:1173] ["tikv reported duplicated request to the same region, which is not expected"] [regionID=1448181] [stack="github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).handleError\n\tgithub.com/pingcap/ticdc@/cdc/kv/client.go:1173\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).eventFeed.func4\n\tgithub.com/pingcap/ticdc@/cdc/kv/client.go:630\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57"]
[2021/07/27 16:04:51.532 +08:00] [INFO] [util.go:99] ["init log"] [file=/data2/cdcup/cdc-8300/log/cdc.log] [level=info]
[2021/07/27 16:04:51.532 +08:00] [INFO] [version.go:47] ["Welcome to Change Data Capture (CDC)"] [release-version=v4.0.14] [git-hash=5a7851967f686da896b45acd3f3e968bfe53d6bd] [git-branch=heads/refs/tags/v4.0.14] [utc-build-time="2021-07-15 05:48:23"] [go-version="go version go1.13 linux/amd64"] [failpoint-build=false]

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v4.0.14
        ```

    - TiCDC version (execute `cdc version`):

        ```
         [release-version=v4.0.14] [git-hash=5a7851967f686da896b45acd3f3e968bfe53d6bd] [git-branch=heads/refs/tags/v4.0.14]
        ```

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve? 
Close #2386, workaround the ErrPrewriteNotMatch by reconnection EventFeed RPC

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
Close gPRC stream and re-create it when meeting `ErrPrewriteNotMatch` to avoid duplicated request error
```

### CODE REVIEW

File: cdc/kv/region_worker.go [hunk 1]
```diff
@@ -291,7 +286,11 @@ func (w *regionWorker) handleSingleRegionError(ctx context.Context, err error, s
 	// check and cancel gRPC stream before reconnecting region, in case of the
 	// scenario that region connects to the same TiKV store again and reuses
 	// resource in this region worker by accident.
-	retErr := w.checkShouldExit(state.sri.rpcCtx.Addr)
+	retErr := w.checkShouldExit()
+
+	if err == cerror.ErrPrewriteNotMatch {
```
Comment (overvenus) [inline cdc/kv/region_worker.go:291]:
```suggestion
	if errors.Cause(err) == cerror.ErrPrewriteNotMatch {
```

File: cdc/kv/region_worker.go [hunk 2]
```diff
@@ -228,17 +228,12 @@ func (w *regionWorker) checkRegionStateEmpty() (empty bool) {
...
 	// If there is not region maintained by this region worker, exit it and
 	// cancel the gRPC stream.
 	if empty {
-		cancel, ok := w.session.getStreamCancel(addr)
-		if ok {
-			cancel()
-		} else {
-			log.Warn("gRPC stream cancel func not found", zap.String("addr", addr))
-		}
+		w.cancelStream(0)
```
Comment (overvenus) [inline cdc/kv/region_worker.go:236]:
```suggestion
		w.cancelStream(time.Duration(0))
```

Add type, it improves readability.

File: cdc/kv/region_worker.go [hunk 3]
```diff
@@ -291,7 +286,11 @@ func (w *regionWorker) handleSingleRegionError(ctx context.Context, err error, s
 	// check and cancel gRPC stream before reconnecting region, in case of the
 	// scenario that region connects to the same TiKV store again and reuses
 	// resource in this region worker by accident.
-	retErr := w.checkShouldExit(state.sri.rpcCtx.Addr)
+	retErr := w.checkShouldExit()
+
+	if err == cerror.ErrPrewriteNotMatch {
+		w.cancelStream(time.Second)
```
Comment (overvenus) [inline cdc/kv/region_worker.go:292]: Could you add comments about the cancel?
